function evaluated = evaluate_phase1c_step5_case( ...
        definition,cfg,dataF,dataCF,resultsF,resultsCF)
%EVALUATE_PHASE1C_STEP5_CASE Evaluate the frozen matched Case07 branches.

modes = definition.algorithms;
windows = definition.windows;
trackingFault = tracking_table( ...
    "F",modes,windows,dataF,resultsF);
trackingCounterfactual = tracking_table( ...
    "CF",modes,windows,dataCF,resultsCF);

[driftDirection,driftVector] = true_drift_direction( ...
    dataF,definition);
faultDeviation = fault_deviation_table( ...
    modes,windows,dataF.t,resultsF,resultsCF,driftDirection);
retention = retention_table( ...
    modes,definition,cfg,dataF,dataCF,resultsF,resultsCF);
[protection,m4Window,m3Detail,m4Detail] = protection_tables( ...
    definition,dataF,resultsF);
memory = memory_table( ...
    modes,definition,dataF.t,resultsF,resultsCF);
direction = direction_table(definition,resultsF.M4.tracker.cycle);
constraints = constraint_table(modes,definition,resultsF);
tradeoff = tradeoff_table( ...
    modes,dataF,trackingFault,trackingCounterfactual, ...
    faultDeviation,retention,resultsF,resultsCF,driftDirection);
assessment = assess_tradeoff(tradeoff,m3Detail);

evaluated = struct( ...
    'tracking_fault',trackingFault, ...
    'tracking_counterfactual',trackingCounterfactual, ...
    'fault_deviation',faultDeviation, ...
    'retention',retention, ...
    'protection',protection, ...
    'm4_window',m4Window, ...
    'm3_detail',m3Detail, ...
    'm4_detail',m4Detail, ...
    'memory',memory, ...
    'direction',direction, ...
    'constraints',constraints, ...
    'tradeoff',tradeoff, ...
    'assessment',assessment, ...
    'true_drift_direction',driftDirection, ...
    'true_drift_vector_pF',driftVector);
end

function tableOut = tracking_table(branch,modes,windows,data,results)
rows = cell(numel(modes)*height(windows),1);
rowIndex = 0;
truth = [data.Cs1,data.Cs2];
for mode = modes.'
    estimate = results.(char(mode)).cHist;
    errorP = estimate-truth;
    for windowIndex = 1:height(windows)
        rowIndex = rowIndex+1;
        window = windows(windowIndex,:);
        index = sample_window(data.t,window.start_s,window.end_s);
        localError = errorP(index,:);
        endpoint = localError(end,:);
        rows{rowIndex} = table(branch,mode,window.window, ...
            sqrt(mean(localError(:,1).^2)), ...
            sqrt(mean(localError(:,2).^2)), ...
            mean(localError(:,1)),mean(localError(:,2)), ...
            endpoint(1),endpoint(2), ...
            sqrt(mean(sum(localError.^2,2))),norm(endpoint), ...
            'VariableNames',{'branch','algorithm_mode','window', ...
            'Cs1_RMSE_pF','Cs2_RMSE_pF','Cs1_mean_error_pF', ...
            'Cs2_mean_error_pF','Cs1_endpoint_error_pF', ...
            'Cs2_endpoint_error_pF','parameter_error_RMS_norm_pF', ...
            'endpoint_error_norm_pF'});
    end
end
tableOut = vertcat(rows{:});
end

function [direction,vector] = true_drift_direction(data,definition)
w0 = definition.windows(definition.windows.window == "W0",:);
w2 = definition.windows(definition.windows.window == "W2",:);
index0 = find(data.t < w0.end_s,1,'last');
index2 = find(data.t < w2.end_s,1,'last');
vector = [data.Cs1(index2)-data.Cs1(index0); ...
    data.Cs2(index2)-data.Cs2(index0)];
direction = vector/(norm(vector)+eps);
end

function tableOut = fault_deviation_table( ...
        modes,windows,time,resultsF,resultsCF,driftDirection)
rows = cell(numel(modes)*height(windows),1);
rowIndex = 0;
for mode = modes.'
    delta = resultsF.(char(mode)).cHist- ...
        resultsCF.(char(mode)).cHist;
    for windowIndex = 1:height(windows)
        rowIndex = rowIndex+1;
        window = windows(windowIndex,:);
        index = sample_window(time,window.start_s,window.end_s);
        local = delta(index,:);
        meanVector = mean(local,1).';
        endpoint = local(end,:).';
        parallelScalar = local*driftDirection;
        perpendicular = local-parallelScalar*driftDirection.';
        cosineMean = vector_cosine(meanVector,driftDirection);
        rows{rowIndex} = table(mode,window.window, ...
            meanVector(1),meanVector(2), ...
            sqrt(mean(local(:,1).^2)),sqrt(mean(local(:,2).^2)), ...
            sqrt(mean(sum(local.^2,2))),endpoint(1),endpoint(2), ...
            norm(endpoint),max(vecnorm(local,2,2)),cosineMean, ...
            mean(parallelScalar),sqrt(mean(parallelScalar.^2)), ...
            sqrt(mean(sum(perpendicular.^2,2))), ...
            'VariableNames',{'algorithm_mode','window', ...
            'mean_delta_Cs1_fault_pF','mean_delta_Cs2_fault_pF', ...
            'RMS_delta_Cs1_fault_pF','RMS_delta_Cs2_fault_pF', ...
            'RMS_delta_norm_pF','endpoint_delta_Cs1_fault_pF', ...
            'endpoint_delta_Cs2_fault_pF','endpoint_delta_norm_pF', ...
            'maximum_delta_norm_pF','cosine_with_true_drift', ...
            'mean_parallel_signed_pF','RMS_parallel_pF', ...
            'RMS_perpendicular_pF'});
    end
end
tableOut = vertcat(rows{:});
end

function tableOut = retention_table( ...
        modes,definition,cfg,dataF,dataCF,resultsF,resultsCF)
windowNames = ["W1" "W2"];
rows = cell(numel(modes)*numel(windowNames),1);
rowIndex = 0;
for windowName = windowNames
    window = definition.windows( ...
        definition.windows.window == windowName,:);
    index = sample_window(dataF.t,window.start_s,window.end_s);
    trueFaultRms = fundamental_rms( ...
        dataF.t(index),dataF.irB(index),cfg.f);
    trueCounterfactualRms = fundamental_rms( ...
        dataCF.t(index),dataCF.irB(index),cfg.f);
    trueIncrement = trueFaultRms-trueCounterfactualRms;
    for mode = modes.'
        rowIndex = rowIndex+1;
        estimateFault = fundamental_rms(dataF.t(index), ...
            resultsF.(char(mode)).ir.B(index),cfg.f);
        estimateCounterfactual = fundamental_rms(dataCF.t(index), ...
            resultsCF.(char(mode)).ir.B(index),cfg.f);
        estimatedIncrement = estimateFault-estimateCounterfactual;
        ratio = estimatedIncrement/(trueIncrement+eps);
        conventionalTrue = trueFaultRms/(trueCounterfactualRms+eps);
        conventionalEstimated = estimateFault/(estimateCounterfactual+eps);
        rows{rowIndex} = table(windowName,mode,trueFaultRms, ...
            trueCounterfactualRms,trueIncrement,estimateFault, ...
            estimateCounterfactual,estimatedIncrement,ratio,ratio-1, ...
            100*(ratio-1),conventionalTrue,conventionalEstimated, ...
            'VariableNames',{'window','algorithm_mode', ...
            'true_fault_RMS_A','true_counterfactual_RMS_A', ...
            'true_fault_increment_A','estimated_fault_RMS_A', ...
            'estimated_counterfactual_RMS_A', ...
            'estimated_fault_increment_A', ...
            'fault_increment_retention_ratio', ...
            'fault_increment_retention_error', ...
            'fault_increment_retention_error_pct', ...
            'conventional_true_factor','conventional_estimated_factor'});
    end
end
tableOut = vertcat(rows{:});
end

function [tableOut,m4Window,m3Detail,m4Detail] = protection_tables( ...
        definition,data,results)
m3Cycle = results.M3.tracker.cycle;
m4Cycle = results.M4.tracker.cycle;
m3Active = m3Cycle.gate > 0;
faultOnset = definition.fault.onset_s;
faultClear = definition.fault.clear_s;

m3OnsetIndex = find(m3Active & m3Cycle.time_s >= faultOnset,1,'first');
if isempty(m3OnsetIndex)
    m3Onset = NaN;
else
    m3Onset = m3Cycle.time_s(m3OnsetIndex);
end
m3ReleaseIndex = first_consecutive( ...
    ~m3Active & m3Cycle.time_s >= faultClear,2);
if isempty(m3OnsetIndex) || isnan(m3ReleaseIndex)
    m3Release = NaN;
else
    m3Release = m3Cycle.time_s(m3ReleaseIndex);
end
activeAfterOnset = find(m3Active & m3Cycle.time_s >= faultOnset);
if isempty(activeAfterOnset)
    trueGateChange = [NaN NaN];
    gateLast = NaN;
else
    gateFirst = m3Cycle.time_s(activeAfterOnset(1));
    gateLast = m3Cycle.time_s(activeAfterOnset(end));
    truthFirst = [interp1(data.t,data.Cs1,gateFirst), ...
        interp1(data.t,data.Cs2,gateFirst)];
    truthLast = [interp1(data.t,data.Cs1,gateLast), ...
        interp1(data.t,data.Cs2,gateLast)];
    trueGateChange = truthLast-truthFirst;
end

m4Window = m4_window_table(definition,m4Cycle);
suppression = 1-m4Cycle.update_weight;
w0 = cycle_window(m4Cycle.time_s,definition,"W0");
preMedian = median(suppression(w0));
preMad = median(abs(suppression(w0)-preMedian));
preP95 = prctile(suppression(w0),95);
numericTolerance = max(1e-12,100*eps(max(1,abs(preMedian))));
if preMad <= numericTolerance
    materialThreshold = max(preP95,preMedian+numericTolerance);
else
    materialThreshold = preMedian+3*preMad;
end
materialIndex = first_consecutive( ...
    suppression > materialThreshold & m4Cycle.time_s >= faultOnset,2);
recoveryIndex = first_consecutive( ...
    suppression <= materialThreshold & m4Cycle.time_s >= faultClear,2);
materialOnset = index_time(m4Cycle.time_s,materialIndex);
recoveryTime = index_time(m4Cycle.time_s,recoveryIndex);
overlap = cycle_window(m4Cycle.time_s,definition,"W1") | ...
    cycle_window(m4Cycle.time_s,definition,"W2");
m3Overlap = cycle_window(m3Cycle.time_s,definition,"W1") | ...
    cycle_window(m3Cycle.time_s,definition,"W2");

tableOut = table( ...
    ["M2";"M3";"M4"], ...
    ["full adaptation";"gate inactive before fault"; ...
     "continuous weighted update"], ...
    ["full adaptation";"hard freeze when gate active"; ...
     "nonzero evidence-weighted adaptation"], ...
    ["not applicable";"persistent gate-off after clear"; ...
     "two cycles inside robust W0 suppression band"], ...
    [NaN;m3Onset;materialOnset], ...
    [NaN;mean(m3Active(m3Overlap));NaN], ...
    [1;1-mean(m3Active(m3Overlap)); ...
     mean(m4Cycle.update_weight(overlap))], ...
    [0;mean(m3Active(m3Overlap)); ...
     mean(suppression(overlap))], ...
    [NaN;m3Release;recoveryTime], ...
    [NaN;m3Release-faultClear;recoveryTime-faultClear], ...
    'VariableNames',{'algorithm_mode','pre_behavior', ...
    'overlap_behavior','release_recovery_definition', ...
    'protection_onset_s','hard_gate_active_ratio_overlap', ...
    'mean_update_weight_overlap','mean_update_suppression_overlap', ...
    'release_or_recovery_time_s','release_or_recovery_latency_s'});

m3Detail = struct( ...
    'gate_onset_s',m3Onset, ...
    'gate_onset_latency_s',m3Onset-faultOnset, ...
    'gate_last_active_s',gateLast, ...
    'gate_active_ratio_W1',mean(m3Active( ...
        cycle_window(m3Cycle.time_s,definition,"W1"))), ...
    'gate_active_ratio_W2',mean(m3Active( ...
        cycle_window(m3Cycle.time_s,definition,"W2"))), ...
    'gate_active_ratio_overlap',mean(m3Active(m3Overlap)), ...
    'release_time_s',m3Release, ...
    'release_latency_s',m3Release-faultClear, ...
    'true_Cs1_change_during_gate_pF',trueGateChange(1), ...
    'true_Cs2_change_during_gate_pF',trueGateChange(2));
m4Detail = struct( ...
    'pre_suppression_median',preMedian, ...
    'pre_suppression_MAD',preMad, ...
    'pre_suppression_P95',preP95, ...
    'material_threshold',materialThreshold, ...
    'material_onset_s',materialOnset, ...
    'material_onset_latency_s',materialOnset-faultOnset, ...
    'recovery_time_s',recoveryTime, ...
    'recovery_latency_s',recoveryTime-faultClear, ...
    'overlap_mean_g',mean(m4Cycle.update_weight(overlap)), ...
    'overlap_median_g',median(m4Cycle.update_weight(overlap)), ...
    'overlap_min_g',min(m4Cycle.update_weight(overlap)), ...
    'overlap_mean_fault_evidence', ...
        mean(m4Cycle.fault_evidence_score(overlap)), ...
    'overlap_Delta_USR',mean(suppression(overlap))-mean(suppression(w0)));
end

function tableOut = m4_window_table(definition,cycle)
rows = cell(4,1);
for k = 1:4
    windowName = "W"+string(k-1);
    index = cycle_window(cycle.time_s,definition,windowName);
    rows{k} = table(windowName,mean(cycle.update_weight(index)), ...
        median(cycle.update_weight(index)),min(cycle.update_weight(index)), ...
        mean(1-cycle.update_weight(index)), ...
        mean(cycle.fault_evidence_score(index)), ...
        mean(cycle.evidence_ratio_base(index)), ...
        mean(cycle.evidence_ratio_quad(index)), ...
        'VariableNames',{'window','mean_g','median_g','min_g', ...
        'mean_USR','mean_fault_evidence','mean_Ein_over_baseIn', ...
        'mean_Ein_over_Equad'});
end
tableOut = vertcat(rows{:});
end

function tableOut = memory_table(modes,definition,time,resultsF,resultsCF)
windowNames = ["W3" "W4"];
rows = cell(numel(modes)*2,1);
rowIndex = 0;
aucIndex = time >= definition.fault.clear_s & ...
    time < definition.windows.end_s( ...
    definition.windows.window == "W4");
for mode = modes.'
    delta = resultsF.(char(mode)).cHist-resultsCF.(char(mode)).cHist;
    distance = vecnorm(delta,2,2);
    auc = trapz(time(aucIndex),distance(aucIndex));
    for windowName = windowNames
        rowIndex = rowIndex+1;
        window = definition.windows( ...
            definition.windows.window == windowName,:);
        index = sample_window(time,window.start_s,window.end_s);
        rows{rowIndex} = table(mode,windowName,mean(distance(index)), ...
            distance(find(index,1,'last')),auc, ...
            'VariableNames',{'algorithm_mode','window', ...
            'mean_memory_norm_pF','endpoint_memory_norm_pF', ...
            'post_fault_AUC_pF_s'});
    end
end
tableOut = vertcat(rows{:});
end

function tableOut = direction_table(definition,cycle)
windowNames = ["W0" "W1" "W2" "W3"];
rows = cell(numel(windowNames),1);
for k = 1:numel(windowNames)
    windowName = windowNames(k);
    index = cycle_window(cycle.time_s,definition,windowName);
    valid = index & cycle.direction_candidate_valid;
    local = cycle.cos_local_fault(valid);
    raw = cycle.cos_raw_fault(valid);
    rows{k} = table(windowName,sum(index),sum(valid),mean(valid(index)), ...
        safe_mean(local),safe_percentile(local,50), ...
        safe_percentile(local,5),safe_percentile(local,95), ...
        safe_mean(abs(local)),safe_mean(raw), ...
        safe_percentile(raw,50),safe_percentile(raw,5), ...
        safe_percentile(raw,95),safe_mean(abs(raw)), ...
        'VariableNames',{'window','cycle_count','valid_cycle_count', ...
        'valid_direction_ratio','mean_cos_local_fault', ...
        'median_cos_local_fault','P05_cos_local_fault', ...
        'P95_cos_local_fault','mean_abs_cos_local_fault', ...
        'mean_cos_raw_fault','median_cos_raw_fault', ...
        'P05_cos_raw_fault','P95_cos_raw_fault', ...
        'mean_abs_cos_raw_fault'});
end
tableOut = vertcat(rows{:});
end

function tableOut = constraint_table(modes,definition,results)
rows = cell(numel(modes),1);
for k = 1:numel(modes)
    mode = modes(k);
    cycle = results.(char(mode)).tracker.cycle;
    overlap = cycle_window(cycle.time_s,definition,"W1") | ...
        cycle_window(cycle.time_s,definition,"W2");
    if mode == "M4"
        rate = sum(cycle.rate_limit_active(overlap));
        projection = sum(cycle.projection_active(overlap));
    else
        change = diff(cycle{:,{'Cs1_pF','Cs2_pF'}},1,1);
        rateAll = any(abs(change) >= 1.2-1e-12,2);
        bounds = cycle{2:end,{'Cs1_pF','Cs2_pF'}};
        projectionAll = any(bounds <= 1e-12 | bounds >= 40-1e-12,2);
        overlapChanges = overlap(2:end);
        rate = sum(rateAll(overlapChanges));
        projection = sum(projectionAll(overlapChanges));
    end
    rows{k} = table(mode,rate,projection, ...
        'VariableNames',{'algorithm_mode','rate_limit_active_cycles', ...
        'projection_active_cycles'});
end
tableOut = vertcat(rows{:});
end

function tableOut = tradeoff_table( ...
        modes,data,trackingFault,trackingCF, ...
        deviation,retention,resultsF,resultsCF,driftDirection)
rows = cell(numel(modes),1);
overlapSample = sample_window(data.t,1.62,1.88);
for k = 1:numel(modes)
    mode = modes(k);
    errorFault = resultsF.(char(mode)).cHist(overlapSample,:)- ...
        [data.Cs1(overlapSample),data.Cs2(overlapSample)];
    errorCF = resultsCF.(char(mode)).cHist(overlapSample,:)- ...
        [data.Cs1(overlapSample),data.Cs2(overlapSample)];
    trackingMetric = sqrt(mean(sum(errorFault.^2,2)));
    cfMetric = sqrt(mean(sum(errorCF.^2,2)));
    retentionRows = retention(retention.algorithm_mode == mode,:);
    retentionMetric = mean(abs( ...
        retentionRows.fault_increment_retention_error));
    delta = resultsF.(char(mode)).cHist(overlapSample,:)- ...
        resultsCF.(char(mode)).cHist(overlapSample,:);
    meanDelta = mean(delta,1).';
    rows{k} = table(mode,trackingMetric,cfMetric,retentionMetric, ...
        sqrt(mean(sum(delta.^2,2))), ...
        vector_cosine(meanDelta,driftDirection), ...
        trackingMetric+1e-9 < cfMetric, ...
        'VariableNames',{'algorithm_mode', ...
        'overlap_parameter_tracking_error_pF', ...
        'counterfactual_overlap_tracking_error_pF', ...
        'mean_abs_retention_ratio_error', ...
        'overlap_fault_induced_RMS_norm_pF', ...
        'fault_bias_cosine_with_true_drift', ...
        'fault_bias_apparently_improves_tracking'});
end
tableOut = vertcat(rows{:});
% Keep explicit dependencies visible in the saved workspace/table workflow.
assert(height(trackingFault) == 15 && height(trackingCF) == 15 && ...
    height(deviation) == 15);
end

function assessment = assess_tradeoff(tradeoff,m3Detail)
m2 = tradeoff(tradeoff.algorithm_mode == "M2",:);
m3 = tradeoff(tradeoff.algorithm_mode == "M3",:);
m4 = tradeoff(tradeoff.algorithm_mode == "M4",:);
driftBetter = m4.overlap_parameter_tracking_error_pF < ...
    m3.overlap_parameter_tracking_error_pF;
retentionBetter = m4.mean_abs_retention_ratio_error < ...
    m2.mean_abs_retention_ratio_error;
highAlignment = abs(m4.fault_bias_cosine_with_true_drift) >= 0.90;
confounded = m4.fault_bias_apparently_improves_tracking || highAlignment;
m3HardFreezeObserved = isfinite(m3Detail.gate_onset_s) && ...
    m3Detail.gate_active_ratio_overlap > 0;
if driftBetter && retentionBetter && ~confounded && m3HardFreezeObserved
    label = "TRADEOFF_DEMONSTRATED";
elseif driftBetter || retentionBetter
    label = "MIXED";
else
    label = "NOT_DEMONSTRATED";
end
assessment = struct( ...
    'label',label, ...
    'm4_drift_tracking_better_than_m3',driftBetter, ...
    'm4_fault_retention_better_than_m2',retentionBetter, ...
    'm4_geometric_confounding',confounded, ...
    'm4_fault_bias_highly_aligned_with_true_drift',highAlignment, ...
    'm3_hard_freeze_observed',m3HardFreezeObserved);
end

function index = sample_window(time,startTime,endTime)
index = time >= startTime & time < endTime;
if ~any(index)
    error('Phase1C:Step5Window','Sample window [%.3f, %.3f) is empty.', ...
        startTime,endTime);
end
end

function index = cycle_window(time,definition,windowName)
window = definition.windows(definition.windows.window == windowName,:);
index = time >= window.start_s & time < window.end_s;
if ~any(index)
    error('Phase1C:Step5CycleWindow','Cycle window %s is empty.',windowName);
end
end

function index = first_consecutive(mask,count)
index = NaN;
for k = 1:numel(mask)-count+1
    if all(mask(k:k+count-1))
        index = k;
        return
    end
end
end

function time = index_time(times,index)
if isnan(index)
    time = NaN;
else
    time = times(index);
end
end

function value = vector_cosine(a,b)
if norm(a) <= sqrt(eps) || norm(b) <= sqrt(eps)
    value = NaN;
else
    value = dot(a,b)/(norm(a)*norm(b));
end
end

function value = fundamental_rms(time,signal,frequency)
omega = 2*pi*frequency;
coefficients = [sin(omega*time),cos(omega*time), ...
    ones(size(time))]\signal;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
end

function value = safe_mean(x)
if isempty(x)
    value = NaN;
else
    value = mean(x,'omitmissing');
end
end

function value = safe_percentile(x,percentile)
if isempty(x)
    value = NaN;
else
    value = prctile(x,percentile);
end
end
