function definition = phase1c_case07_definition()
%PHASE1C_CASE07_DEFINITION Pre-registered independent Step 5 case.

definition = struct();
definition.schema_version = "phase1c_step5_case07_v1";
definition.case_name = "Case07_overlap_drift_fault";
definition.source_case = "Case06_drift_then_fault";
definition.seed = 105;
definition.model = "AI6109_MOA_AutoComp9";
definition.simulation_duration_s = 4.0;
definition.sample_time_s = 2e-5;
definition.fundamental_frequency_hz = 50;
definition.snr_db = 30;

definition.drift = struct( ...
    'start_s',0.80, ...
    'end_s',2.20, ...
    'Cs1_initial_pF',10.0, ...
    'Cs1_change_pF',3.0, ...
    'Cs2_initial_pF',10.0, ...
    'Cs2_change_pF',-2.0, ...
    'profile',"cubic smooth step x^2(3-2x)");
definition.fault = struct( ...
    'factor',1.30, ...
    'onset_s',1.50, ...
    'ramp_up_end_s',1.56, ...
    'plateau_end_s',1.90, ...
    'clear_s',1.96, ...
    'profile',"cubic smooth ramp up, plateau, cubic smooth ramp down");

definition.reference = struct( ...
    'source',"B-phase voltage from AutoComp9", ...
    'reconstruction_function',"reconstruct_refs_from_b", ...
    'phase_error_deg',0.0, ...
    'initialization_start_s',0.10, ...
    'initialization_end_s',0.70);
definition.noise = struct( ...
    'source',"exact Case06 seed-105 measurement-noise replay", ...
    'rng_seed',10105, ...
    'snr_db',30.0, ...
    'branch_policy',"one shared noise vector per phase for F and CF");

definition.windows = table( ...
    ["W0";"W1";"W2";"W3";"W4"], ...
    [1.20;1.62;1.74;1.98;2.40], ...
    [1.45;1.74;1.88;2.18;2.80], ...
    ["pre-fault active drift";"overlap early"; ...
     "overlap late";"post-fault active drift"; ...
     "post-drift recovery"], ...
    'VariableNames',{'window','start_s','end_s','description'});
definition.window_boundary = "start inclusive, end exclusive";
definition.algorithms = ["M2";"M3";"M4"];
definition.branches = ["F";"CF"];

definition.assessment = struct( ...
    'overlap_windows',["W1" "W2"], ...
    'drift_metric',"fault-branch RMS parameter-error norm over W1 union W2", ...
    'retention_metric',"mean absolute matched retention-ratio error over W1 and W2", ...
    'geometric_check', ...
        "fault branch must not obtain lower overlap error than its matched CF branch", ...
    'demonstrated_rule', ...
        "M4 drift metric < M3, M4 retention metric < M2, and no geometric false improvement", ...
    'mixed_rule', ...
        "only one objective improves, or both improve with geometric confounding", ...
    'not_demonstrated_rule', ...
        "neither required objective improves");
end
