function result = run_phase1c_step5_simultaneous_drift_fault()
%RUN_PHASE1C_STEP5_SIMULTANEOUS_DRIFT_FAULT Run frozen Case07 Step 5.

step5Root = fileparts(mfilename('fullpath'));
phase1cRoot = fileparts(step5Root);
projectRoot = fileparts(fileparts(phase1cRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
tablesRoot = fullfile(step5Root,'tables');
figuresRoot = fullfile(step5Root,'figures');
diagnosticsRoot = fullfile(step5Root,'diagnostics');
workspaceRoot = fullfile(step5Root,'workspace');
ensure_directories([string(tablesRoot),string(figuresRoot), ...
    string(diagnosticsRoot),string(workspaceRoot)]);
addpath(matlabRoot);
addpath(step5Root);

frozenSpec = freeze_phase1c_case07_specification();
snapshotPath = fullfile(workspaceRoot,'case07_configuration_snapshot.mat');
snapshot = load(snapshotPath,'definition');
definition = snapshot.definition;
protectedBefore = capture_protected_files( ...
    projectRoot,matlabRoot,phase1cRoot,step5Root);
metadata = capture_metadata(projectRoot,matlabRoot,definition,frozenSpec);

cfg = patent_default_config();
cfg.model = char(definition.model);
cfg.StopTime = definition.simulation_duration_s;
cfg.SNR_dB = definition.snr_db;
assert_config(cfg,definition);
selfPF = repmat(cfg.Cself_pF,1,3);

fprintf('STEP5_NOISE_REPLAY_START source=%s seed=%d\n', ...
    definition.source_case,definition.seed);
[sharedNoise,noiseReplay] = derive_case06_noise(cfg,definition.seed);
timeInput = (0:cfg.Ts:cfg.StopTime).';
signalsF = build_phase1c_case07_signals(timeInput,definition,"F");
signalsCF = build_phase1c_case07_signals(timeInput,definition,"CF");
assert_matched_inputs(signalsF,signalsCF,sharedNoise,definition);

fprintf('STEP5_BRANCH_SIMULATION_START branch=F\n');
dataF = simulate_phase1c_case07(cfg,signalsF,sharedNoise);
fprintf('STEP5_BRANCH_SIMULATION_START branch=CF\n');
dataCF = simulate_phase1c_case07(cfg,signalsCF,sharedNoise);
fairness = validate_branch_fairness( ...
    dataF,dataCF,signalsF,signalsCF,definition);
if ~fairness.pass
    error('Phase1C:Step5Fairness','Case07 matched-branch fairness failed.');
end

ref = reconstruct_refs_from_b(dataF.t,dataF.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
resultsF = struct();
resultsCF = struct();
for mode = definition.algorithms.'
    fprintf('STEP5_ALGORITHM_START mode=%s branch=F\n',mode);
    resultsF.(char(mode)) = run_phase1a_algorithm( ...
        mode,dataF,ref,cfg,selfPF);
    fprintf('STEP5_ALGORITHM_START mode=%s branch=CF\n',mode);
    resultsCF.(char(mode)) = run_phase1a_algorithm( ...
        mode,dataCF,ref,cfg,selfPF);
end
algorithmFairness = validate_algorithm_prefault_identity( ...
    dataF.t,resultsF,resultsCF,definition.fault.onset_s);
if ~algorithmFairness.pass
    error('Phase1C:Step5AlgorithmFairness', ...
        'Algorithm states differ before the Case07 fault onset.');
end

evaluated = evaluate_phase1c_step5_case( ...
    definition,cfg,dataF,dataCF,resultsF,resultsCF);
regression = validate_regression(projectRoot,protectedBefore);
validation = validate_step5( ...
    definition,frozenSpec,fairness,algorithmFairness,evaluated,regression);
if ~validation.overall_pass
    error('Phase1C:Step5Validation', ...
        'Step 5 execution validation failed before reporting.');
end

write_outputs(tablesRoot,diagnosticsRoot,evaluated, ...
    resultsF,resultsCF);
figurePaths = generate_phase1c_step5_figures( ...
    figuresRoot,definition,dataF,resultsF,resultsCF,evaluated);

caseDetail = minimal_case_detail( ...
    dataF,dataCF,signalsF,signalsCF,sharedNoise,resultsF,resultsCF);
schemaVersion = "phase1c_step5_simultaneous_drift_fault_v1";
workspacePath = fullfile(workspaceRoot,'case07_step5_workspace.mat');
result = struct( ...
    'schema_version',schemaVersion, ...
    'definition',definition, ...
    'cfg',cfg, ...
    'metadata',metadata, ...
    'frozen_specification',frozenSpec, ...
    'noise_replay',noiseReplay, ...
    'fairness',fairness, ...
    'algorithm_fairness',algorithmFairness, ...
    'evaluated',evaluated, ...
    'regression',regression, ...
    'validation',validation, ...
    'figure_paths',figurePaths, ...
    'case_detail',caseDetail);
save(workspacePath,'schemaVersion','definition','cfg','metadata', ...
    'frozenSpec','noiseReplay','fairness','algorithmFairness', ...
    'evaluated','regression','validation','figurePaths', ...
    'caseDetail','result','-v7.3');

assert_protected_unchanged(protectedBefore);
print_results(evaluated,regression,fairness,workspacePath);
fprintf('STEP5_EXECUTION_STATUS=PASS\n');
fprintf('M4_OVERLAP_TRADEOFF_ASSESSMENT=%s\n', ...
    evaluated.assessment.label);
end

function [noise,replay] = derive_case06_noise(cfg,seed)
noisyCfg = cfg;
noisyCfg.SNR_dB = 30;
cleanCfg = cfg;
cleanCfg.SNR_dB = Inf;
[noisy,~] = simulate_phase2_case(noisyCfg,'fault_with_drift',seed);
[clean,~] = simulate_phase2_case(cleanCfg,'fault_with_drift',seed);
noise = struct( ...
    'A',noisy.ia-clean.ia, ...
    'B',noisy.ib-clean.ib, ...
    'C',noisy.ic-clean.ic);
nonCurrentDifference = max(abs([ ...
    noisy.ua-clean.ua;noisy.ub-clean.ub;noisy.uc-clean.uc; ...
    noisy.Cs1-clean.Cs1;noisy.Cs2-clean.Cs2]));
if nonCurrentDifference > 0
    error('Phase1C:Step5NoiseReplay', ...
        'Noisy and clean Case06 runs differ outside measurement noise.');
end
replay = struct( ...
    'source_case',"Case06_drift_then_fault", ...
    'seed',seed, ...
    'rng_seed',seed+10000, ...
    'snr_db',30, ...
    'noise_rms_A',sqrt(mean(noise.A.^2)), ...
    'noise_rms_B',sqrt(mean(noise.B.^2)), ...
    'noise_rms_C',sqrt(mean(noise.C.^2)), ...
    'non_current_max_abs_difference',nonCurrentDifference);
end

function assert_matched_inputs(signalsF,signalsCF,noise,definition)
if ~isequal(signalsF.t,signalsCF.t) || ...
        ~isequal(signalsF.Cs1_pF,signalsCF.Cs1_pF) || ...
        ~isequal(signalsF.Cs2_pF,signalsCF.Cs2_pF) || ...
        ~isequal(signalsF.drift_progress,signalsCF.drift_progress)
    error('Phase1C:Step5MatchedInputs', ...
        'F and CF branch inputs differ outside the fault schedule.');
end
beforeFault = signalsF.t < definition.fault.onset_s;
if any(signalsF.fault_scale(beforeFault) ~= ...
        signalsCF.fault_scale(beforeFault)) || ...
        any(~isfinite([noise.A;noise.B;noise.C]))
    error('Phase1C:Step5MatchedInputs', ...
        'Matched input validation failed.');
end
end

function fairness = validate_branch_fairness( ...
        dataF,dataCF,signalsF,signalsCF,definition)
beforeFault = dataF.t < definition.fault.onset_s;
fields = {'t','ua','ub','uc','ia','ib','ic','irA','irB','irC', ...
    'Cs1','Cs2','Ca','Cb','Cc'};
differences = zeros(numel(fields),1);
for k = 1:numel(fields)
    differences(k) = max(abs( ...
        dataF.(fields{k})(beforeFault)-dataCF.(fields{k})(beforeFault)));
end
inputDifference = max(abs([ ...
    signalsF.Cs1_pF-signalsCF.Cs1_pF; ...
    signalsF.Cs2_pF-signalsCF.Cs2_pF]));
faultOnlyDifference = max(abs( ...
    signalsF.fault_scale-signalsCF.fault_scale));
overlap = dataF.t >= definition.fault.ramp_up_end_s & ...
    dataF.t < definition.fault.plateau_end_s;
truthChangesDuringOverlap = range(dataF.Cs1(overlap)) > 0 && ...
    range(dataF.Cs2(overlap)) > 0;
faultActiveDuringOverlap = all(abs(signalsF.fault_scale(overlap)- ...
    definition.fault.factor) < 1e-12);
fairness = struct( ...
    'pre_fault_field_names',{fields}, ...
    'pre_fault_max_abs_by_field',differences, ...
    'pre_fault_max_abs_difference',max(differences), ...
    'non_fault_input_max_abs_difference',inputDifference, ...
    'fault_schedule_max_abs_difference',faultOnlyDifference, ...
    'truth_changes_during_overlap',truthChangesDuringOverlap, ...
    'fault_active_during_overlap',faultActiveDuringOverlap);
fairness.pass = fairness.pre_fault_max_abs_difference == 0 && ...
    fairness.non_fault_input_max_abs_difference == 0 && ...
    fairness.fault_schedule_max_abs_difference > 0 && ...
    truthChangesDuringOverlap && faultActiveDuringOverlap;
end

function fairness = validate_algorithm_prefault_identity( ...
        time,resultsF,resultsCF,faultOnset)
beforeFault = time < faultOnset;
modes = ["M2" "M3" "M4"];
parameterDifference = zeros(3,1);
currentDifference = zeros(3,1);
for k = 1:3
    mode = modes(k);
    parameterDifference(k) = max(abs( ...
        resultsF.(char(mode)).cHist(beforeFault,:)- ...
        resultsCF.(char(mode)).cHist(beforeFault,:)),[],'all');
    currentDifference(k) = max(abs( ...
        resultsF.(char(mode)).ir.B(beforeFault)- ...
        resultsCF.(char(mode)).ir.B(beforeFault)));
end
fairness = struct( ...
    'algorithm_modes',modes, ...
    'parameter_max_abs_difference_pF',parameterDifference, ...
    'resistive_current_max_abs_difference_A',currentDifference, ...
    'pass',all(parameterDifference == 0) && all(currentDifference == 0));
end

function regression = validate_regression(projectRoot,protectedBefore)
baselinePath = fullfile(projectRoot,'paper_research', ...
    'phase1a_baseline','baseline_workspace.mat');
formal = load(baselinePath,'validation');
if ~isfield(formal,'validation') || ...
        ~isfield(formal.validation,'checks')
    error('Phase1C:Step5FormalValidation', ...
        'Frozen formal validation is unavailable.');
end
formalChecks = formal.validation.checks;
historical = run_phase1a_step7_regression();
regression = struct( ...
    'formal_check_count',height(formalChecks), ...
    'formal_pass_count',nnz(formalChecks.pass), ...
    'formal_pass',height(formalChecks) == 19 && all(formalChecks.pass), ...
    'historical_check_count',height(historical.regression), ...
    'historical_pass_count',nnz(historical.regression.pass), ...
    'historical_pass',historical.historical_results_reproduced, ...
    'protected_file_count',height(protectedBefore));
regression.pass = regression.formal_pass && regression.historical_pass;
end

function validation = validate_step5( ...
        definition,frozenSpec,fairness,algorithmFairness,evaluated,regression)
trackingFinite = all(isfinite([ ...
    evaluated.tracking_fault.Cs1_RMSE_pF; ...
    evaluated.tracking_fault.Cs2_RMSE_pF; ...
    evaluated.tracking_counterfactual.Cs1_RMSE_pF; ...
    evaluated.tracking_counterfactual.Cs2_RMSE_pF]));
retentionFinite = all(isfinite([ ...
    evaluated.retention.true_fault_increment_A; ...
    evaluated.retention.estimated_fault_increment_A; ...
    evaluated.retention.fault_increment_retention_ratio]));
validation = struct( ...
    'specification_hashes_pass',all(frozenSpec.pass), ...
    'branch_fairness_pass',fairness.pass, ...
    'algorithm_prefault_identity_pass',algorithmFairness.pass, ...
    'tracking_rows',height(evaluated.tracking_fault), ...
    'counterfactual_rows',height(evaluated.tracking_counterfactual), ...
    'fault_deviation_rows',height(evaluated.fault_deviation), ...
    'retention_rows',height(evaluated.retention), ...
    'protection_rows',height(evaluated.protection), ...
    'memory_rows',height(evaluated.memory), ...
    'tradeoff_rows',height(evaluated.tradeoff), ...
    'tracking_metrics_finite',trackingFinite, ...
    'retention_metrics_finite',retentionFinite, ...
    'overlap_is_real',fairness.truth_changes_during_overlap && ...
        fairness.fault_active_during_overlap, ...
    'formal_regression_pass',regression.pass, ...
    'unique_formal_case',definition.case_name == ...
        "Case07_overlap_drift_fault");
validation.overall_pass = validation.specification_hashes_pass && ...
    validation.branch_fairness_pass && ...
    validation.algorithm_prefault_identity_pass && ...
    validation.tracking_rows == 15 && ...
    validation.counterfactual_rows == 15 && ...
    validation.fault_deviation_rows == 15 && ...
    validation.retention_rows == 6 && ...
    validation.protection_rows == 3 && ...
    validation.memory_rows == 6 && ...
    validation.tradeoff_rows == 3 && ...
    validation.tracking_metrics_finite && ...
    validation.retention_metrics_finite && ...
    validation.overlap_is_real && validation.formal_regression_pass && ...
    validation.unique_formal_case;
end

function write_outputs(tablesRoot,diagnosticsRoot,evaluated,resultsF,resultsCF)
writetable(evaluated.tracking_fault, ...
    fullfile(tablesRoot,'actual_parameter_tracking.csv'));
writetable(evaluated.tracking_counterfactual, ...
    fullfile(tablesRoot,'no_fault_drift_baseline.csv'));
writetable(evaluated.fault_deviation, ...
    fullfile(tablesRoot,'fault_induced_parameter_deviation.csv'));
writetable(evaluated.retention, ...
    fullfile(tablesRoot,'fault_increment_preservation.csv'));
writetable(evaluated.protection, ...
    fullfile(tablesRoot,'protection_behavior.csv'));
writetable(evaluated.m4_window, ...
    fullfile(tablesRoot,'m4_window_response.csv'));
writetable(evaluated.memory, ...
    fullfile(tablesRoot,'post_fault_memory.csv'));
writetable(evaluated.tradeoff, ...
    fullfile(tablesRoot,'two_objective_tradeoff.csv'));
writetable(evaluated.direction, ...
    fullfile(diagnosticsRoot,'direction_overlap_diagnostics.csv'));
writetable(evaluated.constraints, ...
    fullfile(diagnosticsRoot,'constraint_activity.csv'));
writetable(resultsF.M3.tracker.cycle, ...
    fullfile(diagnosticsRoot,'m3_fault_cycle_diagnostics.csv'));
writetable(resultsF.M4.tracker.cycle, ...
    fullfile(diagnosticsRoot,'m4_fault_cycle_diagnostics.csv'));
writetable(resultsCF.M4.tracker.cycle, ...
    fullfile(diagnosticsRoot,'m4_counterfactual_cycle_diagnostics.csv'));
end

function detail = minimal_case_detail( ...
        dataF,dataCF,signalsF,signalsCF,noise,resultsF,resultsCF)
detail = struct( ...
    't',dataF.t, ...
    'Cs1_true',dataF.Cs1, ...
    'Cs2_true',dataF.Cs2, ...
    'fault_scale_F',signalsF.fault_scale, ...
    'fault_scale_CF',signalsCF.fault_scale, ...
    'shared_noise_A',noise.A, ...
    'shared_noise_B',noise.B, ...
    'shared_noise_C',noise.C, ...
    'irB_true_F',dataF.irB, ...
    'irB_true_CF',dataCF.irB, ...
    'M2_cHist_F',resultsF.M2.cHist, ...
    'M2_cHist_CF',resultsCF.M2.cHist, ...
    'M3_cHist_F',resultsF.M3.cHist, ...
    'M3_cHist_CF',resultsCF.M3.cHist, ...
    'M4_cHist_F',resultsF.M4.cHist, ...
    'M4_cHist_CF',resultsCF.M4.cHist, ...
    'M2_irB_F',resultsF.M2.ir.B, ...
    'M2_irB_CF',resultsCF.M2.ir.B, ...
    'M3_irB_F',resultsF.M3.ir.B, ...
    'M3_irB_CF',resultsCF.M3.ir.B, ...
    'M4_irB_F',resultsF.M4.ir.B, ...
    'M4_irB_CF',resultsCF.M4.ir.B, ...
    'M3_cycle_F',resultsF.M3.tracker.cycle, ...
    'M4_cycle_F',resultsF.M4.tracker.cycle, ...
    'M4_cycle_CF',resultsCF.M4.tracker.cycle);
end

function assert_config(cfg,definition)
if cfg.StopTime ~= definition.simulation_duration_s || ...
        cfg.Ts ~= definition.sample_time_s || ...
        cfg.f ~= definition.fundamental_frequency_hz || ...
        cfg.SNR_dB ~= definition.snr_db || ...
        string(cfg.model) ~= definition.model || ...
        cfg.phase_error_deg ~= definition.reference.phase_error_deg
    error('Phase1C:Step5Config','Runtime cfg differs from frozen Case07.');
end
end

function protected = capture_protected_files( ...
        projectRoot,matlabRoot,phase1cRoot,step5Root)
paths = strings(0,1);
sourceFiles = [dir(fullfile(matlabRoot,'*.m')); ...
    dir(fullfile(matlabRoot,'*.slx')); ...
    dir(fullfile(matlabRoot,'tests','*.m'))];
for k = 1:numel(sourceFiles)
    paths(end+1,1) = string(fullfile( ...
        sourceFiles(k).folder,sourceFiles(k).name)); %#ok<AGROW>
end
roots = [ ...
    string(fullfile(projectRoot,'paper_research','phase1a_baseline'))
    string(fullfile(projectRoot,'paper_research','phase1b_fault_absorption'))
    string(phase1cRoot)];
for root = roots.'
    files = dir(fullfile(root,'**','*'));
    files = files(~[files.isdir]);
    for k = 1:numel(files)
        path = string(fullfile(files(k).folder,files(k).name));
        if startsWith(path,string(step5Root)) || ...
                endsWith(path,'STEP5_SIMULTANEOUS_DRIFT_FAULT.md')
            continue
        end
        paths(end+1,1) = path; %#ok<AGROW>
    end
end
paths = unique(paths,'stable');
hash = strings(size(paths));
for k = 1:numel(paths)
    hash(k) = step5_file_sha256(paths(k));
end
protected = table(paths,hash,'VariableNames',{'path','sha256'});
end

function assert_protected_unchanged(protected)
for k = 1:height(protected)
    if step5_file_sha256(protected.path(k)) ~= protected.sha256(k)
        error('Phase1C:Step5ProtectedFile', ...
            'Protected file changed during Step 5: %s.',protected.path(k));
    end
end
end

function metadata = capture_metadata( ...
        projectRoot,matlabRoot,definition,frozenSpec)
[commitCode,commit] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1C:Step5GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'model_sha256',step5_file_sha256( ...
        fullfile(matlabRoot,definition.model+'.slx')), ...
    'specification_sha256',frozenSpec.expected_sha256(1), ...
    'snapshot_sha256',frozenSpec.expected_sha256(2), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_dirty',strlength(strtrim(string(status))) > 0, ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function ensure_directories(paths)
for path = paths
    if ~isfolder(path)
        mkdir(path);
    end
end
end

function print_results(evaluated,regression,fairness,workspacePath)
disp(evaluated.tracking_fault(ismember( ...
    evaluated.tracking_fault.window,["W1","W2"]),:));
disp(evaluated.fault_deviation(ismember( ...
    evaluated.fault_deviation.window,["W1","W2"]),:));
disp(evaluated.retention);
disp(evaluated.protection);
disp(evaluated.memory);
disp(evaluated.tradeoff);
fprintf('STEP5_BRANCH_PREFAULT_MAX_ABS=%.17g\n', ...
    fairness.pre_fault_max_abs_difference);
fprintf('STEP5_FORMAL_VALIDATOR=%d/%d\n', ...
    regression.formal_pass_count,regression.formal_check_count);
fprintf('STEP5_HISTORICAL_REGRESSION=%d/%d\n', ...
    regression.historical_pass_count,regression.historical_check_count);
fprintf('STEP5_PROTECTED_FILE_COUNT=%d\n', ...
    regression.protected_file_count);
fprintf('STEP5_WORKSPACE=%s\n',workspacePath);
end
