function result = run_phase2p1_vi_mapping()
%RUN_PHASE2P1_VI_MAPPING Phase 2-P1B curve-mapping safety gate.
%
% The script reads only the two literature-curve CSV interfaces. It does
% not load Simulink, generate aged alpha/Uref, or invoke M0/M2/M3/M4.
% Until paired, traceable digitized curves are present, execution stops
% without creating q_lit, an aged waveform, or model parameters.

scriptDir = fileparts(mfilename('fullpath'));
phaseDir = fileparts(scriptDir);
outputDir = fullfile(phaseDir,'analysis_outputs');
beforePath = fullfile(phaseDir,'literature_vi_before.csv');
afterPath = fullfile(phaseDir,'literature_vi_after.csv');

assert(isfile(beforePath),'Phase2P1:MissingBeforeTemplate', ...
    'Missing literature V-I input: %s',beforePath);
assert(isfile(afterPath),'Phase2P1:MissingAfterTemplate', ...
    'Missing literature V-I input: %s',afterPath);

beforeCurve = readtable(beforePath,'TextType','string');
afterCurve = readtable(afterPath,'TextType','string');
expectedVariables = ["x_value","current","x_definition", ...
    "source_figure","digitization_uncertainty"];
validate_schema(beforeCurve,expectedVariables,"before");
validate_schema(afterCurve,expectedVariables,"after");

analysisName = [ ...
    "normalized_vi_curves"; ...
    "q_statistics_median_p5_p95_spread"; ...
    "optimal_constant_scaling_residual_epsilon_shape"; ...
    "healthy_local_power_law_fit"; ...
    "aged_local_power_law_fit"; ...
    "I1_I3_I5_nonproportional_prediction"; ...
    "vi_direction_consistency_deltaI" ...
    ];
plannedOutput = [ ...
    "normalized before/after curves with original x retained"; ...
    "q(V), median, P5, P95, and spread"; ...
    "optimal scale c* and epsilon_shape"; ...
    "healthy local K and alpha with fit diagnostics"; ...
    "aged local K and alpha with fit diagnostics"; ...
    "predicted I1/I3/I5 gains and nonproportionality check"; ...
    "deltaI(V)=Iaged(V)-Ihealthy(V) and direction flag" ...
    ];
interfaceStatus = repmat("RESERVED_NOT_EXECUTED",numel(analysisName),1);
analysisPlan = table(analysisName,plannedOutput,interfaceStatus, ...
    'VariableNames',{'analysis_name','planned_output','interface_status'});

beforeRows = height(beforeCurve);
afterRows = height(afterCurve);
if beforeRows == 0 && afterRows == 0
    mappingStatus = "FAIL_SOURCE_FIGURE_NOT_UNIQUELY_DIGITIZABLE";
    p1bStatus = "FAIL";
elseif xor(beforeRows == 0,afterRows == 0)
    mappingStatus = "INCOMPLETE_DIGITIZED_CURVE_PAIR";
    p1bStatus = "FAIL";
else
    validate_populated_curve(beforeCurve,"before");
    validate_populated_curve(afterCurve,"after");
    mappingStatus = "DIGITIZED_CURVES_PRESENT_PENDING_MAPPING_IMPLEMENTATION";
    p1bStatus = "PENDING_MAPPING_IMPLEMENTATION";
end

% Reserved result fields deliberately contain no scientific values. They
% define the future interface without fabricating curves or parameters.
result = struct( ...
    'p1b_curve_mapping',p1bStatus, ...
    'mapping_status',mappingStatus, ...
    'before_input_path',string(beforePath), ...
    'after_input_path',string(afterPath), ...
    'before_row_count',beforeRows, ...
    'after_row_count',afterRows, ...
    'analysis_plan',analysisPlan, ...
    'normalized_before',table(), ...
    'normalized_after',table(), ...
    'q_curve',table(), ...
    'q_statistics',table(), ...
    'epsilon_shape',[], ...
    'healthy_local_fit',table(), ...
    'aged_local_fit',table(), ...
    'harmonic_prediction',table(), ...
    'vi_direction_check',table(), ...
    'model_parameters_generated',false, ...
    'formal_aged_model_run',false, ...
    'algorithm_runs',0);

write_status(fullfile(outputDir,'vi_mapping_status.txt'),result);

fprintf('MAPPING_STATUS = %s\n',mappingStatus);
fprintf('P1B_CURVE_MAPPING = %s\n',p1bStatus);
fprintf('BEFORE_DIGITIZED_ROWS = %d\n',beforeRows);
fprintf('AFTER_DIGITIZED_ROWS = %d\n',afterRows);
fprintf('MODEL_ALPHA_A_GENERATED = NO\n');
fprintf('MODEL_UREF_A_GENERATED = NO\n');
fprintf('FORMAL_AGED_MODEL_RUN = NO\n');
fprintf('M0_M2_M3_M4_RUN = NO\n');
fprintf('HISTORICAL_MATRIX_RERUN = NO\n');
end

function validate_schema(curve,expectedVariables,label)
actualVariables = string(curve.Properties.VariableNames);
assert(isequal(actualVariables,expectedVariables), ...
    'Phase2P1:InvalidCurveSchema', ...
    '%s curve variables must be exactly: %s', ...
    label,strjoin(expectedVariables,','));
end

function validate_populated_curve(curve,label)
assert(isnumeric(curve.x_value) && isnumeric(curve.current), ...
    'Phase2P1:NonNumericCurve', ...
    '%s x_value and current must be numeric.',label);
assert(all(isfinite(curve.x_value)) && all(isfinite(curve.current)), ...
    'Phase2P1:NonFiniteCurve', ...
    '%s x_value/current contains non-finite values.',label);
assert(all(curve.current > 0), ...
    'Phase2P1:NonPositiveCurrent', ...
    '%s current must be positive for log-domain V-I mapping.',label);
assert(~any(ismissing(curve.x_definition)) && ...
    ~any(ismissing(curve.source_figure)), ...
    'Phase2P1:MissingProvenance', ...
    '%s x_definition/source_figure contains missing values.',label);

definitions = unique(strip(string(curve.x_definition)));
assert(isscalar(definitions) && definitions ~= "", ...
    'Phase2P1:MixedXDefinition', ...
    '%s must preserve one explicit original x_definition.',label);
end

function write_status(path,result)
fileId = fopen(path,'wt','n','UTF-8');
assert(fileId >= 0,'Phase2P1:StatusWrite', ...
    'Unable to write mapping status: %s',path);
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId,'MAPPING_STATUS=%s\n',result.mapping_status);
fprintf(fileId,'P1B_CURVE_MAPPING=%s\n',result.p1b_curve_mapping);
fprintf(fileId,'BEFORE_DIGITIZED_ROWS=%d\n',result.before_row_count);
fprintf(fileId,'AFTER_DIGITIZED_ROWS=%d\n',result.after_row_count);
fprintf(fileId,'SOURCE_IMAGE_FILE=NOT_AVAILABLE\n');
fprintf(fileId,'SOURCE_IMAGE_SHA256=NOT_AVAILABLE\n');
fprintf(fileId,'DIGITIZATION_EXECUTED=NO\n');
fprintf(fileId,'TABLE2_E1MA_CROSSCHECK=NOT_PERFORMED_NO_DIGITIZED_CURVES\n');
fprintf(fileId,'COVERAGE_CHECK=NOT_EVALUABLE_NO_DIGITIZED_CURVES\n');
fprintf(fileId,'AGING_SHAPE_MAPPING=NOT_FROZEN\n');
fprintf(fileId,'AGED_MODEL_FROZEN=NO\n');
fprintf(fileId,'EXTERNAL_VALIDATION_8_GROUPS_AUTHORIZED=NO\n');
fprintf(fileId,'MODEL_PARAMETERS_GENERATED=NO\n');
fprintf(fileId,'FORMAL_AGED_MODEL_RUN=NO\n');
fprintf(fileId,'M0_M2_M3_M4_RUN=NO\n');
fprintf(fileId,'CASE05P_CASE06P_RUN=NO\n');
fprintf(fileId,'HISTORICAL_MATRIX_RERUN=NO\n');
clear cleanupFile;
end
