% branch_wide.m
%
% Branch 3: wide data (D >= N, numeric, no many-missing, no
% categorical, not sparse). Linear models dominate when features
% outnumber observations.
%
% Appends one entry to BRANCHES. Requires THRESHOLDS.

WIDE_MODELS = [ ...
    model_recipe('LinearSVM', 'fitclinear', ...
        struct('Learner','svm','Solver','lbfgs'), ...
        'Interp',         {{'low','high'}}, ...
        'MulticlassECOC', true) ...
    model_recipe('LinearSVMWithShrinkage', 'fitclinear', ...
        struct('Learner','svm','Solver','sparsa'), ...
        'Interp',         {{'low','high'}}, ...
        'MulticlassECOC', true) ...
    model_recipe('LinearDiscriminant', 'fitcdiscr', ...
        struct('DiscrimType','linear','FillCoeffs','off','SaveMemory','on'), ...
        'Interp', {{'low','high'}}) ...
    ...
    model_recipe('LinearStandardizedSVM', 'fitcsvm', ...
        struct('KernelFunction','linear','Standardize',true), ...
        'Interp',         {{'low','high'}}, ...
        'MulticlassECOC', true, ...
        'Condition',      @(f) f.N <= THRESHOLDS.standardized_svm_N) ...
    ...
    model_recipe('LogisticRegression', 'fitclinear', ...
        struct('Learner','logistic','Solver','lbfgs'), ...
        'Interp',         {{'low','high'}}, ...
        'MulticlassECOC', true) ...
    model_recipe('LogisticRegressionWithShrinkage', 'fitclinear', ...
        struct('Learner','logistic','Solver','sparsa'), ...
        'Interp',         {{'low','high'}}, ...
        'MulticlassECOC', true) ...
    ...
    model_recipe('KNN', 'fitcknn', ...
        struct('Distance','cosine','NumNeighbors',1), ...
        'Interp',    {{'low'}}, ...
        'Condition', @(f) f.N <= THRESHOLDS.wide_knn_N && f.smallestClassSize >= THRESHOLDS.wide_knn_smallest_class) ...
];

BRANCHES(end+1) = struct( ...
    'id',     3, ...
    'name',   'wide', ...
    'entry',  @(f) f.isWide && ~f.hasManyMissing && ~f.hasCategorical && ~f.isSparse, ...
    'models', {WIDE_MODELS});

clear WIDE_MODELS

% Copyright 2026 The MathWorks, Inc.
