% branch_regular.m
%
% Default branch (id 4): regular data — numeric, in-memory tall,
% no many-missing, no sparse. Applies when no other branch matches.
%
% Appends one entry to BRANCHES. Requires THRESHOLDS from
% classifier_thresholds.m. Uses model_recipe() from model_recipe.m.

REGULAR_MODELS = [ ...
    model_recipe('Tree', 'fitctree', ...
        struct(), ...
        'Interp', {{'low','high'}}) ...
    model_recipe('TreeIC', 'fitctree', ...
        struct('PredictorSelection','interaction-curvature'), ...
        'Interp', {{'low','high'}}) ...
    model_recipe('QuadraticDiscriminant', 'fitcdiscr', ...
        struct('DiscrimType','pseudoquadratic'), ...
        'Interp', {{'low','high'}}) ...
    ...
    model_recipe('LogisticRegression', 'fitclinear', ...
        struct('Learner','logistic','Solver','lbfgs','Lambda',0), ...
        'Interp', {{'high'}}, ...
        'MulticlassECOC', true) ...
    model_recipe('GAM', 'fitcgam', ...
        struct(), ...
        'Interp', {{'high'}}, ...
        'BinaryOnly', true) ...
    ...
    model_recipe('GaussianSVM', 'fitcsvm', ...
        struct('KernelFunction','rbf','Standardize',true,'KernelScale','auto'), ...
        'Interp',         {{'low'}}, ...
        'MulticlassECOC', true, ...
        'Condition',      @(f) ~f.isBig) ...
    ...
    model_recipe('KernelSVM', 'fitckernel', ...
        struct('Learner','svm','Standardize',true,'KernelScale','auto'), ...
        'Interp',         {{'low'}}, ...
        'MulticlassECOC', true, ...
        'Condition',      @(f) f.isBig) ...
    model_recipe('KernelLogistic', 'fitckernel', ...
        struct('Learner','logistic','Standardize',true,'KernelScale','auto'), ...
        'Interp',         {{'low'}}, ...
        'MulticlassECOC', true, ...
        'Condition',      @(f) f.isBig) ...
    ...
    model_recipe('NeuralNetwork', 'fitcnet', ...
        struct('Standardize',true), ...
        'Interp',    {{'low'}}, ...
        'Condition', @(f) ~f.isBig) ...
    ...
    model_recipe('KNN', 'fitcknn', ...
        struct('Distance','cosine','NumNeighbors',1), ...
        'Interp',    {{'low'}}, ...
        'Condition', @(f) ~f.isBig && f.isHighD) ...
    model_recipe('KNN', 'fitcknn', ...
        struct('Distance','euclidean','NumNeighbors',1,'Standardize',true), ...
        'Interp',    {{'low'}}, ...
        'Condition', @(f) ~f.isBig && ~f.isHighD) ...
    ...
    model_recipe('LightRandomForest', 'fitcensemble', ...
        struct('Method','Bag','NumLearningCycles',30), ...
        'InnerLearnerFn', 'templateTree', ...
        'Interp',         {{'low'}}, ...
        'Condition',      @(f) f.isBig) ...
    model_recipe('DarkRandomForest', 'fitcensemble', ...
        struct('Method','Bag','NumLearningCycles',100), ...
        'InnerLearnerFn', 'templateTree', ...
        'Interp',         {{'low'}}, ...
        'Condition',      @(f) ~f.isBig) ...
    ...
    model_recipe('LogitBoost', 'fitcensemble', ...
        struct('Method','LogitBoost','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'BinaryOnly',       true, ...
        'Condition',        @(f) ~f.isHighD) ...
    model_recipe('RoughAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isHighD && ~f.isBinary) ...
    model_recipe('FineAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits', @(f) 5*f.nClasses*(f.nClasses-1)), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isHighD && ~f.isBinary) ...
];

BRANCHES(end+1) = struct( ...
    'id',     4, ...
    'name',   'regular', ...
    'entry',  @(f) true, ...    % default — always last
    'models', {REGULAR_MODELS});

clear REGULAR_MODELS

% Copyright 2026 The MathWorks, Inc.
