% branch_many_missing.m
%
% Branch 1: many missing values (hasManyMissing, not sparse).
% Tree-based models and NaiveBayes handle NaN natively; SVM and KNN
% do not, so they're excluded.
%
% Appends one entry to BRANCHES. Requires THRESHOLDS.

MANY_MISSING_MODELS = [ ...
    model_recipe('Tree', 'fitctree', ...
        struct('MinParentSize',1), ...
        'Interp', {{'low','high'}}) ...
    model_recipe('TreeIC', 'fitctree', ...
        struct('MinParentSize',1,'PredictorSelection','interaction-curvature'), ...
        'Interp', {{'low','high'}}) ...
    model_recipe('NaiveBayes', 'fitcnb', ...
        struct(), ...
        'Interp', {{'low','high'}}) ...
    model_recipe('GAM', 'fitcgam', ...
        struct(), ...
        'Interp',    {{'low','high'}}, ...
        'BinaryOnly', true) ...
    ...
    model_recipe('LightRandomForest', 'fitcensemble', ...
        struct('Method','Bag','NumLearningCycles',30), ...
        'InnerLearnerFn', 'templateTree', ...
        'Interp',         {{'low'}}, ...
        'Condition',      @(f) f.isBig) ...
    model_recipe('DarkRandomForest', 'fitcensemble', ...
        struct('Method','Bag','NumLearningCycles',100), ...
        'InnerLearnerFn', 'templateTree', ...
        'Interp',         {{'low'}}, ...
        'Condition',      @(f) ~f.isBig) ...
    ...
    model_recipe('LogitBoost', 'fitcensemble', ...
        struct('Method','LogitBoost','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'BinaryOnly',       true, ...
        'Condition',        @(f) ~f.isHighD) ...
    model_recipe('RoughAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isHighD && ~f.isBinary) ...
    model_recipe('FineAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits', @(f) 5*f.nClasses*(f.nClasses-1)), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isHighD && ~f.isBinary) ...
    ...
    ... % KNN subspace: numeric features only (no categorical implied
    ... % by "not-Branch-2"). NPredToSample = min(5, ceil(sqrt(D))).
    model_recipe('KNNSubspace', 'fitcensemble', ...
        struct('Method','Subspace','NumLearningCycles',30, ...
               'NPredToSample', @(f) min(5, ceil(sqrt(f.D)))), ...
        'InnerLearnerFn', 'templateKNN', ...
        'Interp',         {{'low'}}, ...
        'Condition',      @(f) ~f.hasCategorical) ...
];

BRANCHES(end+1) = struct( ...
    'id',     1, ...
    'name',   'many_missing', ...
    'entry',  @(f) f.hasManyMissing && ~f.isSparse, ...
    'models', {MANY_MISSING_MODELS});

clear MANY_MISSING_MODELS

% Copyright 2026 The MathWorks, Inc.
