% imbalanced_boosting.m
%
% Overrides the "Boosted ensembles" model list produced by branches 1,
% 2, and 4 when isImbalanced. Applied AFTER base branch selection.
%
% Contract: a *script* invoked via
%
%     run(fullfile(skillPath, 'references', 'imbalanced_boosting.m'))
%
% populates IMBALANCED_BOOSTING_MODELS in the caller's workspace. The
% caller then substitutes these recipes for the branch's built-in
% boosting recipes (LogitBoost, RoughAdaBoost, FineAdaBoost).
%
% RUSBoost inclusion is gated on smallestClassSize — RUS's
% undersampling produces unstable learners with too few minority
% observations.

% model_recipe() lives alongside this file in references/. See
% classifier_branches.m for the reason it is not in scripts/.
IB_HERE = fileparts(mfilename('fullpath'));

run(fullfile(IB_HERE, 'classifier_thresholds.m'));  % populates THRESHOLDS

IB_RUSBOOST_MIN = THRESHOLDS.rusboost_smallest_class;

IMBALANCED_BOOSTING_MODELS = [ ...
    ... % RUSBoost family (only when smallest class large enough).
    model_recipe('RoughRUSBoost', 'fitcensemble', ...
        struct('Method','RUSBoost','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) f.smallestClassSize >= IB_RUSBOOST_MIN) ...
    model_recipe('FineRUSBoost', 'fitcensemble', ...
        struct('Method','RUSBoost','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits', @(f) 5*f.nClasses*(f.nClasses-1)), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) f.smallestClassSize >= IB_RUSBOOST_MIN && ~f.isBinary) ...
    ...
    ... % Standard boosting (same as balanced case; included so a
    ... % head-to-head with RUSBoost is possible).
    model_recipe('LogitBoost', 'fitcensemble', ...
        struct('Method','LogitBoost','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'BinaryOnly',       true) ...
    model_recipe('RoughAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits',10), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isBinary) ...
    model_recipe('FineAdaBoost', 'fitcensemble', ...
        struct('Method','AdaBoostM2','NumLearningCycles',30,'LearnRate',0.1), ...
        'InnerLearnerFn',   'templateTree', ...
        'InnerLearnerArgs', struct('MaxNumSplits', @(f) 5*f.nClasses*(f.nClasses-1)), ...
        'Interp',           {{'low'}}, ...
        'Condition',        @(f) ~f.isBinary) ...
];

clear IB_HERE IB_RUSBOOST_MIN

% Copyright 2026 The MathWorks, Inc.
