function evaluated = evaluate_phase1c_step5b_case( ...
        definition,cfg,dataF,dataCF,resultsF,resultsCF,case07Evaluated)
%EVALUATE_PHASE1C_STEP5B_CASE Evaluate triggered overlap confirmation.

base = evaluate_phase1c_step5_case( ...
    definition,cfg,dataF,dataCF,resultsF,resultsCF);
[gateInterval,adaptation] = gate_interval_analysis( ...
    definition,dataF,resultsF,resultsCF);
tradeoff = triggered_tradeoff(base,adaptation);
crossCase = cross_case_table(base,case07Evaluated);

evaluated = base;
evaluated.gate_interval = gateInterval;
evaluated.gate_interval_adaptation = adaptation;
evaluated.triggered_tradeoff = tradeoff;
evaluated.cross_case = crossCase;
end

function [detail,tableOut] = gate_interval_analysis( ...
        definition,data,resultsF,resultsCF)
m3Cycle = resultsF.M3.tracker.cycle;
active = logical(m3Cycle.gate);
firstIndex = find(active & ...
    m3Cycle.time_s >= definition.fault.onset_s,1,'first');
if isempty(firstIndex)
    error('Phase1C:Step5BM3NotTriggered', ...
        'M3 did not trigger; Step 5B is inconclusive.');
end
lastIndex = firstIndex;
while lastIndex < height(m3Cycle) && active(lastIndex+1)
    lastIndex = lastIndex+1;
end
startTime = m3Cycle.time_s(firstIndex);
endTime = m3Cycle.time_s(lastIndex);
sampleStart = find(data.t <= startTime,1,'last');
sampleEnd = find(data.t <= endTime,1,'last');
trueChange = [data.Cs1(sampleEnd)-data.Cs1(sampleStart), ...
    data.Cs2(sampleEnd)-data.Cs2(sampleStart)];

modes = definition.algorithms;
rows = cell(numel(modes),1);
for k = 1:numel(modes)
    mode = modes(k);
    deltaF = resultsF.(char(mode)).cHist(sampleEnd,:)- ...
        resultsF.(char(mode)).cHist(sampleStart,:);
    deltaCF = resultsCF.(char(mode)).cHist(sampleEnd,:)- ...
        resultsCF.(char(mode)).cHist(sampleStart,:);
    deltaFault = deltaF-deltaCF;
    fNorm = norm(deltaF);
    if fNorm <= sqrt(eps)
        purity = NaN;
    else
        purity = norm(deltaCF)/fNorm;
    end
    rows{k} = table(mode,startTime,endTime,endTime-startTime, ...
        trueChange(1),trueChange(2),deltaF(1),deltaF(2), ...
        abs(deltaF(1))/(abs(trueChange(1))+eps), ...
        abs(deltaF(2))/(abs(trueChange(2))+eps), ...
        deltaCF(1),deltaCF(2),deltaFault(1),deltaFault(2), ...
        fNorm,norm(deltaCF),norm(deltaFault),purity, ...
        'VariableNames',{'algorithm_mode','gate_start_s','gate_end_s', ...
        'gate_duration_s','true_delta_Cs1_pF','true_delta_Cs2_pF', ...
        'F_delta_Cs1_pF','F_delta_Cs2_pF','drift_capture_ratio_Cs1', ...
        'drift_capture_ratio_Cs2','CF_delta_Cs1_pF', ...
        'CF_delta_Cs2_pF','fault_induced_delta_Cs1_pF', ...
        'fault_induced_delta_Cs2_pF','F_movement_norm_pF', ...
        'CF_drift_movement_norm_pF','fault_induced_movement_norm_pF', ...
        'drift_adaptation_purity'});
end
tableOut = vertcat(rows{:});

m4Cycle = resultsF.M4.tracker.cycle;
m4SameInterval = m4Cycle.time_s >= startTime & ...
    m4Cycle.time_s <= endTime;
w1 = cycle_window(m3Cycle.time_s,definition,"W1");
w2 = cycle_window(m3Cycle.time_s,definition,"W2");
overlap = w1 | w2;
releaseIndex = find(~active & m3Cycle.time_s > endTime,1,'first');
if isempty(releaseIndex)
    releaseTime = NaN;
else
    releaseTime = m3Cycle.time_s(releaseIndex);
end
detail = struct( ...
    'gate_onset_s',startTime, ...
    'gate_onset_latency_s',startTime-definition.fault.onset_s, ...
    'gate_end_s',endTime, ...
    'gate_duration_s',endTime-startTime, ...
    'gate_release_s',releaseTime, ...
    'gate_release_latency_s',releaseTime-definition.fault.clear_s, ...
    'gate_active_ratio_W1',mean(active(w1)), ...
    'gate_active_ratio_W2',mean(active(w2)), ...
    'gate_active_ratio_overlap',mean(active(overlap)), ...
    'true_delta_Cs1_pF',trueChange(1), ...
    'true_delta_Cs2_pF',trueChange(2), ...
    'm4_mean_g_same_interval', ...
        mean(m4Cycle.update_weight(m4SameInterval)), ...
    'm4_median_g_same_interval', ...
        median(m4Cycle.update_weight(m4SameInterval)), ...
    'm4_min_g_same_interval', ...
        min(m4Cycle.update_weight(m4SameInterval)));
end

function assessment = triggered_tradeoff(base,adaptation)
m2Retention = base.retention( ...
    base.retention.algorithm_mode == "M2",:);
m3Retention = base.retention( ...
    base.retention.algorithm_mode == "M3",:);
m4Retention = base.retention( ...
    base.retention.algorithm_mode == "M4",:);
m3Move = adaptation(adaptation.algorithm_mode == "M3",:);
m4Move = adaptation(adaptation.algorithm_mode == "M4",:);

criterionA = mean(abs(m4Retention.fault_increment_retention_error)) < ...
    mean(abs(m2Retention.fault_increment_retention_error));
criterionB = m4Move.F_movement_norm_pF > ...
    m3Move.F_movement_norm_pF+1e-9;
criterionC = m4Move.CF_drift_movement_norm_pF > ...
    m4Move.fault_induced_movement_norm_pF;
count = nnz([criterionA criterionB criterionC]);
if count == 3
    label = "DEMONSTRATED";
elseif count == 0
    label = "NOT_DEMONSTRATED";
else
    label = "MIXED";
end
assessment = table(criterionA,criterionB,criterionC, ...
    mean(abs(m2Retention.fault_increment_retention_error)), ...
    mean(abs(m3Retention.fault_increment_retention_error)), ...
    mean(abs(m4Retention.fault_increment_retention_error)), ...
    m3Move.F_movement_norm_pF,m4Move.F_movement_norm_pF, ...
    m4Move.CF_drift_movement_norm_pF, ...
    m4Move.fault_induced_movement_norm_pF,label, ...
    'VariableNames',{'criterion_A_retention_vs_M2', ...
    'criterion_B_adaptation_vs_M3','criterion_C_drift_dominates_fault', ...
    'M2_mean_abs_retention_error','M3_mean_abs_retention_error', ...
    'M4_mean_abs_retention_error','M3_F_movement_norm_pF', ...
    'M4_F_movement_norm_pF','M4_CF_drift_movement_norm_pF', ...
    'M4_fault_induced_movement_norm_pF','assessment'});
end

function tableOut = cross_case_table(case08,case07)
caseNames = ["Case07_factor1.30";"Case08_factor1.60"];
evaluations = {case07;case08};
gateTriggered = false(2,1);
m3OverlapActiveRatio = zeros(2,1);
m4MeanG = zeros(2,1);
m4BiasReduction = zeros(2,1);
m2Retention = zeros(2,1);
m3Retention = zeros(2,1);
m4Retention = zeros(2,1);
for k = 1:2
    current = evaluations{k};
    gateTriggered(k) = isfinite(current.m3_detail.gate_onset_s);
    m3OverlapActiveRatio(k) = current.m3_detail.gate_active_ratio_overlap;
    m4MeanG(k) = current.m4_detail.overlap_mean_g;
    m2 = current.tradeoff(current.tradeoff.algorithm_mode == "M2",:);
    m4 = current.tradeoff(current.tradeoff.algorithm_mode == "M4",:);
    m4BiasReduction(k) = 1- ...
        m4.overlap_fault_induced_RMS_norm_pF/ ...
        m2.overlap_fault_induced_RMS_norm_pF;
    for mode = ["M2" "M3" "M4"]
        rows = current.retention(current.retention.algorithm_mode == mode,:);
        value = mean(rows.fault_increment_retention_ratio);
        switch mode
            case "M2"
                m2Retention(k) = value;
            case "M3"
                m3Retention(k) = value;
            case "M4"
                m4Retention(k) = value;
        end
    end
end
tableOut = table(caseNames,gateTriggered,m3OverlapActiveRatio,m4MeanG, ...
    m4BiasReduction,m2Retention,m3Retention,m4Retention, ...
    'VariableNames',{'case_name','M3_gate_triggered', ...
    'M3_overlap_active_ratio','M4_overlap_mean_g', ...
    'M4_fault_bias_reduction_vs_M2','M2_mean_retention', ...
    'M3_mean_retention','M4_mean_retention'});
end

function index = cycle_window(time,definition,windowName)
window = definition.windows(definition.windows.window == windowName,:);
index = time >= window.start_s & time < window.end_s;
if ~any(index)
    error('Phase1C:Step5BCycleWindow','Cycle window %s is empty.',windowName);
end
end
