function row = evaluate_case_metrics(data,ir,cHist,methodName,sceneName,cfg)
idx = data.t>=0.8;
row = table(string(sceneName),string(methodName), ...
    mean(abs(cHist(idx,1)-data.Cs1(idx))),mean(abs(cHist(idx,2)-data.Cs2(idx))), ...
    max(abs(cHist(idx,1)-data.Cs1(idx))),max(abs(cHist(idx,2)-data.Cs2(idx))), ...
    fund_err(data.t(idx),data.irA(idx),ir.A(idx),cfg.f), ...
    fund_err(data.t(idx),data.irB(idx),ir.B(idx),cfg.f), ...
    fund_err(data.t(idx),data.irC(idx),ir.C(idx),cfg.f), ...
    'VariableNames',{'scene','method','Cs1_MAE_pF','Cs2_MAE_pF','Cs1_MaxErr_pF','Cs2_MaxErr_pF', ...
    'A_FundErr_pct','B_FundErr_pct','C_FundErr_pct'});
end

function e = fund_err(t,xTrue,xEst,f)
r1=harmonic_rms(t,xTrue,f); r2=harmonic_rms(t,xEst,f);
e=(r2-r1)/(r1+eps)*100;
end
function r=harmonic_rms(t,x,f)
w=2*pi*f; H=[sin(w*t),cos(w*t),ones(size(t))]; b=H\x;
r=hypot(b(1),b(2))/sqrt(2);
end
