function definition = phase1c_step6_definition()
%PHASE1C_STEP6_DEFINITION Pre-registered minimal Step 6 ablation.

definition = struct();
definition.schema_version = "phase1c_step6_ablation_v1";
definition.method_name = ...
    "M4 - Residual-Evidence Weighted Adaptive Identification";
definition.method_acronym = "REW-AI";
definition.freeze_version = "paper_method_v1";
definition.no_parameter_optimization = true;
definition.cases = [ ...
    "Case02_slow_drift"; ...
    "Case05_fault_only"; ...
    "Case07_overlap_drift_fault"; ...
    "Case08_overlap_drift_fault_f160"];
definition.variants = [ ...
    "M2"; ...
    "M3"; ...
    "A_FULL"; ...
    "A_NO_WEIGHT"; ...
    "A_BACKGROUND_ONLY"; ...
    "A_FIXED_LAMBDA"];
definition.production_variant = "A_FULL";
definition.ablation_only_variants = [ ...
    "A_NO_WEIGHT";"A_BACKGROUND_ONLY";"A_FIXED_LAMBDA"];
definition.variant_rule = [ ...
    "frozen full VFF-RLS adaptation"; ...
    "frozen hard fault gate"; ...
    "frozen M4-v0, unchanged"; ...
    "M4 information update with g identically one"; ...
    "M4 information update with p_q identically one"; ...
    "M4 information update with lambda identically lambda_max"];
definition.direction_control_ablation = "NOT APPLICABLE";
definition.direction_role = "DIAGNOSTIC ONLY";
definition.c_only_ablation = "EXCLUDED: state-inconsistent hidden absorption";
definition.contribution_labels = [ ...
    "SUPPORTED";"LIMITED";"NOT DEMONSTRATED";"NOT APPLICABLE"];
definition.windows = struct( ...
    'case02_metric',[0.80 4.00], ...
    'case05_pre',[2.60 2.90], ...
    'case05_fault',[3.40 3.80], ...
    'case05_onset_s',3.00, ...
    'case07_overlap',[1.62 1.88], ...
    'case08_overlap',[1.62 1.88]);
definition.fixed_lambda = 0.995;
definition.parameters = table( ...
    ["gate_ratio";"gate_quad_ratio";"lambda_min";"lambda_max"; ...
     "innovation_scale";"baseIn_alpha";"baseIn_condition"; ...
     "regularization";"rate_limit_pF_per_cycle"; ...
     "projection_lower_pF";"projection_upper_pF"], ...
    [1.12;1.20;0.55;0.995;0.20;0.015;1.08;1e-10;1.2;0;40], ...
    ["inherited cfg";"inherited cfg";"inherited cfg"; ...
     "inherited cfg";"frozen M2/M4 source";"frozen M4 source"; ...
     "frozen M4 source";"frozen M4 source";"inherited cfg"; ...
     "inherited cfg";"inherited cfg"], ...
    false(11,1), ...
    'VariableNames',{'parameter','value','origin','tuned_in_phase1c'});
end
