function evaluated = evaluate_phase1c_step4_case( ...
        caseInfo,data,counterfactualData,cfg,algorithmResults, ...
        counterfactualResults,metadata,staticBias)
%EVALUATE_PHASE1C_STEP4_CASE Evaluate one frozen fault case.

preSample = data.t >= 2.60 & data.t < 2.90;
faultSample = data.t >= 3.40 & data.t < 3.80;
faultOnsetS = 3.00;
modes = ["M2","M3","M4"];
rows = cell(numel(modes),1);

truePre = fundamental_rms(data.t(preSample),data.irB(preSample),cfg.f);
trueFault = fundamental_rms( ...
    data.t(faultSample),data.irB(faultSample),cfg.f);
trueFactor = trueFault/(truePre+eps);

for k = 1:numel(modes)
    mode = modes(k);
    result = algorithmResults.(char(mode));
    counterfactual = counterfactualResults.(char(mode));
    official = evaluate_phase1a_metrics( ...
        caseInfo,result,data,cfg,metadata);
    estimatedPre = fundamental_rms( ...
        data.t(preSample),result.ir.B(preSample),cfg.f);
    estimatedFault = fundamental_rms( ...
        data.t(faultSample),result.ir.B(faultSample),cfg.f);
    faultChange = parameter_change( ...
        result.cHist,preSample,faultSample);
    counterfactualChange = parameter_change( ...
        counterfactual.cHist,preSample,faultSample);
    faultInduced = faultChange-counterfactualChange;
    rows{k} = table(string(caseInfo.case_name),mode,trueFactor, ...
        official.fault_factor_est,official.fault_retention_error_pct, ...
        truePre,trueFault,estimatedPre,estimatedFault, ...
        faultChange(1),faultChange(2),counterfactualChange(1), ...
        counterfactualChange(2),faultInduced(1),faultInduced(2), ...
        'VariableNames',{'case_name','algorithm_mode', ...
        'fault_factor_true','fault_factor_est', ...
        'fault_retention_error_pct', ...
        'B_fundamental_true_pre_A','B_fundamental_true_fault_A', ...
        'B_fundamental_est_pre_A','B_fundamental_est_fault_A', ...
        'DeltaCs1_pre_post_pF','DeltaCs2_pre_post_pF', ...
        'DeltaCs1_counterfactual_pF','DeltaCs2_counterfactual_pF', ...
        'DeltaCs1_fault_induced_pF','DeltaCs2_fault_induced_pF'});
end
summary = vertcat(rows{:});

m4Cycle = algorithmResults.M4.tracker.cycle;
[m4Diagnostics,m4Direction,cycleDetail] = m4_diagnostics( ...
    caseInfo.case_name,m4Cycle,data,cfg,faultOnsetS);
m3Diagnostics = m3_diagnostics( ...
    caseInfo.case_name,algorithmResults.M3.tracker.cycle, ...
    data,cfg,faultOnsetS);
absorption = absorption_table(summary,staticBias);

evaluated = struct( ...
    'summary',summary, ...
    'absorption',absorption, ...
    'm4_diagnostics',m4Diagnostics, ...
    'm3_diagnostics',m3Diagnostics, ...
    'direction_diagnostics',m4Direction, ...
    'cycle_detail',cycleDetail, ...
    'counterfactual_identity_max_abs_A',max(abs( ...
        counterfactualData.ib-data.ib+ ...
        (data.irB-counterfactualData.irB))));
end

function tableOut = absorption_table(summary,staticBias)
m2 = summary(summary.algorithm_mode == "M2",:);
rows = cell(2,1);
comparisonModes = ["M3","M4"];
for k = 1:2
    mode = comparisonModes(k);
    current = summary(summary.algorithm_mode == mode,:);
    m2Abs1 = abs(m2.DeltaCs1_fault_induced_pF);
    m2Abs2 = abs(m2.DeltaCs2_fault_induced_pF);
    currentAbs1 = abs(current.DeltaCs1_fault_induced_pF);
    currentAbs2 = abs(current.DeltaCs2_fault_induced_pF);
    rows{k} = table(current.case_name,mode, ...
        m2Abs1-currentAbs1,m2Abs2-currentAbs2, ...
        (m2Abs1-currentAbs1)/(m2Abs1+eps), ...
        (m2Abs2-currentAbs2)/(m2Abs2+eps), ...
        currentAbs1/(m2Abs1+eps),currentAbs2/(m2Abs2+eps), ...
        currentAbs1/(abs(staticBias(1))+eps), ...
        currentAbs2/(abs(staticBias(2))+eps), ...
        abs(m2.fault_retention_error_pct)- ...
            abs(current.fault_retention_error_pct), ...
        'VariableNames',{'case_name','algorithm_mode', ...
        'DeltaCs1_abs_reduction_vs_M2_pF', ...
        'DeltaCs2_abs_reduction_vs_M2_pF', ...
        'DeltaCs1_relative_reduction_vs_M2', ...
        'DeltaCs2_relative_reduction_vs_M2', ...
        'parameter_absorption_ratio_Cs1', ...
        'parameter_absorption_ratio_Cs2', ...
        'achieved_to_static_bias_ratio_Cs1', ...
        'achieved_to_static_bias_ratio_Cs2', ...
        'retention_abs_error_reduction_vs_M2_pct_point'});
end
tableOut = vertcat(rows{:});
end

function [row,directionRows,detail] = m4_diagnostics( ...
        caseName,cycle,data,cfg,faultOnsetS)
[cycleStart,pre,fault,response] = cycle_windows(cycle,data,cfg, ...
    faultOnsetS);
g = cycle.update_weight;
suppression = 1-g;
preMedian = median(suppression(pre));
preMad = median(abs(suppression(pre)-preMedian));
preP95 = prctile(suppression(pre),95);
numericalTolerance = max(1e-12,100*eps(max(1,abs(preMedian))));
if preMad <= numericalTolerance
    materialThreshold = max(preP95,preMedian+numericalTolerance);
else
    materialThreshold = preMedian+3*preMad;
end
material = response & suppression > materialThreshold;
materialStartIndex = first_consecutive_pair(material);
if isnan(materialStartIndex)
    materialOnset = NaN;
    materialLatency = NaN;
else
    materialOnset = cycle.time_s(materialStartIndex);
    materialLatency = materialOnset-faultOnsetS;
end
cycleDuration = 1/cfg.f;
excessArea = sum(max(0,suppression(response)-preMedian))*cycleDuration;

faultPercentiles = prctile(g(fault),[5,50,95]);
preUsr = mean(suppression(pre));
faultUsr = mean(suppression(fault));
[isrJPre,isrHPre] = information_ratios(cycle,pre);
[isrJFault,isrHFault] = information_ratios(cycle,fault);
suppressed1 = cycle.delta_c_information_suppressed_1(fault);
suppressed2 = cycle.delta_c_information_suppressed_2(fault);

row = table(string(caseName),mean(g(pre)),mean(g(fault)), ...
    preUsr,faultUsr,faultUsr-preUsr,min(g(fault)), ...
    faultPercentiles(1),faultPercentiles(2),faultPercentiles(3), ...
    preMedian,preMad,preP95,materialThreshold,materialOnset, ...
    materialLatency,excessArea,isrJPre,isrJFault,isrHPre,isrHFault, ...
    sqrt(mean(suppressed1.^2)),sqrt(mean(suppressed2.^2)), ...
    sum(abs(suppressed1)),sum(abs(suppressed2)), ...
    max(abs([suppressed1;suppressed2])), ...
    sum(cycle.rate_limit_active(response)), ...
    sum(cycle.projection_active(response)), ...
    mean(cycle.evidence_ratio_base(pre)), ...
    mean(cycle.evidence_ratio_base(fault)), ...
    mean(cycle.evidence_ratio_quad(pre)), ...
    mean(cycle.evidence_ratio_quad(fault)), ...
    mean(cycle.evidence_background_excess(pre)), ...
    mean(cycle.evidence_background_excess(fault)), ...
    mean(cycle.evidence_phase_weight(pre)), ...
    mean(cycle.evidence_phase_weight(fault)), ...
    mean(cycle.fault_evidence_score(pre)), ...
    mean(cycle.fault_evidence_score(fault)), ...
    'VariableNames',{'case_name','pre_mean_g','fault_mean_g', ...
    'pre_USR','fault_USR','Delta_USR_fault','fault_min_g', ...
    'fault_P05_g','fault_median_g','fault_P95_g', ...
    'pre_suppression_median','pre_suppression_MAD', ...
    'pre_suppression_P95','material_threshold', ...
    'material_suppression_onset_s','material_suppression_latency_s', ...
    'excess_suppression_area_s','ISR_J_pre','ISR_J_fault', ...
    'ISR_h_pre','ISR_h_fault', ...
    'fault_rms_information_suppressed_DeltaCs1_pF', ...
    'fault_rms_information_suppressed_DeltaCs2_pF', ...
    'fault_cumulative_abs_suppressed_DeltaCs1_pF', ...
    'fault_cumulative_abs_suppressed_DeltaCs2_pF', ...
    'fault_max_per_cycle_suppressed_DeltaCs_pF', ...
    'response_rate_limit_cycles','response_projection_cycles', ...
    'pre_mean_Ein_over_baseIn','fault_mean_Ein_over_baseIn', ...
    'pre_mean_Ein_over_Equad','fault_mean_Ein_over_Equad', ...
    'pre_mean_background_excess','fault_mean_background_excess', ...
    'pre_mean_phase_weight','fault_mean_phase_weight', ...
    'pre_mean_fault_evidence','fault_mean_fault_evidence'});

directionRows = [direction_row(caseName,"pre_fault",cycle,pre); ...
    direction_row(caseName,"fault_window",cycle,fault)];
detail = addvars(cycle,repmat(string(caseName),height(cycle),1), ...
    cycleStart,suppression,pre,fault,response,material, ...
    'Before',1,'NewVariableNames',{'case_name','cycle_start_s', ...
    'suppression','is_pre_fault','is_fault_window', ...
    'is_response_window','is_material_suppression'});
end

function row = m3_diagnostics(caseName,cycle,data,cfg,faultOnsetS)
[~,~,~,response] = cycle_windows(cycle,data,cfg,faultOnsetS);
active = cycle.gate > 0;
first = find(active & cycle.time_s >= faultOnsetS,1,'first');
if isempty(first)
    onset = NaN;
    latency = NaN;
else
    onset = cycle.time_s(first);
    latency = onset-faultOnsetS;
end
row = table(string(caseName),onset,latency,mean(active(response)), ...
    sum(active(response)),'VariableNames',{'case_name', ...
    'hard_gate_onset_s','hard_gate_latency_s', ...
    'hard_gate_active_ratio','hard_gate_active_cycles'});
end

function [cycleStart,pre,fault,response] = cycle_windows( ...
        cycle,data,cfg,faultOnsetS)
samplesPerCycle = round((1/median(diff(data.t)))/cfg.f);
cycleStart = cycle.time_s-(samplesPerCycle-1)*median(diff(data.t));
pre = cycleStart >= 2.60 & cycle.time_s < 2.90;
fault = cycleStart >= 3.40 & cycle.time_s < 3.80;
response = cycle.time_s >= faultOnsetS;
if ~any(pre) || ~any(fault) || ~any(response)
    error('Phase1C:Step4CycleWindows','Required cycle window is empty.');
end
end

function index = first_consecutive_pair(mask)
first = find(mask(1:end-1) & mask(2:end),1,'first');
if isempty(first)
    index = NaN;
else
    index = first;
end
end

function [ratioJ,ratioH] = information_ratios(cycle,index)
jRaw = cycle{index,{'J_increment_raw_11','J_increment_raw_12', ...
    'J_increment_raw_21','J_increment_raw_22'}};
jApplied = cycle{index,{'J_increment_applied_11', ...
    'J_increment_applied_12','J_increment_applied_21', ...
    'J_increment_applied_22'}};
hRaw = cycle{index,{'h_increment_raw_1','h_increment_raw_2'}};
hApplied = cycle{index,{'h_increment_applied_1', ...
    'h_increment_applied_2'}};
ratioJ = sum(vecnorm(jRaw-jApplied,2,2))/(sum(vecnorm(jRaw,2,2))+eps);
ratioH = sum(vecnorm(hRaw-hApplied,2,2))/(sum(vecnorm(hRaw,2,2))+eps);
end

function row = direction_row(caseName,phaseName,cycle,index)
valid = index & cycle.direction_candidate_valid;
local = cycle.cos_local_fault(valid);
raw = cycle.cos_raw_fault(valid);
localPercentile = prctile(local,[5,50,95]);
rawPercentile = prctile(raw,[5,50,95]);
row = table(string(caseName),string(phaseName),mean(index), ...
    mean(cycle.direction_candidate_valid(index)),sum(valid), ...
    mean(local),localPercentile(2),localPercentile(1), ...
    localPercentile(3),mean(abs(local)),mean(raw), ...
    rawPercentile(2),rawPercentile(1),rawPercentile(3),mean(abs(raw)), ...
    'VariableNames',{'case_name','phase_name','cycle_fraction', ...
    'valid_direction_ratio','valid_direction_cycles', ...
    'mean_cos_local_fault','median_cos_local_fault', ...
    'P05_cos_local_fault','P95_cos_local_fault', ...
    'mean_abs_cos_local_fault','mean_cos_raw_fault', ...
    'median_cos_raw_fault','P05_cos_raw_fault','P95_cos_raw_fault', ...
    'mean_abs_cos_raw_fault'});
end

function change = parameter_change(cHist,preIndex,faultIndex)
change = mean(cHist(faultIndex,:),1)-mean(cHist(preIndex,:),1);
end

function value = fundamental_rms(t,x,f)
omega = 2*pi*f;
coefficients = [sin(omega*t),cos(omega*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
end
