function result = run_phase1c_step4_fault_preservation()
%RUN_PHASE1C_STEP4_FAULT_PRESERVATION Evaluate frozen Case05/06.

step4Root = fileparts(mfilename('fullpath'));
phase1cRoot = fileparts(step4Root);
projectRoot = fileparts(fileparts(phase1cRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
tablesRoot = fullfile(step4Root,'tables');
figuresRoot = fullfile(step4Root,'figures');
diagnosticsRoot = fullfile(step4Root,'diagnostics');
workspaceRoot = fullfile(step4Root,'workspace');
ensure_directories([string(tablesRoot),string(figuresRoot), ...
    string(diagnosticsRoot),string(workspaceRoot)]);
addpath(matlabRoot);
addpath(step4Root);

frozenBefore = capture_frozen_files(projectRoot,matlabRoot,phase1cRoot);
metadata = capture_metadata(projectRoot,matlabRoot);
cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
selfPF = repmat(cfg.Cself_pF,1,3);
registry = phase1a_case_registry();
registry = registry(ismember(registry.case_name, ...
    ["Case05_fault_only","Case06_drift_then_fault"]),:);
anchors = load_phase1b_anchors(projectRoot);

summaryParts = cell(height(registry),1);
absorptionParts = cell(height(registry),1);
m4Parts = cell(height(registry),1);
m3Parts = cell(height(registry),1);
directionParts = cell(height(registry),1);
cycleParts = cell(height(registry),1);
caseDetails = struct();

for caseIndex = 1:height(registry)
    caseInfo = registry(caseIndex,:);
    fprintf('STEP4_CASE_START=%s seed=%d\n', ...
        caseInfo.case_name,caseInfo.seed);
    signals = generate_coupling_signals( ...
        (0:cfg.Ts:cfg.StopTime).',caseInfo.case_name,caseInfo.seed);
    [data,~] = simulate_phase2_case(cfg, ...
        char(caseInfo.legacy_scenario_name),caseInfo.seed);
    assert_case_integrity(data,signals,caseInfo.case_name);
    ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
        cfg.init_start,cfg.init_end,cfg.phase_error_deg);
    counterfactualData = remove_fault_component(data,signals.fault_scale);

    algorithmResults = struct();
    counterfactualResults = struct();
    for mode = ["M2","M3","M4"]
        algorithmResults.(char(mode)) = run_phase1a_algorithm( ...
            mode,data,ref,cfg,selfPF);
        counterfactualResults.(char(mode)) = run_phase1a_algorithm( ...
            mode,counterfactualData,ref,cfg,selfPF);
    end

    staticBias = anchors.(char(caseInfo.case_name)).static_bias_pF;
    evaluated = evaluate_phase1c_step4_case( ...
        caseInfo,data,counterfactualData,cfg,algorithmResults, ...
        counterfactualResults,metadata,staticBias);
    summaryParts{caseIndex} = evaluated.summary;
    absorptionParts{caseIndex} = evaluated.absorption;
    m4Parts{caseIndex} = evaluated.m4_diagnostics;
    m3Parts{caseIndex} = evaluated.m3_diagnostics;
    directionParts{caseIndex} = evaluated.direction_diagnostics;
    cycleParts{caseIndex} = evaluated.cycle_detail;
    caseDetails.(char(caseInfo.case_name)) = minimal_case_detail( ...
        data,signals,algorithmResults,evaluated.cycle_detail,staticBias);
    fprintf(['STEP4_CASE_COMPLETE=%s M4_factor=%.9f ' ...
        'M4_fault_mean_g=%.9f\n'],caseInfo.case_name, ...
        evaluated.summary.fault_factor_est(3), ...
        evaluated.m4_diagnostics.fault_mean_g);
end

summaryTable = vertcat(summaryParts{:});
absorptionTable = vertcat(absorptionParts{:});
m4Table = vertcat(m4Parts{:});
m3Table = vertcat(m3Parts{:});
directionTable = vertcat(directionParts{:});
cycleDetail = vertcat(cycleParts{:});
prefaultTable = prefault_tracking_table(caseDetails);
regression = validate_frozen_regression( ...
    summaryTable,anchors,projectRoot);
validation = validate_step4(summaryTable,absorptionTable,m4Table, ...
    m3Table,directionTable,cycleDetail,regression);
if ~validation.overall_pass
    error('Phase1C:Step4Validation', ...
        'Step 4 validation failed before M4 interpretation.');
end

summaryPath = fullfile(tablesRoot,'fault_preservation_summary.csv');
absorptionPath = fullfile(tablesRoot,'parameter_absorption_summary.csv');
m4Path = fullfile(tablesRoot,'m4_fault_response_summary.csv');
m3Path = fullfile(tablesRoot,'m3_gate_response_summary.csv');
directionPath = fullfile(diagnosticsRoot,'direction_fault_diagnostics.csv');
cyclePath = fullfile(diagnosticsRoot,'m4_fault_cycle_diagnostics.csv');
prefaultPath = fullfile(diagnosticsRoot,'prefault_tracking_summary.csv');
workspacePath = fullfile(workspaceRoot,'fault_preservation_workspace.mat');
writetable(summaryTable,summaryPath);
writetable(absorptionTable,absorptionPath);
writetable(m4Table,m4Path);
writetable(m3Table,m3Path);
writetable(directionTable,directionPath);
writetable(cycleDetail,cyclePath);
writetable(prefaultTable,prefaultPath);
figurePaths = generate_phase1c_step4_figures( ...
    figuresRoot,summaryTable,caseDetails);

schemaVersion = "phase1c_step4_fault_preservation_v1";
result = struct( ...
    'schema_version',schemaVersion,'cfg',cfg,'case_registry',registry, ...
    'metadata',metadata,'summary_table',summaryTable, ...
    'absorption_table',absorptionTable,'m4_table',m4Table, ...
    'm3_table',m3Table,'direction_table',directionTable, ...
    'cycle_detail',cycleDetail,'prefault_table',prefaultTable, ...
    'case_details',caseDetails, ...
    'anchors',anchors,'regression',regression, ...
    'validation',validation,'figure_paths',figurePaths);
save(workspacePath,'schemaVersion','cfg','registry','metadata', ...
    'summaryTable','absorptionTable','m4Table','m3Table', ...
    'directionTable','cycleDetail','prefaultTable','caseDetails','anchors', ...
    'regression','validation','figurePaths','result','-v7.3');

assert_frozen_unchanged(frozenBefore);
print_results(summaryTable,absorptionTable,m4Table,m3Table, ...
    directionTable,regression,workspacePath);
fprintf('STEP4_EXECUTION_STATUS=PASS\n');
end

function dataOut = remove_fault_component(data,faultScale)
if numel(faultScale) ~= numel(data.t) || any(faultScale <= 0)
    error('Phase1C:Step4FaultScale','Invalid fault-scale vector.');
end
faultIncrementB = (1-1./faultScale).*data.irB;
dataOut = data;
dataOut.ib = data.ib-faultIncrementB;
dataOut.irB = data.irB-faultIncrementB;
preFault = data.t < 3.0;
if max(abs(dataOut.ib(preFault)-data.ib(preFault))) > 0 || ...
        max(abs(dataOut.irB(preFault)-data.irB(preFault))) > 0
    error('Phase1C:Step4Counterfactual', ...
        'Counterfactual differs before fault onset.');
end
end

function assert_case_integrity(data,signals,caseName)
if max(abs(data.Cs1-signals.Cs1_pF)) > 1e-10 || ...
        max(abs(data.Cs2-signals.Cs2_pF)) > 1e-10 || ...
        max(abs(signals.fault_scale)) < 1.5 || ...
        any(signals.fault_scale(data.t < 3.0) ~= 1)
    error('Phase1C:Step4CaseIntegrity', ...
        'Case integrity failed for %s.',caseName);
end
if string(caseName) == "Case05_fault_only" && ...
        (range(data.Cs1) > 1e-10 || range(data.Cs2) > 1e-10)
    error('Phase1C:Step4CaseIntegrity', ...
        'Case05 coupling truth is not constant.');
end
end

function detail = minimal_case_detail( ...
        data,signals,algorithmResults,m4Cycle,staticBias)
detail = struct( ...
    't',data.t,'fault_scale',signals.fault_scale, ...
    'Cs1_true',data.Cs1,'Cs2_true',data.Cs2,'irB_true',data.irB, ...
    'M2_cHist',algorithmResults.M2.cHist, ...
    'M3_cHist',algorithmResults.M3.cHist, ...
    'M4_cHist',algorithmResults.M4.cHist, ...
    'M2_irB',algorithmResults.M2.ir.B, ...
    'M3_irB',algorithmResults.M3.ir.B, ...
    'M4_irB',algorithmResults.M4.ir.B, ...
    'M3_cycle',algorithmResults.M3.tracker.cycle, ...
    'M4_cycle',m4Cycle,'static_bias_pF',staticBias);
end

function anchors = load_phase1b_anchors(projectRoot)
phase1bRoot = fullfile(projectRoot,'paper_research', ...
    'phase1b_fault_absorption');
case05 = readtable(fullfile(phase1bRoot,'step2', ...
    'case05_key_metrics.csv'),'TextType','string');
case06 = readtable(fullfile(phase1bRoot,'step3', ...
    'case06_key_metrics.csv'),'TextType','string');
case05Cycle = readtable(fullfile(phase1bRoot,'step2', ...
    'case05_mechanism_summary.csv'),'TextType','string');
steady05 = case05Cycle.time_start_s >= 3.40 & ...
    case05Cycle.time_end_s < 3.80;
anchors.Case05_fault_only = anchor_struct(case05,mean([ ...
    case05Cycle.delta_Cs1_LS_pred_pF(steady05), ...
    case05Cycle.delta_Cs2_LS_pred_pF(steady05)],1));
anchors.Case06_drift_then_fault = anchor_struct(case06,[ ...
    case06.static_LS_steady_mean_Cs1_pF, ...
    case06.static_LS_steady_mean_Cs2_pF]);
end

function anchor = anchor_struct(row,staticBias)
anchor = struct( ...
    'true_fault_factor',row.true_fault_factor, ...
    'M2_fault_factor',row.M2_actual_fault_factor, ...
    'M3_fault_factor',row.M3_auxiliary_fault_factor, ...
    'M2_fault_induced_DeltaCs1_pF', ...
        row.recursive_fault_induced_Delta_Cs1_pF, ...
    'M2_fault_induced_DeltaCs2_pF', ...
        row.recursive_fault_induced_Delta_Cs2_pF, ...
    'static_bias_pF',staticBias);
end

function regression = validate_frozen_regression(summary,anchors,projectRoot)
baseline = readtable(fullfile(projectRoot,'paper_research', ...
    'phase1a_baseline','baseline_summary.csv'),'TextType','string');
current = summary(ismember(summary.algorithm_mode,["M2","M3"]),:);
baseline = baseline(ismember(baseline.case_name,unique(current.case_name)) & ...
    ismember(baseline.algorithm_mode,["M2","M3"]),:);
current = sortrows(current,{'case_name','algorithm_mode'});
baseline = sortrows(baseline,{'case_name','algorithm_mode'});
formalDifference = [ ...
    current.fault_factor_true-baseline.fault_factor_true, ...
    current.fault_factor_est-baseline.fault_factor_est, ...
    current.fault_retention_error_pct- ...
        baseline.fault_retention_error_pct, ...
    current.DeltaCs1_pre_post_pF-baseline.Cs1_pre_post_change_pF, ...
    current.DeltaCs2_pre_post_pF-baseline.Cs2_pre_post_change_pF];

caseNames = ["Case05_fault_only","Case06_drift_then_fault"];
phase1bDifference = zeros(2,5);
for k = 1:2
    caseName = caseNames(k);
    anchor = anchors.(char(caseName));
    m2 = summary(summary.case_name == caseName & ...
        summary.algorithm_mode == "M2",:);
    m3 = summary(summary.case_name == caseName & ...
        summary.algorithm_mode == "M3",:);
    phase1bDifference(k,:) = [ ...
        m2.fault_factor_true-anchor.true_fault_factor, ...
        m2.fault_factor_est-anchor.M2_fault_factor, ...
        m3.fault_factor_est-anchor.M3_fault_factor, ...
        m2.DeltaCs1_fault_induced_pF- ...
            anchor.M2_fault_induced_DeltaCs1_pF, ...
        m2.DeltaCs2_fault_induced_pF- ...
            anchor.M2_fault_induced_DeltaCs2_pF];
end
regression = struct( ...
    'formal_max_abs_difference',max(abs(formalDifference),[],'all'), ...
    'phase1b_anchor_max_abs_difference', ...
        max(abs(phase1bDifference),[],'all'), ...
    'formal_workspace_equivalent',all(abs(formalDifference) <= 1e-12,'all'), ...
    'phase1b_anchor_pass',all(abs(phase1bDifference) <= 1e-10,'all'));
regression.pass = regression.formal_workspace_equivalent && ...
    regression.phase1b_anchor_pass;
end

function validation = validate_step4(summary,absorption,m4,m3,direction, ...
        cycle,regression)
validation = struct( ...
    'summary_rows',height(summary), ...
    'absorption_rows',height(absorption), ...
    'm4_rows',height(m4),'m3_rows',height(m3), ...
    'direction_rows',height(direction), ...
    'cycle_cases',numel(unique(cycle.case_name)), ...
    'regression_pass',regression.pass, ...
    'weights_valid',all(cycle.update_weight > 0 & ...
        cycle.update_weight <= 1), ...
    'core_metrics_finite',all(isfinite([ ...
        summary.fault_factor_true;summary.fault_factor_est; ...
        summary.fault_retention_error_pct; ...
        summary.DeltaCs1_fault_induced_pF; ...
        summary.DeltaCs2_fault_induced_pF])), ...
    'material_latency_finite',all(isfinite( ...
        m4.material_suppression_latency_s)), ...
    'gate_latency_finite',all(isfinite(m3.hard_gate_latency_s)));
validation.overall_pass = validation.summary_rows == 6 && ...
    validation.absorption_rows == 4 && validation.m4_rows == 2 && ...
    validation.m3_rows == 2 && validation.direction_rows == 4 && ...
    validation.cycle_cases == 2 && validation.regression_pass && ...
    validation.weights_valid && validation.core_metrics_finite && ...
    validation.gate_latency_finite;
end

function ensure_directories(paths)
for path = paths
    if ~isfolder(path)
        mkdir(path);
    end
end
end

function frozen = capture_frozen_files(projectRoot,matlabRoot,phase1cRoot)
paths = [ ...
    string(fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx'))
    string(fullfile(matlabRoot,'track_coupling_cvff_rls.m'))
    string(fullfile(matlabRoot,'track_coupling_m4_weighted_rls.m'))
    string(fullfile(matlabRoot,'m4_fault_evidence.m'))
    string(fullfile(matlabRoot,'patent_default_config.m'))
    string(fullfile(matlabRoot,'phase1a_case_registry.m'))
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_summary.csv'))
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_workspace.mat'))
    string(fullfile(projectRoot,'paper_research', ...
        'phase1b_fault_absorption','step2','case05_key_metrics.csv'))
    string(fullfile(projectRoot,'paper_research', ...
        'phase1b_fault_absorption','step3','case06_key_metrics.csv'))
    string(fullfile(phase1cRoot,'STEP1_M4_METHOD_SPECIFICATION.md'))
    string(fullfile(phase1cRoot,'STEP2_M4_IMPLEMENTATION.md'))
    string(fullfile(phase1cRoot,'STEP3_NORMAL_TRACKING_VERIFICATION.md'))];
hash = strings(size(paths));
for k = 1:numel(paths)
    hash(k) = file_sha256(paths(k));
end
frozen = table(paths,hash,'VariableNames',{'path','sha256'});
end

function assert_frozen_unchanged(frozen)
for k = 1:height(frozen)
    if file_sha256(frozen.path(k)) ~= frozen.sha256(k)
        error('Phase1C:Step4FrozenFile', ...
            'Frozen file changed during Step 4: %s.',frozen.path(k));
    end
end
end

function metadata = capture_metadata(projectRoot,matlabRoot)
[commitCode,commit] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1C:Step4GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'model_sha256',file_sha256( ...
        fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx')), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_dirty_status',dirty_label(status), ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function label = dirty_label(status)
if strlength(strtrim(string(status))) == 0
    label = "CLEAN";
else
    label = "DIRTY";
end
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1C:Step4Hash','Unable to open %s.',path);
end
cleanupObject = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
clear cleanupObject
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_results(summary,absorption,m4,m3,direction, ...
        regression,workspacePath)
disp(summary);
disp(absorption);
disp(m4);
disp(m3);
disp(direction);
fprintf('STEP4_FORMAL_MAX_ABS=%.17g\n', ...
    regression.formal_max_abs_difference);
fprintf('STEP4_PHASE1B_ANCHOR_MAX_ABS=%.17g\n', ...
    regression.phase1b_anchor_max_abs_difference);
fprintf('STEP4_REGRESSION_PASS=%s\n',string(regression.pass));
fprintf('STEP4_WORKSPACE=%s\n',workspacePath);
end
