function result = run_phase1b_step4_controlled_factors()
%RUN_PHASE1B_STEP4_CONTROLLED_FACTORS Run 11 formal one-factor conditions.

step4Root = fileparts(mfilename('fullpath'));
phase1bRoot = fileparts(step4Root);
projectRoot = fileparts(fileparts(phase1bRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
step2Root = fullfile(phase1bRoot,'step2');
step3Root = fullfile(phase1bRoot,'step3');
figuresRoot = fullfile(step4Root,'figures');
addpath(matlabRoot);
addpath(step2Root);
addpath(step4Root);
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

frozen = frozen_files(projectRoot,matlabRoot,phase1bRoot,step2Root,step3Root);
assert_frozen_integrity(frozen);
runMetadata = capture_metadata(projectRoot,frozen);

cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
cfg.output_dir = step4Root;
seed = 106;
selfPF = repmat(cfg.Cself_pF,1,3);
conditionTable = formal_conditions(seed);
nConditions = height(conditionTable);
executionOrder = [6,1:5,7:nConditions];
summaryRows = cell(nConditions,1);
cycleTables = cell(nConditions,1);
validationRows = cell(nConditions,1);
noiseRows = cell(nConditions,1);

baselineData = struct();
baselineSignals = struct();
baselineNoise = struct();
baselineValidation = struct();

for executionIndex = 1:numel(executionOrder)
    k = executionOrder(executionIndex);
    condition = conditionTable(k,:);
    fprintf('STEP4_CONDITION_START=%s (%d/%d)\n', ...
        condition.condition_id,executionIndex,nConditions);

    if condition.factor_type == "fault_amplitude"
        [data,signals,noiseInfo] = simulate_step4_fault_amplitude( ...
            cfg,seed,condition.fault_factor_target);
        if k == 6
            baselineData = data;
            baselineSignals = signals;
            baselineNoise = noiseInfo;
        end
    else
        data = baselineData;
        signals = baselineSignals;
        noiseInfo = baselineNoise;
    end

    ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
        cfg.init_start,cfg.init_end,condition.reference_phase_error_deg);
    [summaryRow,cycleTable,conditionValidation,details] = ...
        evaluate_step4_condition( ...
        data,signals,ref,cfg,selfPF,condition);

    if k == 6
        baselineValidation = validate_step2_baseline( ...
            data,signals,ref,details,summaryRow,step2Root);
        if ~baselineValidation.overall_pass
            error('Phase1B:Step4Baseline', ...
                'The shared 1.60 + 0 deg baseline did not reproduce Step 2.');
        end
    end

    noiseConsistency = noise_consistency( ...
        condition,noiseInfo,baselineNoise,k == 6);
    summaryRow.noise_signature_max_abs = ...
        noiseConsistency.normalized_signature_max_abs;
    summaryRows{k} = summaryRow;
    cycleTables{k} = cycleTable;
    validationRows{k} = validation_to_row( ...
        condition.condition_id,conditionValidation);
    noiseRows{k} = noiseConsistency;
    if ~conditionValidation.overall_pass
        error('Phase1B:Step4Condition', ...
            'Mechanism validation failed for %s.',condition.condition_id);
    end
    fprintf(['STEP4_CONDITION_COMPLETE=%s eta=%.9f ' ...
        'faultBias=%.6f,%.6f factor=%.6f\n'], ...
        condition.condition_id,summaryRow.eta_geom_post, ...
        summaryRow.DeltaCs1_fault_induced, ...
        summaryRow.DeltaCs2_fault_induced,summaryRow.fault_factor_est);
    clear data signals noiseInfo ref details cycleTable
end

summaryTable = struct2table(vertcat(summaryRows{:}),'AsArray',true);
summaryTable = sortrows(summaryTable,'condition_order');
cycleDetail = vertcat(cycleTables{:});
cycleDetail = sortrows(cycleDetail,{'condition_order','cycle_index'});
validationTable = struct2table(vertcat(validationRows{:}),'AsArray',true);
noiseConsistencyTable = struct2table(vertcat(noiseRows{:}),'AsArray',true);

formalValidation = validate_formal_design( ...
    conditionTable,summaryTable,validationTable,noiseConsistencyTable, ...
    baselineValidation);
if ~formalValidation.overall_pass
    error('Phase1B:Step4FormalValidation', ...
        'The controlled-factor design failed formal validation.');
end

summaryPath = fullfile(step4Root,'controlled_factor_summary.csv');
cyclePath = fullfile(step4Root,'controlled_factor_cycles.csv');
validationPath = fullfile(step4Root,'controlled_factor_validation.csv');
noisePath = fullfile(step4Root,'controlled_factor_noise_consistency.csv');
workspacePath = fullfile(step4Root,'controlled_factor_workspace.mat');
writetable(summaryTable,summaryPath);
writetable(cycleDetail,cyclePath);
writetable(validationTable,validationPath);
writetable(noiseConsistencyTable,noisePath);
figurePaths = generate_phase1b_step4_figures(figuresRoot,summaryTable);

referencePhaseConvention = struct( ...
    'entry_point',"reconstruct_refs_from_b", ...
    'unit',"degree", ...
    'sign_convention', ...
        "positive error advances the reconstructed reference phase", ...
    'fundamental_definition',"phi1 = fitted_phi1 + deg2rad(delta)", ...
    'third_harmonic_definition',"phi3 = fitted_phi3 + 3*deg2rad(delta)", ...
    'physical_fault_waveform_modified',false);
schemaVersion = "phase1b_mechanism_v1";
result = struct( ...
    'schema_version',schemaVersion, ...
    'runMetadata',runMetadata, ...
    'conditionTable',conditionTable, ...
    'summaryTable',summaryTable, ...
    'cycleDetail',cycleDetail, ...
    'validationTable',validationTable, ...
    'noiseConsistencyTable',noiseConsistencyTable, ...
    'baselineValidation',baselineValidation, ...
    'formalValidation',formalValidation, ...
    'referencePhaseConvention',referencePhaseConvention, ...
    'figurePaths',figurePaths, ...
    'summaryPath',string(summaryPath), ...
    'cyclePath',string(cyclePath), ...
    'workspacePath',string(workspacePath));
save(workspacePath,'schemaVersion','cfg','conditionTable','summaryTable', ...
    'cycleDetail','validationTable','noiseConsistencyTable', ...
    'baselineValidation','formalValidation','referencePhaseConvention', ...
    'runMetadata','figurePaths','result','-v7.3');

assert_frozen_integrity(frozen);
print_key_results(summaryTable,baselineValidation,formalValidation, ...
    summaryPath,workspacePath);
fprintf('STEP4_CONTROLLED_FACTOR_EXPERIMENTS=PASS\n');
end

function conditions = formal_conditions(seed)
conditionId = [ ...
    "fault_factor_1p05"
    "fault_factor_1p10"
    "fault_factor_1p20"
    "fault_factor_1p30"
    "fault_factor_1p40"
    "fault_factor_1p60_phase_0deg"
    "phase_error_0p33deg"
    "phase_error_0p50deg"
    "phase_error_1p00deg"
    "phase_error_2p00deg"
    "phase_error_3p00deg"];
conditionOrder = (1:11).';
factorType = [repmat("fault_amplitude",6,1); ...
    repmat("reference_phase_error",5,1)];
factorValue = [1.05;1.10;1.20;1.30;1.40;1.60;0.33;0.50;1;2;3];
faultFactorTarget = [1.05;1.10;1.20;1.30;1.40;1.60; ...
    repmat(1.60,5,1)];
referencePhaseErrorDeg = [zeros(6,1);0.33;0.50;1;2;3];
amplitudeSweepMember = [true(6,1);false(5,1)];
phaseSweepMember = [false(5,1);true;true(5,1)];
seedColumn = repmat(seed,11,1);
conditions = table(conditionId,conditionOrder,factorType,factorValue, ...
    faultFactorTarget,referencePhaseErrorDeg,amplitudeSweepMember, ...
    phaseSweepMember,seedColumn,'VariableNames', ...
    {'condition_id','condition_order','factor_type','factor_value', ...
    'fault_factor_target','reference_phase_error_deg', ...
    'amplitude_sweep_member','phase_sweep_member','seed'});
end

function validation = validate_step2_baseline( ...
        data,signals,ref,details,summaryRow,step2Root)
formal = load(fullfile(step2Root,'case05_mechanism_workspace.mat'), ...
    'data','signals','ref','originalM2','instrumented');
key = readtable(fullfile(step2Root,'case05_key_metrics.csv'), ...
    'TextType','string');
dataNames = {'t','ua','ub','uc','ia','ib','ic','irA','irB','irC', ...
    'Cs1','Cs2'};
dataError = 0;
for k = 1:numel(dataNames)
    name = dataNames{k};
    dataError = max(dataError,max(abs(data.(name)-formal.data.(name))));
end
refNames = {'ua','ub','uc','dua','dub','duc','A1','A3','phi1','phi3'};
refError = 0;
for k = 1:numel(refNames)
    name = refNames{k};
    refError = max(refError,max(abs(ref.(name)-formal.ref.(name)),[],'all'));
end
validation = struct();
validation.data_max_abs = dataError;
validation.fault_scale_max_abs = max(abs( ...
    signals.fault_scale-formal.signals.fault_scale));
validation.reference_max_abs = refError;
validation.M2_hist_max_abs = max(abs( ...
    details.originalM2.hist-formal.originalM2.hist),[],'all');
validation.M2_cycle_max_abs = max(abs( ...
    details.originalM2.cycle{:,:}-formal.originalM2.cycle{:,:}),[],'all');
validation.instrumented_fault_hist_max_abs = max(abs( ...
    details.instrumented.fault.hist-formal.instrumented.fault.hist),[],'all');
validation.instrumented_counterfactual_hist_max_abs = max(abs( ...
    details.instrumented.counterfactual.hist- ...
    formal.instrumented.counterfactual.hist),[],'all');
validation.key_metric_max_abs = max(abs([ ...
    summaryRow.fault_factor_true-key.true_fault_factor, ...
    summaryRow.fault_factor_est-key.M2_actual_fault_factor, ...
    summaryRow.DeltaCs1_actual_M2-key.M2_actual_Delta_Cs1_pF, ...
    summaryRow.DeltaCs2_actual_M2-key.M2_actual_Delta_Cs2_pF, ...
    summaryRow.DeltaCs1_fault_induced- ...
        key.recursive_fault_induced_Delta_Cs1_pF, ...
    summaryRow.DeltaCs2_fault_induced- ...
        key.recursive_fault_induced_Delta_Cs2_pF, ...
    summaryRow.eta_geom_ramp-key.eta_geom_fault_ramp_mean, ...
    summaryRow.eta_geom_post-key.eta_geom_post_fault_mean, ...
    summaryRow.false_compensation_ratio- ...
        key.delta_coupling_to_fault_fundamental_ratio, ...
    summaryRow.false_compensation_phase- ...
        key.delta_coupling_fault_phase_difference_deg]));
allErrors = [validation.data_max_abs,validation.fault_scale_max_abs, ...
    validation.reference_max_abs,validation.M2_hist_max_abs, ...
    validation.M2_cycle_max_abs, ...
    validation.instrumented_fault_hist_max_abs, ...
    validation.instrumented_counterfactual_hist_max_abs, ...
    validation.key_metric_max_abs];
validation.max_abs = max(allErrors);
validation.overall_pass = all(allErrors <= 1e-12);
end

function row = noise_consistency(condition,noiseInfo,baselineNoise,isBaseline)
if isBaseline
    signatureError = 0;
else
    signatureError = max(abs([ ...
        noiseInfo.normalizedA-baselineNoise.normalizedA; ...
        noiseInfo.normalizedB-baselineNoise.normalizedB; ...
        noiseInfo.normalizedC-baselineNoise.normalizedC]));
end
row = struct( ...
    'condition_id',string(condition.condition_id), ...
    'configured_SNR_dB',noiseInfo.configured_SNR_dB, ...
    'realized_SNR_A_dB',noiseInfo.realized_SNR_A_dB, ...
    'realized_SNR_B_dB',noiseInfo.realized_SNR_B_dB, ...
    'realized_SNR_C_dB',noiseInfo.realized_SNR_C_dB, ...
    'normalized_signature_max_abs',signatureError);
end

function row = validation_to_row(conditionId,validation)
row = validation;
row.condition_id = string(conditionId);
end

function validation = validate_formal_design( ...
        conditionTable,summaryTable,validationTable,noiseTable,baseline)
validation = struct();
validation.unique_condition_count = numel(unique(summaryTable.condition_id));
validation.amplitude_condition_count = sum(summaryTable.amplitude_sweep_member);
validation.phase_condition_count = sum(summaryTable.phase_sweep_member);
validation.registry_matches = isequal( ...
    sort(summaryTable.condition_id),sort(conditionTable.condition_id));
validation.all_condition_checks_pass = all( ...
    validationTable.overall_pass);
validation.noise_signature_max_abs = max( ...
    noiseTable.normalized_signature_max_abs);
validation.baseline_pass = baseline.overall_pass;
validation.no_cherry_picking = height(summaryTable) == 11 && ...
    validation.registry_matches;
validation.overall_pass = validation.unique_condition_count == 11 && ...
    validation.amplitude_condition_count == 6 && ...
    validation.phase_condition_count == 6 && ...
    validation.all_condition_checks_pass && ...
    validation.noise_signature_max_abs <= 1e-12 && ...
    validation.baseline_pass && validation.no_cherry_picking;
end

function frozen = frozen_files( ...
        projectRoot,matlabRoot,phase1bRoot,step2Root,step3Root)
frozen = table( ...
    ["model";"baseline_csv";"baseline_workspace";"step1_report"; ...
    "step2_report";"step3_report";"step2_workspace"; ...
    "step3_workspace";"step2_summary";"step3_summary"; ...
    "step2_observations";"step3_observations";"tracker"; ...
    "dispatcher";"reference_reconstruction";"default_config"], ...
    [string(fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx')); ...
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_summary.csv')); ...
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_workspace.mat')); ...
    string(fullfile(phase1bRoot,'STEP1_THEORY_AND_DATA_DEFINITION.md')); ...
    string(fullfile(phase1bRoot,'STEP2_BASELINE_MECHANISM.md')); ...
    string(fullfile(phase1bRoot,'STEP3_CASE06_VERIFICATION.md')); ...
    string(fullfile(step2Root,'case05_mechanism_workspace.mat')); ...
    string(fullfile(step3Root,'case06_mechanism_workspace.mat')); ...
    string(fullfile(step2Root,'case05_mechanism_summary.csv')); ...
    string(fullfile(step3Root,'case06_mechanism_summary.csv')); ...
    string(fullfile(step2Root,'observation_blocks_case05.mat')); ...
    string(fullfile(step3Root,'observation_blocks_case06.mat')); ...
    string(fullfile(matlabRoot,'track_coupling_cvff_rls.m')); ...
    string(fullfile(matlabRoot,'run_phase1a_algorithm.m')); ...
    string(fullfile(matlabRoot,'reconstruct_refs_from_b.m')); ...
    string(fullfile(matlabRoot,'patent_default_config.m'))], ...
    ["56067ADAADF59B5921D7156A2ABB61777C4E98B69CB4150759C3CB1D4D6A2A70"; ...
    "E7BEB3ECFEDF521105B67198684752BB32AFAAEFD84ACA80822BA57FBD9D0AB3"; ...
    "A90632B72479E7B6ADC4E410DB37542E9CA4985CA8381B6BAFC8F71C961E87B5"; ...
    "02859DD0D35E35C18722B452DC7A5C9EE73B55CC6E7A26FC5566500F6E4B9041"; ...
    "C98A2D9C53D6986EB4B9C202BEBC00DDD3A197B147615F68D5D073B652275CC1"; ...
    "983BB31BDB297C7DC8086C663D85A2ADA3ED62717E48274AB722051A0371844F"; ...
    "AA585D987828728479BE4C521DFEFBD339120ECBD30C9E1DD9FAED216587A112"; ...
    "9E3190869BCF764841F062EDB0F152DADE56D1DDA2F3C85B55F0DD4915C553A4"; ...
    "F20A07ED08120951245A5F96342FBB1B051040C427154BD274779E8145E57A74"; ...
    "009969AF53D04BCFBAECF4B812C53C50D20D299383285A99156B32B5988D6238"; ...
    "1169CA3246FD790D09DC7B908C24AB55485E068A6AE9690D2FFBAA35A37CA32B"; ...
    "897FD061F277A920D0FCED7F98421759A51BB49040749CFA86DB8F67F4B6B279"; ...
    "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"; ...
    "5CA47CA0EC43C79058A24756BCD538D66FDF73087B08102A55570B1154E6B2C5"; ...
    "0B79D411ECF0EBFD9E814A2CE59FF3368DED845DA54CA99F689256254251FAFE"; ...
    "D9F3E6894F51C3D978421C9E1E93828A9205F418C77D01AC449B994A3D789726"], ...
    'VariableNames',{'name','path','expected_sha256'});
end

function assert_frozen_integrity(frozen)
for k = 1:height(frozen)
    actual = file_sha256(frozen.path(k));
    if actual ~= frozen.expected_sha256(k)
        error('Phase1B:Integrity','Frozen file changed: %s.',frozen.name(k));
    end
end
end

function metadata = capture_metadata(projectRoot,frozen)
[commitCode,commit] = system(sprintf('git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1B:GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_status',string(status), ...
    'frozen_manifest',frozen, ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1B:HashFailure','Unable to open %s.',path);
end
cleanupObj = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
clear cleanupObj
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_key_results(summaryTable,baseline,formal,summaryPath,workspacePath)
amplitude = sortrows(summaryTable(summaryTable.amplitude_sweep_member,:), ...
    'fault_factor_target');
phase = sortrows(summaryTable(summaryTable.phase_sweep_member,:), ...
    'reference_phase_error_deg');
fprintf('BASELINE_REPRODUCTION_MAX=%.17g\n',baseline.max_abs);
fprintf('FORMAL_CONDITION_COUNTS=%d,%d,%d\n', ...
    formal.unique_condition_count,formal.amplitude_condition_count, ...
    formal.phase_condition_count);
fprintf('AMPLITUDE_ETA_POST_RANGE=%.17g,%.17g\n', ...
    min(amplitude.eta_geom_post),max(amplitude.eta_geom_post));
fprintf('AMPLITUDE_FAULT_BIAS_CS1_RANGE=%.17g,%.17g\n', ...
    min(amplitude.DeltaCs1_fault_induced), ...
    max(amplitude.DeltaCs1_fault_induced));
fprintf('PHASE_ETA_POST_RANGE=%.17g,%.17g\n', ...
    min(phase.eta_geom_post),max(phase.eta_geom_post));
fprintf('PHASE_RETENTION_ERROR_RANGE=%.17g,%.17g\n', ...
    min(phase.fault_retention_error),max(phase.fault_retention_error));
fprintf('RATE_LIMIT_MAX=%d PROJECTION_MAX=%d\n', ...
    max(summaryTable.rate_limit_cycles),max(summaryTable.projection_cycles));
fprintf('SUMMARY_CSV=%s\n',summaryPath);
fprintf('WORKSPACE_MAT=%s\n',workspacePath);
end
