classdef M4WeightedInformationUpdateTest < matlab.unittest.TestCase
    %M4WEIGHTEDINFORMATIONUPDATETEST Structural tests for M4-v0.

    methods (TestClassSetup)
        function addProjectPath(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(root));
        end
    end

    methods (Test)
        function testForcedOneReproducesM2(testCase)
            [data,ref,cfg,selfPF] = ...
                M4WeightedInformationUpdateTest.fixtureData();
            m2 = track_coupling_cvff_rls(data,ref,cfg,selfPF,false);
            m4 = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF,struct('forced_update_weight',1));
            reference = M4WeightedInformationUpdateTest.m2StateReference( ...
                data,ref,cfg,selfPF);
            irM2 = extract_resistive_current(data,ref,selfPF,m2.hist);
            irM4 = extract_resistive_current(data,ref,selfPF,m4.hist);

            testCase.verifyEqual(m4.hist,m2.hist,'AbsTol',1e-12);
            testCase.verifyEqual(m4.cycle.Cs1_pF,m2.cycle.Cs1_pF, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(m4.cycle.Cs2_pF,m2.cycle.Cs2_pF, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(m4.cycle.lambda,m2.cycle.lambda, ...
                'AbsTol',1e-15);
            testCase.verifyEqual(m4.cycle.base_in,m2.cycle.base_in, ...
                'AbsTol',1e-15);
            testCase.verifyEqual(m4.cycle{:,{'J_11','J_12','J_21','J_22'}}, ...
                reference{:,{'J_11','J_12','J_21','J_22'}}, ...
                'RelTol',5e-14,'AbsTol',1e-18);
            testCase.verifyEqual(m4.cycle{:,{'h_1','h_2'}}, ...
                reference{:,{'h_1','h_2'}}, ...
                'RelTol',5e-14,'AbsTol',1e-18);
            testCase.verifyEqual(m4.cycle.rate_limit_active, ...
                reference.rate_limit_active);
            testCase.verifyEqual(m4.cycle.projection_active, ...
                reference.projection_active);
            testCase.verifyEqual(irM4.A,irM2.A,'AbsTol',1e-15);
            testCase.verifyEqual(irM4.B,irM2.B,'AbsTol',1e-15);
            testCase.verifyEqual(irM4.C,irM2.C,'AbsTol',1e-15);
        end

        function testForcedZeroFreezesAllRecursiveStates(testCase)
            [data,ref,cfg,selfPF] = ...
                M4WeightedInformationUpdateTest.fixtureData();
            options = struct('forced_update_weight',0);

            result = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF,options);

            testCase.verifyEqual(result.cycle.update_weight, ...
                zeros(height(result.cycle),1),'AbsTol',0);
            testCase.verifyEqual(result.cycle.Cs1_pF, ...
                repmat(result.initial_state.c(1),height(result.cycle),1), ...
                'AbsTol',0);
            testCase.verifyEqual(result.cycle.Cs2_pF, ...
                repmat(result.initial_state.c(2),height(result.cycle),1), ...
                'AbsTol',0);
            testCase.verifyEqual(result.cycle{:,{'J_11','J_12','J_21','J_22'}}, ...
                repmat(reshape(result.initial_state.J.',1,4), ...
                height(result.cycle),1),'AbsTol',0);
            testCase.verifyEqual(result.cycle{:,{'h_1','h_2'}}, ...
                repmat(result.initial_state.h(:).',height(result.cycle),1), ...
                'AbsTol',0);
            testCase.verifyEqual(diff(result.cycle.base_in), ...
                zeros(height(result.cycle)-1,1),'AbsTol',0);
            testCase.verifyEqual(result.cycle.delta_c_applied_1, ...
                zeros(height(result.cycle),1),'AbsTol',0);
            testCase.verifyEqual(result.cycle.delta_c_applied_2, ...
                zeros(height(result.cycle),1),'AbsTol',0);
        end

        function testForcedHalfScalesInformationAndBaselineIncrements(testCase)
            [data,ref,cfg,selfPF] = ...
                M4WeightedInformationUpdateTest.fixtureData();
            options = struct('forced_update_weight',0.5);

            result = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF,options);

            testCase.verifyEqual(result.cycle.update_weight, ...
                0.5*ones(height(result.cycle),1),'AbsTol',0);
            testCase.verifyEqual( ...
                result.cycle{:,{'J_increment_applied_11', ...
                'J_increment_applied_12','J_increment_applied_21', ...
                'J_increment_applied_22'}}, ...
                0.5*result.cycle{:,{'J_increment_raw_11', ...
                'J_increment_raw_12','J_increment_raw_21', ...
                'J_increment_raw_22'}}, ...
                'RelTol',5e-14,'AbsTol',1e-20);
            testCase.verifyEqual( ...
                result.cycle{:,{'h_increment_applied_1', ...
                'h_increment_applied_2'}}, ...
                0.5*result.cycle{:,{'h_increment_raw_1', ...
                'h_increment_raw_2'}}, ...
                'RelTol',5e-14,'AbsTol',1e-20);
            testCase.verifyEqual( ...
                result.cycle.base_in_increment_applied, ...
                0.5*result.cycle.base_in_increment_candidate, ...
                'RelTol',5e-14,'AbsTol',5e-20);
        end

        function testEvidenceMonotonicity(testCase)
            baseIn = 1;
            Equad = ones(1,101);
            Ein = linspace(0.5,3,101);

            evidence = m4_fault_evidence( ...
                Ein,Equad,baseIn,1.12,1.20,NaN);

            testCase.verifyGreaterThanOrEqual( ...
                diff(evidence.score),-1e-14);
            testCase.verifyLessThanOrEqual( ...
                diff(evidence.update_weight),1e-14);
            testCase.verifyGreaterThan(evidence.update_weight,0);
            testCase.verifyLessThanOrEqual(evidence.update_weight,1);
            testCase.verifyEqual(evidence.update_weight(Ein<=baseIn), ...
                ones(size(evidence.update_weight(Ein<=baseIn))), ...
                'AbsTol',0);
        end

        function testPhaseConsistencyIsMonotonic(testCase)
            baseIn = 1;
            Ein = 1.5*ones(1,101);
            ratioQuad = linspace(0.05,2.0,101);
            Equad = Ein./ratioQuad;

            evidence = m4_fault_evidence( ...
                Ein,Equad,baseIn,1.12,1.20,NaN);

            testCase.verifyGreaterThanOrEqual( ...
                diff(evidence.phase_weight),-1e-14);
            testCase.verifyGreaterThanOrEqual( ...
                diff(evidence.score),-1e-14);
            testCase.verifyLessThanOrEqual( ...
                diff(evidence.update_weight),1e-14);
        end

        function testControlPathHasNoTruthLeakage(testCase)
            trackerSource = fileread( ...
                which('track_coupling_m4_weighted_rls'));
            evidenceSource = fileread(which('m4_fault_evidence'));
            source = [trackerSource,newline,evidenceSource];
            forbidden = [ ...
                'Cs1_true|Cs2_true|fault_factor_true|fault_label|' ...
                'r_fault|counterfactual|Case05|Case06|case_name'];

            matches = regexp(source,forbidden,'match');

            testCase.verifyEmpty(matches);
        end

        function testDirectionDiagnosticsDoNotAffectControl(testCase)
            [data,ref,cfg,selfPF] = ...
                M4WeightedInformationUpdateTest.fixtureData();
            enabled = struct('forced_update_weight',0.5, ...
                'direction_diagnostics_enabled',true);
            disabled = struct('forced_update_weight',0.5, ...
                'direction_diagnostics_enabled',false);
            controlVariables = { ...
                'Cs1_pF','Cs2_pF','lambda','base_in', ...
                'fault_evidence_score','update_weight', ...
                'delta_c_raw_1','delta_c_raw_2', ...
                'delta_c_applied_1','delta_c_applied_2', ...
                'J_11','J_12','J_21','J_22','h_1','h_2'};

            resultEnabled = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF,enabled);
            resultDisabled = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF,disabled);

            testCase.verifyEqual(resultEnabled.hist,resultDisabled.hist, ...
                'AbsTol',0);
            testCase.verifyEqual( ...
                resultEnabled.cycle{:,controlVariables}, ...
                resultDisabled.cycle{:,controlVariables},'AbsTol',0);
            testCase.verifyFalse( ...
                any(resultDisabled.cycle.direction_candidate_valid));
            testCase.verifyTrue(all(isnan( ...
                resultDisabled.cycle.cos_local_fault)));
            testCase.verifyTrue(all(isnan( ...
                resultDisabled.cycle.cos_raw_fault)));
        end

        function testRequiredLogSchemaIsPresent(testCase)
            [data,ref,cfg,selfPF] = ...
                M4WeightedInformationUpdateTest.fixtureData();
            required = M4WeightedInformationUpdateTest.requiredLogNames();

            result = track_coupling_m4_weighted_rls( ...
                data,ref,cfg,selfPF);

            testCase.verifyTrue(all(ismember( ...
                required,result.cycle.Properties.VariableNames)));
            testCase.verifyTrue(all(isfinite( ...
                result.cycle.update_weight)));
            testCase.verifyGreaterThan(result.cycle.update_weight,0);
            testCase.verifyLessThanOrEqual(result.cycle.update_weight,1);
        end
    end

    methods (Static, Access=private)
        function [data,ref,cfg,selfPF] = fixtureData()
            cfg = patent_default_config();
            cfg.Ts = 2e-4;
            cfg.StopTime = 1.2;
            cfg.SNR_dB = Inf;
            time = (0:cfg.Ts:cfg.StopTime).';
            omega = 2*pi*cfg.f;
            voltageAmplitude = sqrt(2)*cfg.Uph;
            phase = [2*pi/3,0,-2*pi/3];
            ref = struct( ...
                'ua',voltageAmplitude*sin(omega*time+phase(1)), ...
                'ub',voltageAmplitude*sin(omega*time+phase(2)), ...
                'uc',voltageAmplitude*sin(omega*time+phase(3)), ...
                'dua',omega*voltageAmplitude*cos(omega*time+phase(1)), ...
                'dub',omega*voltageAmplitude*cos(omega*time+phase(2)), ...
                'duc',omega*voltageAmplitude*cos(omega*time+phase(3)), ...
                'phi1',0,'phi3',0);
            selfPF = repmat(cfg.Cself_pF,1,3);
            coupling = [12;8];
            resistiveAmplitude = sqrt(2)*cfg.moa_Iref_A;
            irA = resistiveAmplitude*sin(omega*time+phase(1));
            irB = resistiveAmplitude*sin(omega*time+phase(2));
            irC = resistiveAmplitude*sin(omega*time+phase(3));
            ia = selfPF(1)*1e-12.*ref.dua+ ...
                coupling(1)*1e-12.*(ref.dua-ref.dub)+irA;
            ib = selfPF(2)*1e-12.*ref.dub+ ...
                coupling(1)*1e-12.*(ref.dub-ref.dua)+ ...
                coupling(2)*1e-12.*(ref.dub-ref.duc)+irB;
            ic = selfPF(3)*1e-12.*ref.duc+ ...
                coupling(2)*1e-12.*(ref.duc-ref.dub)+irC;
            data = struct('t',time,'ia',ia,'ib',ib,'ic',ic);
        end

        function reference = m2StateReference(data,ref,cfg,selfPF)
            time = data.t;
            sampleRate = 1/median(diff(time));
            samplesPerCycle = round(sampleRate/cfg.f);
            c = initial_coupling_estimate(data,ref,cfg,selfPF);
            initializationIndex = ...
                time >= cfg.init_start & time < cfg.init_end;
            [X0,~] = coupling_regressor( ...
                data,ref,initializationIndex,selfPF);
            J = 0.05*(X0'*X0)+1e-8*eye(2);
            h = J*c;
            baseIn = NaN;
            rows = struct([]);
            startIndex = find(time >= cfg.init_end,1);
            startIndex = floor((startIndex-1)/samplesPerCycle)* ...
                samplesPerCycle+1;
            for cycleStart = startIndex:samplesPerCycle: ...
                    (numel(time)-samplesPerCycle+1)
                index = cycleStart:(cycleStart+samplesPerCycle-1);
                [X,y] = coupling_regressor(data,ref,index,selfPF);
                R = X'*X;
                z = X'*y;
                localLs = (R+1e-10*eye(2))\z;
                innovation = norm((localLs-c)./[5;5]);
                lambda = cfg.lambda_max- ...
                    (cfg.lambda_max-cfg.lambda_min)* ...
                    min(max(innovation/0.20,0),1);
                [Ein,~] = ...
                    M4WeightedInformationUpdateTest.residualComponents( ...
                    data,ref,index,c,selfPF,cfg.f);
                if isnan(baseIn)
                    baseIn = Ein;
                end
                J = lambda*J+R;
                h = lambda*h+z;
                cRaw = (J+1e-10*eye(2))\h;
                deltaRaw = cRaw-c;
                deltaRate = max(min(deltaRaw, ...
                    cfg.rate_limit_pF_per_cycle), ...
                    -cfg.rate_limit_pF_per_cycle);
                cAfterRate = c+deltaRate;
                cFinal = min(max(cAfterRate, ...
                    cfg.coupling_bounds_pF(1)), ...
                    cfg.coupling_bounds_pF(2));
                rateActive = any(deltaRate ~= deltaRaw);
                projectionActive = any(cFinal ~= cAfterRate);
                c = cFinal;
                if Ein < 1.08*baseIn
                    baseIn = 0.985*baseIn+0.015*Ein;
                end
                row = struct('J_11',J(1,1),'J_12',J(1,2), ...
                    'J_21',J(2,1),'J_22',J(2,2), ...
                    'h_1',h(1),'h_2',h(2), ...
                    'rate_limit_active',logical(rateActive), ...
                    'projection_active',logical(projectionActive));
                if isempty(rows)
                    rows = row;
                else
                    rows(end+1,1) = row; %#ok<AGROW>
                end
            end
            reference = struct2table(rows);
        end

        function [Ein,Equad] = residualComponents( ...
                data,ref,index,c,selfPF,frequency)
            [X,y] = coupling_regressor(data,ref,index,selfPF);
            residual = y-X*c;
            pointsPerPhase = numel(index);
            time = data.t(index);
            omega = 2*pi*frequency;
            phase = [2*pi/3,0,-2*pi/3];
            EinPerPhase = zeros(3,1);
            EquadPerPhase = zeros(3,1);
            for phaseIndex = 1:3
                phaseRows = (phaseIndex-1)*pointsPerPhase+1: ...
                    phaseIndex*pointsPerPhase;
                phaseResidual = residual(phaseRows);
                inPhaseBasis = [ ...
                    sin(omega*time+ref.phi1+phase(phaseIndex)), ...
                    sin(3*omega*time+ref.phi3)];
                quadratureBasis = [ ...
                    cos(omega*time+ref.phi1+phase(phaseIndex)), ...
                    cos(3*omega*time+ref.phi3)];
                basis = [inPhaseBasis,quadratureBasis, ...
                    ones(pointsPerPhase,1)];
                coefficients = basis\phaseResidual;
                EinPerPhase(phaseIndex) = sqrt(mean( ...
                    (inPhaseBasis*coefficients(1:2)).^2));
                EquadPerPhase(phaseIndex) = sqrt(mean( ...
                    (quadratureBasis*coefficients(3:4)).^2));
            end
            Ein = sqrt(mean(EinPerPhase.^2));
            Equad = sqrt(mean(EquadPerPhase.^2));
        end

        function names = requiredLogNames()
            names = { ...
                'time_s','Cs1_pF','Cs2_pF','lambda', ...
                'innovation_scalar','E_in','E_quad','base_in', ...
                'evidence_ratio_base','evidence_ratio_quad', ...
                'evidence_background_excess','evidence_phase_weight', ...
                'fault_evidence_score','update_weight', ...
                'delta_c_local_1','delta_c_local_2', ...
                'delta_c_raw_1','delta_c_raw_2', ...
                'delta_c_applied_1','delta_c_applied_2', ...
                'delta_c_suppressed_1','delta_c_suppressed_2', ...
                'J_increment_norm_raw','J_increment_norm_applied', ...
                'h_increment_norm_raw','h_increment_norm_applied', ...
                'rate_limit_active','projection_active', ...
                'm4_evidence_valid', ...
                'fault_direction_candidate_1', ...
                'fault_direction_candidate_2', ...
                'direction_candidate_valid','cos_local_fault', ...
                'cos_raw_fault','delta_c_parallel_1', ...
                'delta_c_parallel_2','delta_c_perpendicular_1', ...
                'delta_c_perpendicular_2','R_condition_number'};
        end
    end
end
