classdef M5DirectionalUpdateTest < matlab.unittest.TestCase
    %M5DIRECTIONALUPDATETEST Structural tests for M5 Step2.

    properties (TestParameter)
        intermediateWeight = struct( ...
            'quarter',0.25, ...
            'half',0.50, ...
            'threeQuarter',0.75)
    end

    methods (TestClassSetup)
        function addProjectPath(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(root));
        end
    end

    methods (Test)
        function testProjectorIdentities(testCase)
            result = m5_directional_update([1;2],0.5,"directional");
            tolerance = 1e-14;

            testCase.verifyEqual(result.P_f.',result.P_f, ...
                'AbsTol',tolerance);
            testCase.verifyEqual(result.P_perp.',result.P_perp, ...
                'AbsTol',tolerance);
            testCase.verifyEqual(result.P_f*result.P_f,result.P_f, ...
                'AbsTol',tolerance);
            testCase.verifyEqual( ...
                result.P_perp*result.P_perp,result.P_perp, ...
                'AbsTol',tolerance);
            testCase.verifyEqual(result.P_f*result.P_perp,zeros(2), ...
                'AbsTol',tolerance);
            testCase.verifyEqual(result.P_f+result.P_perp,eye(2), ...
                'AbsTol',tolerance);
            testCase.verifyEqual( ...
                result.P_f*result.fault_direction, ...
                result.fault_direction,'AbsTol',tolerance);
            testCase.verifyEqual( ...
                result.P_perp*result.fault_direction,zeros(2,1), ...
                'AbsTol',tolerance);
        end

        function testWeightOneEndpoint(testCase)
            deltaRaw = [1.7;-0.4];
            result = m5_directional_update( ...
                deltaRaw,1,"directional");

            testCase.verifyEqual(result.operator,eye(2),'AbsTol',1e-14);
            testCase.verifyEqual( ...
                result.delta_protected,deltaRaw,'AbsTol',1e-14);
        end

        function testWeightZeroEndpoint(testCase)
            deltaRaw = [1.7;-0.4];
            result = m5_directional_update( ...
                deltaRaw,0,"directional");

            testCase.verifyEqual( ...
                result.P_f*result.delta_protected,zeros(2,1), ...
                'AbsTol',1e-14);
            testCase.verifyEqual( ...
                result.P_perp*result.delta_protected,result.delta_perp, ...
                'AbsTol',1e-14);
        end

        function testIntermediateWeight(testCase,intermediateWeight)
            deltaRaw = [1.7;-0.4];
            result = m5_directional_update( ...
                deltaRaw,intermediateWeight,"directional");

            testCase.verifyEqual( ...
                norm(result.P_f*result.delta_protected), ...
                intermediateWeight*result.parallel_norm, ...
                'RelTol',1e-12,'AbsTol',1e-14);
            testCase.verifyEqual( ...
                result.P_perp*result.delta_protected,result.delta_perp, ...
                'AbsTol',1e-14);
        end

        function testMatchedControlsForParallelInput(testCase)
            direction = [1;-1]/sqrt(2);
            deltaRaw = 3*direction;
            directional = m5_directional_update( ...
                deltaRaw,0.37,"directional");
            globalControl = m5_directional_update( ...
                deltaRaw,0.37,"global");

            testCase.verifyEqual( ...
                directional.delta_protected, ...
                globalControl.delta_protected,'AbsTol',1e-14);
        end

        function testMatchedControlsForPerpendicularInput(testCase)
            deltaRaw = [1;1]/sqrt(2);
            directional = m5_directional_update( ...
                deltaRaw,0.37,"directional");
            globalControl = m5_directional_update( ...
                deltaRaw,0.37,"global");

            testCase.verifyEqual( ...
                directional.delta_protected,deltaRaw,'AbsTol',1e-14);
            testCase.verifyEqual( ...
                globalControl.delta_protected,0.37*deltaRaw, ...
                'AbsTol',1e-14);
        end

        function testInformationStateReconciliation(testCase)
            regularization = 1e-10;
            JStar = [3,0.5;0.5,2];
            thetaPrevious = [0.2;-0.1];
            hStar = [2;-1];
            thetaRaw = (JStar+regularization*eye(2))\hStar;
            update = m5_directional_update( ...
                thetaRaw-thetaPrevious,0.37,"directional");
            thetaDirectional = thetaPrevious+update.delta_protected;
            hReconciled = (JStar+regularization*eye(2))*thetaDirectional;
            thetaSolveback = ...
                (JStar+regularization*eye(2))\hReconciled;

            testCase.verifyEqual( ...
                thetaSolveback,thetaDirectional, ...
                'RelTol',1e-12,'AbsTol',1e-14);
            testCase.verifyEqual( ...
                hReconciled-(JStar+regularization*eye(2))* ...
                thetaDirectional,zeros(2,1),'AbsTol',1e-14);
        end

        function testTrackerWeightOneReproducesM2(testCase)
            [data,ref,cfg,selfPF] = M5DirectionalUpdateTest.fixtureData();
            m2 = track_coupling_cvff_rls(data,ref,cfg,selfPF,false);
            options = struct('forced_selected_weight',1);
            m5 = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_FULL",options);

            testCase.verifyEqual(m5.hist,m2.hist,'AbsTol',1e-12);
            testCase.verifyEqual( ...
                m5.cycle.h_reconciled_1,m5.cycle.h_star_1, ...
                'RelTol',5e-14,'AbsTol',1e-18);
            testCase.verifyEqual( ...
                m5.cycle.h_reconciled_2,m5.cycle.h_star_2, ...
                'RelTol',5e-14,'AbsTol',1e-18);
            testCase.verifyLessThanOrEqual( ...
                max(m5.cycle.solveback_error_norm),1e-12);
        end

        function testTrackerWeightZeroRemovesParallelComponent(testCase)
            [data,ref,cfg,selfPF] = M5DirectionalUpdateTest.fixtureData();
            options = struct('forced_selected_weight',0);
            result = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_FULL",options);
            faultProjector = 0.5*[1,-1;-1,1];
            perpendicularProjector = eye(2)-faultProjector;
            protected = [result.cycle.delta_protected_Cs1.'; ...
                result.cycle.delta_protected_Cs2.'];
            rawPerpendicular = [result.cycle.delta_perp_Cs1.'; ...
                result.cycle.delta_perp_Cs2.'];

            testCase.verifyEqual( ...
                faultProjector*protected,zeros(size(protected)), ...
                'AbsTol',1e-12);
            testCase.verifyEqual( ...
                perpendicularProjector*protected,rawPerpendicular, ...
                'AbsTol',1e-12);
            testCase.verifyLessThanOrEqual( ...
                max(result.cycle.reconciliation_residual_norm),1e-12);
        end

        function testMatchedTrackersSharePreoperatorPath(testCase)
            [data,ref,cfg,selfPF] = M5DirectionalUpdateTest.fixtureData();
            options = struct('forced_selected_weight',0.5);
            directional = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_FULL",options);
            globalControl = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"GLOBAL_CONTINUOUS_MATCHED",options);
            firstDirectional = directional.cycle(1,:);
            firstGlobal = globalControl.cycle(1,:);

            testCase.verifyEqual( ...
                firstDirectional{:,{'theta_previous_Cs1', ...
                'theta_previous_Cs2','theta_M2_raw_Cs1', ...
                'theta_M2_raw_Cs2','delta_raw_Cs1','delta_raw_Cs2', ...
                'J11','J12','J21','J22','h_star_1','h_star_2', ...
                'selected_weight','baseIn_previous','baseIn_candidate'}}, ...
                firstGlobal{:,{'theta_previous_Cs1', ...
                'theta_previous_Cs2','theta_M2_raw_Cs1', ...
                'theta_M2_raw_Cs2','delta_raw_Cs1','delta_raw_Cs2', ...
                'J11','J12','J21','J22','h_star_1','h_star_2', ...
                'selected_weight','baseIn_previous','baseIn_candidate'}}, ...
                'AbsTol',1e-14);
        end

        function testForcedWeightMakesHardContinuousMatched(testCase)
            [data,ref,cfg,selfPF] = M5DirectionalUpdateTest.fixtureData();
            options = struct('forced_selected_weight',0.5);
            hard = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_DH",options);
            continuous = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_FULL",options);

            testCase.verifyEqual(hard.hist,continuous.hist,'AbsTol',0);
            testCase.verifyEqual( ...
                hard.cycle.theta_projected_Cs1, ...
                continuous.cycle.theta_projected_Cs1,'AbsTol',0);
            testCase.verifyEqual( ...
                hard.cycle.theta_projected_Cs2, ...
                continuous.cycle.theta_projected_Cs2,'AbsTol',0);
        end

        function testRequiredInstrumentationSchema(testCase)
            [data,ref,cfg,selfPF] = M5DirectionalUpdateTest.fixtureData();
            result = track_coupling_m5_directional_rls( ...
                data,ref,cfg,selfPF,"M5_FULL");
            required = M5DirectionalUpdateTest.requiredLogNames();

            testCase.verifyTrue(all(ismember( ...
                required,result.cycle.Properties.VariableNames)));
            testCase.verifyFalse(any(result.cycle.forced_weight_active));
        end

        function testProductionPathHasNoTruthInputOrDoubleRew(testCase)
            trackerSource = fileread( ...
                which('track_coupling_m5_directional_rls'));
            helperSource = fileread(which('m5_directional_update'));
            source = [trackerSource,newline,helperSource];
            forbidden = [ ...
                'Cs1_true|Cs2_true|fault_factor_true|true_fault|' ...
                'counterfactual|Phase1B|future_sample|condition_label|' ...
                'track_coupling_m4_weighted_rls|delta_c_raw'];
            evidenceCallCount = numel(regexp( ...
                trackerSource,'m4_fault_evidence\(','match'));

            testCase.verifyEmpty(regexp(source,forbidden,'match'));
            testCase.verifyEqual(evidenceCallCount,1);
        end

        function testConstraintOrderIsFrozen(testCase)
            source = fileread(which('track_coupling_m5_directional_rls'));
            positions = M5DirectionalUpdateTest.controlPathPositions(source);

            testCase.verifyEqual(sort(positions),positions);
            testCase.verifyTrue(all(isfinite(positions)));
        end

        function testFrozenSourceHashes(testCase)
            actual = M5DirectionalUpdateTest.frozenHashes();
            expected = [ ...
                "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
                "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
                "A0504AD65B490F803AED454BF4D8CD2C6F724D0A96DF60502F7F32789521EEC1"
                "486FF017CE4491C84FBBF84D042EF661A5AFC5A8D255F0B88AC583304D593D15"
                "7582F66875A1099DF9656F9A89FE12D8FF6972C55D4A034736527A7DB00E03D5"
                "5C623E150C179E8F86823C02D5B22760C4FBD4EEA496C7FE3B2CF1154814AD16"];

            testCase.verifyEqual(actual,expected);
        end
    end

    methods (Static, Access=private)
        function [data,ref,cfg,selfPF] = fixtureData()
            cfg = patent_default_config();
            cfg.Ts = 2e-4;
            cfg.StopTime = 1.2;
            cfg.SNR_dB = Inf;
            time = (0:cfg.Ts:cfg.StopTime).';
            omega = 2*pi*cfg.f;
            voltageAmplitude = sqrt(2)*cfg.Uph;
            phase = [2*pi/3,0,-2*pi/3];
            ref = struct( ...
                'ua',voltageAmplitude*sin(omega*time+phase(1)), ...
                'ub',voltageAmplitude*sin(omega*time+phase(2)), ...
                'uc',voltageAmplitude*sin(omega*time+phase(3)), ...
                'dua',omega*voltageAmplitude*cos(omega*time+phase(1)), ...
                'dub',omega*voltageAmplitude*cos(omega*time+phase(2)), ...
                'duc',omega*voltageAmplitude*cos(omega*time+phase(3)), ...
                'phi1',0,'phi3',0);
            selfPF = repmat(cfg.Cself_pF,1,3);
            coupling = [12;8];
            resistiveAmplitude = sqrt(2)*cfg.moa_Iref_A;
            irA = resistiveAmplitude*sin(omega*time+phase(1));
            irB = resistiveAmplitude*sin(omega*time+phase(2));
            irC = resistiveAmplitude*sin(omega*time+phase(3));
            ia = selfPF(1)*1e-12.*ref.dua+ ...
                coupling(1)*1e-12.*(ref.dua-ref.dub)+irA;
            ib = selfPF(2)*1e-12.*ref.dub+ ...
                coupling(1)*1e-12.*(ref.dub-ref.dua)+ ...
                coupling(2)*1e-12.*(ref.dub-ref.duc)+irB;
            ic = selfPF(3)*1e-12.*ref.duc+ ...
                coupling(2)*1e-12.*(ref.duc-ref.dub)+irC;
            data = struct('t',time,'ia',ia,'ib',ib,'ic',ic);
        end

        function names = requiredLogNames()
            names = { ...
                'time_s','theta_previous_Cs1','theta_previous_Cs2', ...
                'theta_M2_raw_Cs1','theta_M2_raw_Cs2', ...
                'delta_raw_Cs1','delta_raw_Cs2', ...
                'delta_parallel_Cs1','delta_parallel_Cs2', ...
                'delta_perp_Cs1','delta_perp_Cs2', ...
                'parallel_norm','perp_norm','gate','w_hard','w_REW', ...
                'selected_weight','theta_preconstraint_Cs1', ...
                'theta_preconstraint_Cs2','delta_protected_Cs1', ...
                'delta_protected_Cs2','theta_rate_Cs1', ...
                'theta_rate_Cs2','theta_projected_Cs1', ...
                'theta_projected_Cs2','rate_limit_active', ...
                'projection_active','raw_angle_to_df_deg', ...
                'protected_angle_to_df_deg','post_rate_angle_to_df_deg', ...
                'post_projection_angle_to_df_deg','J11','J12','J21','J22', ...
                'h_star_1','h_star_2','h_reconciled_1','h_reconciled_2', ...
                'solveback_error_norm','reconciliation_residual_norm', ...
                'final_h_Jtheta_mismatch_norm','baseIn_previous', ...
                'baseIn_candidate','baseIn_new'};
        end

        function positions = controlPathPositions(source)
            labels = [ ...
                "thetaM2Raw ="
                "m5_directional_update("
                "h = (J+regularization"
                "rateLimitedDelta ="
                "thetaProjected ="];
            positions = nan(size(labels));
            for k = 1:numel(labels)
                match = strfind(source,labels(k));
                positions(k) = match(1);
            end
        end

        function hashes = frozenHashes()
            root = fileparts(fileparts(mfilename('fullpath')));
            names = [ ...
                "track_coupling_cvff_rls.m"
                "track_coupling_cvff_rls.m"
                "track_coupling_m4_weighted_rls.m"
                "m4_fault_evidence.m"
                "coupling_regressor.m"
                "run_phase1a_algorithm.m"];
            hashes = strings(size(names));
            for k = 1:numel(names)
                hashes(k) = M5DirectionalUpdateTest.fileSha256( ...
                    fullfile(root,names(k)));
            end
        end

        function hash = fileSha256(path)
            fileId = fopen(path,'rb');
            if fileId < 0
                error('M5:HashFailure','Unable to hash %s.',path);
            end
            cleanup = onCleanup(@() fclose(fileId));
            bytes = fread(fileId,Inf,'*uint8');
            digester = java.security.MessageDigest.getInstance('SHA-256');
            digester.update(bytes);
            hashBytes = typecast(digester.digest(),'uint8');
            hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
        end
    end
end
