classdef Phase1AMetricsTest < matlab.unittest.TestCase
    %PHASE1AMETRICSTEST Phase 1A Step 4 pure metric-layer tests.

    methods (TestClassSetup)
        function addProjectPath(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(root));
        end
    end

    methods (Test)
        function testResultFieldsMatchSchemaAndLegacyBMetric(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case02_slow_drift","M0");
            expectedLegacy = evaluate_case_metrics(data,result.ir, ...
                result.cHist,"M0",caseInfo.case_name,cfg);

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);
            schema = phase1a_result_schema();

            testCase.verifyEqual( ...
                string(metrics.Properties.VariableNames).', ...
                schema.variable_names);
            testCase.verifyEqual(string(varfun(@class,metrics, ...
                'OutputFormat','cell')).',schema.variable_types);
            testCase.verifyEqual(height(metrics),1,'AbsTol',0);
            testCase.verifyEqual( ...
                metrics.B_resistive_fundamental_error_pct, ...
                expectedLegacy.B_FundErr_pct,'AbsTol',1e-12);
        end

        function testNonFaultMetricsAreNaN(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case02_slow_drift","M3");

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);
            faultValues = metrics{1,{ ...
                'fault_factor_true','fault_factor_est', ...
                'fault_retention_error_pct', ...
                'Cs1_pre_post_change_pF','Cs2_pre_post_change_pF'}};

            testCase.verifyTrue(all(isnan(faultValues)));
        end

        function testM0GateMetricsAreNaN(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M0");

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);

            Phase1AMetricsTest.verifyGateNaN(testCase,metrics);
        end

        function testM2GateMetricsAreNaNEvenWithCycleFlags(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M2");
            result.tracker.cycle = Phase1AMetricsTest.activeGateLog();

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);

            Phase1AMetricsTest.verifyGateNaN(testCase,metrics);
        end

        function testM3WithoutGateMetricsAreNaN(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M3");
            result.tracker.cycle = table([1;2],[0;0], ...
                'VariableNames',{'time_s','gate'});

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);

            Phase1AMetricsTest.verifyGateNaN(testCase,metrics);
        end

        function testM3UsesActualGateLog(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M3");
            result.tracker.cycle = Phase1AMetricsTest.activeGateLog();

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);

            testCase.verifyEqual(metrics.first_gate_trigger_s,3.06, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(metrics.gate_duration_cycles,3, ...
                'AbsTol',0);
            testCase.verifyEqual(metrics.gate_duration_s,3/cfg.f, ...
                'AbsTol',1e-12);
        end

        function testFaultWindowsFactorsAndParameterChanges(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M2");

            metrics = evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata);

            testCase.verifyEqual(metrics.fault_factor_true,1.6, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(metrics.fault_factor_est,1.4, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(metrics.fault_retention_error_pct,-12.5, ...
                'AbsTol',1e-10);
            testCase.verifyEqual(metrics.Cs1_pre_post_change_pF,5, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(metrics.Cs2_pre_post_change_pF,-5, ...
                'AbsTol',1e-12);
        end

        function testCase05AndCase06UseSameFaultEvaluation(testCase)
            [case05,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M2");
            case06 = Phase1AMetricsTest.caseInfo( ...
                "Case06_drift_then_fault");

            metrics05 = evaluate_phase1a_metrics( ...
                case05,result,data,cfg,metadata);
            metrics06 = evaluate_phase1a_metrics( ...
                case06,result,data,cfg,metadata);
            fields = {'fault_factor_true','fault_factor_est', ...
                'fault_retention_error_pct', ...
                'Cs1_pre_post_change_pF','Cs2_pre_post_change_pF'};

            testCase.verifyEqual(metrics05{1,fields},metrics06{1,fields}, ...
                'AbsTol',0);
        end

        function testHistoricalReferenceValuesAreFrozen(testCase)
            reference = phase1a_historical_reference();

            testCase.verifyEqual(reference.reference_role, ...
                "regression_only");
            testCase.verifyEqual(reference.Case02_slow_drift.M0. ...
                B_resistive_fundamental_error_pct,8.9587533463069, ...
                'AbsTol',1e-15);
            testCase.verifyEqual(reference.Case02_slow_drift.M3. ...
                Cs1_RMSE_pF,0.157320251866564,'AbsTol',1e-15);
            testCase.verifyEqual(reference.Case06_drift_then_fault.M2. ...
                Cs1_pre_post_change_pF,5.00627092717497, ...
                'AbsTol',1e-15);
            testCase.verifyEqual(reference.Case06_drift_then_fault.M3. ...
                fault_factor_est,1.58287648629316,'AbsTol',1e-15);
        end

        function testUnknownCaseErrors(testCase)
            [~,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M0");
            caseInfo = Phase1AMetricsTest.caseInfo("Case99_unknown");

            testCase.verifyError(@() evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata), ...
                'Phase1A:UnknownCase');
        end

        function testMissingTruthFieldErrors(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M0");
            data = rmfield(data,'Cs2');

            testCase.verifyError(@() evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata), ...
                'Phase1A:MissingInputField');
        end

        function testM3MissingGateLogErrors(testCase)
            [caseInfo,result,data,cfg,metadata] = ...
                Phase1AMetricsTest.fixture("Case05_fault_only","M3");
            result.tracker = struct();

            testCase.verifyError(@() evaluate_phase1a_metrics( ...
                caseInfo,result,data,cfg,metadata), ...
                'Phase1A:MissingGateLog');
        end

        function testEvaluationLayerDoesNotCallSimulationOrAlgorithms(testCase)
            source = fileread(which('evaluate_phase1a_metrics'));
            forbiddenCalls = [ ...
                'track_coupling_cvff_rls\s*\(|' ...
                'initial_coupling_estimate\s*\(|' ...
                'generate_coupling_signals\s*\(|' ...
                'simulate_phase2_case\s*\(|' ...
                '\<sim\s*\('];

            testCase.verifyEmpty(regexp(source,forbiddenCalls,'once'));
        end
    end

    methods (Static, Access=private)
        function [caseInfo,result,data,cfg,metadata] = fixture(caseName,mode)
            cfg = struct('metric_start',0.8,'f',50);
            t = (0:1e-3:4).';
            w = 2*pi*cfg.f;
            trueScale = 1+0.6*(t>=3.0);
            estimatedScale = 1+0.4*(t>=3.0);
            irA = sin(w*t+2*pi/3);
            irC = sin(w*t-2*pi/3);
            data = struct( ...
                't',t, ...
                'Cs1',10*ones(size(t)), ...
                'Cs2',10*ones(size(t)), ...
                'irA',irA, ...
                'irB',trueScale.*sin(w*t), ...
                'irC',irC);
            cHist = [10*ones(size(t)),10*ones(size(t))];
            cHist(t>=3.0,1) = 15;
            cHist(t>=3.0,2) = 5;
            ir = struct('A',irA, ...
                'B',estimatedScale.*sin(w*t),'C',irC);
            tracker = struct();
            if mode == "M3"
                tracker.cycle = table([1;2],[0;0], ...
                    'VariableNames',{'time_s','gate'});
            end
            result = struct('algorithm_mode',mode,'cHist',cHist, ...
                'ir',ir,'tracker',tracker);
            caseInfo = Phase1AMetricsTest.caseInfo(caseName);
            metadata = struct( ...
                'model_sha256',"TEST_SHA256", ...
                'run_timestamp',"2026-09-17T00:00:00+08:00", ...
                'git_commit',"TEST_COMMIT", ...
                'git_branch',"main", ...
                'git_dirty_status',"TEST");
        end

        function info = caseInfo(caseName)
            registry = phase1a_case_registry();
            match = registry.case_name == caseName;
            if any(match)
                info = table2struct(registry(match,:));
            else
                info = struct('case_name',caseName,'seed',999, ...
                    'model',"AI6109_MOA_AutoComp9.slx");
            end
        end

        function cycle = activeGateLog()
            cycle = table([1.00;3.06;3.08;3.10;3.14], ...
                [0;1;1;0;1], ...
                'VariableNames',{'time_s','gate'});
        end

        function verifyGateNaN(testCase,metrics)
            values = metrics{1,{ ...
                'first_gate_trigger_s','gate_duration_cycles', ...
                'gate_duration_s'}};
            testCase.verifyTrue(all(isnan(values)));
        end
    end
end
