function result = run_m5_step2_smoke()
%RUN_M5_STEP2_SMOKE Run the limited Case05/06 structural smoke.

stepRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(fileparts(stepRoot)));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
addpath(matlabRoot);
addpath(stepRoot);

hashBefore = capture_frozen_hashes(matlabRoot);
structuralTable = run_m5_step2_structural_checks();
if ~all(structuralTable.pass)
    error('M5:StructuralChecksFailed', ...
        'M5 algebra checks failed before the smoke run.');
end

cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
selfPF = repmat(cfg.Cself_pF,1,3);
registry = phase1a_case_registry();
registry = registry(ismember(registry.case_name, ...
    ["Case05_fault_only","Case06_drift_then_fault"]),:);
variants = [ ...
    "M5_DH"
    "M5_FULL"
    "GLOBAL_HARD_MATCHED"
    "GLOBAL_CONTINUOUS_MATCHED"];

summaryRows = struct([]);
caseCycles = struct();
caseResults = struct();
for caseIndex = 1:height(registry)
    caseInfo = registry(caseIndex,:);
    fprintf('M5_STEP2_SMOKE_CASE_START=%s seed=%d\n', ...
        caseInfo.case_name,caseInfo.seed);
    inputTime = (0:cfg.Ts:cfg.StopTime).';
    signals = generate_coupling_signals( ...
        inputTime,caseInfo.case_name,caseInfo.seed);
    [data,~] = simulate_phase2_case(cfg, ...
        char(caseInfo.legacy_scenario_name),caseInfo.seed);
    assert_case_integrity(data,signals,caseInfo.case_name);
    ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
        cfg.init_start,cfg.init_end,cfg.phase_error_deg);

    combinedCycle = table();
    variantResults = struct();
    for variantIndex = 1:numel(variants)
        variant = variants(variantIndex);
        tracker = track_coupling_m5_directional_rls( ...
            data,ref,cfg,selfPF,variant);
        cycle = tracker.cycle;
        cycleIndex = (1:height(cycle)).';
        caseNameColumn = repmat(caseInfo.case_name,height(cycle),1);
        segment = segment_labels(cycle.time_s);
        cycle = addvars(cycle,caseNameColumn,cycleIndex,segment, ...
            'Before',1,'NewVariableNames', ...
            {'case_name','cycle_index','segment'});
        combinedCycle = [combinedCycle;cycle]; %#ok<AGROW>
        summaryRows = append_summary_rows(summaryRows,caseInfo.case_name, ...
            tracker.variant,cycle);
        variantResults.(char(variant)) = tracker;
    end

    caseField = char(caseInfo.case_name);
    caseCycles.(caseField) = combinedCycle;
    caseResults.(caseField) = variantResults;
    outputName = cycle_output_name(caseInfo.case_name);
    writetable(combinedCycle,fullfile(stepRoot,outputName));
    fprintf('M5_STEP2_SMOKE_CASE_COMPLETE=%s rows=%d\n', ...
        caseInfo.case_name,height(combinedCycle));
end

summaryTable = struct2table(summaryRows);
summaryPath = fullfile(stepRoot,'M5_STEP2_SMOKE_SUMMARY.csv');
writetable(summaryTable,summaryPath);

hashAfter = capture_frozen_hashes(matlabRoot);
hashAudit = build_hash_audit(hashBefore,hashAfter);
hashPath = fullfile(stepRoot,'M5_STEP2_HASH_AUDIT.csv');
writetable(hashAudit,hashPath);

requiredSchema = required_log_names();
case05Pass = case_pass(summaryTable,"Case05_fault_only");
case06Pass = case_pass(summaryTable,"Case06_drift_then_fault");
hashPass = all(hashAudit.pass);
structuralPass = all(structuralTable.pass);
instrumentationPass = all(cellfun(@(fieldName) ...
    all(ismember(requiredSchema, ...
    caseCycles.(fieldName).Properties.VariableNames)), ...
    fieldnames(caseCycles)));

result = struct( ...
    'schema_version',"m5_step2_structural_v1", ...
    'cfg',cfg, ...
    'case_registry',registry, ...
    'variants',variants, ...
    'structural_table',structuralTable, ...
    'summary_table',summaryTable, ...
    'hash_audit',hashAudit, ...
    'case_cycles',caseCycles, ...
    'case_results',caseResults, ...
    'case05_pass',case05Pass, ...
    'case06_pass',case06Pass, ...
    'hash_pass',hashPass, ...
    'instrumentation_pass',instrumentationPass, ...
    'overall_pass',case05Pass && case06Pass && hashPass && ...
    structuralPass && instrumentationPass);

workspacePath = fullfile(stepRoot,'m5_step2_smoke_workspace.mat');
save(workspacePath,'result','-v7.3');
fprintf('M5_STEP2_CASE05_SMOKE_PASS=%d\n',case05Pass);
fprintf('M5_STEP2_CASE06_SMOKE_PASS=%d\n',case06Pass);
fprintf('M5_STEP2_HASH_PASS=%d\n',hashPass);
fprintf('M5_STEP2_INSTRUMENTATION_PASS=%d\n',instrumentationPass);
fprintf('M5_STEP2_SMOKE_OVERALL_PASS=%d\n',result.overall_pass);
fprintf('M5_STEP2_SMOKE_SUMMARY=%s\n',summaryPath);
fprintf('M5_STEP2_HASH_AUDIT=%s\n',hashPath);
fprintf('M5_STEP2_WORKSPACE=%s\n',workspacePath);
if ~result.overall_pass
    error('M5:SmokeValidationFailed', ...
        'One or more M5 Step2 structural smoke checks failed.');
end
end

function assert_case_integrity(data,signals,caseName)
if max(abs(data.Cs1-signals.Cs1_pF)) > 1e-10 || ...
        max(abs(data.Cs2-signals.Cs2_pF)) > 1e-10
    error('M5:CaseIntegrity','Coupling truth mismatch for %s.',caseName);
end
if any(signals.fault_scale(data.t < 3.0) ~= 1) || ...
        max(signals.fault_scale) < 1.5
    error('M5:CaseIntegrity','Fault profile mismatch for %s.',caseName);
end
end

function segment = segment_labels(time)
segment = repmat("PRE_FAULT",numel(time),1);
segment(time >= 3.0 & time < 3.4) = "FAULT_ACTIVE";
segment(time >= 3.4) = "LATE_FAULT";
end

function name = cycle_output_name(caseName)
if caseName == "Case05_fault_only"
    name = 'm5_step2_cycle_instrumentation_case05.csv';
else
    name = 'm5_step2_cycle_instrumentation_case06.csv';
end
end

function rows = append_summary_rows(rows,caseName,variant,cycle)
segments = ["ALL","PRE_FAULT","FAULT_ACTIVE","LATE_FAULT","POST_FAULT"];
for k = 1:numel(segments)
    row = summary_row(caseName,variant,cycle,segments(k));
    if isempty(rows)
        rows = row;
    else
        rows(end+1,1) = row; %#ok<AGROW>
    end
end
end

function row = summary_row(caseName,variant,cycle,segmentName)
if segmentName == "ALL"
    selected = true(height(cycle),1);
elseif segmentName == "POST_FAULT"
    selected = false(height(cycle),1);
else
    selected = cycle.segment == segmentName;
end
part = cycle(selected,:);
schemaComplete = all(ismember(required_log_names(), ...
    cycle.Properties.VariableNames));
corePass = schemaComplete && ...
    all(cycle.selected_weight >= 0 & cycle.selected_weight <= 1) && ...
    max(cycle.solveback_error_norm) <= 1e-10 && ...
    max(cycle.reconciliation_residual_norm) <= 1e-10 && ...
    max(cycle.decomposition_error_norm) <= 1e-10;

if isempty(part)
    metrics = empty_segment_metrics();
else
    parallelEnergy = sum(part.parallel_norm.^2);
    perpendicularEnergy = sum(part.perp_norm.^2);
    metrics = struct( ...
        'selected_weight_min',min(part.selected_weight), ...
        'selected_weight_mean',mean(part.selected_weight), ...
        'selected_weight_max',max(part.selected_weight), ...
        'w_REW_min',min(part.w_REW), ...
        'w_REW_mean',mean(part.w_REW), ...
        'w_REW_max',max(part.w_REW), ...
        'parallel_norm_mean',mean(part.parallel_norm), ...
        'perp_norm_mean',mean(part.perp_norm), ...
        'parallel_energy_fraction',parallelEnergy/( ...
        parallelEnergy+perpendicularEnergy+eps), ...
        'angle_valid_cycles',nnz(isfinite(part.raw_angle_to_df_deg)), ...
        'near_zero_raw_cycles',nnz(isnan(part.raw_angle_to_df_deg)), ...
        'negative_df_projection_cycles', ...
        nnz(part.raw_signed_projection_df < 0), ...
        'gate_active_cycles',nnz(part.gate), ...
        'rew_below_one_cycles',nnz(part.w_REW < 1), ...
        'rate_limit_cycles',nnz(part.rate_limit_active), ...
        'projection_cycles',nnz(part.projection_active), ...
        'max_solveback_error',max(part.solveback_error_norm), ...
        'max_reconciliation_residual', ...
        max(part.reconciliation_residual_norm), ...
        'max_decomposition_error',max(part.decomposition_error_norm), ...
        'max_abs_rate_rotation_deg',safe_max_abs(part.rate_rotation_deg), ...
        'max_abs_projection_rotation_deg', ...
        safe_max_abs(part.projection_rotation_deg));
end

row = struct( ...
    'case_name',caseName, ...
    'variant',variant.mode, ...
    'variant_role',variant.role, ...
    'operator_scope',variant.scope, ...
    'weight_type',variant.weight_type, ...
    'segment',segmentName, ...
    'segment_available',~isempty(part), ...
    'cycle_count',height(part), ...
    'schema_complete',schemaComplete, ...
    'smoke_pass',corePass, ...
    'selected_weight_min',metrics.selected_weight_min, ...
    'selected_weight_mean',metrics.selected_weight_mean, ...
    'selected_weight_max',metrics.selected_weight_max, ...
    'w_REW_min',metrics.w_REW_min, ...
    'w_REW_mean',metrics.w_REW_mean, ...
    'w_REW_max',metrics.w_REW_max, ...
    'parallel_norm_mean',metrics.parallel_norm_mean, ...
    'perp_norm_mean',metrics.perp_norm_mean, ...
    'parallel_energy_fraction',metrics.parallel_energy_fraction, ...
    'angle_valid_cycles',metrics.angle_valid_cycles, ...
    'near_zero_raw_cycles',metrics.near_zero_raw_cycles, ...
    'negative_df_projection_cycles', ...
    metrics.negative_df_projection_cycles, ...
    'gate_active_cycles',metrics.gate_active_cycles, ...
    'rew_below_one_cycles',metrics.rew_below_one_cycles, ...
    'rate_limit_cycles',metrics.rate_limit_cycles, ...
    'projection_cycles',metrics.projection_cycles, ...
    'max_solveback_error',metrics.max_solveback_error, ...
    'max_reconciliation_residual', ...
    metrics.max_reconciliation_residual, ...
    'max_decomposition_error',metrics.max_decomposition_error, ...
    'max_abs_rate_rotation_deg',metrics.max_abs_rate_rotation_deg, ...
    'max_abs_projection_rotation_deg', ...
    metrics.max_abs_projection_rotation_deg, ...
    'notes',segment_note(segmentName));
end

function metrics = empty_segment_metrics()
metrics = struct( ...
    'selected_weight_min',NaN,'selected_weight_mean',NaN, ...
    'selected_weight_max',NaN,'w_REW_min',NaN,'w_REW_mean',NaN, ...
    'w_REW_max',NaN,'parallel_norm_mean',NaN,'perp_norm_mean',NaN, ...
    'parallel_energy_fraction',NaN,'angle_valid_cycles',0, ...
    'near_zero_raw_cycles',0,'negative_df_projection_cycles',0, ...
    'gate_active_cycles',0,'rew_below_one_cycles',0, ...
    'rate_limit_cycles',0,'projection_cycles',0, ...
    'max_solveback_error',NaN,'max_reconciliation_residual',NaN, ...
    'max_decomposition_error',NaN,'max_abs_rate_rotation_deg',NaN, ...
    'max_abs_projection_rotation_deg',NaN);
end

function note = segment_note(segmentName)
if segmentName == "POST_FAULT"
    note = "Unavailable: the frozen Case05/06 fault persists to run end.";
else
    note = "Descriptive structural smoke only; no performance threshold.";
end
end

function value = safe_max_abs(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = max(abs(values));
end
end

function names = required_log_names()
names = { ...
    'time_s','theta_previous_Cs1','theta_previous_Cs2', ...
    'theta_M2_raw_Cs1','theta_M2_raw_Cs2', ...
    'delta_raw_Cs1','delta_raw_Cs2', ...
    'delta_parallel_Cs1','delta_parallel_Cs2', ...
    'delta_perp_Cs1','delta_perp_Cs2','parallel_norm','perp_norm', ...
    'gate','w_hard','w_REW','selected_weight', ...
    'theta_preconstraint_Cs1','theta_preconstraint_Cs2', ...
    'delta_protected_Cs1','delta_protected_Cs2', ...
    'theta_rate_Cs1','theta_rate_Cs2','theta_projected_Cs1', ...
    'theta_projected_Cs2','rate_limit_active','projection_active', ...
    'raw_angle_to_df_deg','protected_angle_to_df_deg', ...
    'post_rate_angle_to_df_deg','post_projection_angle_to_df_deg', ...
    'J11','J12','J21','J22','h_star_1','h_star_2', ...
    'h_reconciled_1','h_reconciled_2','solveback_error_norm', ...
    'reconciliation_residual_norm','final_h_Jtheta_mismatch_norm', ...
    'baseIn_previous','baseIn_candidate','baseIn_new'};
end

function pass = case_pass(summaryTable,caseName)
rows = summaryTable.case_name == caseName & summaryTable.segment == "ALL";
pass = nnz(rows) == 4 && all(summaryTable.smoke_pass(rows));
end

function tableOut = capture_frozen_hashes(matlabRoot)
[roles,names,expected] = frozen_hash_definition();
actual = strings(size(names));
for k = 1:numel(names)
    actual(k) = file_sha256(fullfile(matlabRoot,names(k)));
end
tableOut = table(roles,names,expected,actual, ...
    'VariableNames',{'role','file_name','expected_sha256','sha256'});
end

function audit = build_hash_audit(before,after)
audit = table( ...
    before.role,before.file_name,before.expected_sha256, ...
    before.sha256,after.sha256, ...
    before.sha256 == before.expected_sha256, ...
    after.sha256 == before.expected_sha256, ...
    before.sha256 == after.sha256, ...
    'VariableNames',{'role','file_name','expected_sha256', ...
    'sha256_before','sha256_after','before_matches_expected', ...
    'after_matches_expected','unchanged_during_run'});
audit.pass = audit.before_matches_expected & ...
    audit.after_matches_expected & audit.unchanged_during_run;
end

function [roles,names,hashes] = frozen_hash_definition()
roles = ["M2";"M3";"M4";"M4_EVIDENCE";"REGRESSOR";"DISPATCHER"];
names = [ ...
    "track_coupling_cvff_rls.m"
    "track_coupling_cvff_rls.m"
    "track_coupling_m4_weighted_rls.m"
    "m4_fault_evidence.m"
    "coupling_regressor.m"
    "run_phase1a_algorithm.m"];
hashes = [ ...
    "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
    "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
    "A0504AD65B490F803AED454BF4D8CD2C6F724D0A96DF60502F7F32789521EEC1"
    "486FF017CE4491C84FBBF84D042EF661A5AFC5A8D255F0B88AC583304D593D15"
    "7582F66875A1099DF9656F9A89FE12D8FF6972C55D4A034736527A7DB00E03D5"
    "5C623E150C179E8F86823C02D5B22760C4FBD4EEA496C7FE3B2CF1154814AD16"];
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('M5:HashFailure','Unable to hash %s.',path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end
