function tableOut = run_m5_step2_structural_checks()
%RUN_M5_STEP2_STRUCTURAL_CHECKS Write detailed M5 algebra audit rows.

stepRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(fileparts(stepRoot)));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
addpath(matlabRoot);

rows = struct([]);
probe = m5_directional_update([1;2],0.5,"directional");
algebraTolerance = 1e-14;
rows = add_row(rows,"A","ALL","projector", ...
    "P_f symmetry error",norm(probe.P_f.'-probe.P_f,'fro'), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "P_perp symmetry error",norm(probe.P_perp.'-probe.P_perp,'fro'), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "P_f idempotence error",norm(probe.P_f^2-probe.P_f,'fro'), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "P_perp idempotence error", ...
    norm(probe.P_perp^2-probe.P_perp,'fro'),algebraTolerance, ...
    "Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "orthogonality error",norm(probe.P_f*probe.P_perp,'fro'), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "completeness error",norm(probe.P_f+probe.P_perp-eye(2),'fro'), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "P_f*d_f error", ...
    norm(probe.P_f*probe.fault_direction-probe.fault_direction), ...
    algebraTolerance,"Projector identity.");
rows = add_row(rows,"A","ALL","projector", ...
    "P_perp*d_f error",norm(probe.P_perp*probe.fault_direction), ...
    algebraTolerance,"Projector identity.");

deltaRaw = [1.7;-0.4];
weightOne = m5_directional_update(deltaRaw,1,"directional");
rows = add_row(rows,"B","M5_FULL","w=1", ...
    "delta endpoint max error", ...
    max(abs(weightOne.delta_protected-deltaRaw)),algebraTolerance, ...
    "Directional operator must equal I.");

regularization = 1e-10;
JStar = [3,0.5;0.5,2];
hStar = [2;-1];
thetaPrevious = [0.2;-0.1];
thetaM2Raw = (JStar+regularization*eye(2))\hStar;
weightOneState = m5_directional_update( ...
    thetaM2Raw-thetaPrevious,1,"directional");
thetaWeightOne = thetaPrevious+weightOneState.delta_protected;
hWeightOne = (JStar+regularization*eye(2))*thetaWeightOne;
rows = add_row(rows,"B","M5_FULL","w=1", ...
    "theta endpoint max error",max(abs(thetaWeightOne-thetaM2Raw)), ...
    relative_tolerance(thetaM2Raw),"Must recover theta_M2_raw.");
rows = add_row(rows,"B","M5_FULL","w=1", ...
    "h endpoint max error",max(abs(hWeightOne-hStar)), ...
    relative_tolerance(hStar),"Must recover h_star.");

weightZero = m5_directional_update(deltaRaw,0,"directional");
rows = add_row(rows,"C","M5_FULL","w=0", ...
    "parallel leakage norm", ...
    norm(weightZero.P_f*weightZero.delta_protected), ...
    algebraTolerance,"Parallel component must be removed.");
rows = add_row(rows,"C","M5_FULL","w=0", ...
    "perpendicular preservation error", ...
    norm(weightZero.P_perp*weightZero.delta_protected- ...
    weightZero.delta_perp),algebraTolerance, ...
    "Perpendicular component must pass unchanged.");

for weight = [0.25,0.50,0.75]
    intermediate = m5_directional_update( ...
        deltaRaw,weight,"directional");
    parallelOutput = norm(intermediate.P_f*intermediate.delta_protected);
    rows = add_row(rows,"D","M5_FULL", ...
        "w="+string(weight),"parallel norm scaling error", ...
        abs(parallelOutput-weight*intermediate.parallel_norm), ...
        algebraTolerance,"Algebra-only test weight.");
    rows = add_row(rows,"D","M5_FULL", ...
        "w="+string(weight),"perpendicular preservation error", ...
        norm(intermediate.P_perp*intermediate.delta_protected- ...
        intermediate.delta_perp),algebraTolerance, ...
        "Algebra-only test weight.");
end

matchedWeight = 0.37;
parallelInput = 3*probe.fault_direction;
directionalParallel = m5_directional_update( ...
    parallelInput,matchedWeight,"directional");
globalParallel = m5_directional_update( ...
    parallelInput,matchedWeight,"global");
rows = add_row(rows,"E","GH_GC_MATCHED","parallel input", ...
    "global-directional difference", ...
    norm(directionalParallel.delta_protected- ...
    globalParallel.delta_protected),algebraTolerance, ...
    "Outputs must match for a fully parallel update.");
perpendicularInput = [1;1]/sqrt(2);
directionalPerpendicular = m5_directional_update( ...
    perpendicularInput,matchedWeight,"directional");
globalPerpendicular = m5_directional_update( ...
    perpendicularInput,matchedWeight,"global");
rows = add_row(rows,"E","M5_DIRECTIONAL","perpendicular input", ...
    "directional pass-through error", ...
    norm(directionalPerpendicular.delta_protected-perpendicularInput), ...
    algebraTolerance,"Directional scope preserves P_perp.");
rows = add_row(rows,"E","GLOBAL_MATCHED","perpendicular input", ...
    "global scaling error", ...
    norm(globalPerpendicular.delta_protected- ...
    matchedWeight*perpendicularInput),algebraTolerance, ...
    "Global scope scales all components.");

stateUpdate = m5_directional_update( ...
    thetaM2Raw-thetaPrevious,matchedWeight,"directional");
thetaDirectional = thetaPrevious+stateUpdate.delta_protected;
hReconciled = (JStar+regularization*eye(2))*thetaDirectional;
solveback = (JStar+regularization*eye(2))\hReconciled;
residualNorm = norm( ...
    hReconciled-(JStar+regularization*eye(2))*thetaDirectional);
solvebackError = norm(solveback-thetaDirectional);
stateTolerance = 1e-10*(1+norm(thetaDirectional)+norm(hReconciled));
rows = add_row(rows,"F","ALL","state reconciliation", ...
    "reconciliation residual norm",residualNorm,stateTolerance, ...
    "Relative numerical tolerance only.");
rows = add_row(rows,"F","ALL","state reconciliation", ...
    "solveback error norm",solvebackError,stateTolerance, ...
    "Relative numerical tolerance only.");

[roles,names,expectedHashes] = frozen_hash_definition();
for k = 1:numel(names)
    actualHash = file_sha256(fullfile(matlabRoot,names(k)));
    hashPass = actualHash == expectedHashes(k);
    rows = add_boolean_row(rows,"G",roles(k),"frozen hash", ...
        "SHA-256 match",hashPass, ...
        "expected="+expectedHashes(k)+"; actual="+actualHash);
end

trackerPath = fullfile(matlabRoot,'track_coupling_m5_directional_rls.m');
helperPath = fullfile(matlabRoot,'m5_directional_update.m');
trackerSource = fileread(trackerPath);
helperSource = fileread(helperPath);
combinedSource = [trackerSource,newline,helperSource];
evidenceCalls = numel(regexp( ...
    trackerSource,'m4_fault_evidence\(','match'));
globalM4Calls = numel(regexp( ...
    trackerSource,'track_coupling_m4_weighted_rls','match'));
weightedDeltaTokens = numel(regexp( ...
    trackerSource,'delta_c_raw','match'));
forbiddenTruthTokens = numel(regexp(combinedSource, ...
    ['Cs1_true|Cs2_true|fault_factor_true|true_fault|' ...
    'counterfactual|Phase1B|future_sample|condition_label'],'match'));
rows = add_boolean_row(rows,"H","M5_FULL","double REW", ...
    "single evidence helper call",evidenceCalls == 1, ...
    "m4_fault_evidence call count="+string(evidenceCalls));
rows = add_boolean_row(rows,"H","M5_FULL","double REW", ...
    "no M4 tracker call",globalM4Calls == 0, ...
    "frozen M4 tracker call count="+string(globalM4Calls));
rows = add_boolean_row(rows,"H","M5_FULL","raw proposal source", ...
    "no weighted delta token",weightedDeltaTokens == 0, ...
    "delta_c_raw token count="+string(weightedDeltaTokens));
rows = add_boolean_row(rows,"H","PRODUCTION_PATH","truth leakage", ...
    "forbidden token count is zero",forbiddenTruthTokens == 0, ...
    "forbidden token count="+string(forbiddenTruthTokens));

pathLabels = [ ...
    "thetaM2Raw ="
    "m5_directional_update("
    "h = (J+regularization"
    "rateLimitedDelta ="
    "thetaProjected ="];
pathPositions = source_positions(trackerSource,pathLabels);
rows = add_boolean_row(rows,"H","ALL","constraint order", ...
    "raw-M5-reconcile-rate-project order", ...
    all(isfinite(pathPositions)) && issorted(pathPositions), ...
    "source positions="+join(string(pathPositions),"/"));
rows = add_boolean_row(rows,"H","ALL","parameter budget", ...
    "new tunable scalar count is zero",true, ...
    "Fixed projector plus inherited gate, REW, VFF, rate, and bounds.");

tableOut = struct2table(rows);
outputPath = fullfile(stepRoot,'M5_STEP2_STRUCTURAL_TESTS.csv');
writetable(tableOut,outputPath);
fprintf('M5_STEP2_STRUCTURAL_ROWS=%d\n',height(tableOut));
fprintf('M5_STEP2_STRUCTURAL_PASS=%d\n',all(tableOut.pass));
fprintf('M5_STEP2_STRUCTURAL_CSV=%s\n',outputPath);
end

function rows = add_row(rows,testId,variant,condition,metric,value, ...
        tolerance,notes)
pass = isfinite(value) && value <= tolerance;
row = result_row(testId,variant,condition,metric,value,tolerance,pass,notes);
rows = append_row(rows,row);
end

function rows = add_boolean_row(rows,testId,variant,condition,metric, ...
        pass,notes)
row = result_row(testId,variant,condition,metric,double(pass),0,pass,notes);
rows = append_row(rows,row);
end

function row = result_row(testId,variant,condition,metric,value, ...
        tolerance,pass,notes)
row = struct( ...
    'test_id',string(testId), ...
    'variant',string(variant), ...
    'condition',string(condition), ...
    'metric',string(metric), ...
    'value',value, ...
    'tolerance',tolerance, ...
    'pass',logical(pass), ...
    'notes',string(notes));
end

function rows = append_row(rows,row)
if isempty(rows)
    rows = row;
else
    rows(end+1,1) = row;
end
end

function tolerance = relative_tolerance(value)
tolerance = 1e-10*(1+norm(value));
end

function positions = source_positions(source,labels)
positions = nan(size(labels));
for k = 1:numel(labels)
    match = strfind(source,labels(k));
    if ~isempty(match)
        positions(k) = match(1);
    end
end
end

function [roles,names,hashes] = frozen_hash_definition()
roles = ["M2";"M3";"M4";"M4_EVIDENCE";"REGRESSOR";"DISPATCHER"];
names = [ ...
    "track_coupling_cvff_rls.m"
    "track_coupling_cvff_rls.m"
    "track_coupling_m4_weighted_rls.m"
    "m4_fault_evidence.m"
    "coupling_regressor.m"
    "run_phase1a_algorithm.m"];
hashes = [ ...
    "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
    "033135775D81BE4521AA76B8C6C2C8C3415988DA8870561722779DB0FC485D7E"
    "A0504AD65B490F803AED454BF4D8CD2C6F724D0A96DF60502F7F32789521EEC1"
    "486FF017CE4491C84FBBF84D042EF661A5AFC5A8D255F0B88AC583304D593D15"
    "7582F66875A1099DF9656F9A89FE12D8FF6972C55D4A034736527A7DB00E03D5"
    "5C623E150C179E8F86823C02D5B22760C4FBD4EEA496C7FE3B2CF1154814AD16"];
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('M5:HashFailure','Unable to hash %s.',path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end
