function result = analyze_fault_projection(X,rFault)
%ANALYZE_FAULT_PROJECTION Stable SVD/QR fault-subspace analysis.

[U,S,~] = svd(X,'econ');
singularValues = diag(S);
if isempty(singularValues)
    error('Phase1B:EmptyRegressor','The cycle regressor is empty.');
end
rankTolerance = max(size(X))*eps(singularValues(1));
rankX = sum(singularValues > rankTolerance);
if rankX == 0
    Qx = zeros(size(X,1),0);
    sigmaMin = 0;
    cond2X = Inf;
else
    Qx = U(:,1:rankX);
    sigmaMin = singularValues(rankX);
    cond2X = singularValues(1)/sigmaMin;
end

rParallel = Qx*(Qx'*rFault);
rPerp = rFault-rParallel;
rFaultEnergy = norm(rFault,2)^2;
rParallelEnergy = norm(rParallel,2)^2;
rPerpEnergy = norm(rPerp,2)^2;
closureError = abs(rFaultEnergy-rParallelEnergy-rPerpEnergy) / ...
    max(rFaultEnergy,eps);

deltaCLS = X\rFault;
projectionFitError = norm(X*deltaCLS-rParallel,2) / ...
    max(norm(rParallel,2),eps);
etaGeom = NaN;
if rFaultEnergy > 0
    etaGeom = rParallelEnergy/rFaultEnergy;
end

result = struct( ...
    'rank_X',rankX, ...
    'rank_tolerance',rankTolerance, ...
    'sigma_max',singularValues(1), ...
    'sigma_min',sigmaMin, ...
    'cond2_X',cond2X, ...
    'r_fault_norm',sqrt(rFaultEnergy), ...
    'r_parallel_norm',sqrt(rParallelEnergy), ...
    'r_perp_norm',sqrt(rPerpEnergy), ...
    'eta_geom',etaGeom, ...
    'energy_closure_relerr',closureError, ...
    'delta_c_LS',deltaCLS, ...
    'projection_fit_relerr',projectionFitError, ...
    'r_parallel',rParallel, ...
    'r_perp',rPerp);
end
