function [out,observationBlocks] = instrument_phase1b_vff_rls( ...
        data,ref,cfg,selfPF,faultScale,caseName)
%INSTRUMENT_PHASE1B_VFF_RLS Independent M2 fault/counterfactual replay.
% This function mirrors the frozen M2 update order without modifying or
% calling the original tracker implementation.

t = data.t;
N = numel(t);
fs = 1/median(diff(t));
Nc = round(fs/cfg.f);
c0 = initial_coupling_estimate(data,ref,cfg,selfPF);
idx0 = t >= cfg.init_start & t < cfg.init_end;
[X0,~] = coupling_regressor(data,ref,idx0,selfPF);
J0 = 0.05*(X0'*X0)+1e-8*eye(2);
h0 = J0*c0;

faultState = new_state(c0,J0,h0);
counterfactualState = new_state(c0,J0,h0);
lambdaNeutralState = new_state(c0,J0,h0);
faultHist = repmat(c0(:).',N,1);
counterfactualHist = faultHist;
lambdaNeutralHist = faultHist;

start = find(t >= cfg.init_end,1);
start = floor((start-1)/Nc)*Nc+1;
starts = start:Nc:(N-Nc+1);
nCycles = numel(starts);
rows = repmat(empty_cycle_row(),nCycles,1);
blocks = repmat(empty_observation_block(),nCycles,1);
faultBasic = zeros(nCycles,8);
counterfactualBasic = zeros(nCycles,8);
lambdaNeutralBasic = zeros(nCycles,8);
lastFilled = start-1;

for k = 1:nCycles
    s = starts(k);
    idx = s:(s+Nc-1);
    [X,yFault] = coupling_regressor(data,ref,idx,selfPF);
    [rFault,~] = build_phase1b_fault_component( ...
        faultScale,data.irB,idx);
    yCounterfactual = yFault-rFault;
    counterfactualIdentityError = max(abs( ...
        (yFault-yCounterfactual)-rFault));
    if ~isequal(size(X),[3*numel(idx),2]) || ...
            ~isequal(size(rFault),[3*numel(idx),1])
        error('Phase1B:ObservationAlignment', ...
            'X and r_fault are not aligned in the regression space.');
    end

    geometry = analyze_fault_projection(X,rFault);
    faultBefore = faultState;
    counterfactualBefore = counterfactualState;
    lambdaNeutralBefore = lambdaNeutralState;
    [faultState,faultLog] = advance_branch( ...
        faultState,X,yFault,t(idx),ref,cfg);
    [counterfactualState,counterfactualLog] = advance_branch( ...
        counterfactualState,X,yCounterfactual,t(idx),ref,cfg);
    [lambdaNeutralState,lambdaNeutralLog] = advance_branch( ...
        lambdaNeutralState,X,yFault,t(idx),ref,cfg, ...
        counterfactualLog.lambda);

    directA = faultLog.lambda*faultBefore.J+faultLog.R+1e-10*eye(2);
    directFault = directA\(X'*rFault);
    faultHist(idx,:) = repmat(faultState.c(:).',numel(idx),1);
    counterfactualHist(idx,:) = repmat( ...
        counterfactualState.c(:).',numel(idx),1);
    lambdaNeutralHist(idx,:) = repmat( ...
        lambdaNeutralState.c(:).',numel(idx),1);
    lastFilled = idx(end);

    rows(k) = make_cycle_row(caseName,k,t(idx(1)),t(idx(end)), ...
        idx(1),idx(end),faultScale(idx),data.Cs1(idx),data.Cs2(idx), ...
        faultBefore,counterfactualBefore,faultState,counterfactualState, ...
        lambdaNeutralBefore,lambdaNeutralState, ...
        faultLog,counterfactualLog,lambdaNeutralLog,geometry,directFault, ...
        counterfactualIdentityError);

    blocks(k) = struct( ...
        'cycle_index',k, ...
        'idx',idx(:), ...
        'X',X, ...
        'y_fault',yFault, ...
        'y_counterfactual',yCounterfactual, ...
        'r_fault',rFault, ...
        'r_parallel',geometry.r_parallel, ...
        'r_perp',geometry.r_perp);

    faultBasic(k,:) = [t(idx(end)),faultState.c(:).', ...
        faultLog.lambda,faultLog.Ein,faultLog.Equad,0,faultState.baseIn];
    counterfactualBasic(k,:) = [t(idx(end)),counterfactualState.c(:).', ...
        counterfactualLog.lambda,counterfactualLog.Ein, ...
        counterfactualLog.Equad,0,counterfactualState.baseIn];
    lambdaNeutralBasic(k,:) = [t(idx(end)),lambdaNeutralState.c(:).', ...
        lambdaNeutralLog.lambda,lambdaNeutralLog.Ein, ...
        lambdaNeutralLog.Equad,0,lambdaNeutralState.baseIn];
end

if lastFilled < N
    faultHist(lastFilled+1:N,:) = repmat( ...
        faultState.c(:).',N-lastFilled,1);
    counterfactualHist(lastFilled+1:N,:) = repmat( ...
        counterfactualState.c(:).',N-lastFilled,1);
    lambdaNeutralHist(lastFilled+1:N,:) = repmat( ...
        lambdaNeutralState.c(:).',N-lastFilled,1);
end

cycleTable = struct2table(rows,'AsArray',true);
basicNames = {'time_s','Cs1_pF','Cs2_pF','lambda', ...
    'E_in','E_quad','gate','base_in'};
out = struct();
out.schema_version = "phase1b_mechanism_v1";
out.c0 = c0;
out.Nc = Nc;
out.fault = struct( ...
    'hist',faultHist, ...
    'cycle',array2table(faultBasic,'VariableNames',basicNames));
out.counterfactual = struct( ...
    'hist',counterfactualHist, ...
    'cycle',array2table(counterfactualBasic,'VariableNames',basicNames));
out.lambda_neutral = struct( ...
    'hist',lambdaNeutralHist, ...
    'cycle',array2table(lambdaNeutralBasic,'VariableNames',basicNames));
out.mechanism_cycle_table = cycleTable;
observationBlocks = blocks;
end

function state = new_state(c,J,h)
state = struct('c',c,'J',J,'h',h,'baseIn',NaN);
end

function [state,log] = advance_branch(state,X,y,tt,ref,cfg,lambdaOverride)
R = X'*X;
z = X'*y;
cls = (R+1e-10*eye(2))\z;
innovation = norm((cls-state.c)./[5;5]);
lambda = cfg.lambda_max-(cfg.lambda_max-cfg.lambda_min)* ...
    min(max(innovation/0.20,0),1);
if nargin >= 7 && isfinite(lambdaOverride)
    lambda = lambdaOverride;
end
[Ein,Equad] = residual_components_xy( ...
    X,y,state.c,tt,ref,cfg.f);
if isnan(state.baseIn)
    state.baseIn = Ein;
end
gateTrigger = tt(end)>1.0 && ...
    Ein>cfg.gate_ratio*state.baseIn && ...
    Ein>cfg.gate_quad_ratio*Equad;

JBefore = state.J;
hBefore = state.h;
cBefore = state.c;
baseBefore = state.baseIn;
stateMismatchBefore = state.h-state.J*state.c;

state.J = lambda*state.J+R;
state.h = lambda*state.h+z;
cRaw = (state.J+1e-10*eye(2))\state.h;
deltaRaw = cRaw-state.c;
rateActive = abs(deltaRaw) > cfg.rate_limit_pF_per_cycle;
deltaRate = max(min(deltaRaw,cfg.rate_limit_pF_per_cycle), ...
    -cfg.rate_limit_pF_per_cycle);
cRateLimited = state.c+deltaRate;
projectionActive = cRateLimited < cfg.coupling_bounds_pF(1) | ...
    cRateLimited > cfg.coupling_bounds_pF(2);
state.c = min(max(cRateLimited,cfg.coupling_bounds_pF(1)), ...
    cfg.coupling_bounds_pF(2));
if Ein < 1.08*state.baseIn
    state.baseIn = 0.985*state.baseIn+0.015*Ein;
end
stateMismatchAfter = state.h-state.J*state.c;

log = struct( ...
    'R',R,'z',z,'cls',cls,'innovation',innovation,'lambda',lambda, ...
    'Ein',Ein,'Equad',Equad,'gateTrigger',gateTrigger, ...
    'JBefore',JBefore,'hBefore',hBefore,'cBefore',cBefore, ...
    'baseBefore',baseBefore,'cRaw',cRaw, ...
    'deltaRaw',deltaRaw,'rateActive',rateActive, ...
    'cRateLimited',cRateLimited,'projectionActive',projectionActive, ...
    'JAfter',state.J,'hAfter',state.h,'cAfter',state.c, ...
    'baseAfter',state.baseIn, ...
    'stateMismatchBefore',stateMismatchBefore, ...
    'stateMismatchAfter',stateMismatchAfter);
end

function [Ein,Equad] = residual_components_xy(X,y,c,tt,ref,f)
e = y-X*c;
n = numel(tt);
w = 2*pi*f;
phase = [2*pi/3,0,-2*pi/3];
EinP = zeros(3,1);
EqP = zeros(3,1);
for p = 1:3
    ep = e((p-1)*n+1:p*n);
    Bin = [sin(w*tt+ref.phi1+phase(p)),sin(3*w*tt+ref.phi3)];
    Bq = [cos(w*tt+ref.phi1+phase(p)),cos(3*w*tt+ref.phi3)];
    B = [Bin,Bq,ones(n,1)];
    coef = B\ep;
    EinP(p) = sqrt(mean((Bin*coef(1:2)).^2));
    EqP(p) = sqrt(mean((Bq*coef(3:4)).^2));
end
Ein = sqrt(mean(EinP.^2));
Equad = sqrt(mean(EqP.^2));
end

function row = make_cycle_row(caseName,cycleIndex,timeStart,timeEnd, ...
        sampleStart,sampleEnd,faultScale,Cs1True,Cs2True, ...
        faultBefore,counterfactualBefore,faultAfter,counterfactualAfter, ...
        lambdaNeutralBefore,lambdaNeutralAfter, ...
        faultLog,counterfactualLog,lambdaNeutralLog, ...
        geometry,directFault,identityError)
row = empty_cycle_row();
row.schema_version = "phase1b_mechanism_v1";
row.case_name = string(caseName);
row.algorithm_mode = "M2";
row.cycle_index = cycleIndex;
row.time_start_s = timeStart;
row.time_end_s = timeEnd;
row.sample_start_index = sampleStart;
row.sample_end_index = sampleEnd;
row.n_samples = sampleEnd-sampleStart+1;
row.fault_factor_true = mean(faultScale);
row.fault_factor_start = faultScale(1);
row.fault_factor_end = faultScale(end);
row.Cs1_true_pF = mean(Cs1True);
row.Cs2_true_pF = mean(Cs2True);
row.Cs1_est_before_pF = faultBefore.c(1);
row.Cs2_est_before_pF = faultBefore.c(2);
row.Cs1_est_pF = faultAfter.c(1);
row.Cs2_est_pF = faultAfter.c(2);
row.Cs1_cf_before_pF = counterfactualBefore.c(1);
row.Cs2_cf_before_pF = counterfactualBefore.c(2);
row.Cs1_cf_est_pF = counterfactualAfter.c(1);
row.Cs2_cf_est_pF = counterfactualAfter.c(2);
row.Cs1_lambda_neutral_before_pF = lambdaNeutralBefore.c(1);
row.Cs2_lambda_neutral_before_pF = lambdaNeutralBefore.c(2);
row.Cs1_lambda_neutral_est_pF = lambdaNeutralAfter.c(1);
row.Cs2_lambda_neutral_est_pF = lambdaNeutralAfter.c(2);
row.rank_X = geometry.rank_X;
row.sigma_max_X_A_per_pF = geometry.sigma_max;
row.sigma_min_X_A_per_pF = geometry.sigma_min;
row.cond2_X = geometry.cond2_X;
row.r_fault_norm_A = geometry.r_fault_norm;
row.r_parallel_norm_A = geometry.r_parallel_norm;
row.r_perp_norm_A = geometry.r_perp_norm;
row.eta_geom = geometry.eta_geom;
row.projection_energy_closure_relerr = geometry.energy_closure_relerr;
row.projection_fit_relerr = geometry.projection_fit_relerr;
row.counterfactual_identity_max_abs_A = identityError;
row.delta_Cs1_LS_pred_pF = geometry.delta_c_LS(1);
row.delta_Cs2_LS_pred_pF = geometry.delta_c_LS(2);
row.cLS1_code_pF = faultLog.cls(1);
row.cLS2_code_pF = faultLog.cls(2);
row.innovation = faultLog.innovation;
row.lambda = faultLog.lambda;
row.cLS1_cf_code_pF = counterfactualLog.cls(1);
row.cLS2_cf_code_pF = counterfactualLog.cls(2);
row.innovation_cf = counterfactualLog.innovation;
row.lambda_cf = counterfactualLog.lambda;
row.innovation_lambda_neutral = lambdaNeutralLog.innovation;
row.lambda_neutral = lambdaNeutralLog.lambda;
row.R11 = faultLog.R(1,1);
row.R12 = faultLog.R(1,2);
row.R22 = faultLog.R(2,2);
row.z1 = faultLog.z(1);
row.z2 = faultLog.z(2);
row.J11_before = faultLog.JBefore(1,1);
row.J12_before = faultLog.JBefore(1,2);
row.J22_before = faultLog.JBefore(2,2);
row.h1_before = faultLog.hBefore(1);
row.h2_before = faultLog.hBefore(2);
row.J11_after = faultLog.JAfter(1,1);
row.J12_after = faultLog.JAfter(1,2);
row.J22_after = faultLog.JAfter(2,2);
row.h1_after = faultLog.hAfter(1);
row.h2_after = faultLog.hAfter(2);
row.delta_Cs1_RLS_direct_raw_pF = directFault(1);
row.delta_Cs2_RLS_direct_raw_pF = directFault(2);
row.delta_Cs1_RLS_fault_cf_raw_pF = ...
    faultLog.cRaw(1)-counterfactualLog.cRaw(1);
row.delta_Cs2_RLS_fault_cf_raw_pF = ...
    faultLog.cRaw(2)-counterfactualLog.cRaw(2);
row.Cs1_raw_pF = faultLog.cRaw(1);
row.Cs2_raw_pF = faultLog.cRaw(2);
row.Cs1_rate_limited_pF = faultLog.cRateLimited(1);
row.Cs2_rate_limited_pF = faultLog.cRateLimited(2);
row.Cs1_projected_pF = faultAfter.c(1);
row.Cs2_projected_pF = faultAfter.c(2);
row.Cs1_cf_raw_pF = counterfactualLog.cRaw(1);
row.Cs2_cf_raw_pF = counterfactualLog.cRaw(2);
row.Cs1_cf_rate_limited_pF = counterfactualLog.cRateLimited(1);
row.Cs2_cf_rate_limited_pF = counterfactualLog.cRateLimited(2);
row.delta_Cs1_RLS_pred_pF = faultAfter.c(1)-faultBefore.c(1);
row.delta_Cs2_RLS_pred_pF = faultAfter.c(2)-faultBefore.c(2);
row.delta_Cs1_actual_pF = NaN;
row.delta_Cs2_actual_pF = NaN;
row.prediction_error_Cs1_pF = NaN;
row.prediction_error_Cs2_pF = NaN;
row.rate_limit_active_Cs1 = faultLog.rateActive(1);
row.rate_limit_active_Cs2 = faultLog.rateActive(2);
row.projection_active_Cs1 = faultLog.projectionActive(1);
row.projection_active_Cs2 = faultLog.projectionActive(2);
row.E_in_A = faultLog.Ein;
row.E_quad_A = faultLog.Equad;
row.base_in_A = faultAfter.baseIn;
row.E_in_cf_A = counterfactualLog.Ein;
row.E_quad_cf_A = counterfactualLog.Equad;
row.base_in_cf_A = counterfactualAfter.baseIn;
row.gate_trigger_condition = faultLog.gateTrigger;
row.gate_active = false;
row.gate_hold_before = 0;
row.gate_hold_after = 0;
row.state_mismatch_norm_before = norm(faultLog.stateMismatchBefore,2);
row.state_mismatch_norm_after = norm(faultLog.stateMismatchAfter,2);
row.state_mismatch_rel_after = norm(faultLog.stateMismatchAfter,2) / ...
    max(norm(faultLog.hAfter,2),eps);
row.state_mismatch_cf_norm_after = ...
    norm(counterfactualLog.stateMismatchAfter,2);
row.state_mismatch_cf_rel_after = ...
    norm(counterfactualLog.stateMismatchAfter,2) / ...
    max(norm(counterfactualLog.hAfter,2),eps);
end

function row = empty_cycle_row()
row = struct( ...
    'schema_version',"",'case_name',"",'algorithm_mode',"", ...
    'cycle_index',0,'time_start_s',0,'time_end_s',0, ...
    'sample_start_index',0,'sample_end_index',0,'n_samples',0, ...
    'fault_factor_true',0,'fault_factor_start',0,'fault_factor_end',0, ...
    'Cs1_true_pF',0,'Cs2_true_pF',0, ...
    'Cs1_est_before_pF',0,'Cs2_est_before_pF',0, ...
    'Cs1_est_pF',0,'Cs2_est_pF',0, ...
    'Cs1_cf_before_pF',0,'Cs2_cf_before_pF',0, ...
    'Cs1_cf_est_pF',0,'Cs2_cf_est_pF',0, ...
    'Cs1_lambda_neutral_before_pF',0, ...
    'Cs2_lambda_neutral_before_pF',0, ...
    'Cs1_lambda_neutral_est_pF',0, ...
    'Cs2_lambda_neutral_est_pF',0, ...
    'rank_X',0,'sigma_max_X_A_per_pF',0, ...
    'sigma_min_X_A_per_pF',0,'cond2_X',0, ...
    'r_fault_norm_A',0,'r_parallel_norm_A',0,'r_perp_norm_A',0, ...
    'eta_geom',NaN,'projection_energy_closure_relerr',0, ...
    'projection_fit_relerr',0,'counterfactual_identity_max_abs_A',0, ...
    'delta_Cs1_LS_pred_pF',0,'delta_Cs2_LS_pred_pF',0, ...
    'cLS1_code_pF',0,'cLS2_code_pF',0,'innovation',0,'lambda',0, ...
    'cLS1_cf_code_pF',0,'cLS2_cf_code_pF',0, ...
    'innovation_cf',0,'lambda_cf',0, ...
    'innovation_lambda_neutral',0,'lambda_neutral',0, ...
    'R11',0,'R12',0,'R22',0,'z1',0,'z2',0, ...
    'J11_before',0,'J12_before',0,'J22_before',0, ...
    'h1_before',0,'h2_before',0, ...
    'J11_after',0,'J12_after',0,'J22_after',0, ...
    'h1_after',0,'h2_after',0, ...
    'delta_Cs1_RLS_direct_raw_pF',0, ...
    'delta_Cs2_RLS_direct_raw_pF',0, ...
    'delta_Cs1_RLS_fault_cf_raw_pF',0, ...
    'delta_Cs2_RLS_fault_cf_raw_pF',0, ...
    'Cs1_raw_pF',0,'Cs2_raw_pF',0, ...
    'Cs1_rate_limited_pF',0,'Cs2_rate_limited_pF',0, ...
    'Cs1_projected_pF',0,'Cs2_projected_pF',0, ...
    'Cs1_cf_raw_pF',0,'Cs2_cf_raw_pF',0, ...
    'Cs1_cf_rate_limited_pF',0,'Cs2_cf_rate_limited_pF',0, ...
    'delta_Cs1_RLS_pred_pF',0,'delta_Cs2_RLS_pred_pF',0, ...
    'delta_Cs1_actual_pF',NaN,'delta_Cs2_actual_pF',NaN, ...
    'prediction_error_Cs1_pF',NaN,'prediction_error_Cs2_pF',NaN, ...
    'rate_limit_active_Cs1',false,'rate_limit_active_Cs2',false, ...
    'projection_active_Cs1',false,'projection_active_Cs2',false, ...
    'E_in_A',0,'E_quad_A',0,'base_in_A',0, ...
    'E_in_cf_A',0,'E_quad_cf_A',0,'base_in_cf_A',0, ...
    'gate_trigger_condition',false,'gate_active',false, ...
    'gate_hold_before',0,'gate_hold_after',0, ...
    'state_mismatch_norm_before',0,'state_mismatch_norm_after',0, ...
    'state_mismatch_rel_after',0, ...
    'state_mismatch_cf_norm_after',0,'state_mismatch_cf_rel_after',0);
end

function block = empty_observation_block()
block = struct( ...
    'cycle_index',0, ...
    'idx',zeros(0,1), ...
    'X',zeros(0,2), ...
    'y_fault',zeros(0,1), ...
    'y_counterfactual',zeros(0,1), ...
    'r_fault',zeros(0,1), ...
    'r_parallel',zeros(0,1), ...
    'r_perp',zeros(0,1));
end
