function result = run_phase1b_step2_case05()
%RUN_PHASE1B_STEP2_CASE05 Case05 fault-absorption mechanism experiment.

step2Root = fileparts(mfilename('fullpath'));
phase1bRoot = fileparts(step2Root);
projectRoot = fileparts(fileparts(phase1bRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
figuresRoot = fullfile(step2Root,'figures');
addpath(matlabRoot);
addpath(step2Root);
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

expected = frozen_integrity();
modelPath = fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx');
baselineCsvPath = fullfile(projectRoot,'paper_research', ...
    'phase1a_baseline','baseline_summary.csv');
baselineWorkspacePath = fullfile(projectRoot,'paper_research', ...
    'phase1a_baseline','baseline_workspace.mat');
step1Path = fullfile(phase1bRoot,'STEP1_THEORY_AND_DATA_DEFINITION.md');
assert(file_sha256(modelPath) == expected.model_sha256, ...
    'Phase1B:Integrity','AutoComp9 hash mismatch.');
assert(file_sha256(baselineCsvPath) == expected.baseline_csv_sha256, ...
    'Phase1B:Integrity','Phase 1A baseline CSV hash mismatch.');
assert(file_sha256(step1Path) == expected.step1_sha256, ...
    'Phase1B:Integrity','Step 1 report hash mismatch.');
runMetadata = capture_metadata(projectRoot,modelPath,baselineCsvPath,step1Path);

cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
cfg.output_dir = step2Root;
registry = phase1a_case_registry();
caseInfo = registry(registry.case_name == "Case05_fault_only",:);
if height(caseInfo) ~= 1
    error('Phase1B:CaseRegistry','Case05 registry entry is not unique.');
end
seed = caseInfo.seed;
tInput = (0:cfg.Ts:cfg.StopTime).';
signals = generate_coupling_signals(tInput,caseInfo.case_name,seed);

fprintf('PHASE1B_STEP2_CASE_START=%s seed=%d\n', ...
    caseInfo.case_name,seed);
[data,~] = simulate_phase2_case(cfg, ...
    char(caseInfo.legacy_scenario_name),seed);
ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
selfPF = repmat(cfg.Cself_pF,1,3);

originalM2 = track_coupling_cvff_rls(data,ref,cfg,selfPF,false);
originalM3 = track_coupling_cvff_rls(data,ref,cfg,selfPF,true);
[instrumented,observationBlocks] = instrument_phase1b_vff_rls( ...
    data,ref,cfg,selfPF,signals.fault_scale,caseInfo.case_name);

formal = load(baselineWorkspacePath,'caseData','algorithmResults');
formalCase = formal.caseData.Case05_fault_only;
formalM2 = formal.algorithmResults.Case05_fault_only.M2;
formalM3 = formal.algorithmResults.Case05_fault_only.M3;
formalCsv = readtable(baselineCsvPath,'TextType','string');
formalM2Row = formalCsv( ...
    formalCsv.case_name == "Case05_fault_only" & ...
    formalCsv.algorithm_mode == "M2",:);
if height(formalM2Row) ~= 1
    error('Phase1B:FormalRow','Formal Case05 M2 row is not unique.');
end

validation = validate_replay(data,signals,originalM2,originalM3, ...
    instrumented,formalCase,formalM2,formalM3);
if ~validation.instrumentation_equivalent
    error('Phase1B:InstrumentationMismatch', ...
        'Independent instrumentation does not match frozen M2.');
end

cycleTable = instrumented.mechanism_cycle_table;
c0 = instrumented.c0(:).';
originalBefore = [c0; ...
    originalM2.cycle.Cs1_pF(1:end-1), ...
    originalM2.cycle.Cs2_pF(1:end-1)];
originalAfter = [originalM2.cycle.Cs1_pF,originalM2.cycle.Cs2_pF];
actualDelta = originalAfter-originalBefore;
cycleTable.delta_Cs1_actual_pF = actualDelta(:,1);
cycleTable.delta_Cs2_actual_pF = actualDelta(:,2);
cycleTable.prediction_error_Cs1_pF = ...
    cycleTable.delta_Cs1_RLS_pred_pF-actualDelta(:,1);
cycleTable.prediction_error_Cs2_pF = ...
    cycleTable.delta_Cs2_RLS_pred_pF-actualDelta(:,2);

analysis = calculate_mechanism_metrics(data,signals,ref,cfg,selfPF, ...
    originalM2,originalM3,instrumented,cycleTable,formalM2Row);
validation.observation_alignment = all(cycleTable.n_samples == 1000) && ...
    all(cycleTable.rank_X == 2);
validation.counterfactual_identity_max_abs_A = ...
    max(cycleTable.counterfactual_identity_max_abs_A);
validation.projection_energy_closure_max = ...
    max(cycleTable.projection_energy_closure_relerr);
validation.projection_fit_relerr_max = ...
    max(cycleTable.projection_fit_relerr);
validation.projection_pass = ...
    validation.projection_energy_closure_max <= 1e-10;
validation.prediction_replay_max_abs_pF = max(abs([ ...
    cycleTable.prediction_error_Cs1_pF; ...
    cycleTable.prediction_error_Cs2_pF]));
validation.overall_pass = validation.instrumentation_equivalent && ...
    validation.observation_alignment && validation.projection_pass && ...
    validation.prediction_replay_max_abs_pF <= 1e-12;

summaryPath = fullfile(step2Root,'case05_mechanism_summary.csv');
keyMetricsPath = fullfile(step2Root,'case05_key_metrics.csv');
observationPath = fullfile(step2Root,'observation_blocks_case05.mat');
workspacePath = fullfile(step2Root,'case05_mechanism_workspace.mat');
writetable(cycleTable,summaryPath);
keyMetricsTable = struct2table(analysis.key_metrics,'AsArray',true);
writetable(keyMetricsTable,keyMetricsPath);

schemaVersion = "phase1b_mechanism_v1";
save(observationPath,'schemaVersion','observationBlocks', ...
    'runMetadata','-v7.3');

figurePaths = generate_phase1b_step2_figures( ...
    figuresRoot,data,signals,originalM2,instrumented, ...
    cycleTable,observationBlocks,analysis);
result = struct( ...
    'schema_version',schemaVersion, ...
    'cfg',cfg, ...
    'caseInfo',caseInfo, ...
    'runMetadata',runMetadata, ...
    'cycleTable',cycleTable, ...
    'keyMetrics',analysis.key_metrics, ...
    'validation',validation, ...
    'figurePaths',figurePaths, ...
    'summaryPath',string(summaryPath), ...
    'keyMetricsPath',string(keyMetricsPath), ...
    'observationPath',string(observationPath), ...
    'workspacePath',string(workspacePath));
save(workspacePath,'cfg','caseInfo','runMetadata','signals','data','ref', ...
    'originalM2','originalM3','instrumented','cycleTable','analysis', ...
    'validation','figurePaths','result','-v7.3');

print_key_results(analysis.key_metrics,validation,summaryPath,workspacePath);
if ~validation.overall_pass
    error('Phase1B:Step2Validation', ...
        'One or more Phase 1B Step 2 validation checks failed.');
end
fprintf('STEP2_BASELINE_MECHANISM=PASS\n');
end

function validation = validate_replay(data,signals,originalM2,originalM3, ...
        instrumented,formalCase,formalM2,formalM3)
validation = struct();
validation.Cs1_replay_max_abs = max(abs( ...
    originalM2.hist(:,1)-instrumented.fault.hist(:,1)));
validation.Cs2_replay_max_abs = max(abs( ...
    originalM2.hist(:,2)-instrumented.fault.hist(:,2)));
validation.lambda_replay_max_abs = max(abs( ...
    originalM2.cycle.lambda-instrumented.fault.cycle.lambda));
validation.E_in_replay_max_abs = max(abs( ...
    originalM2.cycle.E_in-instrumented.fault.cycle.E_in));
validation.E_quad_replay_max_abs = max(abs( ...
    originalM2.cycle.E_quad-instrumented.fault.cycle.E_quad));
validation.base_in_replay_max_abs = max(abs( ...
    originalM2.cycle.base_in-instrumented.fault.cycle.base_in));
validation.gate_replay_max_abs = max(abs( ...
    originalM2.cycle.gate-instrumented.fault.cycle.gate));
replayErrors = [validation.Cs1_replay_max_abs, ...
    validation.Cs2_replay_max_abs,validation.lambda_replay_max_abs, ...
    validation.E_in_replay_max_abs,validation.E_quad_replay_max_abs, ...
    validation.base_in_replay_max_abs,validation.gate_replay_max_abs];
validation.instrumentation_equivalent = all(replayErrors <= 1e-12);

validation.formal_time_max_abs = max(abs(data.t-formalCase.t));
validation.formal_Cs1_truth_max_abs = max(abs(data.Cs1-formalCase.Cs1_true));
validation.formal_Cs2_truth_max_abs = max(abs(data.Cs2-formalCase.Cs2_true));
validation.formal_fault_scale_max_abs = max(abs( ...
    signals.fault_scale-formalCase.fault_scale));
validation.formal_irB_true_max_abs = max(abs(data.irB-formalCase.irB_true));
validation.formal_M2_cHist_max_abs = max(abs( ...
    originalM2.hist-formalM2.cHist),[],'all');
validation.formal_M2_cycle_max_abs = max(abs( ...
    originalM2.cycle{:,:}-formalM2.cycle{:,:}),[],'all');
validation.formal_M3_cHist_max_abs = max(abs( ...
    originalM3.hist-formalM3.cHist),[],'all');
formalErrors = [validation.formal_time_max_abs, ...
    validation.formal_Cs1_truth_max_abs,validation.formal_Cs2_truth_max_abs, ...
    validation.formal_fault_scale_max_abs,validation.formal_irB_true_max_abs, ...
    validation.formal_M2_cHist_max_abs,validation.formal_M2_cycle_max_abs, ...
    validation.formal_M3_cHist_max_abs];
validation.formal_case_reproduced = all(formalErrors <= 1e-12);
end

function analysis = calculate_mechanism_metrics( ...
        data,signals,ref,cfg,selfPF,originalM2,originalM3, ...
        instrumented,cycleTable,formalM2Row)
t = data.t;
preIdx = t >= 2.60 & t < 2.90;
postIdx = t >= 3.40 & t < 3.80;
preCycle = cycleTable.time_start_s >= 2.60 & cycleTable.time_end_s < 2.90;
rampCycle = cycleTable.r_fault_norm_A > 0 & ...
    cycleTable.time_start_s < 3.06 & cycleTable.time_end_s > 3.00;
postCycle = cycleTable.time_start_s >= 3.06;
steadyCycle = cycleTable.time_start_s >= 3.40 & ...
    cycleTable.time_end_s < 3.80;
faultCycle = cycleTable.r_fault_norm_A > 0;

faultHist = instrumented.fault.hist;
counterfactualHist = instrumented.counterfactual.hist;
lambdaNeutralHist = instrumented.lambda_neutral.hist;
actualChange = parameter_change(originalM2.hist,preIdx,postIdx);
faultReplayChange = parameter_change(faultHist,preIdx,postIdx);
counterfactualChange = parameter_change(counterfactualHist,preIdx,postIdx);
lambdaNeutralChange = parameter_change(lambdaNeutralHist,preIdx,postIdx);
predictedFaultInduced = faultReplayChange-counterfactualChange;
lambdaFeedbackContribution = faultReplayChange-lambdaNeutralChange;

irM2 = extract_resistive_current(data,ref,selfPF,originalM2.hist);
irCounterfactualParameters = extract_resistive_current( ...
    data,ref,selfPF,counterfactualHist);
irM3 = extract_resistive_current(data,ref,selfPF,originalM3.hist);
trueFactor = fault_factor(t,data.irB,preIdx,postIdx,cfg.f);
m2Factor = fault_factor(t,irM2.B,preIdx,postIdx,cfg.f);
counterfactualParameterFactor = fault_factor( ...
    t,irCounterfactualParameters.B,preIdx,postIdx,cfg.f);
m3Factor = fault_factor(t,irM3.B,preIdx,postIdx,cfg.f);

deltaC = faultHist-counterfactualHist;
deltaCouplingB = deltaC(:,1)*1e-12.*(ref.dub-ref.dua) + ...
    deltaC(:,2)*1e-12.*(ref.dub-ref.duc);
rFaultB = (1-1./signals.fault_scale).*data.irB;
[rFaultRms,rFaultPhase] = fundamental_properties( ...
    t(postIdx),rFaultB(postIdx),cfg.f);
[deltaCouplingRms,deltaCouplingPhase] = fundamental_properties( ...
    t(postIdx),deltaCouplingB(postIdx),cfg.f);
correlationMatrix = corrcoef(rFaultB(postIdx),deltaCouplingB(postIdx));
if numel(correlationMatrix) == 4
    couplingFaultCorrelation = correlationMatrix(1,2);
else
    couplingFaultCorrelation = NaN;
end

key = struct();
key.case_name = "Case05_fault_only";
key.seed = 106;
key.true_fault_factor = trueFactor;
key.M2_actual_fault_factor = m2Factor;
key.M2_formal_fault_factor = formalM2Row.fault_factor_est;
key.counterfactual_parameter_fault_factor = counterfactualParameterFactor;
key.M3_auxiliary_fault_factor = m3Factor;
key.M2_actual_Delta_Cs1_pF = actualChange(1);
key.M2_actual_Delta_Cs2_pF = actualChange(2);
key.M2_formal_Delta_Cs1_pF = formalM2Row.Cs1_pre_post_change_pF;
key.M2_formal_Delta_Cs2_pF = formalM2Row.Cs2_pre_post_change_pF;
key.recursive_fault_induced_Delta_Cs1_pF = predictedFaultInduced(1);
key.recursive_fault_induced_Delta_Cs2_pF = predictedFaultInduced(2);
key.recursive_prediction_error_Cs1_pF = ...
    predictedFaultInduced(1)-actualChange(1);
key.recursive_prediction_error_Cs2_pF = ...
    predictedFaultInduced(2)-actualChange(2);
key.recursive_prediction_relative_error_Cs1_pct = ...
    100*key.recursive_prediction_error_Cs1_pF/(abs(actualChange(1))+eps);
key.recursive_prediction_relative_error_Cs2_pct = ...
    100*key.recursive_prediction_error_Cs2_pF/(abs(actualChange(2))+eps);
key.counterfactual_Delta_Cs1_pF = counterfactualChange(1);
key.counterfactual_Delta_Cs2_pF = counterfactualChange(2);
key.lambda_neutral_Delta_Cs1_pF = lambdaNeutralChange(1);
key.lambda_neutral_Delta_Cs2_pF = lambdaNeutralChange(2);
key.lambda_feedback_contribution_Cs1_pF = lambdaFeedbackContribution(1);
key.lambda_feedback_contribution_Cs2_pF = lambdaFeedbackContribution(2);
key.eta_geom_fault_ramp_mean = mean(cycleTable.eta_geom(rampCycle));
key.eta_geom_post_fault_mean = mean(cycleTable.eta_geom(postCycle));
key.eta_geom_fault_min = min(cycleTable.eta_geom(faultCycle));
key.eta_geom_fault_max = max(cycleTable.eta_geom(faultCycle));
key.rank_X_min = min(cycleTable.rank_X);
key.rank_X_max = max(cycleTable.rank_X);
key.cond2_X_min = min(cycleTable.cond2_X);
key.cond2_X_max = max(cycleTable.cond2_X);
key.cond2_X_mean = mean(cycleTable.cond2_X);
key.lambda_fault_pre_mean = mean(cycleTable.lambda(preCycle));
key.lambda_cf_pre_mean = mean(cycleTable.lambda_cf(preCycle));
key.lambda_fault_ramp_mean = mean(cycleTable.lambda(rampCycle));
key.lambda_cf_ramp_mean = mean(cycleTable.lambda_cf(rampCycle));
key.lambda_fault_post_mean = mean(cycleTable.lambda(steadyCycle));
key.lambda_cf_post_mean = mean(cycleTable.lambda_cf(steadyCycle));
key.lambda_fault_minus_cf_ramp_mean = mean( ...
    cycleTable.lambda(rampCycle)-cycleTable.lambda_cf(rampCycle));
key.lambda_fault_minus_cf_post_mean = mean( ...
    cycleTable.lambda(steadyCycle)-cycleTable.lambda_cf(steadyCycle));
key.rate_limit_active_Cs1_cycles = sum( ...
    cycleTable.rate_limit_active_Cs1 & faultCycle);
key.rate_limit_active_Cs2_cycles = sum( ...
    cycleTable.rate_limit_active_Cs2 & faultCycle);
key.rate_limit_active_any_cycles = sum( ...
    (cycleTable.rate_limit_active_Cs1 | ...
    cycleTable.rate_limit_active_Cs2) & faultCycle);
key.projection_active_Cs1_cycles = sum( ...
    cycleTable.projection_active_Cs1 & faultCycle);
key.projection_active_Cs2_cycles = sum( ...
    cycleTable.projection_active_Cs2 & faultCycle);
key.state_mismatch_pre_mean = mean( ...
    cycleTable.state_mismatch_rel_after(preCycle));
key.state_mismatch_ramp_mean = mean( ...
    cycleTable.state_mismatch_rel_after(rampCycle));
key.state_mismatch_post_mean = mean( ...
    cycleTable.state_mismatch_rel_after(steadyCycle));
key.state_mismatch_post_max = max( ...
    cycleTable.state_mismatch_rel_after(postCycle));
key.E_in_pre_mean_A = mean(cycleTable.E_in_A(preCycle));
key.E_in_ramp_mean_A = mean(cycleTable.E_in_A(rampCycle));
key.E_in_post_mean_A = mean(cycleTable.E_in_A(steadyCycle));
key.E_quad_pre_mean_A = mean(cycleTable.E_quad_A(preCycle));
key.E_quad_ramp_mean_A = mean(cycleTable.E_quad_A(rampCycle));
key.E_quad_post_mean_A = mean(cycleTable.E_quad_A(steadyCycle));
key.E_in_post_change_pct = 100*(key.E_in_post_mean_A- ...
    key.E_in_pre_mean_A)/(key.E_in_pre_mean_A+eps);
key.E_quad_post_change_pct = 100*(key.E_quad_post_mean_A- ...
    key.E_quad_pre_mean_A)/(key.E_quad_pre_mean_A+eps);
key.r_fault_B_fundamental_rms_A = rFaultRms;
key.delta_coupling_B_fundamental_rms_A = deltaCouplingRms;
key.delta_coupling_to_fault_fundamental_ratio = ...
    deltaCouplingRms/(rFaultRms+eps);
key.delta_coupling_fault_phase_difference_deg = ...
    wrap_to_180(deltaCouplingPhase-rFaultPhase);
key.delta_coupling_fault_correlation = couplingFaultCorrelation;
key.M2_fault_retention_error_pct = 100*(m2Factor-trueFactor)/trueFactor;
key.counterfactual_parameter_retention_error_pct = ...
    100*(counterfactualParameterFactor-trueFactor)/trueFactor;

analysis = struct( ...
    'key_metrics',key, ...
    'masks',struct('pre_cycle',preCycle,'ramp_cycle',rampCycle, ...
        'post_cycle',postCycle,'steady_cycle',steadyCycle, ...
        'fault_cycle',faultCycle,'pre_sample',preIdx,'post_sample',postIdx), ...
    'irM2',irM2, ...
    'irCounterfactualParameters',irCounterfactualParameters, ...
    'irM3',irM3, ...
    'rFaultB',rFaultB, ...
    'deltaCouplingB',deltaCouplingB);
end

function change = parameter_change(cHist,preIdx,postIdx)
change = mean(cHist(postIdx,:),1)-mean(cHist(preIdx,:),1);
end

function value = fault_factor(t,x,preIdx,postIdx,f)
value = fundamental_rms(t(postIdx),x(postIdx),f) / ...
    (fundamental_rms(t(preIdx),x(preIdx),f)+eps);
end

function value = fundamental_rms(t,x,f)
w = 2*pi*f;
coefficients = [sin(w*t),cos(w*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
end

function [value,phaseDeg] = fundamental_properties(t,x,f)
w = 2*pi*f;
coefficients = [sin(w*t),cos(w*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
phaseDeg = rad2deg(atan2(coefficients(2),coefficients(1)));
end

function value = wrap_to_180(value)
value = mod(value+180,360)-180;
end

function expected = frozen_integrity()
expected = struct( ...
    'model_sha256', ...
    "56067ADAADF59B5921D7156A2ABB61777C4E98B69CB4150759C3CB1D4D6A2A70", ...
    'baseline_csv_sha256', ...
    "E7BEB3ECFEDF521105B67198684752BB32AFAAEFD84ACA80822BA57FBD9D0AB3", ...
    'step1_sha256', ...
    "02859DD0D35E35C18722B452DC7A5C9EE73B55CC6E7A26FC5566500F6E4B9041");
end

function metadata = capture_metadata(projectRoot,modelPath,csvPath,step1Path)
[commitCode,commit] = system(sprintf('git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1B:GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_status',string(status), ...
    'model_sha256',file_sha256(modelPath), ...
    'baseline_csv_sha256',file_sha256(csvPath), ...
    'step1_report_sha256',file_sha256(step1Path), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1B:HashFailure','Unable to open %s.',path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_key_results(key,validation,summaryPath,workspacePath)
fprintf('INSTRUMENTATION_REPLAY_MAX=%.17g\n',max([ ...
    validation.Cs1_replay_max_abs,validation.Cs2_replay_max_abs, ...
    validation.lambda_replay_max_abs,validation.E_in_replay_max_abs, ...
    validation.E_quad_replay_max_abs,validation.base_in_replay_max_abs]));
fprintf('FORMAL_CASE_REPRODUCED=%d\n',validation.formal_case_reproduced);
fprintf('PROJECTION_CLOSURE_MAX=%.17g\n', ...
    validation.projection_energy_closure_max);
fprintf('TRUE_FAULT_FACTOR=%.17g\n',key.true_fault_factor);
fprintf('M2_FAULT_FACTOR=%.17g\n',key.M2_actual_fault_factor);
fprintf('M2_DELTA_CS_PF=%.17g,%.17g\n', ...
    key.M2_actual_Delta_Cs1_pF,key.M2_actual_Delta_Cs2_pF);
fprintf('RECURSIVE_FAULT_INDUCED_DELTA_CS_PF=%.17g,%.17g\n', ...
    key.recursive_fault_induced_Delta_Cs1_pF, ...
    key.recursive_fault_induced_Delta_Cs2_pF);
fprintf('ETA_GEOM_RAMP_POST=%.17g,%.17g\n', ...
    key.eta_geom_fault_ramp_mean,key.eta_geom_post_fault_mean);
fprintf('COND2_X_RANGE=%.17g,%.17g\n', ...
    key.cond2_X_min,key.cond2_X_max);
fprintf('RATE_LIMIT_CYCLES=%d,%d\n', ...
    key.rate_limit_active_Cs1_cycles,key.rate_limit_active_Cs2_cycles);
fprintf('PROJECTION_CYCLES=%d,%d\n', ...
    key.projection_active_Cs1_cycles,key.projection_active_Cs2_cycles);
fprintf('SUMMARY_CSV=%s\n',summaryPath);
fprintf('WORKSPACE_MAT=%s\n',workspacePath);
end
