function evaluated = evaluate_phase1c_step3_case( ...
        caseInfo,data,~,cfg,algorithmResults,metadata)
%EVALUATE_PHASE1C_STEP3_CASE Evaluate one no-fault case for M2/M3/M4.

modes = ["M2","M3","M4"];
summaryRows = cell(numel(modes),1);
lagRows = cell(0,1);
metricIndex = data.t >= cfg.metric_start;

for modeIndex = 1:numel(modes)
    mode = modes(modeIndex);
    algorithmResult = algorithmResults.(char(mode));
    official = evaluate_phase1a_metrics( ...
        caseInfo,algorithmResult,data,cfg,metadata);
    maxErrorCs1 = max(abs(algorithmResult.cHist(metricIndex,1)- ...
        data.Cs1(metricIndex)));
    maxErrorCs2 = max(abs(algorithmResult.cHist(metricIndex,2)- ...
        data.Cs2(metricIndex)));

    meanWeight = NaN;
    unnecessarySuppression = NaN;
    hardGateActiveRatio = NaN;
    if mode == "M4"
        meanWeight = mean(algorithmResult.tracker.cycle.update_weight);
        unnecessarySuppression = mean( ...
            1-algorithmResult.tracker.cycle.update_weight);
    elseif mode == "M3"
        hardGateActiveRatio = mean(algorithmResult.tracker.cycle.gate > 0);
    end

    summaryRows{modeIndex} = table( ...
        string(caseInfo.case_name),mode,official.Cs1_RMSE_pF, ...
        official.Cs2_RMSE_pF,maxErrorCs1,maxErrorCs2, ...
        official.B_resistive_fundamental_error_pct, ...
        meanWeight,unnecessarySuppression,hardGateActiveRatio, ...
        'VariableNames',{'case_name','algorithm_mode', ...
        'Cs1_RMSE_pF','Cs2_RMSE_pF', ...
        'Cs1_max_abs_error_pF','Cs2_max_abs_error_pF', ...
        'B_resistive_fundamental_error_pct', ...
        'mean_update_weight','unnecessary_suppression_ratio', ...
        'hard_gate_active_ratio'});

    if any(string(caseInfo.case_name) == ...
            ["Case02_slow_drift","Case03_smooth_step"])
        lagRows{end+1,1} = tracking_lag_row( ...
            caseInfo.case_name,mode,data,algorithmResult); %#ok<AGROW>
    end
end

m4 = algorithmResults.M4;
cycle = m4.tracker.cycle;
cycleIndex = (1:height(cycle)).';
trueCs1 = interp1(data.t,data.Cs1,cycle.time_s,'linear');
trueCs2 = interp1(data.t,data.Cs2,cycle.time_s,'linear');
deltaTrueCs1 = [NaN;diff(trueCs1)];
deltaTrueCs2 = [NaN;diff(trueCs2)];
driftMagnitude = hypot(deltaTrueCs1,deltaTrueCs2);
suppression = 1-cycle.update_weight;
parameterErrorNorm = hypot(cycle.Cs1_pF-trueCs1, ...
    cycle.Cs2_pF-trueCs2);

cycleDetail = addvars(cycle, ...
    repmat(string(caseInfo.case_name),height(cycle),1),cycleIndex, ...
    trueCs1,trueCs2,deltaTrueCs1,deltaTrueCs2,driftMagnitude, ...
    suppression,parameterErrorNorm, ...
    'Before',1,'NewVariableNames',{'case_name','cycle_index', ...
    'Cs1_true_pF','Cs2_true_pF','delta_Cs1_true_pF', ...
    'delta_Cs2_true_pF','drift_magnitude_pF_per_cycle', ...
    'normal_suppression','parameter_error_norm_pF'});

m4Diagnostics = m4_diagnostics_row(caseInfo.case_name,cycle);
directionDiagnostics = direction_diagnostics_row( ...
    caseInfo.case_name,cycle);
phaseDiagnostics = phase_diagnostics( ...
    caseInfo.case_name,cycleDetail);

if string(caseInfo.case_name) == "Case01_static"
    correlationRows = empty_correlation_table();
else
    correlationRows = drift_correlation_rows( ...
        caseInfo.case_name,cycleDetail);
end

evaluated = struct( ...
    'summary',vertcat(summaryRows{:}), ...
    'm4_diagnostics',m4Diagnostics, ...
    'cycle_detail',cycleDetail, ...
    'correlations',correlationRows, ...
    'direction_diagnostics',directionDiagnostics, ...
    'phase_diagnostics',phaseDiagnostics, ...
    'tracking_lag',combine_lag_rows(lagRows));
end

function tableOut = combine_lag_rows(rows)
if isempty(rows)
    tableOut = table('Size',[0,8], ...
        'VariableTypes',{'string','string','double','double', ...
        'double','double','double','double'}, ...
        'VariableNames',{'case_name','algorithm_mode', ...
        'Cs1_midpoint_crossing_lag_s','Cs2_midpoint_crossing_lag_s', ...
        'Cs1_true_midpoint_crossing_s','Cs2_true_midpoint_crossing_s', ...
        'Cs1_est_midpoint_crossing_s','Cs2_est_midpoint_crossing_s'});
else
    tableOut = vertcat(rows{:});
end
end

function row = m4_diagnostics_row(caseName,cycle)
g = cycle.update_weight;
jRaw = cycle{:,{'J_increment_raw_11','J_increment_raw_12', ...
    'J_increment_raw_21','J_increment_raw_22'}};
jApplied = cycle{:,{'J_increment_applied_11', ...
    'J_increment_applied_12','J_increment_applied_21', ...
    'J_increment_applied_22'}};
hRaw = cycle{:,{'h_increment_raw_1','h_increment_raw_2'}};
hApplied = cycle{:,{'h_increment_applied_1', ...
    'h_increment_applied_2'}};
jRawNorm = vecnorm(jRaw,2,2);
hRawNorm = vecnorm(hRaw,2,2);
informationRatioJ = sum(vecnorm(jRaw-jApplied,2,2))/ ...
    (sum(jRawNorm)+eps);
informationRatioH = sum(vecnorm(hRaw-hApplied,2,2))/ ...
    (sum(hRawNorm)+eps);
suppressedCs1 = cycle.delta_c_information_suppressed_1;
suppressedCs2 = cycle.delta_c_information_suppressed_2;
percentiles = prctile(g,[5,50,95]);

row = table(string(caseName),mean(g),mean(1-g),min(g), ...
    percentiles(1),percentiles(2),percentiles(3), ...
    mean(g<0.99),mean(g<0.95),mean(g<0.90), ...
    informationRatioJ,informationRatioH, ...
    sqrt(mean(suppressedCs1.^2)), ...
    sqrt(mean(suppressedCs2.^2)), ...
    max(abs([suppressedCs1;suppressedCs2])), ...
    abs(mean(1-g)-(1-mean(g))), ...
    sum(cycle.rate_limit_active),sum(cycle.projection_active), ...
    'VariableNames',{'case_name','mean_update_weight', ...
    'unnecessary_suppression_ratio','min_update_weight', ...
    'P05_update_weight','P50_update_weight','P95_update_weight', ...
    'fraction_g_below_0p99','fraction_g_below_0p95', ...
    'fraction_g_below_0p90','information_suppression_ratio_J', ...
    'information_suppression_ratio_h', ...
    'rms_information_suppressed_DeltaCs1_pF', ...
    'rms_information_suppressed_DeltaCs2_pF', ...
    'max_information_suppressed_DeltaCs_pF', ...
    'USR_closure_abs_error','rate_limit_cycles','projection_cycles'});
end

function row = direction_diagnostics_row(caseName,cycle)
valid = cycle.direction_candidate_valid;
localCosine = cycle.cos_local_fault(valid);
rawCosine = cycle.cos_raw_fault(valid);
localStats = cosine_stats(localCosine);
rawStats = cosine_stats(rawCosine);
row = table(string(caseName),mean(valid),sum(valid),height(cycle), ...
    localStats.mean,localStats.median,localStats.p05,localStats.p95, ...
    localStats.mean_abs,rawStats.mean,rawStats.median,rawStats.p05, ...
    rawStats.p95,rawStats.mean_abs, ...
    'VariableNames',{'case_name','valid_direction_ratio', ...
    'valid_direction_cycles','total_cycles', ...
    'mean_cos_local_fault','median_cos_local_fault', ...
    'P05_cos_local_fault','P95_cos_local_fault', ...
    'mean_abs_cos_local_fault','mean_cos_raw_fault', ...
    'median_cos_raw_fault','P05_cos_raw_fault','P95_cos_raw_fault', ...
    'mean_abs_cos_raw_fault'});
end

function stats = cosine_stats(values)
if isempty(values)
    stats = struct('mean',NaN,'median',NaN,'p05',NaN,'p95',NaN, ...
        'mean_abs',NaN);
    return
end
percentiles = prctile(values,[5,95]);
stats = struct('mean',mean(values),'median',median(values), ...
    'p05',percentiles(1),'p95',percentiles(2), ...
    'mean_abs',mean(abs(values)));
end

function rows = drift_correlation_rows(caseName,cycle)
x = cycle.drift_magnitude_pF_per_cycle;
rows = [ ...
    correlation_row(caseName,"normal_suppression",x, ...
        cycle.normal_suppression)
    correlation_row(caseName,"fault_evidence_score",x, ...
        cycle.fault_evidence_score)];
end

function row = correlation_row(caseName,targetName,x,y)
valid = isfinite(x) & isfinite(y);
pearson = NaN;
spearman = NaN;
if nnz(valid) >= 3 && numel(unique(x(valid))) > 1 && ...
        numel(unique(y(valid))) > 1
    matrix = corrcoef(x(valid),y(valid),'Rows','complete');
    pearson = matrix(1,2);
    spearman = corr(x(valid),y(valid), ...
        'Type','Spearman','Rows','complete');
end
row = table(string(caseName),string(targetName),nnz(valid), ...
    pearson,spearman,'VariableNames',{'case_name','target_metric', ...
    'valid_cycle_pairs','pearson_r','spearman_rho'});
end

function tableOut = empty_correlation_table()
tableOut = table('Size',[0,5], ...
    'VariableTypes',{'string','string','double','double','double'}, ...
    'VariableNames',{'case_name','target_metric','valid_cycle_pairs', ...
    'pearson_r','spearman_rho'});
end

function rows = phase_diagnostics(caseName,cycle)
[labels,starts,ends] = phase_windows(string(caseName));
rows = cell(numel(labels),1);
for k = 1:numel(labels)
    index = cycle.time_s >= starts(k) & cycle.time_s < ends(k);
    rows{k} = table(string(caseName),labels(k),starts(k),ends(k), ...
        sum(index),mean(cycle.update_weight(index)), ...
        mean(1-cycle.update_weight(index)), ...
        mean(cycle.fault_evidence_score(index)), ...
        mean(cycle.evidence_ratio_base(index)), ...
        mean(cycle.evidence_ratio_quad(index)), ...
        mean(cycle.E_in(index)),mean(cycle.E_quad(index)), ...
        mean(cycle.base_in(index)), ...
        mean(cycle.parameter_error_norm_pF(index)), ...
        'VariableNames',{'case_name','phase_name','start_s','end_s', ...
        'cycle_count','mean_update_weight', ...
        'unnecessary_suppression_ratio','mean_fault_evidence', ...
        'mean_evidence_ratio_base','mean_evidence_ratio_quad', ...
        'mean_E_in_A','mean_E_quad_A','mean_baseIn_A', ...
        'mean_parameter_error_norm_pF'});
end
rows = vertcat(rows{:});
end

function [labels,starts,ends] = phase_windows(caseName)
switch caseName
    case "Case01_static"
        labels = "steady";
        starts = 0.8;
        ends = 4.000001;
    case "Case02_slow_drift"
        labels = ["drift_onset";"drift_middle";"drift_end";"post_drift"];
        starts = [1.0;1.9;2.9;3.2];
        ends = [1.2;2.1;3.1;4.000001];
    case "Case03_smooth_step"
        labels = ["pre_transition";"transition"; ...
            "early_recovery";"late_post_transition"];
        starts = [0.8;1.45;1.65;2.2];
        ends = [1.45;1.65;2.2;4.000001];
    case "Case04_random_drift"
        labels = ["activation";"random_tracking"];
        starts = [0.8;1.0];
        ends = [1.0;4.000001];
end
end

function row = tracking_lag_row(caseName,mode,data,result)
if string(caseName) == "Case02_slow_drift"
    onset = 1.0;
else
    onset = 1.45;
end
trueLag1 = midpoint_crossing_time(data.t,data.Cs1,onset);
trueLag2 = midpoint_crossing_time(data.t,data.Cs2,onset);
estimatedLag1 = midpoint_crossing_time( ...
    data.t,result.cHist(:,1),onset, ...
    [data.Cs1(1),data.Cs1(end)]);
estimatedLag2 = midpoint_crossing_time( ...
    data.t,result.cHist(:,2),onset, ...
    [data.Cs2(1),data.Cs2(end)]);
row = table(string(caseName),string(mode), ...
    estimatedLag1-trueLag1,estimatedLag2-trueLag2, ...
    trueLag1,trueLag2,estimatedLag1,estimatedLag2, ...
    'VariableNames',{'case_name','algorithm_mode', ...
    'Cs1_midpoint_crossing_lag_s','Cs2_midpoint_crossing_lag_s', ...
    'Cs1_true_midpoint_crossing_s','Cs2_true_midpoint_crossing_s', ...
    'Cs1_est_midpoint_crossing_s','Cs2_est_midpoint_crossing_s'});
end

function crossingTime = midpoint_crossing_time(t,x,onset,endpoints)
if nargin < 4
    endpoints = [x(1),x(end)];
end
direction = sign(endpoints(2)-endpoints(1));
target = mean(endpoints);
index = t >= onset & direction*(x-target) >= 0;
first = find(index,1,'first');
if isempty(first)
    crossingTime = NaN;
else
    crossingTime = t(first);
end
end
