function result = run_phase1c_step3_normal_tracking()
%RUN_PHASE1C_STEP3_NORMAL_TRACKING Evaluate M4-v0 on Case01-04 only.

step3Root = fileparts(mfilename('fullpath'));
phase1cRoot = fileparts(step3Root);
projectRoot = fileparts(fileparts(phase1cRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
tablesRoot = fullfile(step3Root,'tables');
figuresRoot = fullfile(step3Root,'figures');
diagnosticsRoot = fullfile(step3Root,'diagnostics');
workspaceRoot = fullfile(step3Root,'workspace');
ensure_directories([string(tablesRoot),string(figuresRoot), ...
    string(diagnosticsRoot),string(workspaceRoot)]);
addpath(matlabRoot);
addpath(step3Root);

frozenBefore = capture_frozen_files(projectRoot,matlabRoot,phase1cRoot);
metadata = capture_metadata(projectRoot,matlabRoot);
cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
selfPF = repmat(cfg.Cself_pF,1,3);
caseRegistry = phase1a_case_registry();
caseRegistry = caseRegistry(ismember(caseRegistry.case_name, ...
    ["Case01_static","Case02_slow_drift", ...
    "Case03_smooth_step","Case04_random_drift"]),:);

summaryParts = cell(height(caseRegistry),1);
m4Parts = cell(height(caseRegistry),1);
cycleParts = cell(height(caseRegistry),1);
correlationParts = cell(height(caseRegistry),1);
directionParts = cell(height(caseRegistry),1);
phaseParts = cell(height(caseRegistry),1);
lagParts = cell(height(caseRegistry),1);
caseDetails = struct();

for caseIndex = 1:height(caseRegistry)
    caseInfo = caseRegistry(caseIndex,:);
    fprintf('STEP3_CASE_START=%s seed=%d\n', ...
        caseInfo.case_name,caseInfo.seed);
    signals = generate_coupling_signals( ...
        (0:cfg.Ts:cfg.StopTime).',caseInfo.case_name,caseInfo.seed);
    [data,~] = simulate_phase2_case(cfg, ...
        char(caseInfo.legacy_scenario_name),caseInfo.seed);
    assert_no_fault_case(data,signals,caseInfo.case_name);
    ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
        cfg.init_start,cfg.init_end,cfg.phase_error_deg);

    algorithmResults = struct();
    for mode = ["M2","M3","M4"]
        algorithmResults.(char(mode)) = run_phase1a_algorithm( ...
            mode,data,ref,cfg,selfPF);
    end
    evaluated = evaluate_phase1c_step3_case( ...
        caseInfo,data,ref,cfg,algorithmResults,metadata);

    summaryParts{caseIndex} = evaluated.summary;
    m4Parts{caseIndex} = evaluated.m4_diagnostics;
    cycleParts{caseIndex} = evaluated.cycle_detail;
    correlationParts{caseIndex} = evaluated.correlations;
    directionParts{caseIndex} = evaluated.direction_diagnostics;
    phaseParts{caseIndex} = evaluated.phase_diagnostics;
    lagParts{caseIndex} = evaluated.tracking_lag;
    caseDetails.(char(caseInfo.case_name)) = minimal_case_detail( ...
        data,ref,algorithmResults);
    fprintf(['STEP3_CASE_COMPLETE=%s M4_mean_g=%.9f ' ...
        'M4_USR=%.9f\n'],caseInfo.case_name, ...
        evaluated.m4_diagnostics.mean_update_weight, ...
        evaluated.m4_diagnostics.unnecessary_suppression_ratio);
end

summaryTable = vertcat(summaryParts{:});
m4Diagnostics = vertcat(m4Parts{:});
cycleDetail = vertcat(cycleParts{:});
correlationTable = vertcat(correlationParts{:});
directionTable = vertcat(directionParts{:});
phaseTable = vertcat(phaseParts{:});
trackingLagTable = vertcat(lagParts{:});
degradationTable = relative_degradation(summaryTable);
regression = compare_frozen_baseline(summaryTable,projectRoot);
validation = validate_results(summaryTable,m4Diagnostics, ...
    cycleDetail,correlationTable,directionTable,regression);
if ~validation.overall_pass
    error('Phase1C:Step3Validation', ...
        'Step 3 structural/result validation failed.');
end

summaryPath = fullfile(tablesRoot,'normal_tracking_summary.csv');
m4Path = fullfile(tablesRoot,'m4_normal_protection_metrics.csv');
degradationPath = fullfile(tablesRoot,'relative_degradation.csv');
lagPath = fullfile(diagnosticsRoot,'tracking_lag.csv');
correlationPath = fullfile( ...
    diagnosticsRoot,'drift_evidence_correlation.csv');
directionPath = fullfile( ...
    diagnosticsRoot,'direction_diagnostics.csv');
phasePath = fullfile(diagnosticsRoot,'normal_phase_diagnostics.csv');
cyclePath = fullfile(diagnosticsRoot,'m4_cycle_diagnostics.csv');
workspacePath = fullfile(workspaceRoot,'normal_tracking_workspace.mat');

writetable(summaryTable,summaryPath);
writetable(m4Diagnostics,m4Path);
writetable(degradationTable,degradationPath);
writetable(trackingLagTable,lagPath);
writetable(correlationTable,correlationPath);
writetable(directionTable,directionPath);
writetable(phaseTable,phasePath);
writetable(cycleDetail,cyclePath);
figurePaths = generate_phase1c_step3_figures( ...
    figuresRoot,summaryTable,correlationTable,caseDetails);

schemaVersion = "phase1c_step3_normal_tracking_v1";
result = struct( ...
    'schema_version',schemaVersion, ...
    'cfg',cfg, ...
    'case_registry',caseRegistry, ...
    'metadata',metadata, ...
    'summary_table',summaryTable, ...
    'm4_diagnostics',m4Diagnostics, ...
    'degradation_table',degradationTable, ...
    'tracking_lag_table',trackingLagTable, ...
    'correlation_table',correlationTable, ...
    'direction_table',directionTable, ...
    'phase_table',phaseTable, ...
    'cycle_detail',cycleDetail, ...
    'case_details',caseDetails, ...
    'regression',regression, ...
    'validation',validation, ...
    'figure_paths',figurePaths);
save(workspacePath,'schemaVersion','cfg','caseRegistry','metadata', ...
    'summaryTable','m4Diagnostics','degradationTable', ...
    'trackingLagTable','correlationTable','directionTable', ...
    'phaseTable','cycleDetail','caseDetails','regression', ...
    'validation','figurePaths','result','-v7.3');

assert_frozen_unchanged(frozenBefore);
print_results(summaryTable,m4Diagnostics,degradationTable, ...
    correlationTable,directionTable,regression,workspacePath);
fprintf('PHASE1C_STEP3_NORMAL_TRACKING=PASS\n');
end

function ensure_directories(paths)
for path = paths
    if ~isfolder(path)
        mkdir(path);
    end
end
end

function assert_no_fault_case(data,signals,caseName)
if any(abs(signals.fault_scale-1) > 0) || ...
        max(abs(data.Cs1-signals.Cs1_pF)) > 1e-10 || ...
        max(abs(data.Cs2-signals.Cs2_pF)) > 1e-10
    error('Phase1C:Step3CaseIntegrity', ...
        'Case integrity failed for %s.',caseName);
end
end

function detail = minimal_case_detail(data,ref,algorithmResults)
detail = struct( ...
    't',data.t,'Cs1_true',data.Cs1,'Cs2_true',data.Cs2, ...
    'irB_true',data.irB, ...
    'reference_phi1',ref.phi1,'reference_phi3',ref.phi3, ...
    'M2_cHist',algorithmResults.M2.cHist, ...
    'M3_cHist',algorithmResults.M3.cHist, ...
    'M4_cHist',algorithmResults.M4.cHist, ...
    'M2_irB',algorithmResults.M2.ir.B, ...
    'M3_irB',algorithmResults.M3.ir.B, ...
    'M4_irB',algorithmResults.M4.ir.B, ...
    'M2_cycle',algorithmResults.M2.tracker.cycle, ...
    'M3_cycle',algorithmResults.M3.tracker.cycle, ...
    'M4_cycle',algorithmResults.M4.tracker.cycle);
end

function tableOut = relative_degradation(summary)
caseNames = unique(summary.case_name,'stable');
rows = cell(numel(caseNames),1);
for k = 1:numel(caseNames)
    caseName = caseNames(k);
    m2 = summary(summary.case_name == caseName & ...
        summary.algorithm_mode == "M2",:);
    m4 = summary(summary.case_name == caseName & ...
        summary.algorithm_mode == "M4",:);
    rows{k} = table(caseName, ...
        (m4.Cs1_RMSE_pF-m2.Cs1_RMSE_pF)/(m2.Cs1_RMSE_pF+eps), ...
        (m4.Cs2_RMSE_pF-m2.Cs2_RMSE_pF)/(m2.Cs2_RMSE_pF+eps), ...
        m4.Cs1_RMSE_pF-m2.Cs1_RMSE_pF, ...
        m4.Cs2_RMSE_pF-m2.Cs2_RMSE_pF, ...
        (abs(m4.B_resistive_fundamental_error_pct)- ...
        abs(m2.B_resistive_fundamental_error_pct))/ ...
        (abs(m2.B_resistive_fundamental_error_pct)+eps), ...
        abs(m4.B_resistive_fundamental_error_pct)- ...
        abs(m2.B_resistive_fundamental_error_pct), ...
        'VariableNames',{'case_name','Cs1_RMSE_relative_degradation', ...
        'Cs2_RMSE_relative_degradation', ...
        'Cs1_RMSE_absolute_change_pF','Cs2_RMSE_absolute_change_pF', ...
        'B_abs_error_relative_degradation', ...
        'B_abs_error_absolute_change_pct_point'});
end
tableOut = vertcat(rows{:});
end

function regression = compare_frozen_baseline(summary,projectRoot)
frozen = readtable(fullfile(projectRoot,'paper_research', ...
    'phase1a_baseline','baseline_summary.csv'),'TextType','string');
frozen = frozen(ismember(frozen.case_name,unique(summary.case_name)) & ...
    ismember(frozen.algorithm_mode,["M2","M3"]),:);
current = summary(ismember(summary.algorithm_mode,["M2","M3"]),:);
frozen = sortrows(frozen,{'case_name','algorithm_mode'});
current = sortrows(current,{'case_name','algorithm_mode'});
differences = [ ...
    current.Cs1_RMSE_pF-frozen.Cs1_RMSE_pF, ...
    current.Cs2_RMSE_pF-frozen.Cs2_RMSE_pF, ...
    current.B_resistive_fundamental_error_pct- ...
        frozen.B_resistive_fundamental_error_pct];
regression = struct( ...
    'row_count',height(current), ...
    'max_abs_difference',max(abs(differences),[],'all'), ...
    'exact_numeric_match',all(differences == 0,'all'), ...
    'tolerance',1e-12, ...
    'pass',all(abs(differences) <= 1e-12,'all'));
end

function validation = validate_results(summary,m4,cycle,correlation, ...
        direction,regression)
validation = struct();
validation.summary_rows = height(summary);
validation.unique_cases = numel(unique(summary.case_name));
validation.algorithms = unique(summary.algorithm_mode);
validation.m4_rows = height(m4);
validation.correlation_rows = height(correlation);
validation.direction_rows = height(direction);
validation.weights_valid = all(cycle.update_weight > 0 & ...
    cycle.update_weight <= 1);
validation.usr_closure_max_abs = max(m4.USR_closure_abs_error);
validation.no_fault_cases_only = all(ismember(summary.case_name, ...
    ["Case01_static","Case02_slow_drift", ...
    "Case03_smooth_step","Case04_random_drift"]));
validation.regression_pass = regression.pass;
validation.no_missing_core_metrics = all(isfinite([ ...
    summary.Cs1_RMSE_pF;summary.Cs2_RMSE_pF; ...
    summary.Cs1_max_abs_error_pF;summary.Cs2_max_abs_error_pF; ...
    summary.B_resistive_fundamental_error_pct]));
validation.overall_pass = validation.summary_rows == 12 && ...
    validation.unique_cases == 4 && ...
    isequal(validation.algorithms,["M2";"M3";"M4"]) && ...
    validation.m4_rows == 4 && validation.correlation_rows == 6 && ...
    validation.direction_rows == 4 && validation.weights_valid && ...
    validation.usr_closure_max_abs <= 1e-12 && ...
    validation.no_fault_cases_only && validation.regression_pass && ...
    validation.no_missing_core_metrics;
end

function frozen = capture_frozen_files(projectRoot,matlabRoot,phase1cRoot)
paths = [ ...
    string(fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx'))
    string(fullfile(matlabRoot,'track_coupling_cvff_rls.m'))
    string(fullfile(matlabRoot,'track_coupling_m4_weighted_rls.m'))
    string(fullfile(matlabRoot,'m4_fault_evidence.m'))
    string(fullfile(matlabRoot,'patent_default_config.m'))
    string(fullfile(matlabRoot,'phase1a_case_registry.m'))
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_summary.csv'))
    string(fullfile(projectRoot,'paper_research','phase1a_baseline', ...
        'baseline_workspace.mat'))
    string(fullfile(phase1cRoot,'STEP1_M4_METHOD_SPECIFICATION.md'))
    string(fullfile(phase1cRoot,'STEP2_M4_IMPLEMENTATION.md'))];
hash = strings(size(paths));
for k = 1:numel(paths)
    hash(k) = file_sha256(paths(k));
end
frozen = table(paths,hash,'VariableNames',{'path','sha256'});
end

function assert_frozen_unchanged(frozen)
for k = 1:height(frozen)
    if file_sha256(frozen.path(k)) ~= frozen.sha256(k)
        error('Phase1C:Step3FrozenFile', ...
            'Frozen file changed during Step 3: %s.',frozen.path(k));
    end
end
end

function metadata = capture_metadata(projectRoot,matlabRoot)
[commitCode,commit] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1C:Step3GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'model_sha256',file_sha256( ...
        fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx')), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_dirty_status',dirty_label(status), ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function label = dirty_label(status)
if strlength(strtrim(string(status))) == 0
    label = "CLEAN";
else
    label = "DIRTY";
end
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1C:Step3Hash','Unable to open %s.',path);
end
cleanupObject = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
clear cleanupObject
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_results(summary,m4,degradation,correlation,direction, ...
        regression,workspacePath)
disp(summary);
disp(m4);
disp(degradation);
disp(correlation);
disp(direction);
fprintf('STEP3_M2_M3_REGRESSION_MAX_ABS=%.17g\n', ...
    regression.max_abs_difference);
fprintf('STEP3_M2_M3_REGRESSION_PASS=%s\n',string(regression.pass));
fprintf('STEP3_WORKSPACE=%s\n',workspacePath);
end
