function result = run_phase1b_step3_case06()
%RUN_PHASE1B_STEP3_CASE06 External verification of the frozen mechanism.
% Runs only Case06_drift_then_fault and reuses the Step 2 instrumentation.

step3Root = fileparts(mfilename('fullpath'));
phase1bRoot = fileparts(step3Root);
projectRoot = fileparts(fileparts(phase1bRoot));
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
step2Root = fullfile(phase1bRoot,'step2');
figuresRoot = fullfile(step3Root,'figures');
addpath(matlabRoot);
addpath(step2Root);
addpath(step3Root);
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

paths = frozen_paths(projectRoot,matlabRoot,phase1bRoot,step2Root);
expected = frozen_integrity();
assert_frozen_integrity(paths,expected);
runMetadata = capture_metadata(projectRoot,paths);

cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
cfg.output_dir = step3Root;
registry = phase1a_case_registry();
caseInfo = registry(registry.case_name == "Case06_drift_then_fault",:);
if height(caseInfo) ~= 1
    error('Phase1B:CaseRegistry','Case06 registry entry is not unique.');
end
seed = caseInfo.seed;
tInput = (0:cfg.Ts:cfg.StopTime).';
signals = generate_coupling_signals(tInput,caseInfo.case_name,seed);

fprintf('PHASE1B_STEP3_CASE_START=%s seed=%d\n',caseInfo.case_name,seed);
[data,~] = simulate_phase2_case(cfg, ...
    char(caseInfo.legacy_scenario_name),seed);
ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
selfPF = repmat(cfg.Cself_pF,1,3);

originalM2 = track_coupling_cvff_rls(data,ref,cfg,selfPF,false);
originalM3 = track_coupling_cvff_rls(data,ref,cfg,selfPF,true);
[instrumented,observationBlocks] = instrument_phase1b_vff_rls( ...
    data,ref,cfg,selfPF,signals.fault_scale,caseInfo.case_name);

formal = load(paths.baseline_workspace,'caseData','algorithmResults');
formalCase = formal.caseData.Case06_drift_then_fault;
formalM2 = formal.algorithmResults.Case06_drift_then_fault.M2;
formalM3 = formal.algorithmResults.Case06_drift_then_fault.M3;
formalCsv = readtable(paths.baseline_csv,'TextType','string');
formalM2Row = formalCsv( ...
    formalCsv.case_name == "Case06_drift_then_fault" & ...
    formalCsv.algorithm_mode == "M2",:);
formalM3Row = formalCsv( ...
    formalCsv.case_name == "Case06_drift_then_fault" & ...
    formalCsv.algorithm_mode == "M3",:);
if height(formalM2Row) ~= 1 || height(formalM3Row) ~= 1
    error('Phase1B:FormalRow','Formal Case06 rows are not unique.');
end

validation = validate_replay(data,signals,ref,selfPF,originalM2,originalM3, ...
    instrumented,formalCase,formalM2,formalM3);
if ~validation.instrumentation_equivalent
    error('Phase1B:InstrumentationMismatch', ...
        'Step 2 instrumentation does not match frozen Case06 M2.');
end
if ~validation.formal_case_reproduced
    error('Phase1B:FormalMismatch', ...
        'Regenerated Case06 does not match the Phase 1A baseline.');
end

cycleTable = instrumented.mechanism_cycle_table;
c0 = instrumented.c0(:).';
originalBefore = [c0; ...
    originalM2.cycle.Cs1_pF(1:end-1), ...
    originalM2.cycle.Cs2_pF(1:end-1)];
originalAfter = [originalM2.cycle.Cs1_pF,originalM2.cycle.Cs2_pF];
actualDelta = originalAfter-originalBefore;
cycleTable.delta_Cs1_actual_pF = actualDelta(:,1);
cycleTable.delta_Cs2_actual_pF = actualDelta(:,2);
cycleTable.prediction_error_Cs1_pF = ...
    cycleTable.delta_Cs1_RLS_pred_pF-actualDelta(:,1);
cycleTable.prediction_error_Cs2_pF = ...
    cycleTable.delta_Cs2_RLS_pred_pF-actualDelta(:,2);

analysis = calculate_case06_metrics(data,signals,ref,cfg,selfPF, ...
    originalM2,originalM3,instrumented,cycleTable,formalM2Row,formalM3Row);
validation.observation_alignment = all(cycleTable.n_samples == 1000) && ...
    all(cycleTable.rank_X == 2) && all(arrayfun(@(x) ...
    isequal(size(x.X),[3000,2]) && isequal(size(x.r_fault),[3000,1]), ...
    observationBlocks));
validation.counterfactual_identity_max_abs_A = ...
    max(cycleTable.counterfactual_identity_max_abs_A);
validation.projection_energy_closure_max = ...
    max(cycleTable.projection_energy_closure_relerr);
validation.projection_fit_relerr_max = ...
    max(cycleTable.projection_fit_relerr);
validation.projection_pass = ...
    validation.projection_energy_closure_max <= 1e-10;
validation.prediction_replay_max_abs_pF = max(abs([ ...
    cycleTable.prediction_error_Cs1_pF; ...
    cycleTable.prediction_error_Cs2_pF]));
preFault = data.t < 3.00;
validation.branch_pre_fault_max_abs_pF = max(abs( ...
    instrumented.fault.hist(preFault,:)- ...
    instrumented.counterfactual.hist(preFault,:)),[],'all');
validation.case06_only = caseInfo.case_name == "Case06_drift_then_fault";
validation.overall_pass = validation.instrumentation_equivalent && ...
    validation.formal_case_reproduced && validation.observation_alignment && ...
    validation.projection_pass && ...
    validation.prediction_replay_max_abs_pF <= 1e-12 && ...
    validation.branch_pre_fault_max_abs_pF <= 1e-12 && ...
    validation.case06_only;

case05Key = readtable(paths.case05_key_metrics,'TextType','string');
case05Cycles = readtable(paths.case05_summary,'TextType','string');
comparisonTable = build_comparison_table( ...
    case05Key,case05Cycles,analysis.key_metrics);

summaryPath = fullfile(step3Root,'case06_mechanism_summary.csv');
keyMetricsPath = fullfile(step3Root,'case06_key_metrics.csv');
comparisonPath = fullfile(step3Root,'case05_case06_comparison.csv');
observationPath = fullfile(step3Root,'observation_blocks_case06.mat');
workspacePath = fullfile(step3Root,'case06_mechanism_workspace.mat');
writetable(cycleTable,summaryPath);
writetable(struct2table(analysis.key_metrics,'AsArray',true),keyMetricsPath);
writetable(comparisonTable,comparisonPath);

schemaVersion = "phase1b_mechanism_v1";
save(observationPath,'schemaVersion','observationBlocks', ...
    'runMetadata','-v7.3');
figurePaths = generate_phase1b_step3_figures( ...
    figuresRoot,data,originalM2,instrumented,cycleTable, ...
    analysis,case05Cycles,comparisonTable);

result = struct( ...
    'schema_version',schemaVersion, ...
    'cfg',cfg, ...
    'caseInfo',caseInfo, ...
    'runMetadata',runMetadata, ...
    'cycleTable',cycleTable, ...
    'keyMetrics',analysis.key_metrics, ...
    'comparisonTable',comparisonTable, ...
    'validation',validation, ...
    'figurePaths',figurePaths, ...
    'summaryPath',string(summaryPath), ...
    'keyMetricsPath',string(keyMetricsPath), ...
    'comparisonPath',string(comparisonPath), ...
    'observationPath',string(observationPath), ...
    'workspacePath',string(workspacePath));
save(workspacePath,'cfg','caseInfo','runMetadata','signals','data','ref', ...
    'originalM2','originalM3','instrumented','cycleTable','analysis', ...
    'comparisonTable','validation','figurePaths','result','-v7.3');

assert_frozen_integrity(paths,expected);
print_key_results(analysis.key_metrics,validation,summaryPath,workspacePath);
if ~validation.overall_pass
    error('Phase1B:Step3Validation', ...
        'One or more Phase 1B Step 3 validation checks failed.');
end
fprintf('STEP3_CASE06_VERIFICATION=PASS\n');
end

function validation = validate_replay(data,signals,ref,selfPF, ...
        originalM2,originalM3,instrumented,formalCase,formalM2,formalM3)
validation = struct();
validation.Cs1_replay_max_abs = max(abs( ...
    originalM2.hist(:,1)-instrumented.fault.hist(:,1)));
validation.Cs2_replay_max_abs = max(abs( ...
    originalM2.hist(:,2)-instrumented.fault.hist(:,2)));
validation.lambda_replay_max_abs = max(abs( ...
    originalM2.cycle.lambda-instrumented.fault.cycle.lambda));
validation.E_in_replay_max_abs = max(abs( ...
    originalM2.cycle.E_in-instrumented.fault.cycle.E_in));
validation.E_quad_replay_max_abs = max(abs( ...
    originalM2.cycle.E_quad-instrumented.fault.cycle.E_quad));
validation.base_in_replay_max_abs = max(abs( ...
    originalM2.cycle.base_in-instrumented.fault.cycle.base_in));
validation.gate_replay_max_abs = max(abs( ...
    originalM2.cycle.gate-instrumented.fault.cycle.gate));
replayErrors = [validation.Cs1_replay_max_abs, ...
    validation.Cs2_replay_max_abs,validation.lambda_replay_max_abs, ...
    validation.E_in_replay_max_abs,validation.E_quad_replay_max_abs, ...
    validation.base_in_replay_max_abs,validation.gate_replay_max_abs];
validation.instrumentation_equivalent = all(replayErrors <= 1e-12);

validation.formal_time_max_abs = max(abs(data.t-formalCase.t));
validation.formal_Cs1_truth_max_abs = max(abs(data.Cs1-formalCase.Cs1_true));
validation.formal_Cs2_truth_max_abs = max(abs(data.Cs2-formalCase.Cs2_true));
validation.formal_fault_scale_max_abs = max(abs( ...
    signals.fault_scale-formalCase.fault_scale));
validation.formal_irA_true_max_abs = max(abs(data.irA-formalCase.irA_true));
validation.formal_irB_true_max_abs = max(abs(data.irB-formalCase.irB_true));
validation.formal_irC_true_max_abs = max(abs(data.irC-formalCase.irC_true));
validation.formal_M2_cHist_max_abs = max(abs( ...
    originalM2.hist-formalM2.cHist),[],'all');
validation.formal_M2_cycle_max_abs = max(abs( ...
    originalM2.cycle{:,:}-formalM2.cycle{:,:}),[],'all');
irM2 = extract_resistive_current(data,ref,selfPF,originalM2.hist);
validation.formal_M2_irB_max_abs = max(abs(irM2.B-formalM2.irB));
validation.formal_M3_cHist_max_abs = max(abs( ...
    originalM3.hist-formalM3.cHist),[],'all');
validation.formal_M3_cycle_max_abs = max(abs( ...
    originalM3.cycle{:,:}-formalM3.cycle{:,:}),[],'all');
irM3 = extract_resistive_current(data,ref,selfPF,originalM3.hist);
validation.formal_M3_irB_max_abs = max(abs(irM3.B-formalM3.irB));
formalErrors = [validation.formal_time_max_abs, ...
    validation.formal_Cs1_truth_max_abs,validation.formal_Cs2_truth_max_abs, ...
    validation.formal_fault_scale_max_abs,validation.formal_irA_true_max_abs, ...
    validation.formal_irB_true_max_abs,validation.formal_irC_true_max_abs, ...
    validation.formal_M2_cHist_max_abs,validation.formal_M2_cycle_max_abs, ...
    validation.formal_M2_irB_max_abs,validation.formal_M3_cHist_max_abs, ...
    validation.formal_M3_cycle_max_abs,validation.formal_M3_irB_max_abs];
validation.formal_case_reproduced = all(formalErrors <= 1e-12);
end

function analysis = calculate_case06_metrics( ...
        data,signals,ref,cfg,selfPF,originalM2,originalM3, ...
        instrumented,cycleTable,formalM2Row,formalM3Row)
t = data.t;
driftIdx = t >= 0.80 & t <= 2.20;
initialIdx = t >= 0.20 & t < 0.70;
preIdx = t >= 2.60 & t < 2.90;
postIdx = t >= 3.40 & t < 3.80;
preCycle = cycleTable.time_start_s >= 2.60 & cycleTable.time_end_s < 2.90;
rampCycle = cycleTable.r_fault_norm_A > 0 & ...
    cycleTable.time_start_s < 3.06 & cycleTable.time_end_s > 3.00;
postCycle = cycleTable.time_start_s >= 3.06;
steadyCycle = cycleTable.time_start_s >= 3.40 & ...
    cycleTable.time_end_s < 3.80;
faultCycle = cycleTable.r_fault_norm_A > 0;
firstFaultCycle = find(faultCycle,1,'first');

faultHist = instrumented.fault.hist;
counterfactualHist = instrumented.counterfactual.hist;
lambdaNeutralHist = instrumented.lambda_neutral.hist;
actualChange = parameter_change(originalM2.hist,preIdx,postIdx);
faultReplayChange = parameter_change(faultHist,preIdx,postIdx);
counterfactualChange = parameter_change(counterfactualHist,preIdx,postIdx);
lambdaNeutralChange = parameter_change(lambdaNeutralHist,preIdx,postIdx);
predictedFaultInduced = faultReplayChange-counterfactualChange;
lambdaFeedbackContribution = faultReplayChange-lambdaNeutralChange;

irM2 = extract_resistive_current(data,ref,selfPF,originalM2.hist);
irCounterfactualParameters = extract_resistive_current( ...
    data,ref,selfPF,counterfactualHist);
irM3 = extract_resistive_current(data,ref,selfPF,originalM3.hist);
trueFactor = fault_factor(t,data.irB,preIdx,postIdx,cfg.f);
m2Factor = fault_factor(t,irM2.B,preIdx,postIdx,cfg.f);
counterfactualParameterFactor = fault_factor( ...
    t,irCounterfactualParameters.B,preIdx,postIdx,cfg.f);
m3Factor = fault_factor(t,irM3.B,preIdx,postIdx,cfg.f);

deltaC = faultHist-counterfactualHist;
deltaCouplingB = deltaC(:,1)*1e-12.*(ref.dub-ref.dua) + ...
    deltaC(:,2)*1e-12.*(ref.dub-ref.duc);
rFaultB = (1-1./signals.fault_scale).*data.irB;
[rFaultRms,rFaultPhase] = fundamental_properties( ...
    t(postIdx),rFaultB(postIdx),cfg.f);
[deltaCouplingRms,deltaCouplingPhase] = fundamental_properties( ...
    t(postIdx),deltaCouplingB(postIdx),cfg.f);
correlationMatrix = corrcoef(rFaultB(postIdx),deltaCouplingB(postIdx));
if numel(correlationMatrix) == 4
    couplingFaultCorrelation = correlationMatrix(1,2);
else
    couplingFaultCorrelation = NaN;
end

truth = [data.Cs1,data.Cs2];
driftRmse = sqrt(mean((originalM2.hist(driftIdx,:)-truth(driftIdx,:)).^2,1));
trueInitial = mean(truth(initialIdx,:),1);
truePre = mean(truth(preIdx,:),1);
estPre = mean(originalM2.hist(preIdx,:),1);
trueDrift = truePre-trueInitial;
preBias = estPre-truePre;

key = struct();
key.case_name = "Case06_drift_then_fault";
key.seed = 105;
key.drift_window_start_s = 0.80;
key.drift_window_end_s = 2.20;
key.Cs1_drift_tracking_RMSE_pF = driftRmse(1);
key.Cs2_drift_tracking_RMSE_pF = driftRmse(2);
key.Cs1_true_initial_pF = trueInitial(1);
key.Cs2_true_initial_pF = trueInitial(2);
key.Cs1_true_pre_pF = truePre(1);
key.Cs2_true_pre_pF = truePre(2);
key.Cs1_est_pre_pF = estPre(1);
key.Cs2_est_pre_pF = estPre(2);
key.true_drift_Cs1_pF = trueDrift(1);
key.true_drift_Cs2_pF = trueDrift(2);
key.pre_fault_estimation_bias_Cs1_pF = preBias(1);
key.pre_fault_estimation_bias_Cs2_pF = preBias(2);
key.true_fault_factor = trueFactor;
key.M2_actual_fault_factor = m2Factor;
key.M2_formal_fault_factor = formalM2Row.fault_factor_est;
key.counterfactual_parameter_fault_factor = counterfactualParameterFactor;
key.M3_auxiliary_fault_factor = m3Factor;
key.M3_formal_fault_factor = formalM3Row.fault_factor_est;
key.M2_actual_Delta_Cs1_pF = actualChange(1);
key.M2_actual_Delta_Cs2_pF = actualChange(2);
key.M2_formal_Delta_Cs1_pF = formalM2Row.Cs1_pre_post_change_pF;
key.M2_formal_Delta_Cs2_pF = formalM2Row.Cs2_pre_post_change_pF;
key.counterfactual_Delta_Cs1_pF = counterfactualChange(1);
key.counterfactual_Delta_Cs2_pF = counterfactualChange(2);
key.recursive_fault_induced_Delta_Cs1_pF = predictedFaultInduced(1);
key.recursive_fault_induced_Delta_Cs2_pF = predictedFaultInduced(2);
key.recursive_prediction_error_Cs1_pF = ...
    predictedFaultInduced(1)-actualChange(1);
key.recursive_prediction_error_Cs2_pF = ...
    predictedFaultInduced(2)-actualChange(2);
key.recursive_prediction_relative_error_Cs1_pct = ...
    100*key.recursive_prediction_error_Cs1_pF/(abs(actualChange(1))+eps);
key.recursive_prediction_relative_error_Cs2_pct = ...
    100*key.recursive_prediction_error_Cs2_pF/(abs(actualChange(2))+eps);
key.recursive_total_closure_error_Cs1_pF = ...
    counterfactualChange(1)+predictedFaultInduced(1)-actualChange(1);
key.recursive_total_closure_error_Cs2_pF = ...
    counterfactualChange(2)+predictedFaultInduced(2)-actualChange(2);
key.static_LS_first_fault_Cs1_pF = ...
    cycleTable.delta_Cs1_LS_pred_pF(firstFaultCycle);
key.static_LS_first_fault_Cs2_pF = ...
    cycleTable.delta_Cs2_LS_pred_pF(firstFaultCycle);
key.static_LS_ramp_mean_Cs1_pF = ...
    mean(cycleTable.delta_Cs1_LS_pred_pF(rampCycle));
key.static_LS_ramp_mean_Cs2_pF = ...
    mean(cycleTable.delta_Cs2_LS_pred_pF(rampCycle));
key.static_LS_steady_mean_Cs1_pF = ...
    mean(cycleTable.delta_Cs1_LS_pred_pF(steadyCycle));
key.static_LS_steady_mean_Cs2_pF = ...
    mean(cycleTable.delta_Cs2_LS_pred_pF(steadyCycle));
key.direct_RLS_steady_mean_Cs1_pF = ...
    mean(cycleTable.delta_Cs1_RLS_direct_raw_pF(steadyCycle));
key.direct_RLS_steady_mean_Cs2_pF = ...
    mean(cycleTable.delta_Cs2_RLS_direct_raw_pF(steadyCycle));
key.lambda_neutral_Delta_Cs1_pF = lambdaNeutralChange(1);
key.lambda_neutral_Delta_Cs2_pF = lambdaNeutralChange(2);
key.lambda_feedback_contribution_Cs1_pF = lambdaFeedbackContribution(1);
key.lambda_feedback_contribution_Cs2_pF = lambdaFeedbackContribution(2);
key.lambda_contribution_Cs1_pct = 100*abs(lambdaFeedbackContribution(1)) / ...
    (abs(predictedFaultInduced(1))+eps);
key.lambda_contribution_Cs2_pct = 100*abs(lambdaFeedbackContribution(2)) / ...
    (abs(predictedFaultInduced(2))+eps);
key.lambda_contribution_mean_pct = mean([ ...
    key.lambda_contribution_Cs1_pct,key.lambda_contribution_Cs2_pct]);
key.eta_geom_fault_ramp_mean = mean(cycleTable.eta_geom(rampCycle));
key.eta_geom_post_fault_mean = mean(cycleTable.eta_geom(postCycle));
key.eta_geom_fault_min = min(cycleTable.eta_geom(faultCycle));
key.eta_geom_fault_max = max(cycleTable.eta_geom(faultCycle));
key.rank_X_min = min(cycleTable.rank_X);
key.rank_X_max = max(cycleTable.rank_X);
key.cond2_X_min = min(cycleTable.cond2_X);
key.cond2_X_max = max(cycleTable.cond2_X);
key.cond2_X_mean = mean(cycleTable.cond2_X);
key.lambda_fault_pre_mean = mean(cycleTable.lambda(preCycle));
key.lambda_cf_pre_mean = mean(cycleTable.lambda_cf(preCycle));
key.lambda_fault_ramp_mean = mean(cycleTable.lambda(rampCycle));
key.lambda_cf_ramp_mean = mean(cycleTable.lambda_cf(rampCycle));
key.lambda_fault_post_mean = mean(cycleTable.lambda(steadyCycle));
key.lambda_cf_post_mean = mean(cycleTable.lambda_cf(steadyCycle));
key.lambda_fault_minus_cf_ramp_mean = mean( ...
    cycleTable.lambda(rampCycle)-cycleTable.lambda_cf(rampCycle));
key.lambda_fault_minus_cf_post_mean = mean( ...
    cycleTable.lambda(steadyCycle)-cycleTable.lambda_cf(steadyCycle));
key.rate_limit_active_Cs1_cycles = sum( ...
    cycleTable.rate_limit_active_Cs1 & faultCycle);
key.rate_limit_active_Cs2_cycles = sum( ...
    cycleTable.rate_limit_active_Cs2 & faultCycle);
key.rate_limit_active_any_cycles = sum( ...
    (cycleTable.rate_limit_active_Cs1 | ...
    cycleTable.rate_limit_active_Cs2) & faultCycle);
key.projection_active_Cs1_cycles = sum( ...
    cycleTable.projection_active_Cs1 & faultCycle);
key.projection_active_Cs2_cycles = sum( ...
    cycleTable.projection_active_Cs2 & faultCycle);
key.state_mismatch_pre_mean = mean( ...
    cycleTable.state_mismatch_rel_after(preCycle));
key.state_mismatch_ramp_mean = mean( ...
    cycleTable.state_mismatch_rel_after(rampCycle));
key.state_mismatch_post_mean = mean( ...
    cycleTable.state_mismatch_rel_after(steadyCycle));
key.state_mismatch_post_max = max( ...
    cycleTable.state_mismatch_rel_after(postCycle));
key.E_in_pre_mean_A = mean(cycleTable.E_in_A(preCycle));
key.E_in_ramp_mean_A = mean(cycleTable.E_in_A(rampCycle));
key.E_in_post_mean_A = mean(cycleTable.E_in_A(steadyCycle));
key.E_quad_pre_mean_A = mean(cycleTable.E_quad_A(preCycle));
key.E_quad_ramp_mean_A = mean(cycleTable.E_quad_A(rampCycle));
key.E_quad_post_mean_A = mean(cycleTable.E_quad_A(steadyCycle));
key.base_in_pre_mean_A = mean(cycleTable.base_in_A(preCycle));
key.base_in_ramp_mean_A = mean(cycleTable.base_in_A(rampCycle));
key.base_in_post_mean_A = mean(cycleTable.base_in_A(steadyCycle));
key.r_fault_B_fundamental_rms_A = rFaultRms;
key.delta_coupling_B_fundamental_rms_A = deltaCouplingRms;
key.delta_coupling_to_fault_fundamental_ratio = ...
    deltaCouplingRms/(rFaultRms+eps);
key.delta_coupling_fault_phase_difference_deg = ...
    wrap_to_180(deltaCouplingPhase-rFaultPhase);
key.delta_coupling_fault_correlation = couplingFaultCorrelation;
key.M2_fault_retention_error_pct = 100*(m2Factor-trueFactor)/trueFactor;
key.counterfactual_parameter_retention_error_pct = ...
    100*(counterfactualParameterFactor-trueFactor)/trueFactor;

analysis = struct( ...
    'key_metrics',key, ...
    'masks',struct('drift_sample',driftIdx,'initial_sample',initialIdx, ...
        'pre_cycle',preCycle,'ramp_cycle',rampCycle, ...
        'post_cycle',postCycle,'steady_cycle',steadyCycle, ...
        'fault_cycle',faultCycle,'pre_sample',preIdx,'post_sample',postIdx), ...
    'irM2',irM2, ...
    'irCounterfactualParameters',irCounterfactualParameters, ...
    'irM3',irM3, ...
    'rFaultB',rFaultB, ...
    'deltaCouplingB',deltaCouplingB);
end

function comparison = build_comparison_table(case05Key,case05Cycles,case06)
steady05 = case05Cycles.time_start_s >= 3.40 & ...
    case05Cycles.time_end_s < 3.80;
lambdaContribution05 = mean(abs([ ...
    case05Key.lambda_feedback_contribution_Cs1_pF / ...
    (case05Key.recursive_fault_induced_Delta_Cs1_pF+eps), ...
    case05Key.lambda_feedback_contribution_Cs2_pF / ...
    (case05Key.recursive_fault_induced_Delta_Cs2_pF+eps)]))*100;

metric = [ ...
    "eta_geom_post_mean"
    "static_LS_steady_Cs1"
    "static_LS_steady_Cs2"
    "recursive_fault_induced_Delta_Cs1"
    "recursive_fault_induced_Delta_Cs2"
    "actual_M2_Delta_Cs1"
    "actual_M2_Delta_Cs2"
    "fault_factor_true"
    "fault_factor_M2"
    "fault_retention_error"
    "lambda_fault_ramp_mean"
    "lambda_contribution_mean"
    "rate_limit_active_any_cycles"
    "projection_active_total_cycles"
    "state_mismatch_ramp_mean"
    "false_compensation_amplitude_ratio"
    "false_compensation_phase_difference"
    "false_compensation_correlation"];
unit = ["1";"pF";"pF";"pF";"pF";"pF";"pF";"ratio"; ...
    "ratio";"%";"1";"%";"cycles";"cycles";"1";"ratio";"deg";"1"];
case05 = [ ...
    case05Key.eta_geom_post_fault_mean
    mean(case05Cycles.delta_Cs1_LS_pred_pF(steady05))
    mean(case05Cycles.delta_Cs2_LS_pred_pF(steady05))
    case05Key.recursive_fault_induced_Delta_Cs1_pF
    case05Key.recursive_fault_induced_Delta_Cs2_pF
    case05Key.M2_actual_Delta_Cs1_pF
    case05Key.M2_actual_Delta_Cs2_pF
    case05Key.true_fault_factor
    case05Key.M2_actual_fault_factor
    case05Key.M2_fault_retention_error_pct
    case05Key.lambda_fault_ramp_mean
    lambdaContribution05
    case05Key.rate_limit_active_any_cycles
    case05Key.projection_active_Cs1_cycles + ...
        case05Key.projection_active_Cs2_cycles
    case05Key.state_mismatch_ramp_mean
    case05Key.delta_coupling_to_fault_fundamental_ratio
    case05Key.delta_coupling_fault_phase_difference_deg
    case05Key.delta_coupling_fault_correlation];
case06Values = [ ...
    case06.eta_geom_post_fault_mean
    case06.static_LS_steady_mean_Cs1_pF
    case06.static_LS_steady_mean_Cs2_pF
    case06.recursive_fault_induced_Delta_Cs1_pF
    case06.recursive_fault_induced_Delta_Cs2_pF
    case06.M2_actual_Delta_Cs1_pF
    case06.M2_actual_Delta_Cs2_pF
    case06.true_fault_factor
    case06.M2_actual_fault_factor
    case06.M2_fault_retention_error_pct
    case06.lambda_fault_ramp_mean
    case06.lambda_contribution_mean_pct
    case06.rate_limit_active_any_cycles
    case06.projection_active_Cs1_cycles + case06.projection_active_Cs2_cycles
    case06.state_mismatch_ramp_mean
    case06.delta_coupling_to_fault_fundamental_ratio
    case06.delta_coupling_fault_phase_difference_deg
    case06.delta_coupling_fault_correlation];
difference = case06Values-case05;
relativeDifferencePct = 100*difference./abs(case05);
relativeDifferencePct(abs(case05) <= eps) = NaN;
comparison = table(metric,unit,case05,case06Values,difference, ...
    relativeDifferencePct,'VariableNames', ...
    {'Metric','Unit','Case05','Case06','Difference','RelativeDifference_pct'});
end

function change = parameter_change(cHist,preIdx,postIdx)
change = mean(cHist(postIdx,:),1)-mean(cHist(preIdx,:),1);
end

function value = fault_factor(t,x,preIdx,postIdx,f)
value = fundamental_rms(t(postIdx),x(postIdx),f) / ...
    (fundamental_rms(t(preIdx),x(preIdx),f)+eps);
end

function value = fundamental_rms(t,x,f)
w = 2*pi*f;
coefficients = [sin(w*t),cos(w*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
end

function [value,phaseDeg] = fundamental_properties(t,x,f)
w = 2*pi*f;
coefficients = [sin(w*t),cos(w*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
phaseDeg = rad2deg(atan2(coefficients(2),coefficients(1)));
end

function value = wrap_to_180(value)
value = mod(value+180,360)-180;
end

function paths = frozen_paths(projectRoot,matlabRoot,phase1bRoot,step2Root)
paths = struct( ...
    'model',fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx'), ...
    'baseline_csv',fullfile(projectRoot,'paper_research', ...
        'phase1a_baseline','baseline_summary.csv'), ...
    'baseline_workspace',fullfile(projectRoot,'paper_research', ...
        'phase1a_baseline','baseline_workspace.mat'), ...
    'step1_report',fullfile(phase1bRoot, ...
        'STEP1_THEORY_AND_DATA_DEFINITION.md'), ...
    'step2_report',fullfile(phase1bRoot,'STEP2_BASELINE_MECHANISM.md'), ...
    'case05_key_metrics',fullfile(step2Root,'case05_key_metrics.csv'), ...
    'case05_summary',fullfile(step2Root,'case05_mechanism_summary.csv'), ...
    'case05_workspace',fullfile(step2Root,'case05_mechanism_workspace.mat'), ...
    'case05_observations',fullfile(step2Root,'observation_blocks_case05.mat'));
end

function expected = frozen_integrity()
expected = struct( ...
    'model',"56067ADAADF59B5921D7156A2ABB61777C4E98B69CB4150759C3CB1D4D6A2A70", ...
    'baseline_csv',"E7BEB3ECFEDF521105B67198684752BB32AFAAEFD84ACA80822BA57FBD9D0AB3", ...
    'baseline_workspace',"A90632B72479E7B6ADC4E410DB37542E9CA4985CA8381B6BAFC8F71C961E87B5", ...
    'step1_report',"02859DD0D35E35C18722B452DC7A5C9EE73B55CC6E7A26FC5566500F6E4B9041", ...
    'step2_report',"C98A2D9C53D6986EB4B9C202BEBC00DDD3A197B147615F68D5D073B652275CC1", ...
    'case05_key_metrics',"889FB69A32A17D5E55998C68DF99D11E02389A7C0631B4FCAFA05F368C62830A", ...
    'case05_summary',"F20A07ED08120951245A5F96342FBB1B051040C427154BD274779E8145E57A74", ...
    'case05_workspace',"AA585D987828728479BE4C521DFEFBD339120ECBD30C9E1DD9FAED216587A112", ...
    'case05_observations',"1169CA3246FD790D09DC7B908C24AB55485E068A6AE9690D2FFBAA35A37CA32B");
end

function assert_frozen_integrity(paths,expected)
names = string(fieldnames(expected));
for k = 1:numel(names)
    name = names(k);
    if file_sha256(paths.(name)) ~= expected.(name)
        error('Phase1B:Integrity','Frozen input hash mismatch: %s.',name);
    end
end
end

function metadata = capture_metadata(projectRoot,paths)
[commitCode,commit] = system(sprintf('git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,status] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if any([commitCode,branchCode,statusCode] ~= 0)
    error('Phase1B:GitMetadata','Unable to read Git metadata.');
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'git_status',string(status), ...
    'model_sha256',file_sha256(paths.model), ...
    'baseline_csv_sha256',file_sha256(paths.baseline_csv), ...
    'baseline_workspace_sha256',file_sha256(paths.baseline_workspace), ...
    'step1_report_sha256',file_sha256(paths.step1_report), ...
    'step2_report_sha256',file_sha256(paths.step2_report), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1B:HashFailure','Unable to open %s.',path);
end
cleanupObj = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
clear cleanupObj
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_key_results(key,validation,summaryPath,workspacePath)
fprintf('INSTRUMENTATION_REPLAY_MAX=%.17g\n',max([ ...
    validation.Cs1_replay_max_abs,validation.Cs2_replay_max_abs, ...
    validation.lambda_replay_max_abs,validation.E_in_replay_max_abs, ...
    validation.E_quad_replay_max_abs,validation.base_in_replay_max_abs]));
fprintf('FORMAL_CASE_REPRODUCED=%d\n',validation.formal_case_reproduced);
fprintf('DRIFT_RMSE_CS_PF=%.17g,%.17g\n', ...
    key.Cs1_drift_tracking_RMSE_pF,key.Cs2_drift_tracking_RMSE_pF);
fprintf('PRE_TRUE_EST_BIAS_CS1_PF=%.17g,%.17g,%.17g\n', ...
    key.Cs1_true_pre_pF,key.Cs1_est_pre_pF, ...
    key.pre_fault_estimation_bias_Cs1_pF);
fprintf('PRE_TRUE_EST_BIAS_CS2_PF=%.17g,%.17g,%.17g\n', ...
    key.Cs2_true_pre_pF,key.Cs2_est_pre_pF, ...
    key.pre_fault_estimation_bias_Cs2_pF);
fprintf('ETA_GEOM_RAMP_POST=%.17g,%.17g\n', ...
    key.eta_geom_fault_ramp_mean,key.eta_geom_post_fault_mean);
fprintf('STATIC_LS_STEADY_CS_PF=%.17g,%.17g\n', ...
    key.static_LS_steady_mean_Cs1_pF,key.static_LS_steady_mean_Cs2_pF);
fprintf('M2_DELTA_CS_PF=%.17g,%.17g\n', ...
    key.M2_actual_Delta_Cs1_pF,key.M2_actual_Delta_Cs2_pF);
fprintf('COUNTERFACTUAL_DELTA_CS_PF=%.17g,%.17g\n', ...
    key.counterfactual_Delta_Cs1_pF,key.counterfactual_Delta_Cs2_pF);
fprintf('FAULT_INDUCED_DELTA_CS_PF=%.17g,%.17g\n', ...
    key.recursive_fault_induced_Delta_Cs1_pF, ...
    key.recursive_fault_induced_Delta_Cs2_pF);
fprintf('FAULT_FACTORS_TRUE_M2_CF=%.17g,%.17g,%.17g\n', ...
    key.true_fault_factor,key.M2_actual_fault_factor, ...
    key.counterfactual_parameter_fault_factor);
fprintf('FALSE_COMP_RATIO_PHASE_CORR=%.17g,%.17g,%.17g\n', ...
    key.delta_coupling_to_fault_fundamental_ratio, ...
    key.delta_coupling_fault_phase_difference_deg, ...
    key.delta_coupling_fault_correlation);
fprintf('LAMBDA_CONTRIBUTION_MEAN_PCT=%.17g\n', ...
    key.lambda_contribution_mean_pct);
fprintf('RATE_PROJECTION_CYCLES=%d,%d\n', ...
    key.rate_limit_active_any_cycles, ...
    key.projection_active_Cs1_cycles+key.projection_active_Cs2_cycles);
fprintf('SUMMARY_CSV=%s\n',summaryPath);
fprintf('WORKSPACE_MAT=%s\n',workspacePath);
end
