function result = run_phase1b_step5_correlation_evidence
%RUN_PHASE1B_STEP5_CORRELATION_EVIDENCE Analyze frozen Step 4 results only.

step5Root = fileparts(mfilename('fullpath'));
phase1bRoot = fileparts(step5Root);
projectRoot = fileparts(fileparts(phase1bRoot));
step2Root = fullfile(phase1bRoot,'step2');
step3Root = fullfile(phase1bRoot,'step3');
step4Root = fullfile(phase1bRoot,'step4');
figuresRoot = fullfile(step5Root,'figures');
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

frozen = frozen_files(projectRoot,phase1bRoot,step2Root,step3Root,step4Root);
frozen.sha256_before = strings(height(frozen),1);
for k = 1:height(frozen)
    frozen.sha256_before(k) = file_sha256(frozen.path(k));
end

summaryPath = fullfile(step4Root,'controlled_factor_summary.csv');
cyclesPath = fullfile(step4Root,'controlled_factor_cycles.csv');
sourceWorkspacePath = fullfile(step4Root,'controlled_factor_workspace.mat');
summaryTable = readtable(summaryPath,'TextType','string');
cycleDetail = readtable(cyclesPath,'TextType','string');
sourceWorkspace = load(sourceWorkspacePath,'schemaVersion', ...
    'formalValidation','referencePhaseConvention');
case05 = readtable(fullfile(step2Root,'case05_key_metrics.csv'), ...
    'TextType','string');
case06 = readtable(fullfile(step3Root,'case06_key_metrics.csv'), ...
    'TextType','string');

validate_sources(summaryTable,cycleDetail,sourceWorkspace);
amplitude = sortrows(summaryTable(summaryTable.amplitude_sweep_member ~= 0,:), ...
    'fault_factor_true');
phase = sortrows(summaryTable(summaryTable.phase_sweep_member ~= 0,:), ...
    'reference_phase_error_deg');

amplitude.excess_fault_amplitude = amplitude.fault_factor_true - 1;
amplitude.true_increment = amplitude.fault_factor_true - 1;
amplitude.estimated_increment = amplitude.fault_factor_est - 1;
amplitude.lost_increment = amplitude.true_increment - ...
    amplitude.estimated_increment;
amplitude.absolute_fault_factor_loss = abs(amplitude.lost_increment);
amplitude.abs_DeltaCs2_fault_induced = ...
    abs(amplitude.DeltaCs2_fault_induced);
amplitude.false_compensation_RMS_mA = ...
    1e3 * amplitude.false_compensation_fundamental_RMS_A;

phase.lost_increment = phase.fault_factor_true - phase.fault_factor_est;
phase.false_compensation_RMS_mA = ...
    1e3 * phase.false_compensation_fundamental_RMS_A;

correlationSummary = build_correlation_summary(amplitude,phase);
predictionErrorSummary = build_prediction_summary(amplitude,phase);
mechanismEvidenceTable = build_mechanism_evidence( ...
    amplitude,phase,predictionErrorSummary,case05,case06);
figurePaths = generate_phase1b_step5_figures( ...
    figuresRoot,amplitude,phase);

validation = validate_results(correlationSummary,predictionErrorSummary, ...
    mechanismEvidenceTable,figurePaths,amplitude,phase);
frozen.sha256_after = strings(height(frozen),1);
for k = 1:height(frozen)
    frozen.sha256_after(k) = file_sha256(frozen.path(k));
end
frozen.unchanged = frozen.sha256_before == frozen.sha256_after;
validation.frozen_artifacts_unchanged = all(frozen.unchanged);
validation.overall_pass = validation.overall_pass && ...
    validation.frozen_artifacts_unchanged;
if ~validation.overall_pass
    error('Phase1B:Step5Validation','Step 5 validation failed.');
end

correlationPath = fullfile(step5Root,'correlation_summary.csv');
predictionPath = fullfile(step5Root,'prediction_error_summary.csv');
evidencePath = fullfile(step5Root,'mechanism_evidence_table.csv');
workspacePath = fullfile(step5Root,'correlation_workspace.mat');
writetable(correlationSummary,correlationPath);
writetable(predictionErrorSummary,predictionPath);
writetable(mechanismEvidenceTable,evidencePath);

schemaVersion = "phase1b_step5_correlation_v1";
analysisScope = "controlled exploratory evidence; n=6 per sweep";
lostIncrementDefinition = ...
    "true_increment = fault_factor_true - 1; " + ...
    "estimated_increment = fault_factor_est - 1; " + ...
    "lost_increment = true_increment - estimated_increment";
runMetadata = capture_metadata(projectRoot);
result = struct( ...
    'schema_version',schemaVersion, ...
    'analysis_scope',analysisScope, ...
    'lost_increment_definition',lostIncrementDefinition, ...
    'amplitude',amplitude, ...
    'phase',phase, ...
    'correlationSummary',correlationSummary, ...
    'predictionErrorSummary',predictionErrorSummary, ...
    'mechanismEvidenceTable',mechanismEvidenceTable, ...
    'validation',validation, ...
    'frozenManifest',frozen, ...
    'sourceWorkspaceMetadata',sourceWorkspace, ...
    'case05',case05, ...
    'case06',case06, ...
    'figurePaths',figurePaths);
save(workspacePath,'schemaVersion','analysisScope', ...
    'lostIncrementDefinition','amplitude','phase','correlationSummary', ...
    'predictionErrorSummary','mechanismEvidenceTable','validation', ...
    'frozen','sourceWorkspace','case05','case06','figurePaths', ...
    'runMetadata','result','-v7.3');

print_key_results(amplitude,phase,correlationSummary, ...
    predictionErrorSummary,validation);
fprintf('CORRELATION_CSV=%s\n',correlationPath);
fprintf('PREDICTION_CSV=%s\n',predictionPath);
fprintf('EVIDENCE_CSV=%s\n',evidencePath);
fprintf('WORKSPACE_MAT=%s\n',workspacePath);
fprintf('STEP5_CORRELATION_AND_EVIDENCE=PASS\n');
end

function T = build_correlation_summary(amplitude,phase)
rows = cell(0,1);
x = amplitude.excess_fault_amplitude;
rows{end+1} = relationship_row("amplitude","A1_Cs1", ...
    "excess_fault_amplitude","DeltaCs1_fault_induced",x, ...
    amplitude.DeltaCs1_fault_induced,"1","pF", ...
    "Fault-induced Cs1 bias versus fault increment.");
rows{end+1} = relationship_row("amplitude","A1_abs_Cs2", ...
    "excess_fault_amplitude","abs_DeltaCs2_fault_induced",x, ...
    amplitude.abs_DeltaCs2_fault_induced,"1","pF", ...
    "Magnitude of fault-induced Cs2 bias versus fault increment.");
rows{end+1} = relationship_row("amplitude","A3_false_comp_RMS", ...
    "excess_fault_amplitude","false_compensation_RMS",x, ...
    amplitude.false_compensation_RMS_mA,"1","mA", ...
    "False coupling compensation magnitude versus fault increment.");
rows{end+1} = relationship_row("amplitude","A3_lost_increment", ...
    "excess_fault_amplitude","lost_increment",x, ...
    amplitude.lost_increment,"1","fault-factor increment", ...
    "Absolute fault increment removed from the M2 estimate.");
rows{end+1} = relationship_row("amplitude","A3_Cs1_vs_loss", ...
    "DeltaCs1_fault_induced","lost_increment", ...
    amplitude.DeltaCs1_fault_induced,amplitude.lost_increment, ...
    "pF","fault-factor increment", ...
    "Recursive Cs1 bias versus lost fault increment.");
rows{end+1} = relationship_row("amplitude","A3_abs_Cs2_vs_loss", ...
    "abs_DeltaCs2_fault_induced","lost_increment", ...
    amplitude.abs_DeltaCs2_fault_induced,amplitude.lost_increment, ...
    "pF","fault-factor increment", ...
    "Recursive absolute Cs2 bias versus lost fault increment.");
rows{end+1} = invariant_row("amplitude","A4_eta_geom_invariant", ...
    "excess_fault_amplitude","eta_geom_post",x,amplitude.eta_geom_post, ...
    "eta_geom is numerically invariant, so correlation is not a " + ...
    "meaningful mechanism statistic.");

x = phase.reference_phase_error_deg;
rows{end+1} = relationship_row("phase_error","B1_pre_Cs1_bias", ...
    "reference_phase_error","Cs1_pre_estimation_bias",x, ...
    phase.Cs1_pre_estimation_bias_pF,"deg","pF", ...
    "Reference phase error versus normal pre-fault Cs1 bias.");
rows{end+1} = relationship_row("phase_error","B1_pre_Cs2_bias", ...
    "reference_phase_error","Cs2_pre_estimation_bias",x, ...
    phase.Cs2_pre_estimation_bias_pF,"deg","pF", ...
    "Reference phase error versus normal pre-fault Cs2 bias.");
rows{end+1} = relationship_row("phase_error","B2_M2_retention", ...
    "reference_phase_error","M2_fault_retention_error",x, ...
    phase.fault_retention_error,"deg","percent", ...
    "Phase error versus M2 fault retention error.");
rows{end+1} = relationship_row("phase_error","B2_counterfactual_retention", ...
    "reference_phase_error","counterfactual_retention_error",x, ...
    phase.counterfactual_retention_error_pct,"deg","percent", ...
    "Phase error versus retention using counterfactual parameters.");
rows{end+1} = relationship_row("phase_error","B3_eta_geom", ...
    "reference_phase_error","eta_geom_post",x,phase.eta_geom_post, ...
    "deg","1", ...
    "Association is reported with effect size; eta changes only slightly.");
rows{end+1} = relationship_row("phase_error","B4_false_comp_phase", ...
    "reference_phase_error","false_compensation_phase",x, ...
    phase.false_compensation_phase,"deg","deg", ...
    "Reference phase error versus false-compensation direction rotation.");
rows{end+1} = relationship_row("phase_error","B4_false_comp_ratio", ...
    "reference_phase_error","false_compensation_ratio",x, ...
    phase.false_compensation_ratio,"deg","1", ...
    "Reference phase error versus false-compensation amplitude ratio.");
T = struct2table(vertcat(rows{:}),'AsArray',true);
end

function row = relationship_row(sweep,id,predictor,response,x,y,xUnit,yUnit,note)
x = x(:); y = y(:);
valid = isfinite(x) & isfinite(y);
x = x(valid); y = y(valid);
p = polyfit(x,y,1);
yFit = polyval(p,x);
ssRes = sum((y-yFit).^2);
ssTot = sum((y-mean(y)).^2);
if ssTot <= eps(max(abs(y))^2) * numel(y)
    rSquared = NaN;
else
    rSquared = 1 - ssRes/ssTot;
end
row = struct( ...
    'sweep',string(sweep), ...
    'relation_id',string(id), ...
    'analysis_type',"correlation_and_linear_fit", ...
    'predictor',string(predictor), ...
    'response',string(response), ...
    'n',numel(x), ...
    'pearson_r',pearson_local(x,y), ...
    'spearman_rho',spearman_local(x,y), ...
    'linear_slope',p(1), ...
    'linear_intercept',p(2), ...
    'linear_R2',rSquared, ...
    'predictor_min',min(x), ...
    'predictor_max',max(x), ...
    'response_min',min(y), ...
    'response_max',max(y), ...
    'response_range',max(y)-min(y), ...
    'predictor_unit',string(xUnit), ...
    'response_unit',string(yUnit), ...
    'evidence_scope',"controlled exploratory evidence", ...
    'mechanism_note',string(note));
end

function row = invariant_row(sweep,id,predictor,response,x,y,note)
row = relationship_row(sweep,id,predictor,response,x,y,"1","1",note);
row.analysis_type = "descriptive_invariant";
row.pearson_r = NaN;
row.spearman_rho = NaN;
row.linear_slope = NaN;
row.linear_intercept = NaN;
row.linear_R2 = NaN;
end

function T = build_prediction_summary(amplitude,phase)
rows = [ ...
    prediction_row("amplitude","Cs1",amplitude.DeltaCs1_LS, ...
        amplitude.DeltaCs1_fault_induced); ...
    prediction_row("amplitude","Cs2",amplitude.DeltaCs2_LS, ...
        amplitude.DeltaCs2_fault_induced); ...
    prediction_row("phase_error","Cs1",phase.DeltaCs1_LS, ...
        phase.DeltaCs1_fault_induced); ...
    prediction_row("phase_error","Cs2",phase.DeltaCs2_LS, ...
        phase.DeltaCs2_fault_induced)];
T = struct2table(rows,'AsArray',true);
end

function row = prediction_row(sweep,parameter,predicted,actual)
predicted = predicted(:); actual = actual(:);
errorValue = predicted - actual;
relativeErrorPct = 100 * abs(errorValue) ./ max(abs(actual),eps);
row = struct( ...
    'sweep',string(sweep), ...
    'parameter',string(parameter), ...
    'n',numel(actual), ...
    'RMSE_pF',sqrt(mean(errorValue.^2)), ...
    'MAE_pF',mean(abs(errorValue)), ...
    'max_absolute_error_pF',max(abs(errorValue)), ...
    'max_relative_error_pct',max(relativeErrorPct), ...
    'pearson_r',pearson_local(predicted,actual), ...
    'spearman_rho',spearman_local(predicted,actual), ...
    'direction_agreement_pct',100*mean(sign(predicted) == sign(actual)), ...
    'prediction_definition',"static Delta c_LS,f", ...
    'actual_definition',"recursive fault-branch minus counterfactual-branch bias", ...
    'evidence_scope',"controlled exploratory evidence");
end

function T = build_mechanism_evidence(amplitude,phase,prediction,case05,case06)
ampPred = prediction(prediction.sweep == "amplitude",:);
maxAmpRmse = max(ampPred.RMSE_pF);
maxAmpRelative = max(ampPred.max_relative_error_pct);
case05Recovery = case05.counterfactual_parameter_fault_factor(1) - ...
    case05.true_fault_factor(1);
case06Recovery = case06.counterfactual_parameter_fault_factor(1) - ...
    case06.true_fault_factor(1);
rows = [ ...
    evidence_row("E1","r_fault", ...
        "projection onto col(X)","directly verified", ...
        sprintf(['Step 2/3 projection closure <= 5.50e-15; Step 4 ' ...
        'eta_post %.9f to %.9f.'],min(amplitude.eta_geom_post), ...
        max(phase.eta_geom_post)), ...
        "Geometry is conditional on the frozen two-column X/reference model."); ...
    evidence_row("E2","projection onto col(X)", ...
        "Delta c_LS,f","directly verified", ...
        "X*Delta c_LS,f reproduces the projected component by construction " + ...
        "and passed the Step 2/3 projection-fit checks.", ...
        "Static LS describes blockwise equivalent bias, not recursive timing."); ...
    evidence_row("E3","Delta c_LS,f", ...
        "recursive false Cs bias","strongly supported", ...
        sprintf(['Amplitude-sweep maximum RMSE %.6g pF, maximum relative ' ...
        'error %.6g%%, direction agreement 100%%.'], ...
        maxAmpRmse,maxAmpRelative), ...
        "Only six deterministic points per sweep; recursion and state history remain separate."); ...
    evidence_row("E4","recursive false Cs bias", ...
        "false coupling compensation","directly verified", ...
        sprintf(['Compensation RMS rises %.6g to %.6g mA while its amplitude ' ...
        'ratio stays %.6f to %.6f.'], ...
        min(amplitude.false_compensation_RMS_mA), ...
        max(amplitude.false_compensation_RMS_mA), ...
        min(amplitude.false_compensation_ratio), ...
        max(amplitude.false_compensation_ratio)), ...
        "Mapping is evaluated for the frozen B-phase extraction equation."); ...
    evidence_row("E5","false coupling compensation", ...
        "fault increment loss","directly verified", ...
        sprintf(['Case05/Case06 counterfactual recovery residuals are %.6g ' ...
        'and %.6g in fault factor; controlled lost increment %.6g to %.6g.'], ...
        case05Recovery,case06Recovery,min(amplitude.lost_increment), ...
        max(amplitude.lost_increment)), ...
        "Counterfactual recovery is deterministic and is not a population robustness claim.")];
T = struct2table(rows,'AsArray',true);
end

function row = evidence_row(id,upstream,downstream,level,evidence,limitation)
row = struct( ...
    'link_id',string(id), ...
    'upstream_variable',string(upstream), ...
    'downstream_variable',string(downstream), ...
    'evidence_level',string(level), ...
    'quantitative_evidence',string(evidence), ...
    'limitation',string(limitation));
end

function r = pearson_local(x,y)
if numel(x) < 2 || std(x) == 0 || std(y) == 0
    r = NaN;
    return
end
R = corrcoef(x,y,'Rows','complete');
r = R(1,2);
end

function r = spearman_local(x,y)
rx = tied_rank_local(x);
ry = tied_rank_local(y);
r = pearson_local(rx,ry);
end

function ranks = tied_rank_local(x)
x = x(:);
[sorted,order] = sort(x);
ranksSorted = zeros(size(x));
k = 1;
while k <= numel(sorted)
    last = k;
    while last < numel(sorted) && sorted(last+1) == sorted(k)
        last = last + 1;
    end
    ranksSorted(k:last) = mean(k:last);
    k = last + 1;
end
ranks = zeros(size(x));
ranks(order) = ranksSorted;
end

function validate_sources(summaryTable,cycleDetail,sourceWorkspace)
required = ["condition_id","amplitude_sweep_member","phase_sweep_member", ...
    "fault_factor_true","fault_factor_est","reference_phase_error_deg", ...
    "eta_geom_post","DeltaCs1_LS","DeltaCs2_LS", ...
    "DeltaCs1_fault_induced","DeltaCs2_fault_induced", ...
    "Cs1_pre_estimation_bias_pF","Cs2_pre_estimation_bias_pF", ...
    "fault_retention_error","counterfactual_retention_error_pct", ...
    "false_compensation_fundamental_RMS_A", ...
    "false_compensation_ratio","false_compensation_phase"];
assert(all(ismember(required,string(summaryTable.Properties.VariableNames))), ...
    'Phase1B:MissingField','Step 4 summary is missing required fields.');
assert(height(summaryTable) == 11,'Phase1B:ConditionCount', ...
    'Step 4 summary must contain 11 unique formal conditions.');
assert(numel(unique(summaryTable.condition_id)) == 11, ...
    'Phase1B:ConditionUniqueness','Condition IDs are not unique.');
assert(sum(summaryTable.amplitude_sweep_member) == 6 && ...
    sum(summaryTable.phase_sweep_member) == 6, ...
    'Phase1B:SweepCount','Each formal sweep must contain six points.');
assert(height(cycleDetail) == 1815,'Phase1B:CycleCount', ...
    'Cycle-level source must retain all 1815 rows.');
assert(sourceWorkspace.formalValidation.overall_pass, ...
    'Phase1B:Step4Validation','Step 4 source validation is not PASS.');
end

function validation = validate_results(correlation,prediction,evidence, ...
        figurePaths,amplitude,phase)
validation = struct();
validation.amplitude_n = height(amplitude);
validation.phase_n = height(phase);
validation.correlation_rows = height(correlation);
validation.prediction_rows = height(prediction);
validation.evidence_links = height(evidence);
validation.png_count = sum(isfile(figurePaths(:,1)));
validation.fig_count = sum(isfile(figurePaths(:,2)));
validation.no_missing_meaningful_correlations = all(isfinite( ...
    correlation.pearson_r(correlation.analysis_type == ...
    "correlation_and_linear_fit"))) && all(isfinite( ...
    correlation.spearman_rho(correlation.analysis_type == ...
    "correlation_and_linear_fit")));
validation.all_direction_agreement = all( ...
    prediction.direction_agreement_pct == 100);
validation.eta_amplitude_range = max(amplitude.eta_geom_post) - ...
    min(amplitude.eta_geom_post);
validation.eta_phase_relative_change_pct = 100 * ...
    (phase.eta_geom_post(end)-phase.eta_geom_post(1)) / ...
    phase.eta_geom_post(1);
validation.overall_pass = validation.amplitude_n == 6 && ...
    validation.phase_n == 6 && validation.correlation_rows >= 14 && ...
    validation.prediction_rows == 4 && validation.evidence_links == 5 && ...
    validation.png_count == 6 && validation.fig_count == 6 && ...
    validation.no_missing_meaningful_correlations && ...
    validation.all_direction_agreement;
end

function frozen = frozen_files(projectRoot,phase1bRoot,step2Root,step3Root,step4Root)
matlabRoot = fullfile(projectRoot,'MATLAB一键实验');
paths = [ ...
    string(fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx')); ...
    string(fullfile(projectRoot,'paper_research','phase1a_baseline','baseline_summary.csv')); ...
    string(fullfile(projectRoot,'paper_research','phase1a_baseline','baseline_workspace.mat')); ...
    string(fullfile(phase1bRoot,'STEP1_THEORY_AND_DATA_DEFINITION.md')); ...
    string(fullfile(phase1bRoot,'STEP2_BASELINE_MECHANISM.md')); ...
    string(fullfile(phase1bRoot,'STEP3_CASE06_VERIFICATION.md')); ...
    string(fullfile(phase1bRoot,'STEP4_CONTROLLED_FACTOR_EXPERIMENTS.md')); ...
    string(fullfile(step2Root,'case05_key_metrics.csv')); ...
    string(fullfile(step2Root,'case05_mechanism_workspace.mat')); ...
    string(fullfile(step3Root,'case06_key_metrics.csv')); ...
    string(fullfile(step3Root,'case06_mechanism_workspace.mat')); ...
    string(fullfile(step4Root,'controlled_factor_summary.csv')); ...
    string(fullfile(step4Root,'controlled_factor_cycles.csv')); ...
    string(fullfile(step4Root,'controlled_factor_workspace.mat')); ...
    string(fullfile(step4Root,'controlled_factor_validation.csv')); ...
    string(fullfile(matlabRoot,'track_coupling_cvff_rls.m')); ...
    string(fullfile(matlabRoot,'run_phase1a_algorithm.m')); ...
    string(fullfile(matlabRoot,'reconstruct_refs_from_b.m')); ...
    string(fullfile(matlabRoot,'patent_default_config.m'))];
names = ["model";"phase1a_summary";"phase1a_workspace"; ...
    "step1_report";"step2_report";"step3_report";"step4_report"; ...
    "step2_key";"step2_workspace";"step3_key";"step3_workspace"; ...
    "step4_summary";"step4_cycles";"step4_workspace"; ...
    "step4_validation";"tracker";"dispatcher"; ...
    "reference_reconstruction";"default_config"];
frozen = table(names,paths,'VariableNames',{'name','path'});
end

function metadata = capture_metadata(projectRoot)
[commitCode,commit] = system(sprintf('git -C "%s" rev-parse HEAD',projectRoot));
[branchCode,branch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
if commitCode ~= 0 || branchCode ~= 0
    error('Phase1B:GitMetadata','Unable to read Git metadata.');
end
metadata = struct( ...
    'git_commit',strtrim(string(commit)), ...
    'git_branch',strtrim(string(branch)), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'matlab_version',string(version), ...
    'platform',string(computer), ...
    'simulink_executed',false);
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1B:HashFailure','Unable to open %s.',path);
end
cleanupObj = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
clear cleanupObj
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function print_key_results(amplitude,phase,correlation,prediction,validation)
aCs1 = correlation(correlation.relation_id == "A1_Cs1",:);
aCs2 = correlation(correlation.relation_id == "A1_abs_Cs2",:);
aComp = correlation(correlation.relation_id == "A3_false_comp_RMS",:);
aLoss = correlation(correlation.relation_id == "A3_lost_increment",:);
bEta = correlation(correlation.relation_id == "B3_eta_geom",:);
bPhase = correlation(correlation.relation_id == "B4_false_comp_phase",:);
fprintf('A1_CS1_R=%.17g RHO=%.17g SLOPE=%.17g R2=%.17g\n', ...
    aCs1.pearson_r,aCs1.spearman_rho,aCs1.linear_slope,aCs1.linear_R2);
fprintf('A1_CS2_R=%.17g RHO=%.17g SLOPE=%.17g R2=%.17g\n', ...
    aCs2.pearson_r,aCs2.spearman_rho,aCs2.linear_slope,aCs2.linear_R2);
fprintf('A3_COMP_R=%.17g RHO=%.17g LOSS_R=%.17g RHO=%.17g\n', ...
    aComp.pearson_r,aComp.spearman_rho,aLoss.pearson_r,aLoss.spearman_rho);
fprintf('PREDICTION_MAX_RMSE_PF=%.17g MAX_RELATIVE_ERROR_PCT=%.17g\n', ...
    max(prediction.RMSE_pF),max(prediction.max_relative_error_pct));
fprintf('AMPLITUDE_ETA_RANGE=%.17g LOST_INCREMENT_RANGE=%.17g,%.17g\n', ...
    max(amplitude.eta_geom_post)-min(amplitude.eta_geom_post), ...
    min(amplitude.lost_increment), ...
    max(amplitude.lost_increment));
fprintf('PHASE_ETA_REL_CHANGE_PCT=%.17g ETA_R=%.17g PHASE_ROTATION_R=%.17g\n', ...
    validation.eta_phase_relative_change_pct,bEta.pearson_r, ...
    bPhase.pearson_r);
fprintf('PHASE_RETENTION_RANGE=%.17g,%.17g CF_RANGE=%.17g,%.17g\n', ...
    min(phase.fault_retention_error),max(phase.fault_retention_error), ...
    min(phase.counterfactual_retention_error_pct), ...
    max(phase.counterfactual_retention_error_pct));
fprintf('FROZEN_ARTIFACTS_UNCHANGED=%d FIGURE_PAIRS=%d\n', ...
    validation.frozen_artifacts_unchanged,validation.png_count);
end
