function row = evaluate_case_metrics(data,ir,cHist,methodName,sceneName,cfg)
idx = data.t>=cfg.metric_start;
[aFundErr,aFundPhase,aH3Err,aH3Phase,aRmse,aNrmse] = ...
    signal_metrics(data.t(idx),data.irA(idx),ir.A(idx),cfg.f);
[bFundErr,bFundPhase,bH3Err,bH3Phase,bRmse,bNrmse] = ...
    signal_metrics(data.t(idx),data.irB(idx),ir.B(idx),cfg.f);
[cFundErr,cFundPhase,cH3Err,cH3Phase,cRmse,cNrmse] = ...
    signal_metrics(data.t(idx),data.irC(idx),ir.C(idx),cfg.f);
row = table(string(sceneName),string(methodName), ...
    mean(abs(cHist(idx,1)-data.Cs1(idx))),mean(abs(cHist(idx,2)-data.Cs2(idx))), ...
    max(abs(cHist(idx,1)-data.Cs1(idx))),max(abs(cHist(idx,2)-data.Cs2(idx))), ...
    aFundErr,bFundErr,cFundErr,aFundPhase,bFundPhase,cFundPhase, ...
    aH3Err,bH3Err,cH3Err,aH3Phase,bH3Phase,cH3Phase, ...
    aRmse,bRmse,cRmse,aNrmse,bNrmse,cNrmse, ...
    'VariableNames',{'scene','method','Cs1_MAE_pF','Cs2_MAE_pF','Cs1_MaxErr_pF','Cs2_MaxErr_pF', ...
    'A_FundErr_pct','B_FundErr_pct','C_FundErr_pct', ...
    'A_FundPhaseErr_deg','B_FundPhaseErr_deg','C_FundPhaseErr_deg', ...
    'A_H3Err_pct','B_H3Err_pct','C_H3Err_pct', ...
    'A_H3PhaseErr_deg','B_H3PhaseErr_deg','C_H3PhaseErr_deg', ...
    'A_WaveRMSE_A','B_WaveRMSE_A','C_WaveRMSE_A', ...
    'A_WaveNRMSE_pct','B_WaveNRMSE_pct','C_WaveNRMSE_pct'});
end

function [fundErr,fundPhaseErr,h3Err,h3PhaseErr,waveRmse,waveNrmse] = ...
        signal_metrics(t,xTrue,xEst,f)
[trueRms,truePhase] = harmonic_components(t,xTrue,f);
[estRms,estPhase] = harmonic_components(t,xEst,f);
fundErr = relative_error(estRms(1),trueRms(1));
h3Err = relative_error(estRms(2),trueRms(2));
fundPhaseErr = wrapped_phase_error(estPhase(1),truePhase(1));
h3PhaseErr = wrapped_phase_error(estPhase(2),truePhase(2));
waveRmse = sqrt(mean((xEst-xTrue).^2));
waveNrmse = waveRmse/(rms(xTrue)+eps)*100;
end

function [rmsValue,phaseDeg] = harmonic_components(t,x,f)
w = 2*pi*f;
H = [sin(w*t),cos(w*t),sin(3*w*t),cos(3*w*t),ones(size(t))];
b = H\x;
rmsValue = [hypot(b(1),b(2)),hypot(b(3),b(4))]/sqrt(2);
phaseDeg = rad2deg([atan2(b(2),b(1)),atan2(b(4),b(3))]);
end

function value = relative_error(estimate,truth)
value = (estimate-truth)/(truth+eps)*100;
end

function value = wrapped_phase_error(estimateDeg,truthDeg)
value = mod(estimateDeg-truthDeg+180,360)-180;
end
