function evidence = m4_fault_evidence( ...
        Ein,Equad,baseIn,gateRatio,gateQuadRatio,forcedUpdateWeight)
%M4_FAULT_EVIDENCE Continuous residual evidence for M4-v0.
% This is the M4-v0 structural formula, not the final frozen M4 formula.
% Existing M3 ratios are reused only as normalization scales.

if nargin < 6
    forcedUpdateWeight = NaN;
end
if ~(isscalar(forcedUpdateWeight) && ...
        (isnan(forcedUpdateWeight) || ...
        (isfinite(forcedUpdateWeight) && ...
        forcedUpdateWeight >= 0 && forcedUpdateWeight <= 1)))
    error('M4:InvalidForcedUpdateWeight', ...
        'forcedUpdateWeight must be NaN or a scalar in [0,1].');
end

numericEpsilon = eps;
valid = isfinite(Ein) & isfinite(Equad) & isfinite(baseIn) & ...
    Ein >= 0 & Equad >= 0 & baseIn >= 0 & ...
    isfinite(gateRatio) & gateRatio > 1 & ...
    isfinite(gateQuadRatio) & gateQuadRatio > 0;

ratioBase = Ein./(baseIn+numericEpsilon);
ratioQuad = Ein./(Equad+numericEpsilon);
backgroundExcess = max(0, ...
    (ratioBase-1)./max(gateRatio-1,numericEpsilon));
phaseWeight = min(max(ratioQuad./gateQuadRatio,0),1);
score = backgroundExcess.*phaseWeight;
naturalWeight = 1./(1+score);

ratioBase(~valid) = NaN;
ratioQuad(~valid) = NaN;
backgroundExcess(~valid) = NaN;
phaseWeight(~valid) = NaN;
score(~valid) = NaN;
naturalWeight(~valid) = 1;

if isnan(forcedUpdateWeight)
    updateWeight = naturalWeight;
    forcedActive = false(size(updateWeight));
else
    updateWeight = forcedUpdateWeight*ones(size(naturalWeight));
    forcedActive = true(size(updateWeight));
end

evidence = struct( ...
    'ratio_base',ratioBase, ...
    'ratio_quad',ratioQuad, ...
    'background_excess',backgroundExcess, ...
    'phase_weight',phaseWeight, ...
    'score',score, ...
    'natural_update_weight',naturalWeight, ...
    'update_weight',updateWeight, ...
    'valid',valid, ...
    'forced_active',forcedActive);
end
