function result = m5_directional_update(deltaRaw,weight,scope)
%M5_DIRECTIONAL_UPDATE Apply the fixed M5 parameter-space operator.

arguments
    deltaRaw (2,1) double {mustBeReal,mustBeFinite}
    weight (1,1) double {mustBeReal,mustBeFinite, ...
        mustBeGreaterThanOrEqual(weight,0),mustBeLessThanOrEqual(weight,1)}
    scope (1,1) string {mustBeMember(scope,["directional","global"])}
end

faultDirection = [1;-1]/sqrt(2);
faultProjector = faultDirection*faultDirection.';
perpendicularProjector = eye(2)-faultProjector;
deltaParallel = faultProjector*deltaRaw;
deltaPerpendicular = perpendicularProjector*deltaRaw;

if scope == "directional"
    operator = perpendicularProjector+weight*faultProjector;
    deltaProtected = deltaPerpendicular+weight*deltaParallel;
else
    operator = weight*eye(2);
    deltaProtected = weight*deltaRaw;
end

result = struct( ...
    'scope',scope, ...
    'weight',weight, ...
    'fault_direction',faultDirection, ...
    'P_f',faultProjector, ...
    'P_perp',perpendicularProjector, ...
    'operator',operator, ...
    'delta_raw',deltaRaw, ...
    'delta_parallel',deltaParallel, ...
    'delta_perp',deltaPerpendicular, ...
    'delta_protected',deltaProtected, ...
    'parallel_norm',norm(deltaParallel), ...
    'perp_norm',norm(deltaPerpendicular), ...
    'decomposition_error_norm', ...
    norm(deltaRaw-deltaParallel-deltaPerpendicular));
end

