function diagnostics = m5_step4_cycle_diagnostics( ...
        algorithmId,cycle,windowStart,windowEnd,cfg)
%M5_STEP4_CYCLE_DIAGNOSTICS Explicit schema mapping for cycle logs.

arguments
    algorithmId {mustBeTextScalar}
    cycle table
    windowStart (1,1) double {mustBeFinite}
    windowEnd (1,1) double {mustBeFinite,mustBeGreaterThan(windowEnd,windowStart)}
    cfg (1,1) struct
end

algorithmId = upper(string(algorithmId));
inWindow = cycle.time_s >= windowStart & cycle.time_s < windowEnd;
if ~any(inWindow)
    error('M5Step4:CycleWindow','Cycle window is empty for %s.',algorithmId);
end

diagnostics = blank_diagnostics();
diagnostics.schema_mapping = mapping_label(algorithmId);
diagnostics.cycle_count = nnz(inWindow);
faultDirection = [1;-1]/sqrt(2);
perpendicularProjector = eye(2)-faultDirection*faultDirection.';

if ismember(algorithmId,["GH","GC","M5_DH","M5_FULL"])
    require_fields(cycle,["gate","w_REW","selected_weight", ...
        "rate_limit_active","projection_active","parallel_norm", ...
        "perp_norm","raw_angle_to_df_deg", ...
        "protected_angle_to_df_deg","post_rate_angle_to_df_deg", ...
        "post_projection_angle_to_df_deg"]);
    diagnostics.hard_gate_active_ratio = mean(cycle.gate(inWindow));
    diagnostics.mean_w_REW = mean(cycle.w_REW(inWindow));
    diagnostics.mean_selected_weight = mean(cycle.selected_weight(inWindow));
    diagnostics.rate_limit_cycles = sum(cycle.rate_limit_active(inWindow));
    diagnostics.projection_cycles = sum(cycle.projection_active(inWindow));
    diagnostics.raw_parallel_update_energy_pF2 = ...
        sum(cycle.parallel_norm(inWindow).^2);
    diagnostics.raw_perp_update_energy_pF2 = ...
        sum(cycle.perp_norm(inWindow).^2);
    diagnostics.near_zero_update_cycles = ...
        sum(isnan(cycle.raw_angle_to_df_deg(inWindow)));
    diagnostics.mean_raw_angle_to_df_deg = ...
        mean(cycle.raw_angle_to_df_deg(inWindow),'omitnan');
    diagnostics.mean_protected_angle_to_df_deg = ...
        mean(cycle.protected_angle_to_df_deg(inWindow),'omitnan');
    diagnostics.mean_post_rate_angle_to_df_deg = ...
        mean(cycle.post_rate_angle_to_df_deg(inWindow),'omitnan');
    diagnostics.mean_post_projection_angle_to_df_deg = ...
        mean(cycle.post_projection_angle_to_df_deg(inWindow),'omitnan');
    applied = cycle{inWindow, ...
        {'delta_after_projection_Cs1','delta_after_projection_Cs2'}};
elseif algorithmId == "M4"
    require_fields(cycle,["update_weight","rate_limit_active", ...
        "projection_active","delta_c_raw_1","delta_c_raw_2", ...
        "delta_c_applied_1","delta_c_applied_2"]);
    diagnostics.mean_w_REW = mean(cycle.update_weight(inWindow));
    diagnostics.mean_selected_weight = diagnostics.mean_w_REW;
    diagnostics.rate_limit_cycles = sum(cycle.rate_limit_active(inWindow));
    diagnostics.projection_cycles = sum(cycle.projection_active(inWindow));
    raw = cycle{inWindow,{'delta_c_raw_1','delta_c_raw_2'}};
    [diagnostics.raw_parallel_update_energy_pF2, ...
        diagnostics.raw_perp_update_energy_pF2] = ...
        projected_energy(raw,faultDirection,perpendicularProjector);
    diagnostics.near_zero_update_cycles = sum( ...
        vecnorm(raw,2,2) <= sqrt(eps));
    applied = cycle{inWindow, ...
        {'delta_c_applied_1','delta_c_applied_2'}};
elseif ismember(algorithmId,["M2","M3"])
    require_fields(cycle,["Cs1_pF","Cs2_pF","gate"]);
    if algorithmId == "M3"
        diagnostics.hard_gate_active_ratio = mean(cycle.gate(inWindow));
        diagnostics.mean_selected_weight = 1-diagnostics.hard_gate_active_ratio;
    end
    theta = cycle{:,{'Cs1_pF','Cs2_pF'}};
    appliedAll = [zeros(1,2);diff(theta,1,1)];
    applied = appliedAll(inWindow,:);
    diagnostics.rate_limit_cycles = sum(any(abs(applied) >= ...
        cfg.rate_limit_pF_per_cycle-1e-12,2));
    projectedTheta = theta(inWindow,:);
    diagnostics.projection_cycles = sum(any( ...
        projectedTheta <= cfg.coupling_bounds_pF(1)+1e-12 | ...
        projectedTheta >= cfg.coupling_bounds_pF(2)-1e-12,2));
else
    error('M5Step4:DiagnosticAlgorithm', ...
        'Unsupported diagnostic mapping for %s.',algorithmId);
end

[diagnostics.applied_parallel_update_energy_pF2, ...
    diagnostics.applied_perp_update_energy_pF2] = ...
    projected_energy(applied,faultDirection,perpendicularProjector);
end

function label = mapping_label(algorithmId)
if ismember(algorithmId,["GH","GC","M5_DH","M5_FULL"])
    label = "M5_STEP2_EXPLICIT_FIELDS";
elseif algorithmId == "M4"
    label = "M4_EXPLICIT_FIELDS_FIXED_DF_PROJECTION";
elseif algorithmId == "M3"
    label = "M3_GATE_EXPLICIT_CONSTRAINTS_INFERRED_FROM_STATE";
elseif algorithmId == "M2"
    label = "M2_CONSTRAINTS_INFERRED_FROM_STATE";
else
    label = "UNSUPPORTED";
end
end

function require_fields(cycle,names)
missing = setdiff(names,string(cycle.Properties.VariableNames));
if ~isempty(missing)
    error('M5Step4:CycleSchema', ...
        'Required cycle fields missing: %s.',strjoin(missing,','));
end
end

function [parallelEnergy,perpEnergy] = ...
        projected_energy(delta,faultDirection,perpendicularProjector)
parallelScalar = delta*faultDirection;
perpendicular = delta*perpendicularProjector;
parallelEnergy = sum(parallelScalar.^2);
perpEnergy = sum(perpendicular.^2,'all');
end

function output = blank_diagnostics()
output = struct( ...
    'schema_mapping',"", ...
    'cycle_count',NaN, ...
    'hard_gate_active_ratio',NaN, ...
    'mean_w_REW',NaN, ...
    'mean_selected_weight',NaN, ...
    'raw_parallel_update_energy_pF2',NaN, ...
    'raw_perp_update_energy_pF2',NaN, ...
    'applied_parallel_update_energy_pF2',NaN, ...
    'applied_perp_update_energy_pF2',NaN, ...
    'rate_limit_cycles',NaN, ...
    'projection_cycles',NaN, ...
    'near_zero_update_cycles',NaN, ...
    'mean_raw_angle_to_df_deg',NaN, ...
    'mean_protected_angle_to_df_deg',NaN, ...
    'mean_post_rate_angle_to_df_deg',NaN, ...
    'mean_post_projection_angle_to_df_deg',NaN);
end
