function audit = m5_step5_validate_matrix(matrixPath,registryPath)
%M5_STEP5_VALIDATE_MATRIX Validate the frozen Step5 robustness contract.

arguments
    matrixPath {mustBeTextScalar}
    registryPath {mustBeTextScalar}
end

matrix = readtable(matrixPath,'Delimiter',',','TextType','string', ...
    'VariableNamingRule','preserve');
registry = readtable(registryPath,'Delimiter',',','TextType','string', ...
    'VariableNamingRule','preserve');

required = ["matrix_version","preregistration_state", ...
    "simulation_status","physical_condition_id","evaluation_id", ...
    "geometry_pair_id","source_condition_id","source_registry_index", ...
    "source_mc_cohort","geometry","algorithm_id","truth_seed", ...
    "noise_seed","SNR_dB","reference_phase_error_deg", ...
    "fault_mode","fault_factor","fault_start_s","fault_ramp_up_s", ...
    "fault_ramp_end_s","fault_plateau_end_s","fault_ramp_down_s", ...
    "fault_end_s","relative_fault_onset","drift_rate_multiplier", ...
    "drift_start_s","drift_end_s","drift_duration_s","h3_ratio", ...
    "h3_phase_deg","negative_sequence_pu","Cself_truth_pF", ...
    "Cself_algorithm_pF","Cself_mismatch_pct","CsAC_truth_pF", ...
    "evaluation_window_set_id","simulation_stop_s", ...
    "Cs1_initial_pF","Cs2_initial_pF","drift_direction_Cs1", ...
    "drift_direction_Cs2","drift_delta_Cs1_pF", ...
    "drift_delta_Cs2_pF","drift_norm_pF","Cs1_final_pF", ...
    "Cs2_final_pF","base_nuisance_signature_sha256", ...
    "source_registry_sha256","model_sha256","config_sha256", ...
    "tracker_sha256","projector_sha256","regressor_sha256"];
missing = setdiff(required,string(matrix.Properties.VariableNames));
checks = struct();
checks.required_columns = isempty(missing);
checks.row_count = height(matrix) == 600;
checks.physical_count = numel(unique(matrix.physical_condition_id)) == 150;
checks.pair_count = numel(unique(matrix.geometry_pair_id)) == 50;
checks.evaluation_unique = numel(unique(matrix.evaluation_id)) == 600;
checks.status_not_run = all(matrix.simulation_status == "NOT_RUN");
checks.cohort_o = all(matrix.source_mc_cohort == "O");

geometries = ["ORTHOGONAL","MIXED","PARALLEL"];
algorithms = ["GH","GC","M5_DH","M5_FULL"];
checks.geometry_counts = true;
for geometry = geometries
    checks.geometry_counts = checks.geometry_counts && ...
        nnz(matrix.geometry == geometry) == 200;
end
checks.algorithm_counts = true;
for algorithm = algorithms
    checks.algorithm_counts = checks.algorithm_counts && ...
        nnz(matrix.algorithm_id == algorithm) == 150;
end

checks.physical_algorithm_map = true;
for id = unique(matrix.physical_condition_id,'stable').'
    part = matrix(matrix.physical_condition_id == id,:);
    checks.physical_algorithm_map = checks.physical_algorithm_map && ...
        height(part) == 4 && isequal(sort(part.algorithm_id),sort(algorithms).');
end

stringNuisance = ["source_condition_id","source_mc_cohort","noise_mode", ...
    "fault_mode","evaluation_window_set_id","base_nuisance_signature_sha256"];
numericNuisance = ["source_registry_index","truth_seed","noise_seed", ...
    "SNR_dB","reference_phase_error_deg","fault_factor", ...
    "fault_start_s","fault_ramp_up_s","fault_ramp_end_s", ...
    "fault_plateau_end_s","fault_ramp_down_s","fault_end_s", ...
    "relative_fault_onset","drift_rate_multiplier","drift_start_s", ...
    "drift_end_s","drift_duration_s","h3_ratio","h3_phase_deg", ...
    "negative_sequence_pu","Cself_truth_pF","Cself_algorithm_pF", ...
    "Cself_mismatch_pct","CsAC_truth_pF","simulation_stop_s", ...
    "Cs1_initial_pF","Cs2_initial_pF"];
checks.geometry_pairing = true;
for id = unique(matrix.geometry_pair_id,'stable').'
    part = matrix(matrix.geometry_pair_id == id,:);
    pass = height(part) == 12 && ...
        isequal(sort(unique(part.geometry)),sort(geometries).');
    for name = stringNuisance
        pass = pass && numel(unique(part.(name))) == 1;
    end
    for name = numericNuisance
        values = double(part.(name));
        pass = pass && all(isfinite(values)) && ...
            max(values)-min(values) <= 1e-12*max(1,max(abs(values)));
    end
    checks.geometry_pairing = checks.geometry_pairing && pass;
end

checks.geometry_values = true;
target = struct( ...
    'ORTHOGONAL',[1/sqrt(2),1/sqrt(2),sqrt(13/2),sqrt(13/2)], ...
    'MIXED',[3/sqrt(13),-2/sqrt(13),3,-2], ...
    'PARALLEL',[1/sqrt(2),-1/sqrt(2),sqrt(13/2),-sqrt(13/2)]);
for geometry = geometries
    part = matrix(matrix.geometry == geometry,:);
    values = target.(char(geometry));
    checks.geometry_values = checks.geometry_values && ...
        max(abs(double(part.drift_direction_Cs1)-values(1))) <= 1e-12 && ...
        max(abs(double(part.drift_direction_Cs2)-values(2))) <= 1e-12 && ...
        max(abs(double(part.drift_delta_Cs1_pF)-values(3))) <= 1e-12 && ...
        max(abs(double(part.drift_delta_Cs2_pF)-values(4))) <= 1e-12 && ...
        max(abs(double(part.drift_norm_pF)-sqrt(13))) <= 1e-12 && ...
        max(abs(double(part.Cs1_final_pF)- ...
            (double(part.Cs1_initial_pF)+values(3)))) <= 1e-12 && ...
        max(abs(double(part.Cs2_final_pF)- ...
            (double(part.Cs2_initial_pF)+values(4)))) <= 1e-12;
end

source = registry(registry.registry_kind == "MONTE_CARLO" & ...
    registry.mc_cohort == "O",:);
source = sortrows(source,'registry_index');
checks.source_registry_count = height(source) == 50 && ...
    isequal(double(source.registry_index),(1:50).');
sourceFields = ["truth_seed","noise_seed","SNR_dB", ...
    "reference_phase_error_deg","fault_factor","fault_start_s", ...
    "fault_ramp_up_s","fault_ramp_end_s","fault_plateau_end_s", ...
    "fault_ramp_down_s","fault_end_s","relative_fault_onset", ...
    "drift_rate_multiplier","drift_start_s","drift_end_s", ...
    "drift_duration_s","h3_ratio","h3_phase_deg", ...
    "negative_sequence_pu","Cself_truth_pF","Cself_algorithm_pF", ...
    "Cself_mismatch_pct","CsAC_truth_pF","simulation_stop_s", ...
    "Cs1_initial_pF","Cs2_initial_pF"];
sourceStringFields = ["noise_mode","fault_mode","evaluation_window_set_id"];
checks.source_registry_match = checks.source_registry_count;
for k = 1:height(source)
    base = source(k,:);
    part = matrix(matrix.source_condition_id == base.condition_id,:);
    pass = height(part) == 12 && ...
        all(double(part.source_registry_index) == double(base.registry_index));
    for name = sourceFields
        expected = double(base.(name));
        actual = double(part.(name));
        pass = pass && all(abs(actual-expected) <= ...
            1e-12*max(1,abs(expected)));
    end
    for name = sourceStringFields
        pass = pass && all(part.(name) == base.(name));
    end
    checks.source_registry_match = checks.source_registry_match && pass;
end

checks.seed_unique = numel(unique(matrix.truth_seed)) == 50 && ...
    numel(unique(matrix.noise_seed)) == 50;
checks.seed_distinct = all(matrix.truth_seed ~= matrix.noise_seed);
checks.hash_columns = ...
    all(matrix.source_registry_sha256 == ...
        "8A498E19A455C13CAA7B5371BE2F933CA7B7637B893C656C92DA84D88D1938BE") && ...
    all(matrix.model_sha256 == ...
        "56067ADAADF59B5921D7156A2ABB61777C4E98B69CB4150759C3CB1D4D6A2A70") && ...
    all(matrix.config_sha256 == ...
        "D9F3E6894F51C3D978421C9E1E93828A9205F418C77D01AC449B994A3D789726") && ...
    all(matrix.tracker_sha256 == ...
        "8B580215A6268F4AC3BF27FB357DB6A4A01027DD2410C7FF59EA3C4B46DA4DDB") && ...
    all(matrix.projector_sha256 == ...
        "47D2C12DB80F4BBFE7CE296841074DB6F3FF641CD769907666292E4398E06CA7") && ...
    all(matrix.regressor_sha256 == ...
        "7582F66875A1099DF9656F9A89FE12D8FF6972C55D4A034736527A7DB00E03D5");

names = fieldnames(checks);
values = false(numel(names),1);
for k = 1:numel(names), values(k) = logical(checks.(names{k})); end
audit = struct('pass',all(values),'checks',checks,'matrix',matrix, ...
    'failed_checks',string(names(~values)),'missing_columns',missing);
if ~audit.pass
    error('M5Step5:MatrixIntegrity','Step5 matrix audit failed: %s.', ...
        strjoin(audit.failed_checks,','));
end
end
