function audit = m5_step4_validate_matrix(matrixPath)
%M5_STEP4_VALIDATE_MATRIX Validate the frozen Step 3 execution matrix.

arguments
    matrixPath {mustBeTextScalar}
end

matrix = readtable(matrixPath,'Delimiter',',','TextType','string', ...
    'VariableNamingRule','preserve');
requiredColumns = [ ...
    "case_id","block","source_condition_id","fault_factor", ...
    "drift_geometry","drift_direction_Cs1","drift_direction_Cs2", ...
    "drift_delta_Cs1_pF","drift_delta_Cs2_pF","drift_norm_pF", ...
    "seed","snr_dB","model_sha256","algorithm", ...
    "algorithm_source_sha256","run_or_reuse", ...
    "expected_sim_calls_per_case","analysis_status"];
actualColumns = string(matrix.Properties.VariableNames);
missingColumns = setdiff(requiredColumns,actualColumns,'stable');

algorithms = ["M2";"M3";"M4";"GH";"GC";"M5_DH";"M5_FULL"];
caseIds = unique(matrix.case_id,'stable');
caseComplete = false(numel(caseIds),1);
caseUnique = false(numel(caseIds),1);
for k = 1:numel(caseIds)
    part = matrix(matrix.case_id == caseIds(k),:);
    caseComplete(k) = height(part) == 7 && ...
        isequal(sort(part.algorithm),sort(algorithms));
    caseUnique(k) = numel(unique(part.algorithm)) == height(part);
end

uniqueCases = matrix(~duplicated_case(matrix.case_id),:);
blockCounts = [ ...
    nnz(uniqueCases.block == "A"), ...
    nnz(uniqueCases.block == "B"), ...
    nnz(uniqueCases.block == "C")];
reuseCounts = [ ...
    nnz(matrix.run_or_reuse == "REUSE_FROZEN_RESULT"), ...
    nnz(matrix.run_or_reuse == ...
        "RECOMPUTE_NEW_METRICS_FROM_FROZEN_TRAJECTORY"), ...
    nnz(matrix.run_or_reuse == "RUN_NEW_TRACKER")];
simCalls = sum(uniqueCases.expected_sim_calls_per_case);

factorialAlgorithms = ["GH";"GC";"M5_DH";"M5_FULL"];
factorialComplete = true(numel(caseIds),1);
for k = 1:numel(caseIds)
    part = matrix(matrix.case_id == caseIds(k),:);
    factorialComplete(k) = all(ismember(factorialAlgorithms,part.algorithm));
end

blockC = uniqueCases(uniqueCases.block == "C",:);
geometryNames = sort(unique(blockC.drift_geometry));
directionNorm = hypot(blockC.drift_direction_Cs1, ...
    blockC.drift_direction_Cs2);
driftNorm = hypot(blockC.drift_delta_Cs1_pF, ...
    blockC.drift_delta_Cs2_pF);
geometryPass = isequal(geometryNames, ...
    sort(["MIXED_CASE06";"ORTHOGONAL";"PARALLEL"])) && ...
    all(abs(directionNorm-1) <= 1e-12) && ...
    all(abs(driftNorm-sqrt(13)) <= 1e-12) && ...
    all(abs(blockC.drift_norm_pF-sqrt(13)) <= 1e-12);

statusPass = all(matrix.analysis_status == "PREREGISTERED_NOT_RUN");
audit = struct( ...
    'matrix',matrix, ...
    'row_count',height(matrix), ...
    'case_count',numel(caseIds), ...
    'algorithm_count',numel(unique(matrix.algorithm)), ...
    'block_case_counts',blockCounts, ...
    'reuse_counts',reuseCounts, ...
    'expected_sim_calls',simCalls, ...
    'missing_columns',missingColumns, ...
    'case_algorithm_complete',all(caseComplete), ...
    'case_algorithm_unique',all(caseUnique), ...
    'factorial_complete',all(factorialComplete), ...
    'geometry_pass',geometryPass, ...
    'status_pass',statusPass);
audit.pass = isempty(missingColumns) && audit.row_count == 98 && ...
    audit.case_count == 14 && audit.algorithm_count == 7 && ...
    isequal(blockCounts,[2 6 6]) && ...
    isequal(reuseCounts,[24 6 68]) && simCalls == 34 && ...
    audit.case_algorithm_complete && audit.case_algorithm_unique && ...
    audit.factorial_complete && audit.geometry_pass && audit.status_pass;
end

function duplicate = duplicated_case(caseIds)
duplicate = false(numel(caseIds),1);
seen = strings(0,1);
for k = 1:numel(caseIds)
    duplicate(k) = any(seen == caseIds(k));
    seen(end+1,1) = caseIds(k); %#ok<AGROW>
end
end
