function smoke = run_phase1a_smoke_test()
%RUN_PHASE1A_SMOKE_TEST End-to-end historical smoke test for Case02/06.

matlabRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(matlabRoot);
outputRoot = fullfile(projectRoot,'paper_research','phase1a_baseline');
frozenMetadata = phase1a_baseline_metadata();
modelPath = fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx');
modelSha256 = file_sha256(modelPath);
if modelSha256 ~= frozenMetadata.baseline_model_sha256
    error('Phase1A:BaselineIntegrityFailure', ...
        'AutoComp9 SHA-256 does not match the frozen baseline.');
end

cfg = patent_default_config();
cfg.model = char(frozenMetadata.baseline_model);
self_pF = repmat(cfg.Cself_pF,1,3);
runMetadata = current_run_metadata(modelSha256);
caseRegistry = phase1a_case_registry();
case02Info = caseRegistry(caseRegistry.case_name == ...
    "Case02_slow_drift",:);
case06Info = caseRegistry(caseRegistry.case_name == ...
    "Case06_drift_then_fault",:);

case02 = run_case_once(case02Info,cfg,self_pF,runMetadata);
case06 = run_case_once(case06Info,cfg,self_pF,runMetadata);
resultSummary = [case02.metrics;case06.metrics];
historical = phase1a_historical_reference();
regression = build_regression_table( ...
    case02.metrics,case06.metrics,historical);

smoke = struct();
smoke.step4_checkpoint_commit = ...
    "ac657b407faea8dd2f88efea2e9bfc7769e6faee";
smoke.baseline_integrity = "PASS";
smoke.model_path = string(modelPath);
smoke.model_sha256 = modelSha256;
smoke.cfg = cfg;
smoke.metadata = runMetadata;
smoke.case02 = case02;
smoke.case06 = case06;
smoke.result_summary = resultSummary;
smoke.regression = regression;
smoke.case_simulation_calls = 2;
smoke.low_level_sim_invocations = 4;
smoke.low_level_run_note = ...
    "simulate_phase2_case is called once per case and internally calls sim twice.";
smoke.overall_pass = all(regression.pass);

workspacePath = fullfile(outputRoot,'step5_smoke_workspace.mat');
save(workspacePath,'smoke','-v7.3');
disp(resultSummary);
disp(regression);
fprintf('CASE_SIMULATION_CALLS=%d\n',smoke.case_simulation_calls);
fprintf('LOW_LEVEL_SIM_INVOCATIONS=%d\n',smoke.low_level_sim_invocations);
fprintf('STEP5_END_TO_END_SMOKE_TEST=%s\n', ...
    string(pass_label(smoke.overall_pass)));
if ~smoke.overall_pass
    error('Phase1A:SmokeRegressionFailure', ...
        'One or more frozen historical regressions failed.');
end
end

function result = run_case_once(caseInfo,cfg,self_pF,runMetadata)
tInput = (0:cfg.Ts:cfg.StopTime).';
signals = generate_coupling_signals( ...
    tInput,caseInfo.case_name,caseInfo.seed);
[data,~] = simulate_phase2_case(cfg, ...
    char(caseInfo.legacy_scenario_name),caseInfo.seed);
if numel(data.Cs1) ~= numel(signals.Cs1_pF) || ...
        numel(data.Cs2) ~= numel(signals.Cs2_pF)
    error('Phase1A:CaseSignalMismatch', ...
        'Simulated coupling truth length differs from the frozen generator.');
end
Cs1SignalDifference = max(abs(data.Cs1-signals.Cs1_pF));
Cs2SignalDifference = max(abs(data.Cs2-signals.Cs2_pF));
if Cs1SignalDifference > 1e-10 || Cs2SignalDifference > 1e-10
    error('Phase1A:CaseSignalMismatch', ...
        'Simulated coupling truth differs from the frozen case generator.');
end
ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
modes = phase1a_algorithm_registry().algorithm_mode;
algorithmResults = struct();
metrics = phase1a_result_schema().empty_result_table;
for k = 1:numel(modes)
    mode = modes(k);
    algorithmResults.(mode) = run_phase1a_algorithm( ...
        mode,data,ref,cfg,self_pF);
    metrics = [metrics;evaluate_phase1a_metrics( ...
        caseInfo,algorithmResults.(mode),data,cfg,runMetadata)]; %#ok<AGROW>
end
result = struct('case_info',caseInfo,'signals',signals, ...
    'data',data,'ref',ref,'algorithms',algorithmResults, ...
    'metrics',metrics,'Cs1_signal_max_abs_diff_pF',Cs1SignalDifference, ...
    'Cs2_signal_max_abs_diff_pF',Cs2SignalDifference);
end

function regression = build_regression_table(case02,case06,reference)
rows = [ ...
    regression_row("Case02_slow_drift","M0", ...
        "B_resistive_fundamental_error_pct", ...
        reference.Case02_slow_drift.M0. ...
        B_resistive_fundamental_error_pct, ...
        metric_value(case02,"M0", ...
        "B_resistive_fundamental_error_pct"),reference)
    regression_row("Case02_slow_drift","M3", ...
        "B_resistive_fundamental_error_pct", ...
        reference.Case02_slow_drift.M3. ...
        B_resistive_fundamental_error_pct, ...
        metric_value(case02,"M3", ...
        "B_resistive_fundamental_error_pct"),reference)
    regression_row("Case02_slow_drift","M3","Cs1_RMSE_pF", ...
        reference.Case02_slow_drift.M3.Cs1_RMSE_pF, ...
        metric_value(case02,"M3","Cs1_RMSE_pF"),reference)
    regression_row("Case02_slow_drift","M3","Cs2_RMSE_pF", ...
        reference.Case02_slow_drift.M3.Cs2_RMSE_pF, ...
        metric_value(case02,"M3","Cs2_RMSE_pF"),reference)
    regression_row("Case06_drift_then_fault","TRUTH", ...
        "fault_factor_true", ...
        reference.Case06_drift_then_fault.fault_factor_true, ...
        metric_value(case06,"M0","fault_factor_true"),reference)
    regression_row("Case06_drift_then_fault","M2", ...
        "Cs1_pre_post_change_pF", ...
        reference.Case06_drift_then_fault.M2. ...
        Cs1_pre_post_change_pF, ...
        metric_value(case06,"M2","Cs1_pre_post_change_pF"),reference)
    regression_row("Case06_drift_then_fault","M2", ...
        "Cs2_pre_post_change_pF", ...
        reference.Case06_drift_then_fault.M2. ...
        Cs2_pre_post_change_pF, ...
        metric_value(case06,"M2","Cs2_pre_post_change_pF"),reference)
    regression_row("Case06_drift_then_fault","M2", ...
        "fault_factor_est", ...
        reference.Case06_drift_then_fault.M2.fault_factor_est, ...
        metric_value(case06,"M2","fault_factor_est"),reference)
    regression_row("Case06_drift_then_fault","M3", ...
        "Cs1_pre_post_change_pF", ...
        reference.Case06_drift_then_fault.M3. ...
        Cs1_pre_post_change_pF, ...
        metric_value(case06,"M3","Cs1_pre_post_change_pF"),reference)
    regression_row("Case06_drift_then_fault","M3", ...
        "Cs2_pre_post_change_pF", ...
        reference.Case06_drift_then_fault.M3. ...
        Cs2_pre_post_change_pF, ...
        metric_value(case06,"M3","Cs2_pre_post_change_pF"),reference)
    regression_row("Case06_drift_then_fault","M3", ...
        "fault_factor_est", ...
        reference.Case06_drift_then_fault.M3.fault_factor_est, ...
        metric_value(case06,"M3","fault_factor_est"),reference)
    ];
regression = vertcat(rows{:});
end

function row = regression_row(caseName,algorithmMode,metricName, ...
        historicalValue,newValue,reference)
absoluteDifference = abs(newValue-historicalValue);
relativeDifference = absoluteDifference/(abs(historicalValue)+eps);
absoluteTolerance = reference.absolute_tolerance;
relativeTolerance = reference.relative_tolerance;
passed = absoluteDifference <= ...
    absoluteTolerance+relativeTolerance*abs(historicalValue);
row = {table(caseName,algorithmMode,metricName,historicalValue,newValue, ...
    absoluteDifference,relativeDifference,absoluteTolerance, ...
    relativeTolerance,passed, ...
    'VariableNames',{'case_name','algorithm_mode','metric_name', ...
    'historical_value','new_value','absolute_difference', ...
    'relative_difference','absolute_tolerance','relative_tolerance', ...
    'pass'})};
end

function value = metric_value(metrics,mode,metricName)
row = metrics.algorithm_mode == mode;
if nnz(row) ~= 1
    error('Phase1A:MissingSmokeMetric', ...
        'Expected one metric row for algorithm %s.',mode);
end
value = metrics.(metricName)(row);
end

function metadata = current_run_metadata(modelSha256)
[commitStatus,gitCommit] = system('git rev-parse HEAD');
[branchStatus,gitBranch] = system('git branch --show-current');
[statusCode,gitStatus] = system( ...
    'git status --short --untracked-files=all');
if commitStatus ~= 0 || branchStatus ~= 0 || statusCode ~= 0
    error('Phase1A:GitMetadataFailure', ...
        'Unable to read Git metadata for the smoke test.');
end
dirtyStatus = "CLEAN";
if strlength(strtrim(string(gitStatus))) > 0
    dirtyStatus = "DIRTY";
end
metadata = struct( ...
    'model_sha256',modelSha256, ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',strtrim(string(gitCommit)), ...
    'git_branch',strtrim(string(gitBranch)), ...
    'git_dirty_status',dirtyStatus, ...
    'matlab_version',string(version), ...
    'simulink_version',string(ver('simulink').Version), ...
    'platform',string(computer));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1A:HashFailure','Unable to compute AutoComp9 SHA-256.');
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function label = pass_label(value)
if value
    label = "PASS";
else
    label = "FAIL";
end
end
