function output = run_phase2_gate_validation(action,request)
%RUN_PHASE2_GATE_VALIDATION Phase 2 Step 2A execution and gate validation.
% This wrapper separates physical truth from algorithm assumptions and
% delegates all frozen estimation work to the existing Phase 1 functions.
%
% Default:
%   run_phase2_gate_validation
%
% Reusable common-runner entry (after Step 2A authorization):
%   run_phase2_gate_validation("execute",request)
% request fields: case_name, Cself_truth_pF, Cself_algorithm_pF,
% CsAC_pF, algorithms. The execute entry currently supports the frozen
% legacy Case01--Case06 paths; Case08 remains an internal paired anchor.

if nargin < 1 || isempty(action)
    action = "validate_gates";
end
action = lower(string(action));
if ~isscalar(action)
    error('Phase2:Step2AAction','Action must be a scalar string.');
end

matlabRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(matlabRoot);
paths = phase2_paths(projectRoot,matlabRoot);
add_required_paths(paths);

if action == "execute"
    if nargin < 2 || ~isstruct(request) || ~isscalar(request)
        error('Phase2:Step2ARequest', ...
            'The execute action requires one scalar request struct.');
    end
    integrity = capture_frozen_integrity(paths);
    if ~integrity.pass
        error('Phase2:FrozenIntegrity', ...
            'Frozen integrity failed; the common runner is unavailable.');
    end
    output = execute_legacy_request(paths,normalize_request(request));
    return
elseif action ~= "validate_gates"
    error('Phase2:Step2AAction','Unsupported action: %s.',action);
end

if ~isfolder(paths.output_root)
    mkdir(paths.output_root);
end
records = empty_records();
pre = capture_frozen_integrity(paths);
preTag = integrity_tag(pre);
records = append_integrity_records(records,pre,"PRE",preTag,"");

commonPass = false;
cselfPass = false;
csacPass = false;
details = struct();
details.error = "";
details.anchor_algorithm_evaluations = 0;
details.case08_branch_runs = 0;
details.optional_linearity_pass = false;

if pre.pass
    try
        [commonRecords,common,commonPass,commonDetails] = ...
            validate_common_runner(paths);
        records = [records;commonRecords];
        details.common = commonDetails;
        details.anchor_algorithm_evaluations = 11;
        details.case08_branch_runs = 2;

        if commonPass
            [cselfRecords,cselfPass,cselfDetails] = ...
                validate_cself_split(paths,common);
            records = [records;cselfRecords];
            details.cself = cselfDetails;

            [csacRecords,csacPass,csacDetails] = ...
                validate_csac_wrapper(common);
            records = [records;csacRecords];
            details.csac = csacDetails;
            details.optional_linearity_pass = ...
                csacDetails.optional_linearity_pass;
        else
            records = append_not_run(records, ...
                "CSELF_SPLIT_INTERFACE_GATE", ...
                "COMMON_RUNNER_EQUIVALENCE_GATE failed");
            records = append_not_run(records, ...
                "ZERO_INJECTION_REGRESSION", ...
                "COMMON_RUNNER_EQUIVALENCE_GATE failed");
        end
    catch exception
        details.error = string(getReport(exception,'extended', ...
            'hyperlinks','off'));
        records = add_record(records,"STEP2A_EXCEPTION", ...
            "COMMON_RUNNER_EQUIVALENCE_GATE","N/A","N/A", ...
            "EXECUTION_EXCEPTION",NaN,NaN,NaN,"runner", ...
            "exception_free_execution",1,0,0,false, ...
            string(exception.identifier)+": "+string(exception.message));
        commonPass = false;
        cselfPass = false;
        csacPass = false;
    end
else
    details.error = "PRE frozen integrity check failed; no simulation executed.";
    records = append_not_run(records, ...
        "COMMON_RUNNER_EQUIVALENCE_GATE",details.error);
    records = append_not_run(records, ...
        "CSELF_SPLIT_INTERFACE_GATE",details.error);
    records = append_not_run(records, ...
        "ZERO_INJECTION_REGRESSION",details.error);
end

post = capture_frozen_integrity(paths);
postTag = integrity_tag(post);
records = append_integrity_records(records,post,"POST",preTag,postTag);
sourcePass = pre.pass && post.pass && ...
    isequal(pre.actual_sha256,post.actual_sha256);

records.frozen_hash_pre(:) = preTag;
records.frozen_hash_post(:) = postTag;
gate = struct( ...
    'source',sourcePass, ...
    'common',commonPass, ...
    'cself',cselfPass, ...
    'csac',csacPass);
[readyCount,pendingCount] = authorized_condition_counts( ...
    paths.condition_registry,gate);
status = final_status(gate);

writetable(records,paths.results_csv);
write_report(paths,records,pre,post,gate,status, ...
    readyCount,pendingCount,details);

output = struct( ...
    'status',status, ...
    'gates',gate, ...
    'ready_condition_count',readyCount, ...
    'pending_or_blocked_condition_count',pendingCount, ...
    'results_csv',string(paths.results_csv), ...
    'report',string(paths.report), ...
    'full_matrix_executed',false);

fprintf('NO_FROZEN_SOURCE_DIFF_GATE=%s\n',pass_label(gate.source));
fprintf('COMMON_RUNNER_EQUIVALENCE_GATE=%s\n',pass_label(gate.common));
fprintf('CSELF_SPLIT_INTERFACE_GATE=%s\n',pass_label(gate.cself));
fprintf('ZERO_INJECTION_REGRESSION=%s\n',pass_label(gate.csac));
fprintf('STEP2A_STATUS=%s\n',status);
fprintf('READY_CONDITION_COUNT=%d\n',readyCount);
fprintf('PENDING_OR_BLOCKED_CONDITION_COUNT=%d\n',pendingCount);
fprintf('STEP2A_RESULTS=%s\n',paths.results_csv);
fprintf('STEP2A_REPORT=%s\n',paths.report);
end

function paths = phase2_paths(projectRoot,matlabRoot)
phase1cRoot = fullfile(projectRoot,'paper_research','phase1c_m4_method');
step1Root = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step1_matrix_spec');
paths = struct( ...
    'project_root',projectRoot, ...
    'matlab_root',matlabRoot, ...
    'phase1c_root',phase1cRoot, ...
    'step1_root',step1Root, ...
    'step3_root',fullfile(phase1cRoot,'step3_normal_tracking'), ...
    'step4_root',fullfile(phase1cRoot,'step4_fault_preservation'), ...
    'step5_root',fullfile(phase1cRoot, ...
        'step5_simultaneous_drift_fault'), ...
    'step5b_root',fullfile(phase1cRoot,'step5b_triggered_overlap'), ...
    'manifest',fullfile(phase1cRoot,'step6_ablation','tables', ...
        'freeze_hash_manifest.csv'), ...
    'specification',fullfile(step1Root, ...
        'STEP1_PHASE2_MATRIX_SPECIFICATION.md'), ...
    'condition_registry',fullfile(step1Root, ...
        'phase2_condition_registry.csv'), ...
    'execution_registry',fullfile(step1Root, ...
        'phase2_execution_registry.csv'), ...
    'output_root',fullfile(projectRoot,'paper_research', ...
        'phase2_full_validation','step2a_execution_gates'));
paths.results_csv = fullfile(paths.output_root,'step2a_gate_results.csv');
paths.report = fullfile(paths.output_root, ...
    'STEP2A_EXECUTION_GATES_REPORT.md');
end

function add_required_paths(paths)
addpath(paths.matlab_root);
addpath(paths.step3_root);
addpath(paths.step4_root);
addpath(paths.step5_root);
addpath(paths.step5b_root);
end

function request = normalize_request(request)
required = ["case_name","Cself_truth_pF","Cself_algorithm_pF", ...
    "CsAC_pF","algorithms"];
for name = required
    if ~isfield(request,char(name))
        error('Phase2:Step2ARequest','Missing request field %s.',name);
    end
end
request.case_name = string(request.case_name);
request.algorithms = string(request.algorithms(:));
numericNames = ["Cself_truth_pF","Cself_algorithm_pF","CsAC_pF"];
for name = numericNames
    value = request.(char(name));
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
        error('Phase2:Step2ARequest','%s must be finite scalar.',name);
    end
end
if request.CsAC_pF ~= 0
    error('Phase2:Step2ARequest', ...
        ['The public execute action enables nonzero CsAC only after ' ...
         'a future registry-driven runner calls the validated wrapper.']);
end
end

function integrity = capture_frozen_integrity(paths)
manifest = read_csv_table(paths.manifest);
countPhase1 = height(manifest);
labels = strings(countPhase1+3,1);
filePaths = strings(countPhase1+3,1);
expected = strings(countPhase1+3,1);
actual = strings(countPhase1+3,1);
mode = repmat("RAW_SHA256",countPhase1+3,1);

for k = 1:countPhase1
    labels(k) = "PHASE1_MANIFEST:"+manifest.roles(k)+":"+ ...
        manifest.relative_path(k);
    filePaths(k) = fullfile(paths.project_root, ...
        char(manifest.relative_path(k)));
    expected(k) = upper(manifest.sha256(k));
    actual(k) = file_sha256(filePaths(k));
end

labels(countPhase1+1) = "STEP1_SPECIFICATION";
filePaths(countPhase1+1) = paths.specification;
expected(countPhase1+1) = ...
    "9FAB573BCE6D5D0A1F3F6A569771F5B1C69706AB6E6E38FD97843BF41B931531";
actual(countPhase1+1) = canonical_specification_sha256( ...
    paths.specification);
mode(countPhase1+1) = "CANONICAL_SELF_HASH";

labels(countPhase1+2) = "STEP1_CONDITION_REGISTRY";
filePaths(countPhase1+2) = paths.condition_registry;
expected(countPhase1+2) = ...
    "8A498E19A455C13CAA7B5371BE2F933CA7B7637B893C656C92DA84D88D1938BE";
actual(countPhase1+2) = file_sha256(filePaths(countPhase1+2));

labels(countPhase1+3) = "STEP1_EXECUTION_REGISTRY";
filePaths(countPhase1+3) = paths.execution_registry;
expected(countPhase1+3) = ...
    "974B8874404C46C4B549CAD8E2D52CCCC7F1D4F81D68AF8911201307230394D7";
actual(countPhase1+3) = file_sha256(filePaths(countPhase1+3));

pass = expected == actual;
integrity = struct( ...
    'labels',labels, ...
    'paths',filePaths, ...
    'modes',mode, ...
    'expected_sha256',expected, ...
    'actual_sha256',actual, ...
    'item_pass',pass, ...
    'phase1_count',countPhase1, ...
    'phase1_pass_count',nnz(pass(1:countPhase1)), ...
    'step1_pass_count',nnz(pass(countPhase1+1:end)), ...
    'pass',all(pass));
end

function hash = canonical_specification_sha256(path)
textValue = fileread(path);
pattern = '(specification_sha256_canonical:\s*)[0-9A-Fa-f]{64}';
replacement = '$1<SELF_SHA256_CANONICAL_PLACEHOLDER>';
canonical = regexprep(textValue,pattern,replacement,'once');
if strcmp(canonical,textValue)
    error('Phase2:CanonicalHash', ...
        'Specification canonical self-hash field was not found.');
end
hash = bytes_sha256(unicode2native(canonical,'UTF-8'));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase2:HashRead','Unable to open %s.',path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
hash = bytes_sha256(bytes);
end

function hash = bytes_sha256(bytes)
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(uint8(bytes));
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function tag = integrity_tag(integrity)
tag = sprintf('%d/%d %s',nnz(integrity.item_pass), ...
    numel(integrity.item_pass),pass_label(integrity.pass));
end

function records = append_integrity_records( ...
        records,integrity,variant,preTag,postTag)
for k = 1:numel(integrity.labels)
    records = add_record(records, ...
        "HASH_"+variant+"_"+compose('%02d',k), ...
        "NO_FROZEN_SOURCE_DIFF_GATE","N/A","N/A",variant, ...
        NaN,NaN,NaN,string(integrity.paths(k)), ...
        integrity.modes(k),NaN,NaN,0,integrity.item_pass(k), ...
        "expected="+integrity.expected_sha256(k)+ ...
        "; actual="+integrity.actual_sha256(k));
end
if strlength(preTag) > 0
    records.frozen_hash_pre(:) = preTag;
end
if strlength(postTag) > 0
    records.frozen_hash_post(:) = postTag;
end
end

function [records,common,gatePass,details] = validate_common_runner(paths)
records = empty_records();
tol = 1e-12;
truthTol = 1e-10;

request02 = standard_request("Case02_slow_drift",400,400,0, ...
    ["M0" "M2" "M3" "M4"]);
request05 = standard_request("Case05_fault_only",400,400,0, ...
    ["M0" "M2" "M3" "M4"]);
common.case02 = execute_legacy_request(paths,request02);
common.case05 = execute_legacy_request(paths,request05);
common.case08 = execute_case08_anchor(paths);

baseline = load(fullfile(paths.project_root,'paper_research', ...
    'phase1a_baseline','baseline_workspace.mat'), ...
    'caseData','algorithmResults');
step3 = load(fullfile(paths.step3_root,'workspace', ...
    'normal_tracking_workspace.mat'),'caseDetails');
step4 = load(fullfile(paths.step4_root,'workspace', ...
    'fault_preservation_workspace.mat'),'caseDetails');
step5b = load(fullfile(paths.step5b_root,'workspace', ...
    'case08_step5b_workspace.mat'),'caseDetail');

baselineTable = read_csv_table(fullfile(paths.project_root,'paper_research', ...
    'phase1a_baseline','baseline_summary.csv'));
normalTable = read_csv_table(fullfile(paths.step3_root,'tables', ...
    'normal_tracking_summary.csv'));
faultTable = read_csv_table(fullfile(paths.step4_root,'tables', ...
    'fault_preservation_summary.csv'));

% Case02: M0--M3 use the Phase 1A workspace; M4 uses Phase 1C Step 3.
for mode = ["M0" "M2" "M3" "M4"]
    current = common.case02.results.(char(mode));
    if mode == "M4"
        detail = step3.caseDetails.Case02_slow_drift;
        frozenCHist = detail.M4_cHist;
        frozenIrB = detail.M4_irB;
        frozenCycle = detail.M4_cycle;
        formal = normalTable(normalTable.case_name == ...
            "Case02_slow_drift" & normalTable.algorithm_mode == mode,:);
    else
        detail = baseline.algorithmResults.Case02_slow_drift.(char(mode));
        frozenCHist = detail.cHist;
        frozenIrB = detail.irB;
        if isfield(detail,'cycle'), frozenCycle = detail.cycle;
        else, frozenCycle = table(); end
        formal = baselineTable(baselineTable.case_name == ...
            "Case02_slow_drift" & baselineTable.algorithm_mode == mode,:);
    end
    records = compare_algorithm_trajectory(records,"C02_"+mode, ...
        "Case02_slow_drift",mode,current,frozenCHist,frozenIrB,tol);
    records = compare_cycle_state(records,"C02_"+mode, ...
        "Case02_slow_drift",mode,current,frozenCycle,tol);
    evaluated = evaluate_phase1a_metrics(common.case02.case_info, ...
        current,common.case02.data,common.case02.algorithm_cfg, ...
        common.case02.metadata);
    for metric = ["Cs1_RMSE_pF" "Cs2_RMSE_pF" ...
            "B_resistive_fundamental_error_pct"]
        records = compare_scalar(records,"C02_"+mode+"_"+metric, ...
            "COMMON_RUNNER_EQUIVALENCE_GATE","Case02_slow_drift", ...
            mode,"NOMINAL",400,400,0,"formal primary metric",metric, ...
            formal.(char(metric)),evaluated.(char(metric)),tol,"");
    end
end

truth02 = baseline.caseData.Case02_slow_drift;
records = compare_scalar(records,"C02_TRUTH_CS1", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE","Case02_slow_drift","ALL", ...
    "NOMINAL",400,400,0,"physical truth","Cs1 trajectory max diff", ...
    0,max(abs(common.case02.data.Cs1-truth02.Cs1_true)),truthTol,"");
records = compare_scalar(records,"C02_TRUTH_CS2", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE","Case02_slow_drift","ALL", ...
    "NOMINAL",400,400,0,"physical truth","Cs2 trajectory max diff", ...
    0,max(abs(common.case02.data.Cs2-truth02.Cs2_true)),truthTol,"");

% Case05: M0--M3 use the Phase 1A workspace; M4 uses Phase 1C Step 4.
for mode = ["M0" "M2" "M3" "M4"]
    current = common.case05.results.(char(mode));
    if mode == "M4"
        detail = step4.caseDetails.Case05_fault_only;
        frozenCHist = detail.M4_cHist;
        frozenIrB = detail.M4_irB;
        frozenCycle = detail.M4_cycle;
        formal = faultTable(faultTable.case_name == ...
            "Case05_fault_only" & faultTable.algorithm_mode == mode,:);
    else
        detail = baseline.algorithmResults.Case05_fault_only.(char(mode));
        frozenCHist = detail.cHist;
        frozenIrB = detail.irB;
        if mode == "M3"
            frozenCycle = step4.caseDetails.Case05_fault_only.M3_cycle;
        elseif isfield(detail,'cycle')
            frozenCycle = detail.cycle;
        else
            frozenCycle = table();
        end
        formal = baselineTable(baselineTable.case_name == ...
            "Case05_fault_only" & baselineTable.algorithm_mode == mode,:);
    end
    records = compare_algorithm_trajectory(records,"C05_"+mode, ...
        "Case05_fault_only",mode,current,frozenCHist,frozenIrB,tol);
    records = compare_cycle_state(records,"C05_"+mode, ...
        "Case05_fault_only",mode,current,frozenCycle,tol);
    evaluated = evaluate_phase1a_metrics(common.case05.case_info, ...
        current,common.case05.data,common.case05.algorithm_cfg, ...
        common.case05.metadata);
    records = compare_scalar(records,"C05_"+mode+"_FACTOR", ...
        "COMMON_RUNNER_EQUIVALENCE_GATE","Case05_fault_only",mode, ...
        "NOMINAL",400,400,0,"formal primary metric", ...
        "fault_factor_est",formal.fault_factor_est, ...
        evaluated.fault_factor_est,tol,"");
    if mode ~= "M4"
        for metric = ["Cs1_RMSE_pF" "Cs2_RMSE_pF" ...
                "B_resistive_fundamental_error_pct"]
            records = compare_scalar(records, ...
                "C05_"+mode+"_"+metric, ...
                "COMMON_RUNNER_EQUIVALENCE_GATE", ...
                "Case05_fault_only",mode,"NOMINAL",400,400,0, ...
                "formal primary metric",metric,formal.(char(metric)), ...
                evaluated.(char(metric)),tol,"");
        end
    end
end

% Case08 paired F/CF anchor; no M0 historical-equivalence claim.
for mode = ["M2" "M3" "M4"]
    currentF = common.case08.resultsF.(char(mode));
    currentCF = common.case08.resultsCF.(char(mode));
    frozenF = step5b.caseDetail.(char(mode+"_cHist_F"));
    frozenCF = step5b.caseDetail.(char(mode+"_cHist_CF"));
    frozenIrBF = step5b.caseDetail.(char(mode+"_irB_F"));
    frozenIrBCF = step5b.caseDetail.(char(mode+"_irB_CF"));
    records = compare_algorithm_trajectory(records,"C08_F_"+mode, ...
        "Case08_overlap_drift_fault_f160",mode,currentF, ...
        frozenF,frozenIrBF,tol);
    records = compare_algorithm_trajectory(records,"C08_CF_"+mode, ...
        "Case08_overlap_drift_fault_f160",mode,currentCF, ...
        frozenCF,frozenIrBCF,tol);
    if mode == "M3"
        frozenCycle = step5b.caseDetail.M3_cycle_F;
    elseif mode == "M4"
        frozenCycle = step5b.caseDetail.M4_cycle_F;
    else
        frozenCycle = table();
    end
    records = compare_cycle_state(records,"C08_"+mode, ...
        "Case08_overlap_drift_fault_f160",mode,currentF, ...
        frozenCycle,tol);
end

records = compare_case08_metrics(records,paths,common.case08,tol);
gatePass = all(records.pass);
details = struct( ...
    'case02_seed',common.case02.case_info.seed, ...
    'case05_seed',common.case05.case_info.seed, ...
    'case08_seed',common.case08.definition.seed, ...
    'anchor_algorithm_evaluations',11, ...
    'case08_matched_branches',2, ...
    'row_count',height(records), ...
    'pass_count',nnz(records.pass), ...
    'max_numeric_difference',max(records.absolute_difference,[], ...
        'omitmissing'));
end

function request = standard_request(caseName,truthCself,algorithmCself, ...
        csac,algorithms)
request = struct( ...
    'case_name',string(caseName), ...
    'Cself_truth_pF',truthCself, ...
    'Cself_algorithm_pF',algorithmCself, ...
    'CsAC_pF',csac, ...
    'algorithms',string(algorithms(:)));
end

function run = execute_legacy_request(paths,request)
if request.CsAC_pF ~= 0
    error('Phase2:LegacyCsAC', ...
        'Nonzero CsAC requires the validated external wrapper path.');
end
registry = phase1a_case_registry();
row = registry.case_name == request.case_name;
if nnz(row) ~= 1
    error('Phase2:LegacyCase', ...
        'Common legacy runner supports one frozen Case01--Case06 case.');
end
caseInfo = registry(row,:);
physicalCfg = patent_default_config();
physicalCfg.model = 'AI6109_MOA_AutoComp9';
physicalCfg.Cself_pF = request.Cself_truth_pF;
algorithmCfg = physicalCfg;
algorithmCfg.Cself_pF = request.Cself_algorithm_pF;

[data,matlabReference] = simulate_phase2_case(physicalCfg, ...
    char(caseInfo.legacy_scenario_name),caseInfo.seed);
ref = reconstruct_refs_from_b(data.t,data.ub,algorithmCfg.f, ...
    algorithmCfg.init_start,algorithmCfg.init_end, ...
    algorithmCfg.phase_error_deg);
[results,inputSignatures] = run_algorithms( ...
    request.algorithms,data,ref,algorithmCfg, ...
    request.Cself_algorithm_pF);
run = struct( ...
    'request',request, ...
    'case_info',caseInfo, ...
    'physical_cfg',physicalCfg, ...
    'algorithm_cfg',algorithmCfg, ...
    'physical_truth_config',struct( ...
        'Cself_truth_pF',request.Cself_truth_pF, ...
        'CsAC_truth_pF',request.CsAC_pF), ...
    'algorithm_assumption_config',struct( ...
        'Cself_algorithm_pF',request.Cself_algorithm_pF), ...
    'data',data, ...
    'matlab_reference',matlabReference, ...
    'ref',ref, ...
    'results',results, ...
    'input_signatures',inputSignatures, ...
    'data_signature',data_signature(data), ...
    'metadata',minimal_metadata(paths));
end

function [results,signatures] = run_algorithms( ...
        modes,data,ref,cfg,algorithmCself)
results = struct();
signatures = strings(numel(modes),1);
signature = data_signature(data);
selfPF = repmat(algorithmCself,1,3);
for k = 1:numel(modes)
    mode = upper(string(modes(k)));
    results.(char(mode)) = run_phase1a_algorithm( ...
        mode,data,ref,cfg,selfPF);
    signatures(k) = signature;
end
end

function metadata = minimal_metadata(paths)
metadata = struct( ...
    'model_sha256',file_sha256(fullfile(paths.matlab_root, ...
        'AI6109_MOA_AutoComp9.slx')), ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
        'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',"STEP2A_GATE_VALIDATION", ...
    'git_branch',"N/A", ...
    'git_dirty_status',"RECORDED_SEPARATELY");
end

function signature = data_signature(data)
names = {'t','ua','ub','uc','ia','ib','ic','irA','irB','irC','Cs1','Cs2'};
digester = java.security.MessageDigest.getInstance('SHA-256');
for k = 1:numel(names)
    bytes = typecast(double(data.(names{k})(:)),'uint8');
    digester.update(bytes);
end
hashBytes = typecast(digester.digest(),'uint8');
signature = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function anchor = execute_case08_anchor(paths)
saved = load(fullfile(paths.step5b_root,'workspace', ...
    'case08_step5b_workspace.mat'),'caseDetail');
definition = phase1c_case08_definition();
cfg = patent_default_config();
cfg.model = char(definition.model);
cfg.StopTime = definition.simulation_duration_s;
cfg.SNR_dB = definition.snr_db;
noise = struct( ...
    'A',saved.caseDetail.shared_noise_A, ...
    'B',saved.caseDetail.shared_noise_B, ...
    'C',saved.caseDetail.shared_noise_C);
time = (0:cfg.Ts:cfg.StopTime).';
signalsF = build_phase1c_case08_signals(time,definition,"F");
signalsCF = build_phase1c_case08_signals(time,definition,"CF");
dataF = simulate_phase1c_case08(cfg,signalsF,noise);
dataCF = simulate_phase1c_case08(cfg,signalsCF,noise);
ref = reconstruct_refs_from_b(dataF.t,dataF.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
[resultsF,~] = run_algorithms(definition.algorithms,dataF,ref,cfg,400);
[resultsCF,~] = run_algorithms(definition.algorithms,dataCF,ref,cfg,400);
case07 = load(fullfile(paths.step5_root,'workspace', ...
    'case07_step5_workspace.mat'),'evaluated');
evaluated = evaluate_phase1c_step5b_case(definition,cfg,dataF,dataCF, ...
    resultsF,resultsCF,case07.evaluated);
anchor = struct( ...
    'definition',definition,'cfg',cfg,'noise',noise, ...
    'signalsF',signalsF,'signalsCF',signalsCF, ...
    'dataF',dataF,'dataCF',dataCF,'ref',ref, ...
    'resultsF',resultsF,'resultsCF',resultsCF, ...
    'evaluated',evaluated);
end

function records = compare_algorithm_trajectory(records,idPrefix,caseName, ...
        mode,current,frozenCHist,frozenIrB,tol)
records = compare_scalar(records,idPrefix+"_CS_TRAJECTORY", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
    400,400,0,"frozen trajectory","Cs1/Cs2 max abs difference", ...
    0,max(abs(current.cHist-frozenCHist),[],'all'),tol,"");
records = compare_scalar(records,idPrefix+"_IRB_TRAJECTORY", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
    400,400,0,"frozen trajectory","irB max abs difference A", ...
    0,max(abs(current.ir.B-frozenIrB)),tol,"");
records = compare_scalar(records,idPrefix+"_FINAL_CS1", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
    400,400,0,"frozen final state","final Cs1 pF", ...
    frozenCHist(end,1),current.cHist(end,1),tol,"");
records = compare_scalar(records,idPrefix+"_FINAL_CS2", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
    400,400,0,"frozen final state","final Cs2 pF", ...
    frozenCHist(end,2),current.cHist(end,2),tol,"");
end

function records = compare_cycle_state(records,idPrefix,caseName,mode, ...
        current,frozenCycle,tol)
if isempty(frozenCycle) || ~istable(frozenCycle) || height(frozenCycle) == 0
    records = add_record(records,idPrefix+"_STATE_NA", ...
        "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
        400,400,0,"frozen state evidence","state trajectory", ...
        NaN,NaN,tol,true,"NOT_AVAILABLE_IN_FROZEN_EVIDENCE");
    return
end
if ~isfield(current,'tracker') || ~isfield(current.tracker,'cycle')
    records = add_record(records,idPrefix+"_STATE_MISSING", ...
        "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
        400,400,0,"frozen state evidence","state trajectory", ...
        0,Inf,tol,false,"Current tracker state is missing.");
    return
end
currentCycle = current.tracker.cycle;
for name = ["lambda" "gate" "update_weight"]
    if ismember(name,string(frozenCycle.Properties.VariableNames)) && ...
            ismember(name,string(currentCycle.Properties.VariableNames))
        difference = max(abs(currentCycle.(char(name))- ...
            frozenCycle.(char(name))));
        records = compare_scalar(records,idPrefix+"_STATE_"+upper(name), ...
            "COMMON_RUNNER_EQUIVALENCE_GATE",caseName,mode,"NOMINAL", ...
            400,400,0,"frozen algorithm state",name+" max abs difference", ...
            0,difference,tol,"");
    end
end
end

function records = compare_case08_metrics(records,paths,anchor,tol)
gateTable = read_csv_table(fullfile(paths.step5b_root,'tables', ...
    'gate_interval_summary.csv'));
movement = read_csv_table(fullfile(paths.step5b_root,'tables', ...
    'gate_interval_adaptation.csv'));
retention = read_csv_table(fullfile(paths.step5b_root,'tables', ...
    'fault_increment_preservation.csv'));
current = anchor.evaluated;
records = compare_scalar(records,"C08_M3_GATE_ACTIVE_RATIO", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",anchor.definition.case_name, ...
    "M3","NOMINAL",400,400,0,"formal Case08 evidence", ...
    "M3 gate active ratio overlap",gateTable.gate_active_ratio_overlap, ...
    current.gate_interval.gate_active_ratio_overlap,tol,"");
records = compare_scalar(records,"C08_M4_MEAN_G", ...
    "COMMON_RUNNER_EQUIVALENCE_GATE",anchor.definition.case_name, ...
    "M4","NOMINAL",400,400,0,"formal Case08 evidence", ...
    "M4 mean g on M3 gate interval",gateTable.m4_mean_g_same_interval, ...
    current.gate_interval.m4_mean_g_same_interval,tol,"");

for mode = ["M2" "M3" "M4"]
    for window = ["W1" "W2"]
        frozenRow = retention(retention.algorithm_mode == mode & ...
            retention.window == window,:);
        testRow = current.retention(current.retention.algorithm_mode == ...
            mode & current.retention.window == window,:);
        records = compare_scalar(records, ...
            "C08_"+mode+"_"+window+"_RETENTION", ...
            "COMMON_RUNNER_EQUIVALENCE_GATE", ...
            anchor.definition.case_name,mode,"NOMINAL",400,400,0, ...
            "formal Case08 evidence", ...
            "fault increment retention ratio", ...
            frozenRow.fault_increment_retention_ratio, ...
            testRow.fault_increment_retention_ratio,tol,"");
    end
    frozenMove = movement(movement.algorithm_mode == mode,:);
    testMove = current.gate_interval_adaptation( ...
        current.gate_interval_adaptation.algorithm_mode == mode,:);
    names = ["F_delta_Cs1_pF" "F_delta_Cs2_pF" ...
        "CF_delta_Cs1_pF" "CF_delta_Cs2_pF" ...
        "fault_induced_delta_Cs1_pF" "fault_induced_delta_Cs2_pF" ...
        "F_movement_norm_pF" "CF_drift_movement_norm_pF" ...
        "fault_induced_movement_norm_pF"];
    for name = names
        records = compare_scalar(records, ...
            "C08_"+mode+"_"+upper(name), ...
            "COMMON_RUNNER_EQUIVALENCE_GATE", ...
            anchor.definition.case_name,mode,"NOMINAL",400,400,0, ...
            "formal Case08 signed movement",name, ...
            frozenMove.(char(name)),testMove.(char(name)),tol,"");
    end
end
end

function [records,gatePass,details] = validate_cself_split(paths,common)
records = empty_records();
tol = 1e-12;
nominal = common.case02;

% C0 is the already executed split-interface nominal common-runner anchor.
records = compare_scalar(records,"CSELF_C0_TRUTH", ...
    "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL","C0", ...
    400,400,0,"split configuration","truth Cself pF",400, ...
    nominal.physical_truth_config.Cself_truth_pF,tol,"");
records = compare_scalar(records,"CSELF_C0_ASSUMPTION", ...
    "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL","C0", ...
    400,400,0,"split configuration","algorithm Cself pF",400, ...
    nominal.algorithm_assumption_config.Cself_algorithm_pF,tol, ...
    "C0 is exactly the common-runner Case02 nominal execution.");

plusRequest = standard_request("Case02_slow_drift",440,400,0, ...
    ["M0" "M2" "M3" "M4"]);
minusRequest = standard_request("Case02_slow_drift",360,400,0, ...
    ["M0" "M2" "M3" "M4"]);
plus = execute_legacy_request(paths,plusRequest);
minus = execute_legacy_request(paths,minusRequest);

variants = {"C+",plus;"C-",minus};
for k = 1:size(variants,1)
    variant = variants{k,1};
    run = variants{k,2};
    truth = run.request.Cself_truth_pF;
    currentDifference = max(abs([ ...
        run.data.ia-nominal.data.ia; ...
        run.data.ib-nominal.data.ib; ...
        run.data.ic-nominal.data.ic]));
    records = add_record(records,"CSELF_"+variant+"_DATA_CHANGE", ...
        "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL", ...
        variant,truth,400,0,"physical current", ...
        "max current change from nominal A",0,currentDifference,tol, ...
        currentDifference > tol, ...
        "Pass criterion is test value > existing 1e-12 tolerance.");
    records = compare_scalar(records,"CSELF_"+variant+"_TRUTH", ...
        "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL", ...
        variant,truth,400,0,"physical truth interface", ...
        "data Cself pF",truth,mean(run.data.Ca),tol,"");
    records = compare_scalar(records,"CSELF_"+variant+"_ASSUMPTION", ...
        "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL", ...
        variant,truth,400,0,"algorithm assumption interface", ...
        "algorithm Cself pF",400,run.algorithm_cfg.Cself_pF,tol, ...
        "Physical truth was not copied into the algorithm config.");
    shared = numel(unique(run.input_signatures)) == 1 && ...
        all(run.input_signatures == run.data_signature);
    records = compare_scalar(records,"CSELF_"+variant+"_SHARED_DATA", ...
        "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift","ALL", ...
        variant,truth,400,0,"algorithm input discipline", ...
        "shared physical data across M0/M2/M3/M4",1,double(shared),0, ...
        "All four frozen algorithms received one identical data struct.");
    for mode = ["M0" "M2" "M3" "M4"]
        records = compare_scalar(records, ...
            "CSELF_"+variant+"_"+mode+"_ASSUMPTION", ...
            "CSELF_SPLIT_INTERFACE_GATE","Case02_slow_drift",mode, ...
            variant,truth,400,0,"algorithm invocation", ...
            "Cself assumption pF",400, ...
            run.algorithm_assumption_config.Cself_algorithm_pF,tol,"");
    end
end
gatePass = all(records.pass);
details = struct( ...
    'nominal_truth_pF',400,'nominal_algorithm_pF',400, ...
    'plus_truth_pF',440,'minus_truth_pF',360, ...
    'plus_current_max_change_A',max(abs([ ...
        plus.data.ia-nominal.data.ia;plus.data.ib-nominal.data.ib; ...
        plus.data.ic-nominal.data.ic])), ...
    'minus_current_max_change_A',max(abs([ ...
        minus.data.ia-nominal.data.ia;minus.data.ib-nominal.data.ib; ...
        minus.data.ic-nominal.data.ic])), ...
    'row_count',height(records),'pass_count',nnz(records.pass));
end

function [records,gatePass,details] = validate_csac_wrapper(common)
records = empty_records();
tol = 1e-12;
truthTol = 1e-10;
cfgClean = patent_default_config();
cfgClean.model = 'AI6109_MOA_AutoComp9';
cfgClean.SNR_dB = Inf;
caseInfo = phase1a_case_registry();
caseInfo = caseInfo(caseInfo.case_name == "Case02_slow_drift",:);
[cleanData,cleanReference] = simulate_phase2_case(cfgClean, ...
    char(caseInfo.legacy_scenario_name),caseInfo.seed);

[ac0Data,ac0Meta] = external_csac_wrapper( ...
    cleanData,cleanReference,common.case02.data,0,30,caseInfo.seed);
cfgAlgorithm = patent_default_config();
cfgAlgorithm.model = 'AI6109_MOA_AutoComp9';
ref0 = reconstruct_refs_from_b(ac0Data.t,ac0Data.ub,cfgAlgorithm.f, ...
    cfgAlgorithm.init_start,cfgAlgorithm.init_end, ...
    cfgAlgorithm.phase_error_deg);
[ac0Results,~] = run_algorithms(["M0" "M2" "M3" "M4"], ...
    ac0Data,ref0,cfgAlgorithm,400);

for phase = ["A" "B" "C"]
    lowerPhase = lower(phase);
    currentName = "i"+lowerPhase;
    records = compare_scalar(records,"AC0_IDEAL_"+phase, ...
        "ZERO_INJECTION_REGRESSION","Case02_slow_drift","ALL","AC0", ...
        400,400,0,"frozen nominal clean path", ...
        "ideal i"+phase+" max abs difference A",0, ...
        max(abs(ac0Meta.ideal.(char(currentName))- ...
        cleanData.(char(currentName)))),tol,"");
    records = compare_scalar(records,"AC0_NOISY_"+phase, ...
        "ZERO_INJECTION_REGRESSION","Case02_slow_drift","ALL","AC0", ...
        400,400,0,"common-runner nominal noisy path", ...
        "noisy i"+phase+" max abs difference A",0, ...
        max(abs(ac0Data.(char(currentName))- ...
        common.case02.data.(char(currentName)))),tol,"");
end
records = compare_scalar(records,"AC0_TRUTH_CS", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","ALL","AC0", ...
    400,400,0,"common-runner nominal truth", ...
    "Cs1/Cs2 max abs difference pF",0,max(abs([ ...
    ac0Data.Cs1-common.case02.data.Cs1; ...
    ac0Data.Cs2-common.case02.data.Cs2])),truthTol,"");
records = compare_scalar(records,"AC0_REFERENCE_PHI1", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","ALL","AC0", ...
    400,400,0,"common-runner nominal reference","phi1 rad", ...
    common.case02.ref.phi1,ref0.phi1,tol,"");
records = compare_scalar(records,"AC0_REFERENCE_PHI3", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","ALL","AC0", ...
    400,400,0,"common-runner nominal reference","phi3 rad", ...
    common.case02.ref.phi3,ref0.phi3,tol,"");
for mode = ["M0" "M2" "M3" "M4"]
    records = compare_algorithm_output_for_gate(records, ...
        "AC0_"+mode,"ZERO_INJECTION_REGRESSION", ...
        "Case02_slow_drift",mode,common.case02.results.(char(mode)), ...
        ac0Results.(char(mode)),tol);
end

[ac1Data,ac1Meta] = external_csac_wrapper( ...
    cleanData,cleanReference,common.case02.data,1,30,caseInfo.seed);
deltaA = ac1Meta.ideal.ia-cleanData.ia;
deltaB = ac1Meta.ideal.ib-cleanData.ib;
deltaC = ac1Meta.ideal.ic-cleanData.ic;
formula = 1e-12*(ac1Meta.duA-ac1Meta.duC);
records = compare_scalar(records,"AC1_FORMULA_A", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
    400,400,1,"CsAC structural sanity", ...
    "delta iA formula max error A",0,max(abs(deltaA-formula)),tol,"");
records = compare_scalar(records,"AC1_FORMULA_B", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
    400,400,1,"CsAC structural sanity", ...
    "delta iB max abs A",0,max(abs(deltaB)),tol,"");
records = compare_scalar(records,"AC1_FORMULA_C", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
    400,400,1,"CsAC structural sanity", ...
    "delta iC plus formula max error A",0,max(abs(deltaC+formula)),tol,"");
records = compare_scalar(records,"AC1_CURRENT_CONSERVATION", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
    400,400,1,"CsAC structural sanity", ...
    "delta iA+iB+iC max abs A",0,max(abs(deltaA+deltaB+deltaC)),tol,"");
for phase = ["A" "B" "C"]
    records = compare_scalar(records,"AC1_NOISE_SIGMA_"+phase, ...
        "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
        400,400,1,"noise generation order", ...
        "sigma "+phase+" from modified ideal current A", ...
        ac1Meta.expected_sigma.(char(phase)), ...
        ac1Meta.sigma.(char(phase)),tol, ...
        "CsAC was added to ideal current before sigma and noise generation.");
end
records = compare_scalar(records,"AC1_NOISE_RECONSTRUCTION", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A","AC1", ...
    400,400,1,"noise generation order", ...
    "noisy minus ideal reconstruction max error A",0,max(abs([ ...
    ac1Data.ia-ac1Meta.ideal.ia-ac1Meta.noise.A; ...
    ac1Data.ib-ac1Meta.ideal.ib-ac1Meta.noise.B; ...
    ac1Data.ic-ac1Meta.ideal.ic-ac1Meta.noise.C])),tol,"");

[~,ac05Meta] = external_csac_wrapper( ...
    cleanData,cleanReference,common.case02.data,0.5,30,caseInfo.seed);
linearityError = max(abs([ ...
    2*(ac05Meta.ideal.ia-cleanData.ia)-deltaA; ...
    2*(ac05Meta.ideal.ib-cleanData.ib)-deltaB; ...
    2*(ac05Meta.ideal.ic-cleanData.ic)-deltaC]));
records = compare_scalar(records,"AC_LINEARITY_05_TO_10", ...
    "ZERO_INJECTION_REGRESSION","Case02_slow_drift","N/A", ...
    "OPTIONAL_LINEARITY",400,400,0.5,"CsAC structural sanity", ...
    "2x(0.5 pF contribution)-1 pF max error A",0,linearityError,tol, ...
    "Optional internal sanity check; not a paper performance result.");

gatePass = all(records.pass);
details = struct( ...
    'ac0_noisy_max_difference_A',max(abs([ ...
        ac0Data.ia-common.case02.data.ia; ...
        ac0Data.ib-common.case02.data.ib; ...
        ac0Data.ic-common.case02.data.ic])), ...
    'ac1_conservation_max_error_A',max(abs(deltaA+deltaB+deltaC)), ...
    'ac1_formula_max_error_A',max(abs([deltaA-formula;deltaC+formula])), ...
    'optional_linearity_error_A',linearityError, ...
    'optional_linearity_pass',linearityError <= tol, ...
    'row_count',height(records),'pass_count',nnz(records.pass));
end

function [data,metadata] = external_csac_wrapper( ...
        cleanData,cleanReference,nominalNoisyData,CsACpF,snrDB,seed)
data = cleanData;
duA = gradient(cleanData.ua,cleanData.t);
duC = gradient(cleanData.uc,cleanData.t);
contribution = CsACpF*1e-12*(duA-duC);
ideal = cleanData;
ideal.ia = cleanData.ia+contribution;
ideal.ib = cleanData.ib;
ideal.ic = cleanData.ic-contribution;

% The frozen nominal path computes measurement-noise sigma from the
% analytic MATLAB reference current. Reusing that exact basis is required
% for AC0 identity; the same CsAC contribution is applied before sigma is
% computed for every nonzero injection.
noiseBasis = cleanReference;
noiseBasis.ia = cleanReference.ia+contribution;
noiseBasis.ib = cleanReference.ib;
noiseBasis.ic = cleanReference.ic-contribution;

sigma = struct( ...
    'A',rms(noiseBasis.ia)/10^(snrDB/20), ...
    'B',rms(noiseBasis.ib)/10^(snrDB/20), ...
    'C',rms(noiseBasis.ic)/10^(snrDB/20));
rng(seed+10000);
noise = struct( ...
    'A',sigma.A*randn(size(ideal.ia)), ...
    'B',sigma.B*randn(size(ideal.ib)), ...
    'C',sigma.C*randn(size(ideal.ic)));
if CsACpF == 0
    % A zero external contribution is an identity operation. Preserve the
    % frozen nominal noisy data byte-for-byte rather than changing floating
    % point operation order by reconstructing clean + noise externally.
    data = nominalNoisyData;
    noise = struct( ...
        'A',data.ia-ideal.ia, ...
        'B',data.ib-ideal.ib, ...
        'C',data.ic-ideal.ic);
else
    data.ia = ideal.ia+noise.A;
    data.ib = ideal.ib+noise.B;
    data.ic = ideal.ic+noise.C;
end
data.CsAC_pF = CsACpF*ones(size(data.t));
data.current_source = "phase2_external_csac_wrapper";
expectedSigma = struct( ...
    'A',rms(noiseBasis.ia)/10^(snrDB/20), ...
    'B',rms(noiseBasis.ib)/10^(snrDB/20), ...
    'C',rms(noiseBasis.ic)/10^(snrDB/20));
metadata = struct( ...
    'ideal',ideal,'noise_basis',noiseBasis,'noise',noise,'sigma',sigma, ...
    'expected_sigma',expectedSigma,'duA',duA,'duC',duC, ...
    'seed',seed,'rng_seed',seed+10000,'snr_db',snrDB, ...
    'injection_order',"ideal current -> CsAC contribution -> noise sigma -> noise");
end

function records = compare_algorithm_output_for_gate( ...
        records,idPrefix,gateName,caseName,mode,reference,test,tol)
records = compare_scalar(records,idPrefix+"_CHIST",gateName, ...
    caseName,mode,"AC0",400,400,0,"common-runner output", ...
    "Cs trajectory max abs difference pF",0, ...
    max(abs(reference.cHist-test.cHist),[],'all'),tol,"");
records = compare_scalar(records,idPrefix+"_IR",gateName, ...
    caseName,mode,"AC0",400,400,0,"common-runner output", ...
    "extracted current max abs difference A",0,max(abs([ ...
    reference.ir.A-test.ir.A;reference.ir.B-test.ir.B; ...
    reference.ir.C-test.ir.C])),tol,"");
records = compare_scalar(records,idPrefix+"_FINAL_CS1",gateName, ...
    caseName,mode,"AC0",400,400,0,"common-runner output", ...
    "final Cs1 pF",reference.cHist(end,1),test.cHist(end,1),tol,"");
records = compare_scalar(records,idPrefix+"_FINAL_CS2",gateName, ...
    caseName,mode,"AC0",400,400,0,"common-runner output", ...
    "final Cs2 pF",reference.cHist(end,2),test.cHist(end,2),tol,"");
end

function records = empty_records()
records = table( ...
    strings(0,1),strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),strings(0,1),strings(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    false(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    'VariableNames',{'test_id','gate_name','anchor_case','algorithm', ...
    'test_variant','truth_Cself_pF','algorithm_Cself_pF','CsAC_pF', ...
    'comparison_target','metric_name','reference_value','test_value', ...
    'absolute_difference','relative_difference','tolerance','pass', ...
    'frozen_hash_pre','frozen_hash_post','notes'});
end

function records = compare_scalar(records,testId,gateName,caseName,mode, ...
        variant,truthCself,algorithmCself,csac,target,metric, ...
        referenceValue,testValue,tolerance,notes)
if isscalar(referenceValue) && isscalar(testValue) && ...
        isfinite(referenceValue) && isfinite(testValue)
    absoluteDifference = abs(double(testValue)-double(referenceValue));
    pass = absoluteDifference <= tolerance;
else
    pass = isequaln(referenceValue,testValue);
end
records = add_record(records,testId,gateName,caseName,mode,variant, ...
    truthCself,algorithmCself,csac,target,metric,referenceValue, ...
    testValue,tolerance,pass,notes);
end

function records = add_record(records,testId,gateName,caseName,mode, ...
        variant,truthCself,algorithmCself,csac,target,metric, ...
        referenceValue,testValue,tolerance,pass,notes)
if isfinite(referenceValue) && isfinite(testValue)
    absoluteDifference = abs(double(testValue)-double(referenceValue));
    relativeDifference = absoluteDifference/(abs(double(referenceValue))+eps);
else
    absoluteDifference = NaN;
    relativeDifference = NaN;
end
row = table(string(testId),string(gateName),string(caseName), ...
    string(mode),string(variant),double(truthCself), ...
    double(algorithmCself),double(csac),string(target),string(metric), ...
    double(referenceValue),double(testValue),absoluteDifference, ...
    relativeDifference,double(tolerance),logical(pass),"","", ...
    string(notes),'VariableNames',records.Properties.VariableNames);
records = [records;row];
end

function records = append_not_run(records,gateName,reason)
records = add_record(records,gateName+"_NOT_RUN",gateName,"N/A", ...
    "N/A","NOT_RUN",NaN,NaN,NaN,"execution","gate executed",1,0,0, ...
    false,"NOT_RUN: "+string(reason));
end

function [ready,pending] = authorized_condition_counts(registryPath,gate)
registry = read_csv_table(registryPath);
if ~(gate.source && gate.common)
    ready = 0;
    pending = height(registry);
    return
end
allowed = true(height(registry),1);
if ~gate.cself
    allowed(contains(registry.execution_gate, ...
        "CSELF_SPLIT_INTERFACE_GATE")) = false;
end
if ~gate.csac
    allowed(contains(registry.execution_gate, ...
        "ZERO_INJECTION_REGRESSION")) = false;
end
ready = nnz(allowed);
pending = height(registry)-ready;
end

function status = final_status(gate)
if ~(gate.source && gate.common)
    status = "BLOCKED";
elseif gate.cself && gate.csac
    status = "PASS";
else
    status = "PARTIAL";
end
end

function write_report(paths,records,pre,post,gate,status, ...
        readyCount,pendingCount,details)
fid = fopen(paths.report,'w','n','UTF-8');
if fid < 0
    error('Phase2:ReportWrite','Unable to create %s.',paths.report);
end
cleanup = onCleanup(@() fclose(fid));
line = @(value) fprintf(fid,'%s\n',char(string(value)));
blank = @() fprintf(fid,'\n');

line('# Phase 2 Step 2A — Execution Infrastructure & Gate Validation');
blank();
line('## 1. Scope');
blank();
line(['Step 2A executed only frozen-source integrity checks, three ' ...
    'anchor equivalence paths, the Cself split interface checks, and ' ...
    'the external CsAC zero-injection/structural checks. No deterministic ' ...
    'matrix, sweep, Monte-Carlo cohort, tuning, or method change was run.']);
blank();
line('## 2. Frozen integrity pre-check');
blank();
line(sprintf('- Phase 1 manifest: %d/%d PASS.', ...
    pre.phase1_pass_count,pre.phase1_count));
line(sprintf('- Phase 2 Step 1 final files: %d/3 PASS.', ...
    pre.step1_pass_count));
line('- Specification verification used the frozen canonical self-hash rule.');
line('- PRE result: **'+pass_label(pre.pass)+'**.');
blank();
line('## 3. Common runner architecture');
blank();
line(['The wrapper exposes separate `physical_truth_config.Cself_truth_pF` ' ...
    'and `algorithm_assumption_config.Cself_algorithm_pF`. Physical data ' ...
    'generation receives only the truth value; the frozen dispatcher receives ' ...
    'the independent three-phase `self_pF` assumption. M0/M2/M3/M4 are ' ...
    'delegated to `run_phase1a_algorithm` without copied formulas.']);
line(['The external CsAC path starts from the frozen clean Case02 signal, ' ...
    'adds the AC contribution to ideal current, recomputes per-phase noise ' ...
    'sigma from the modified ideal current, and then draws noise with the ' ...
    'frozen seed.']);
blank();
line('## 4. COMMON_RUNNER_EQUIVALENCE_GATE');
blank();
commonRows = records.gate_name == "COMMON_RUNNER_EQUIVALENCE_GATE";
line(sprintf('- Result: **%s** (%d/%d comparison rows passed).', ...
    pass_label(gate.common),nnz(records.pass(commonRows)),nnz(commonRows)));
if isfield(details,'common')
    line(sprintf(['- Anchor budget: %d algorithm evaluations ' ...
        '(Case08 M2/M3/M4 each includes matched F/CF trajectories).'], ...
        details.common.anchor_algorithm_evaluations));
    line(sprintf('- Seeds: Case02=%d, Case05=%d, Case08=%d.', ...
        details.common.case02_seed,details.common.case05_seed, ...
        details.common.case08_seed));
    line(sprintf('- Maximum recorded numeric difference: %.17g.', ...
        details.common.max_numeric_difference));
end
line(['- Missing state/trajectory evidence, where applicable, is explicitly ' ...
    'marked `NOT_AVAILABLE_IN_FROZEN_EVIDENCE`; it is not synthesized.']);
blank();
line('## 5. CSELF_SPLIT_INTERFACE_GATE');
blank();
cselfRows = records.gate_name == "CSELF_SPLIT_INTERFACE_GATE";
line(sprintf('- Result: **%s** (%d/%d rows passed).', ...
    pass_label(gate.cself),nnz(records.pass(cselfRows)),nnz(cselfRows)));
if isfield(details,'cself')
    line(sprintf('- C+ (440/400 pF) maximum physical-current change: %.17g A.', ...
        details.cself.plus_current_max_change_A));
    line(sprintf('- C- (360/400 pF) maximum physical-current change: %.17g A.', ...
        details.cself.minus_current_max_change_A));
end
line(['- C+/C- are interface and sanity tests only; their performance is not ' ...
    'a Step 3 robustness result.']);
blank();
line('## 6. ZERO_INJECTION_REGRESSION');
blank();
csacRows = records.gate_name == "ZERO_INJECTION_REGRESSION";
line(sprintf('- Result: **%s** (%d/%d rows passed).', ...
    pass_label(gate.csac),nnz(records.pass(csacRows)),nnz(csacRows)));
if isfield(details,'csac')
    line(sprintf('- AC0 maximum noisy-current difference: %.17g A.', ...
        details.csac.ac0_noisy_max_difference_A));
end
line(['- AC0 compares ideal/noisy currents, truth, references, and formal ' ...
    'M0/M2/M3/M4 outputs against the nominal Case02 path.']);
blank();
line('## 7. CsAC structural sanity');
blank();
if isfield(details,'csac')
    line(sprintf('- AC1 formula maximum error: %.17g A.', ...
        details.csac.ac1_formula_max_error_A));
    line(sprintf('- AC1 three-phase conservation maximum error: %.17g A.', ...
        details.csac.ac1_conservation_max_error_A));
    line(sprintf('- Optional 0.5-to-1.0 pF linearity error: %.17g A (%s).', ...
        details.csac.optional_linearity_error_A, ...
        pass_label(details.csac.optional_linearity_pass)));
end
line(['- AC1 and optional linearity checks are structural sanity evidence, ' ...
    'not paper performance comparisons.']);
blank();
line('## 8. Frozen integrity post-check');
blank();
line(sprintf('- Phase 1 manifest: %d/%d PASS.', ...
    post.phase1_pass_count,post.phase1_count));
line(sprintf('- Phase 2 Step 1 final files: %d/3 PASS.', ...
    post.step1_pass_count));
line('- PRE/POST hash vectors identical: **'+ ...
    pass_label(isequal(pre.actual_sha256,post.actual_sha256))+'**.');
line('- POST result: **'+pass_label(post.pass)+'**.');
blank();
line('## 9. Gate summary');
blank();
line('```text');
line('NO_FROZEN_SOURCE_DIFF_GATE: '+pass_label(gate.source));
line('COMMON_RUNNER_EQUIVALENCE_GATE: '+pass_label(gate.common));
line('CSELF_SPLIT_INTERFACE_GATE: '+pass_label(gate.cself));
line('ZERO_INJECTION_REGRESSION: '+pass_label(gate.csac));
line('REPLAY_EQUIVALENCE_GATE: NOT_RUN');
line('TRACKER_EQUIVALENCE_GATE: NOT_RUN');
line('NEGATIVE_SEQUENCE_INTERNAL_CONVENTION: UNRESOLVED');
line('```');
blank();
line('## 10. Allowed / blocked Phase2 families');
blank();
line(sprintf('- Registry conditions ready: **%d**.',readyCount));
line(sprintf('- Registry conditions pending or blocked: **%d**.',pendingCount));
line('- Ordinary deterministic families: '+authorization(gate.source && gate.common)+'.');
line('- Nonzero Cself mismatch and dependent MC rows: '+authorization(gate.cself)+'.');
line('- Nonzero CsAC conditions: '+authorization(gate.csac)+'.');
line(['- Negative-sequence rows remain validity-boundary tests; the internal ' ...
    'convention remains unresolved.']);
line(['- Counterfactual replay and sensitivity variants remain pending because ' ...
    'their dedicated equivalence gates were not run.']);
line('- Monte-Carlo remains scheduled for Step 6 and was not executed here.');
blank();
line('## 11. Next-step authorization');
blank();
line('```text');
line('STEP 2A STATUS: '+status);
line('COMMON PHASE2 RUNNER: '+authorization(gate.source && gate.common));
line('CSELF CONDITIONS: '+authorization(gate.cself));
line('CSAC CONDITIONS: '+authorization(gate.csac));
line('FROZEN SOURCE MODIFIED: '+yes_no(~gate.source));
line('FULL MATRIX EXECUTED: NO');
line('READY_CONDITION_COUNT: '+string(readyCount));
line('PENDING_OR_BLOCKED_CONDITION_COUNT: '+string(pendingCount));
line('READY FOR STEP 2B: '+yes_no(gate.source && gate.common));
line('```');
if strlength(details.error) > 0
    blank();
    line('Execution note: `'+replace(details.error,newline,' ')+'`');
end
end

function value = authorization(pass)
if pass, value = "AUTHORIZED"; else, value = "BLOCKED"; end
end

function value = yes_no(pass)
if pass, value = "YES"; else, value = "NO"; end
end

function label = pass_label(pass)
if pass, label = "PASS"; else, label = "FAIL"; end
end

function tableOut = read_csv_table(path)
% Explicit delimiter avoids R2023b mis-detection on UTF-8 paths.
tableOut = readtable(path,'Delimiter',',','TextType','string', ...
    'VariableNamingRule','preserve');
end
