function output = run_phase2_deterministic_core(action,conditionId)
%RUN_PHASE2_DETERMINISTIC_CORE Phase 2 registry-driven deterministic runner.
% Public entries:
%   run_phase2_deterministic_core("run_condition","P2_FA_FO_130")
%   run_phase2_deterministic_core("smoke_validation")
%   run_phase2_deterministic_core("model_mismatch")
%
% Step 2B-1 is validation only. The six-condition smoke set is deliberately
% fixed here; every physical factor level is read from the frozen registry.

if nargin < 1 || isempty(action)
    action = "smoke_validation";
end
action = lower(strtrim(string(action)));
if ~isscalar(action)
    error('Phase2:RunnerAction','Action must be a scalar string.');
end

paths = runner_paths();
addpath(paths.matlab_root);
conditionRegistry = read_registry(paths.condition_registry);
executionRegistry = read_registry(paths.execution_registry);

if action == "generic_zero_path_regression"
    authorization = step2a_authorization(paths.step2a_report);
    pre = capture_frozen_integrity(paths);
    if ~pre.pass || ~authorization.source || ~authorization.csac
        error('Phase2:GenericZeroAuthorization', ...
            'Frozen integrity or Step 2A CsAC authorization failed.');
    end
    output = generic_zero_path_regression(paths);
    post = capture_frozen_integrity(paths);
    output.frozen_integrity_pass = pre.pass && post.pass && ...
        isequal(pre.actual_sha256,post.actual_sha256);
    if ~output.frozen_integrity_pass
        error('Phase2:FrozenIntegrity', ...
            'Frozen hashes changed during generic zero-path regression.');
    end
    fprintf('GENERIC_ZERO_PATH_REGRESSION=%s\n',pass_fail(output.pass));
    return
elseif action == "model_mismatch"
    output = run_model_mismatch( ...
        paths,conditionRegistry,executionRegistry);
    return
elseif action == "full_deterministic_core"
    output = run_full_deterministic_core( ...
        paths,conditionRegistry,executionRegistry);
    return
elseif action == "run_condition"
    if nargin < 2
        error('Phase2:ConditionRequired', ...
            'run_condition requires one condition_id.');
    end
    pre = capture_frozen_integrity(paths);
    if ~pre.pass
        error('Phase2:FrozenIntegrity', ...
            'PRE frozen integrity failed; execution is blocked.');
    end
    run = execute_condition(conditionRegistry, ...
        executionRegistry,string(conditionId));
    post = capture_frozen_integrity(paths);
    run.frozen_integrity = struct('pre',pre,'post',post, ...
        'unchanged',pre.pass && post.pass && ...
        isequal(pre.actual_sha256,post.actual_sha256));
    if ~run.frozen_integrity.unchanged
        error('Phase2:FrozenIntegrity', ...
            'POST frozen integrity failed or frozen hashes changed.');
    end
    run.rows.frozen_integrity_pass(:) = true;
    output = run;
    return
elseif action ~= "smoke_validation"
    error('Phase2:RunnerAction','Unsupported action: %s.',action);
end

if ~isfolder(paths.output_root)
    mkdir(paths.output_root);
end
smokeIds = ["P2_FA_FO_130";"P2_FA_DF_130";"P2_SN_20"; ...
    "P2_PE_100";"P2_H3_100";"P2_NS_003"];
pre = capture_frozen_integrity(paths);
allRows = empty_result_table();

if pre.pass
    for k = 1:numel(smokeIds)
        try
            currentRun = execute_condition(conditionRegistry, ...
                executionRegistry,smokeIds(k));
            allRows = [allRows;currentRun.rows]; %#ok<AGROW>
            fprintf('STEP2B1 %s: 4/4 evaluations complete.\n',smokeIds(k));
        catch exception
            allRows = [allRows;failure_rows(conditionRegistry, ...
                smokeIds(k),exception)]; %#ok<AGROW>
            fprintf(2,'STEP2B1 %s failed: %s\n', ...
                smokeIds(k),exception.message);
        end
    end
else
    exception = MException('Phase2:FrozenIntegrity', ...
        'PRE frozen integrity failed; smoke simulation was not executed.');
    for k = 1:numel(smokeIds)
        allRows = [allRows;failure_rows(conditionRegistry, ...
            smokeIds(k),exception)]; %#ok<AGROW>
    end
end

post = capture_frozen_integrity(paths);
frozenPass = pre.pass && post.pass && ...
    isequal(pre.actual_sha256,post.actual_sha256);
allRows.frozen_integrity_pass(:) = frozenPass;

main = allRows.record_type == "MAIN";
complete = main & ~allRows.numerical_failure & ...
    ~allRows.metric_missing;
conditionComplete = false(numel(smokeIds),1);
for k = 1:numel(smokeIds)
    index = main & allRows.condition_id == smokeIds(k);
    conditionComplete(k) = nnz(index) == 4 && all(complete(index));
end
runnerPass = height(allRows(main,:)) == 24 && ...
    all(allRows.registry_match(main)) && ...
    all(allRows.shared_data_pass(main)) && ...
    all(~allRows.metric_missing(main)) && ...
    all(~allRows.numerical_failure(main)) && frozenPass;

writetable(allRows,paths.results_csv);
write_report(paths,allRows,smokeIds,conditionComplete,pre,post, ...
    frozenPass,runnerPass);

output = struct( ...
    'status',status_label(runnerPass,pre.pass,frozenPass), ...
    'registry_runner_authorized',runnerPass, ...
    'smoke_conditions_complete',nnz(conditionComplete), ...
    'algorithm_evaluations_complete',nnz(complete), ...
    'frozen_source_modified',~frozenPass, ...
    'full_deterministic_matrix_executed',false, ...
    'ready_for_step2b2',runnerPass, ...
    'results_csv',string(paths.results_csv), ...
    'report',string(paths.report));

fprintf('STEP2B1_STATUS=%s\n',output.status);
fprintf('REGISTRY_RUNNER=%s\n',authorized_label(runnerPass));
fprintf('SMOKE_CONDITIONS=%d/6 COMPLETE\n',nnz(conditionComplete));
fprintf('ALGORITHM_EVALUATIONS=%d/24 COMPLETE\n',nnz(complete));
fprintf('FROZEN_SOURCE_MODIFIED=%s\n',yes_no(~frozenPass));
fprintf('FULL_DETERMINISTIC_MATRIX_EXECUTED=NO\n');
fprintf('READY_FOR_STEP2B2=%s\n',yes_no(runnerPass));
end

function output = run_full_deterministic_core( ...
        paths,conditionRegistry,executionRegistry)
groups = ["FAULT_AMPLITUDE";"SNR";"REFERENCE_PHASE"; ...
    "THIRD_HARMONIC";"NEGATIVE_SEQUENCE"];
isNew = false(height(conditionRegistry),1);
isBlocked = false(height(conditionRegistry),1);
for k = 1:height(conditionRegistry)
    isNew(k) = truthy(conditionRegistry.is_new_phase2_condition(k));
    isBlocked(k) = truthy(conditionRegistry.is_blocked(k));
end
selected = conditionRegistry.registry_kind == "DETERMINISTIC" & ...
    ismember(conditionRegistry.experiment_group,groups) & ...
    isNew & ~isBlocked;
conditions = conditionRegistry(selected,:);
if height(conditions) ~= 25 || numel(unique(conditions.condition_id)) ~= 25
    error('Phase2:FullCoreConditionCount', ...
        'Frozen registry must select exactly 25 unique new conditions.');
end
evaluationMask = ismember(executionRegistry.condition_id, ...
    conditions.condition_id) & ...
    executionRegistry.record_type == "MAIN_ALGORITHM_EVALUATION";
evaluations = executionRegistry(evaluationMask,:);
if height(evaluations) ~= 100 || ...
        any(evaluations.execution_status ~= "READY")
    error('Phase2:FullCoreEvaluationCount', ...
        'Frozen execution registry must select 100 READY evaluations.');
end

if ~isfolder(paths.step2b2_output_root)
    mkdir(paths.step2b2_output_root);
end
pre = capture_frozen_integrity(paths);
rows = empty_result_table();
conditionComplete = false(height(conditions),1);
if pre.pass
    for k = 1:height(conditions)
        conditionId = conditions.condition_id(k);
        try
            current = execute_condition(conditionRegistry, ...
                executionRegistry,conditionId);
            rows = [rows;current.rows]; %#ok<AGROW>
            conditionComplete(k) = all(~current.rows.numerical_failure & ...
                ~current.rows.metric_missing & ...
                current.rows.registry_match & ...
                current.rows.shared_data_pass) && height(current.rows) == 4;
            fprintf('STEP2B2 %02d/25 %s: %d/4 complete.\n', ...
                k,conditionId,nnz(~current.rows.numerical_failure & ...
                ~current.rows.metric_missing));
        catch exception
            rows = [rows;failure_rows(conditionRegistry, ...
                conditionId,exception)]; %#ok<AGROW>
            fprintf(2,'STEP2B2 %02d/25 %s failed: %s\n', ...
                k,conditionId,exception.message);
        end
    end
else
    exception = MException('Phase2:FrozenIntegrity', ...
        'PRE frozen integrity failed; formal batch was not executed.');
    for k = 1:height(conditions)
        rows = [rows;failure_rows(conditionRegistry, ...
            conditions.condition_id(k),exception)]; %#ok<AGROW>
    end
end

post = capture_frozen_integrity(paths);
frozenPass = pre.pass && post.pass && ...
    isequal(pre.actual_sha256,post.actual_sha256);
rows.frozen_integrity_pass(:) = frozenPass;
main = rows.record_type == "MAIN";
complete = main & ~rows.numerical_failure & ~rows.metric_missing;
batchPass = height(rows(main,:)) == 100 && ...
    nnz(conditionComplete) == 25 && ...
    all(rows.registry_match(main)) && ...
    all(rows.shared_data_pass(main)) && ...
    all(~rows.metric_missing(main)) && ...
    all(~rows.numerical_failure(main)) && frozenPass;

writetable(rows,paths.step2b2_results_csv);
write_step2b2_report(paths,rows,conditions,conditionComplete, ...
    pre,post,frozenPass,batchPass);

output = struct( ...
    'status',status_label(batchPass,pre.pass,frozenPass), ...
    'physical_conditions_complete',nnz(conditionComplete), ...
    'algorithm_evaluations_complete',nnz(complete), ...
    'numerical_failures',nnz(main & rows.numerical_failure), ...
    'metric_missing_rows',nnz(main & rows.metric_missing), ...
    'frozen_source_modified',~frozenPass, ...
    'full_deterministic_core_complete',batchPass, ...
    'ready_for_step3',batchPass, ...
    'results_csv',string(paths.step2b2_results_csv), ...
    'report',string(paths.step2b2_report));
fprintf('STEP2B2_STATUS=%s\n',output.status);
fprintf('PHYSICAL_CONDITIONS_COMPLETE=%d/25\n', ...
    output.physical_conditions_complete);
fprintf('ALGORITHM_EVALUATIONS_COMPLETE=%d/100\n', ...
    output.algorithm_evaluations_complete);
fprintf('NUMERICAL_FAILURES=%d\n',output.numerical_failures);
fprintf('METRIC_MISSING_ROWS=%d\n',output.metric_missing_rows);
fprintf('FROZEN_SOURCE_MODIFIED=%s\n', ...
    yes_no(output.frozen_source_modified));
fprintf('FULL_DETERMINISTIC_CORE_COMPLETE=%s\n',yes_no(batchPass));
fprintf('READY_FOR_STEP3=%s\n',yes_no(batchPass));
end

function output = run_model_mismatch( ...
        paths,conditionRegistry,executionRegistry)
cselfIds = ["P2_CS_M10";"P2_CS_M05";"P2_CS_M02"; ...
    "P2_CS_P02";"P2_CS_P05";"P2_CS_P10"];
csacIds = ["P2_AC_005";"P2_AC_010";"P2_AC_020";"P2_AC_030"];
assert_model_mismatch_registry(conditionRegistry,executionRegistry, ...
    cselfIds,csacIds);
authorization = step2a_authorization(paths.step2a_report);
if ~authorization.cself || ~authorization.source
    error('Phase2:Step3Authorization', ...
        'Step 2A does not authorize the Cself formal matrix.');
end
if ~isfolder(paths.step3_output_root)
    mkdir(paths.step3_output_root);
end

pre = capture_frozen_integrity(paths);
rows = empty_step3_result_table();
cselfComplete = false(numel(cselfIds),1);
csacComplete = false(numel(csacIds),1);
gate = empty_generic_gate_details();
if pre.pass
    for k = 1:numel(cselfIds)
        try
            current = execute_condition(conditionRegistry, ...
                executionRegistry,cselfIds(k),true);
            currentRows = augment_step3_rows(current.rows, ...
                current.condition_registry_row, ...
                "Step2A CSELF_SPLIT_INTERFACE_GATE authorization; "+ ...
                "frozen registry retained PENDING_GATE.");
            rows = [rows;currentRows]; %#ok<AGROW>
            cselfComplete(k) = step3_condition_complete(currentRows);
            fprintf('STEP3 CSELF %d/6 %s: %d/4 complete.\n', ...
                k,cselfIds(k),nnz(~currentRows.numerical_failure & ...
                ~currentRows.metric_missing));
        catch exception
            failed = failure_rows(conditionRegistry,cselfIds(k),exception);
            registryRow = conditionRegistry( ...
                conditionRegistry.condition_id == cselfIds(k),:);
            rows = [rows;augment_step3_rows(failed,registryRow, ...
                string(exception.identifier)+": "+ ...
                string(exception.message))]; %#ok<AGROW>
            fprintf(2,'STEP3 CSELF %s failed: %s\n', ...
                cselfIds(k),exception.message);
        end
    end

    try
        gate = generic_zero_path_regression(paths);
    catch exception
        gate = empty_generic_gate_details();
        gate.error = string(getReport(exception,'extended', ...
            'hyperlinks','off'));
        gate.pass = false;
    end
    fprintf('GENERIC_ZERO_PATH_REGRESSION=%s\n',pass_fail(gate.pass));

    if gate.pass && authorization.csac
        for k = 1:numel(csacIds)
            try
                current = execute_condition(conditionRegistry, ...
                    executionRegistry,csacIds(k),true);
                currentRows = augment_step3_rows(current.rows, ...
                    current.condition_registry_row, ...
                    "Step2A ZERO_INJECTION_REGRESSION plus Step3 "+ ...
                    "GENERIC_ZERO_PATH_REGRESSION authorization; "+ ...
                    "frozen registry retained PENDING_GATE.");
                rows = [rows;currentRows]; %#ok<AGROW>
                csacComplete(k) = step3_condition_complete(currentRows);
                fprintf('STEP3 CSAC %d/4 %s: %d/4 complete.\n', ...
                    k,csacIds(k),nnz(~currentRows.numerical_failure & ...
                    ~currentRows.metric_missing));
            catch exception
                failed = failure_rows(conditionRegistry,csacIds(k),exception);
                registryRow = conditionRegistry( ...
                    conditionRegistry.condition_id == csacIds(k),:);
                rows = [rows;augment_step3_rows(failed,registryRow, ...
                    string(exception.identifier)+": "+ ...
                    string(exception.message))]; %#ok<AGROW>
                fprintf(2,'STEP3 CSAC %s failed: %s\n', ...
                    csacIds(k),exception.message);
            end
        end
    end
else
    gate.error = "PRE frozen integrity failed; Step 3 was not executed.";
end

post = capture_frozen_integrity(paths);
frozenPass = pre.pass && post.pass && ...
    isequal(pre.actual_sha256,post.actual_sha256);
rows.frozen_integrity_pass(:) = frozenPass;
mainComplete = ~rows.numerical_failure & ~rows.metric_missing & ...
    rows.registry_match & rows.shared_data_pass;
cselfDone = nnz(cselfComplete);
csacDone = nnz(csacComplete);
if frozenPass && cselfDone == 6 && gate.pass && csacDone == 4
    status = "PASS";
elseif frozenPass && cselfDone == 6 && ~gate.pass && ...
        all(mainComplete)
    status = "PARTIAL";
else
    status = "BLOCKED";
end
readyForStep4 = frozenPass && cselfDone == 6 && ...
    all(mainComplete) && (~gate.pass || csacDone == 4);

writetable(rows,paths.step3_results_csv);
write_step3_report(paths,rows,pre,post,authorization,gate, ...
    cselfDone,csacDone,status,readyForStep4,frozenPass);
output = struct('status',status, ...
    'cself_conditions_complete',cselfDone, ...
    'cself_evaluations_complete',nnz( ...
    ismember(rows.condition_id,cselfIds) & mainComplete), ...
    'generic_zero_path_regression',gate.pass, ...
    'csac_conditions_complete',csacDone, ...
    'csac_evaluations_complete',nnz( ...
    ismember(rows.condition_id,csacIds) & mainComplete), ...
    'numerical_failures',nnz(rows.numerical_failure), ...
    'metric_missing_rows',nnz(rows.metric_missing), ...
    'frozen_source_modified',~frozenPass, ...
    'ready_for_step4',readyForStep4, ...
    'results_csv',string(paths.step3_results_csv), ...
    'report',string(paths.step3_report));
fprintf('STEP_3_STATUS=%s\n',status);
fprintf('CSELF_CONDITIONS_COMPLETE=%d/6\n',cselfDone);
fprintf('CSELF_EVALUATIONS_COMPLETE=%d/24\n', ...
    output.cself_evaluations_complete);
fprintf('GENERIC_ZERO_PATH_REGRESSION=%s\n',pass_fail(gate.pass));
fprintf('CSAC_CONDITIONS_COMPLETE=%d/4\n',csacDone);
fprintf('CSAC_EVALUATIONS_COMPLETE=%d/16\n', ...
    output.csac_evaluations_complete);
fprintf('NUMERICAL_FAILURES=%d\n',output.numerical_failures);
fprintf('FROZEN_SOURCE_MODIFIED=%s\n',yes_no(~frozenPass));
fprintf('READY_FOR_STEP4=%s\n',yes_no(readyForStep4));
end

function assert_model_mismatch_registry(registry,executionRegistry, ...
        cselfIds,csacIds)
ids = [cselfIds;csacIds];
selected = registry(ismember(registry.condition_id,ids),:);
if height(selected) ~= 10 || numel(unique(selected.condition_id)) ~= 10
    error('Phase2:Step3ConditionCount', ...
        'Frozen registry must contain exactly 10 Step 3 conditions.');
end
if nnz(selected.experiment_group == "CSELF_MISMATCH") ~= 6 || ...
        nnz(selected.experiment_group == "CSAC_MISMATCH") ~= 4
    error('Phase2:Step3GroupCount','Step 3 group cardinality mismatch.');
end
if any(arrayfun(@truthy,selected.is_blocked)) || ...
        any(selected.registry_state ~= "FROZEN")
    error('Phase2:Step3RegistryState', ...
        'Step 3 contains blocked or non-frozen conditions.');
end
evaluations = executionRegistry( ...
    ismember(executionRegistry.condition_id,ids) & ...
    executionRegistry.record_type == "MAIN_ALGORITHM_EVALUATION",:);
if height(evaluations) ~= 40 || ...
        any(evaluations.execution_status ~= "PENDING_GATE")
    error('Phase2:Step3EvaluationCount', ...
        'Expected 40 frozen PENDING_GATE evaluation rows.');
end
for id = ids.'
    modes = sort(string(evaluations.algorithm_id( ...
        evaluations.condition_id == id)));
    if ~isequal(modes,["M0";"M2";"M3";"M4"])
        error('Phase2:Step3AlgorithmSet', ...
            'Condition %s does not map to M0/M2/M3/M4.',id);
    end
end
end

function authorization = step2a_authorization(reportPath)
textValue = string(fileread(reportPath));
authorization = struct( ...
    'source',contains(textValue,"NO_FROZEN_SOURCE_DIFF_GATE: PASS"), ...
    'cself',contains(textValue,"CSELF_SPLIT_INTERFACE_GATE: PASS"), ...
    'csac',contains(textValue,"ZERO_INJECTION_REGRESSION: PASS"), ...
    'step2a',contains(textValue,"STEP 2A STATUS: PASS"));
if ~authorization.step2a
    authorization.source = false;
    authorization.cself = false;
    authorization.csac = false;
end
end

function rows = empty_step3_result_table()
rows = empty_result_table();
rows.Cself_truth_pF = zeros(0,1);
rows.Cself_algorithm_pF = zeros(0,1);
rows.Cself_mismatch_pct = zeros(0,1);
rows.CsAC_truth_pF = zeros(0,1);
end

function rows = augment_step3_rows(rows,registryRow,extraNote)
rows.Cself_truth_pF = repmat(registryRow.Cself_truth_pF,height(rows),1);
rows.Cself_algorithm_pF = repmat( ...
    registryRow.Cself_algorithm_pF,height(rows),1);
rows.Cself_mismatch_pct = repmat( ...
    registryRow.Cself_mismatch_pct,height(rows),1);
rows.CsAC_truth_pF = repmat(registryRow.CsAC_truth_pF,height(rows),1);
rows.notes = rows.notes+"; "+string(extraNote);
end

function complete = step3_condition_complete(rows)
complete = height(rows) == 4 && ...
    all(~rows.numerical_failure & ~rows.metric_missing & ...
    rows.registry_match & rows.shared_data_pass);
end

function gate = empty_generic_gate_details()
gate = struct('pass',false,'tolerance',1e-12, ...
    'truth_tolerance',1e-10,'ideal_current_max_difference_A',NaN, ...
    'noisy_current_max_difference_A',NaN, ...
    'reference_max_difference',NaN, ...
    'truth_max_difference',NaN, ...
    'M0_output_max_difference',NaN, ...
    'M2_output_max_difference',NaN, ...
    'M3_output_max_difference',NaN, ...
    'M4_output_max_difference',NaN, ...
    'injection_order', ...
    "ideal current -> CsAC contribution -> noise sigma -> noise", ...
    'shortcut_used',false,'error',"");
end

function gate = generic_zero_path_regression(~)
gate = empty_generic_gate_details();
request = struct('case_name',"Case02_slow_drift", ...
    'Cself_truth_pF',400,'Cself_algorithm_pF',400, ...
    'CsAC_pF',0,'algorithms',["M0" "M2" "M3" "M4"]);
nominal = run_phase2_gate_validation("execute",request);
cfg = patent_default_config();
cfg.model = 'AI6109_MOA_AutoComp9';
cfg.SNR_dB = Inf;
caseRegistry = phase1a_case_registry();
caseInfo = caseRegistry(caseRegistry.case_name == ...
    "Case02_slow_drift",:);
[cleanData,cleanReference] = simulate_phase2_case(cfg, ...
    char(caseInfo.legacy_scenario_name),caseInfo.seed);
signals = generate_coupling_signals( ...
    (0:cfg.Ts:cfg.StopTime).',char(caseInfo.legacy_scenario_name), ...
    caseInfo.seed);
[genericData,metadata] = generic_external_csac_wrapper( ...
    cleanData,cleanReference,0,30,caseInfo.seed+10000,cfg,signals);
ref = reconstruct_refs_from_b(genericData.t,genericData.ub,cfg.f, ...
    cfg.init_start,cfg.init_end,cfg.phase_error_deg);
genericResults = struct();
for mode = ["M0" "M2" "M3" "M4"]
    genericResults.(char(mode)) = run_phase1a_algorithm(mode, ...
        genericData,ref,cfg,repmat(400,1,3));
end
gate.ideal_current_max_difference_A = max(abs([ ...
    metadata.ideal.ia-cleanData.ia; ...
    metadata.ideal.ib-cleanData.ib; ...
    metadata.ideal.ic-cleanData.ic]));
gate.noisy_current_max_difference_A = max(abs([ ...
    genericData.ia-nominal.data.ia; ...
    genericData.ib-nominal.data.ib; ...
    genericData.ic-nominal.data.ic]));
gate.reference_max_difference = max_struct_numeric_difference( ...
    ref,nominal.ref,{'ua','ub','uc','dua','dub','duc', ...
    'A1','A3','phi1','phi3'});
gate.truth_max_difference = max_struct_numeric_difference( ...
    genericData,nominal.data,{'irA','irB','irC','Cs1','Cs2', ...
    'Ca','Cb','Cc'});
for mode = ["M0" "M2" "M3" "M4"]
    gate.(char(mode+"_output_max_difference")) = ...
        algorithm_output_max_difference( ...
        genericResults.(char(mode)),nominal.results.(char(mode)));
end
outputDiffs = [gate.M0_output_max_difference, ...
    gate.M2_output_max_difference,gate.M3_output_max_difference, ...
    gate.M4_output_max_difference];
gate.pass = gate.ideal_current_max_difference_A <= gate.tolerance && ...
    gate.noisy_current_max_difference_A <= gate.tolerance && ...
    gate.reference_max_difference <= gate.tolerance && ...
    gate.truth_max_difference <= gate.truth_tolerance && ...
    all(outputDiffs <= gate.tolerance);
end

function difference = algorithm_output_max_difference(a,b)
difference = max(abs(a.cHist-b.cHist),[],'all');
difference = max(difference,max(abs(a.ir.A-b.ir.A),[],'all'));
difference = max(difference,max(abs(a.ir.B-b.ir.B),[],'all'));
difference = max(difference,max(abs(a.ir.C-b.ir.C),[],'all'));
if isfield(a,'tracker') && isfield(b,'tracker') && ...
        isfield(a.tracker,'cycle') && isfield(b.tracker,'cycle')
    names = intersect(a.tracker.cycle.Properties.VariableNames, ...
        b.tracker.cycle.Properties.VariableNames,'stable');
    for k = 1:numel(names)
        av = a.tracker.cycle.(names{k});
        bv = b.tracker.cycle.(names{k});
        if isnumeric(av) && isnumeric(bv) && isequal(size(av),size(bv))
            difference = max(difference,max(abs(av-bv),[],'all'));
        end
    end
end
end

function difference = max_struct_numeric_difference(a,b,names)
difference = 0;
for k = 1:numel(names)
    av = a.(names{k});
    bv = b.(names{k});
    difference = max(difference,max(abs(av-bv),[],'all'));
end
end

function paths = runner_paths()
matlabRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(matlabRoot);
step1Root = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step1_matrix_spec');
outputRoot = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step2b1_runner_smoke');
paths = struct( ...
    'project_root',projectRoot, ...
    'matlab_root',matlabRoot, ...
    'step1_root',step1Root, ...
    'manifest',fullfile(projectRoot,'paper_research', ...
        'phase1c_m4_method','step6_ablation','tables', ...
        'freeze_hash_manifest.csv'), ...
    'specification',fullfile(step1Root, ...
        'STEP1_PHASE2_MATRIX_SPECIFICATION.md'), ...
    'condition_registry',fullfile(step1Root, ...
        'phase2_condition_registry.csv'), ...
    'execution_registry',fullfile(step1Root, ...
        'phase2_execution_registry.csv'), ...
    'output_root',outputRoot, ...
    'results_csv',fullfile(outputRoot,'step2b1_smoke_results.csv'), ...
    'report',fullfile(outputRoot,'STEP2B1_RUNNER_SMOKE_REPORT.md'));
paths.step2b2_output_root = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step2b2_deterministic_core');
paths.step2b2_results_csv = fullfile(paths.step2b2_output_root, ...
    'step2b2_deterministic_results.csv');
paths.step2b2_report = fullfile(paths.step2b2_output_root, ...
    'STEP2B2_DETERMINISTIC_CORE_REPORT.md');
paths.step2a_report = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step2a_execution_gates', ...
    'STEP2A_EXECUTION_GATES_REPORT.md');
paths.step3_output_root = fullfile(projectRoot,'paper_research', ...
    'phase2_full_validation','step3_model_mismatch');
paths.step3_results_csv = fullfile(paths.step3_output_root, ...
    'step3_model_mismatch_results.csv');
paths.step3_report = fullfile(paths.step3_output_root, ...
    'STEP3_MODEL_MISMATCH_ROBUSTNESS.md');
end

function tableOut = read_registry(path)
% Explicit delimiter avoids R2023b UTF-8 path/header auto-detection issues.
tableOut = readtable(path,'Delimiter',',','TextType','string', ...
    'VariableNamingRule','preserve');
end

function run = execute_condition(conditionRegistry, ...
        executionRegistry,conditionId,allowAuthorizedPending)
if nargin < 4
    allowAuthorizedPending = false;
end
conditionId = string(conditionId);
match = conditionRegistry.condition_id == conditionId;
if nnz(match) ~= 1
    error('Phase2:ConditionRegistryCardinality', ...
        'condition_id %s occurs %d times in condition registry.', ...
        conditionId,nnz(match));
end
row = conditionRegistry(match,:);
if string(row.registry_state) ~= "FROZEN" || truthy(row.is_blocked)
    error('Phase2:ConditionNotExecutable', ...
        'Condition %s is not a frozen executable row.',conditionId);
end

executionRows = executionRegistry( ...
    executionRegistry.condition_id == conditionId & ...
    executionRegistry.record_type == "MAIN_ALGORITHM_EVALUATION",:);
expectedModes = ["M0";"M2";"M3";"M4"];
if height(executionRows) ~= 4 || ...
        ~isequal(sort(string(executionRows.algorithm_id)),expectedModes)
    error('Phase2:ExecutionRegistryCardinality', ...
        'Condition %s must map to exactly M0/M2/M3/M4.',conditionId);
end
statuses = string(executionRows.execution_status);
pendingAuthorized = allowAuthorizedPending && ...
    all(statuses == "PENDING_GATE") && ...
    ismember(string(row.experiment_group), ...
    ["CSELF_MISMATCH","CSAC_MISMATCH"]);
if any(statuses ~= "READY") && ~pendingAuthorized
    error('Phase2:ExecutionRegistryStatus', ...
        'Condition %s has a non-READY evaluation.',conditionId);
end

anchor = find_anchor(conditionRegistry,row);
[targetFactor,targetValue] = target_from_registry(row);
anchorPass = non_target_anchor_match(row,anchor,targetFactor);

[physicalCfg,algorithmCfg,dataCfg,windowCfg,provenance] = ...
    build_configs(row,targetFactor,targetValue);
signals = build_registry_signals(row,physicalCfg);
if string(row.experiment_group) == "CSAC_MISMATCH"
    [data,cleanData,noise] = simulate_registry_csac_condition( ...
        row,physicalCfg,dataCfg.noise_seed);
else
    [data,cleanData,noise] = simulate_registry_condition( ...
        physicalCfg,signals,dataCfg.noise_seed);
end
ref = reconstruct_refs_from_b(data.t,data.ub,algorithmCfg.f, ...
    algorithmCfg.init_start,algorithmCfg.init_end, ...
    algorithmCfg.phase_error_deg);
mappingPass = anchorPass && mapping_audit(row,physicalCfg, ...
    algorithmCfg,signals,data,cleanData,noise,ref);

isFault = string(row.fault_mode) == "PERSISTENT_B_RESISTIVE";
if isFault
    counterfactualData = remove_fault_component(data,signals.fault_scale);
else
    counterfactualData = struct();
end

dataSignature = physical_data_signature(data);
truthSignature = truth_signature(data,signals);
windowSignature = struct_signature(windowCfg);
referenceSignature = reference_signature(ref);
sharedSignature = bytes_sha256(unicode2native(char( ...
    dataSignature+truthSignature+windowSignature+referenceSignature), ...
    'UTF-8'));

resultRows = empty_result_table();
algorithmResults = struct();
counterfactualResults = struct();
for mode = expectedModes.'
    result = run_phase1a_algorithm(mode,data,ref,algorithmCfg, ...
        repmat(row.Cself_algorithm_pF,1,3));
    algorithmResults.(char(mode)) = result;
    if isFault
        counterfactual = run_phase1a_algorithm(mode, ...
            counterfactualData,ref,algorithmCfg, ...
            repmat(row.Cself_algorithm_pF,1,3));
        counterfactualResults.(char(mode)) = counterfactual;
    else
        counterfactual = struct();
    end
    metrics = extract_frozen_metrics(mode,result,counterfactual, ...
        data,algorithmCfg,windowCfg,isFault);
    requiredPass = required_outputs_exist(result) && ...
        required_metrics_exist(mode,metrics,isFault);
    numericalFailure = ~core_outputs_finite(data,ref,result) || ...
        ~requiredPass;
    notes = provenance_note(provenance,isFault,row);
    resultRows = [resultRows;make_result_row(conditionId, ...
        row.experiment_group,mode,targetFactor,targetValue, ...
        row.anchor_case,sharedSignature,metrics,numericalFailure,~requiredPass, ...
        mappingPass,true,false,notes)]; %#ok<AGROW>
end

sharedDataPass = numel(unique(resultRows.data_signature)) == 1 && ...
    all(resultRows.data_signature == sharedSignature);
resultRows.shared_data_pass(:) = sharedDataPass;
run = struct( ...
    'condition_id',conditionId, ...
    'condition_registry_row',row, ...
    'execution_registry_rows',executionRows, ...
    'anchor_registry_row',anchor, ...
    'target_factor',targetFactor, ...
    'target_value',targetValue, ...
    'physical_truth_config',physicalCfg, ...
    'algorithm_assumption_config',algorithmCfg, ...
    'data_generation_config',dataCfg, ...
    'evaluation_window_config',windowCfg, ...
    'provenance',provenance, ...
    'signals',signals, ...
    'data',data, ...
    'clean_data',cleanData, ...
    'noise',noise, ...
    'reference',ref, ...
    'data_signature',dataSignature, ...
    'truth_signature',truthSignature, ...
    'window_signature',windowSignature, ...
    'reference_signature',referenceSignature, ...
    'shared_execution_signature',sharedSignature, ...
    'algorithm_results',algorithmResults, ...
    'counterfactual_results',counterfactualResults, ...
    'registry_mapping_pass',mappingPass, ...
    'shared_data_pass',sharedDataPass, ...
    'rows',resultRows);
end

function anchor = find_anchor(registry,row)
isAnchor = false(height(registry),1);
for k = 1:height(registry)
    isAnchor(k) = truthy(registry.is_anchor(k));
end
match = registry.anchor_case == row.anchor_case & isAnchor;
if nnz(match) ~= 1
    error('Phase2:AnchorCardinality', ...
        'Expected one anchor for %s.',string(row.anchor_case));
end
anchor = registry(match,:);
end

function [name,value] = target_from_registry(row)
switch string(row.experiment_group)
    case "FAULT_AMPLITUDE"
        name = "fault_factor"; value = row.fault_factor;
    case "SNR"
        name = "SNR_dB"; value = row.SNR_dB;
    case "REFERENCE_PHASE"
        name = "reference_phase_error_deg";
        value = row.reference_phase_error_deg;
    case "THIRD_HARMONIC"
        name = "h3_ratio"; value = row.h3_ratio;
    case "NEGATIVE_SEQUENCE"
        name = "negative_sequence_pu";
        value = row.negative_sequence_pu;
    case "CSELF_MISMATCH"
        name = "Cself_truth_pF";
        value = row.Cself_truth_pF;
    case "CSAC_MISMATCH"
        name = "CsAC_truth_pF";
        value = row.CsAC_truth_pF;
    otherwise
        error('Phase2:UnsupportedFamily', ...
            'Unsupported deterministic family: %s.',row.experiment_group);
end
if ~(isnumeric(value) && isscalar(value) && ~isnan(value))
    error('Phase2:InvalidTarget','Target %s is not a valid scalar.',name);
end
end

function pass = non_target_anchor_match(row,anchor,targetName)
physicalFields = [ ...
    "fault_factor","fault_start_s","fault_ramp_up_s", ...
    "fault_ramp_end_s","fault_mode", ...
    "Cs1_initial_pF","Cs2_initial_pF","Cs1_final_pF", ...
    "Cs2_final_pF","drift_direction_id","drift_delta_Cs1_pF", ...
    "drift_delta_Cs2_pF","drift_total_norm_pF", ...
    "drift_rate_multiplier","drift_start_s","drift_end_s", ...
    "drift_duration_s","SNR_dB","noise_mode", ...
    "deterministic_seed","reference_phase_error_deg", ...
    "h3_ratio","h3_phase_deg","negative_sequence_pu", ...
    "negative_sequence_convention_status","Cself_truth_pF", ...
    "Cself_algorithm_pF","CsAC_truth_pF", ...
    "evaluation_window_set_id","simulation_stop_s"];
pass = true;
for name = physicalFields
    if name == targetName || ...
            (targetName == "SNR_dB" && name == "noise_mode")
        continue
    end
    if ~physical_field_equal(name,row.(char(name)),anchor.(char(name)))
        pass = false;
        return
    end
end
end

function equal = physical_field_equal(name,conditionValue,anchorValue)
% The frozen Case06 anchor stores an unspecified base-rate multiplier as
% NaN, while its one-factor descendants explicitly encode the same nominal
% trajectory rate as 1. This is a schema normalization, not a factor change.
if name == "drift_rate_multiplier" && isnumeric(anchorValue) && ...
        isnan(anchorValue) && isnumeric(conditionValue) && ...
        conditionValue == 1
    equal = true;
else
    equal = registry_value_equal(conditionValue,anchorValue);
end
end

function equal = registry_value_equal(a,b)
if isnumeric(a) && isnumeric(b)
    equal = (isnan(a) && isnan(b)) || ...
        (isfinite(a) && isfinite(b) && abs(a-b) <= 1e-12);
else
    equal = string(a) == string(b);
end
end

function [physicalCfg,algorithmCfg,dataCfg,windowCfg,provenance] = ...
        build_configs(row,targetName,targetValue)
physicalCfg = patent_default_config();
physicalCfg.model = 'AI6109_MOA_AutoComp9';
physicalCfg.StopTime = row.simulation_stop_s;
physicalCfg.SNR_dB = row.SNR_dB;
physicalCfg.h3_ratio = row.h3_ratio;
physicalCfg.phi3_deg = row.h3_phase_deg;
physicalCfg.Vneg_pu = row.negative_sequence_pu;
physicalCfg.Cself_pF = row.Cself_truth_pF;
physicalCfg.phase_error_deg = 0;
algorithmCfg = physicalCfg;
algorithmCfg.Cself_pF = row.Cself_algorithm_pF;
algorithmCfg.phase_error_deg = row.reference_phase_error_deg;
dataCfg = struct( ...
    'mode',string(row.data_generation_mode), ...
    'noise_mode',string(row.noise_mode), ...
    'deterministic_seed',row.deterministic_seed, ...
    'noise_seed',row.deterministic_seed+10000, ...
    'anchor_case',string(row.anchor_case), ...
    'fault_mode',string(row.fault_mode));
windowCfg = evaluation_window_config( ...
    string(row.evaluation_window_set_id),physicalCfg);
provenance = struct( ...
    'condition_id',string(row.condition_id), ...
    'registry_version',string(row.registry_version), ...
    'registry_state',string(row.registry_state), ...
    'anchor_case',string(row.anchor_case), ...
    'target_factor',targetName, ...
    'target_value',targetValue, ...
    'interpretation_flag',string(row.interpretation_flag), ...
    'negative_sequence_convention_status', ...
        string(row.negative_sequence_convention_status), ...
    'evaluation_window_set_id', ...
        string(row.evaluation_window_set_id));
end

function windows = evaluation_window_config(id,cfg)
windows = struct('id',id,'metric_start_s',cfg.metric_start, ...
    'metric_end_s',cfg.StopTime+cfg.Ts,'pre_start_s',NaN, ...
    'pre_end_s',NaN,'fault_start_s',NaN,'fault_end_s',NaN, ...
    'response_start_s',NaN);
switch id
    case "WINDOWSET_PERSISTENT_FAULT"
        windows.pre_start_s = 2.60;
        windows.pre_end_s = 2.90;
        windows.fault_start_s = 3.40;
        windows.fault_end_s = 3.80;
        windows.response_start_s = 3.00;
    case "WINDOWSET_C02_TRACKING"
        % The formal healthy/drift metric begins at frozen cfg.metric_start.
    otherwise
        error('Phase2:UnsupportedWindowSet', ...
            'Unsupported Step 2B-1 window set: %s.',id);
end
end

function signals = build_registry_signals(row,cfg)
t = (0:cfg.Ts:cfg.StopTime).';
base = generate_coupling_signals(t,char(row.anchor_case), ...
    row.deterministic_seed);
signals = base;
if string(row.fault_mode) == "PERSISTENT_B_RESISTIVE"
    progress = smooth_step(t,row.fault_start_s,row.fault_ramp_end_s);
    signals.fault_scale = 1+(row.fault_factor-1)*progress;
else
    signals.fault_scale = ones(size(t));
end
end

function y = smooth_step(t,t0,t1)
x = min(max((t-t0)/(t1-t0),0),1);
y = x.^2.*(3-2*x);
end

function [data,cleanData,noise] = simulate_registry_condition( ...
        cfg,signals,noiseSeed)
zero = zeros(size(signals.t));
cleanData = run_once(cfg,signals,zero,zero,zero);
rng(noiseSeed);
noise = struct( ...
    'A',noise_for_snr(cleanData.ia,cfg.SNR_dB), ...
    'B',noise_for_snr(cleanData.ib,cfg.SNR_dB), ...
    'C',noise_for_snr(cleanData.ic,cfg.SNR_dB));
data = run_once(cfg,signals,noise.A,noise.B,noise.C);
for name = ["Ca","Cb","Cc"]
    data.(char(name)) = cfg.Cself_pF*ones(size(data.t));
    cleanData.(char(name)) = cfg.Cself_pF*ones(size(data.t));
end
data.scenario = "phase2_registry";
cleanData.scenario = "phase2_registry_clean";
data.current_source = "simulink";
cleanData.current_source = "simulink";
end

function [data,idealData,noise] = simulate_registry_csac_condition( ...
        row,cfg,noiseSeed)
% External structural-mismatch path. AutoComp9 remains unchanged.
caseRegistry = phase1a_case_registry();
caseInfo = caseRegistry(caseRegistry.case_name == row.anchor_case,:);
if height(caseInfo) ~= 1 || string(row.anchor_case) ~= "Case02_slow_drift"
    error('Phase2:CsACAnchor', ...
        'CsAC formal rows must use the frozen Case02 anchor.');
end
cleanCfg = cfg;
cleanCfg.SNR_dB = Inf;
[cleanData,cleanReference] = simulate_phase2_case(cleanCfg, ...
    char(caseInfo.legacy_scenario_name),caseInfo.seed);
signals = generate_coupling_signals( ...
    (0:cfg.Ts:cfg.StopTime).',char(caseInfo.legacy_scenario_name), ...
    caseInfo.seed);
[data,metadata] = generic_external_csac_wrapper(cleanData, ...
    cleanReference,row.CsAC_truth_pF,cfg.SNR_dB,noiseSeed,cfg,signals);
idealData = metadata.ideal;
noise = metadata.noise;
end

function [data,metadata] = generic_external_csac_wrapper( ...
        cleanData,cleanReference,CsACpF,snrDB,rngSeed,cfg,signals)
% This function deliberately has no CsAC==0 shortcut. Zero and nonzero
% injections traverse the identical ideal -> contribution -> sigma -> RNG
% -> noisy-current chain required by the Step 3 strengthened gate.
duA = gradient(cleanData.ua,cleanData.t);
duC = gradient(cleanData.uc,cleanData.t);
contribution = CsACpF*1e-12*(duA-duC);
ideal = cleanData;
ideal.ia = cleanData.ia+contribution;
ideal.ib = cleanData.ib+zeros(size(contribution));
ideal.ic = cleanData.ic-contribution;
noiseBasis = cleanReference;
noiseBasis.ia = cleanReference.ia+contribution;
noiseBasis.ib = cleanReference.ib+zeros(size(contribution));
noiseBasis.ic = cleanReference.ic-contribution;
sigma = struct( ...
    'A',rms(noiseBasis.ia)/10^(snrDB/20), ...
    'B',rms(noiseBasis.ib)/10^(snrDB/20), ...
    'C',rms(noiseBasis.ic)/10^(snrDB/20));
rng(rngSeed);
noise = struct( ...
    'A',sigma.A*randn(size(ideal.ia)), ...
    'B',sigma.B*randn(size(ideal.ib)), ...
    'C',sigma.C*randn(size(ideal.ic)));
% Route the structural contribution and newly generated noise through the
% existing additive current inputs. This preserves the model's floating-
% point operation path while keeping the injection external to AutoComp9.
data = run_once(cfg,signals,contribution+noise.A,noise.B, ...
    -contribution+noise.C);
for name = ["Ca","Cb","Cc"]
    data.(char(name)) = cfg.Cself_pF*ones(size(data.t));
end
data.CsAC_pF = CsACpF*ones(size(data.t));
ideal.CsAC_pF = data.CsAC_pF;
data.scenario = "phase2_registry_csac";
ideal.scenario = "phase2_registry_csac_ideal";
data.current_source = "phase2_external_csac_generic_path";
ideal.current_source = "phase2_external_csac_generic_path_ideal";
metadata = struct('ideal',ideal,'noise_basis',noiseBasis, ...
    'noise',noise,'sigma',sigma,'duA',duA,'duC',duC, ...
    'contribution',contribution,'rng_seed',rngSeed, ...
    'injection_order', ...
    "ideal current -> CsAC contribution -> noise sigma -> noise");
end

function data = run_once(cfg,signals,noiseA,noiseB,noiseC)
in = Simulink.SimulationInput(cfg.model);
vars = struct('StopTime',cfg.StopTime,'h3_ratio',cfg.h3_ratio, ...
    'phi3_deg',cfg.phi3_deg,'Vneg_pu',cfg.Vneg_pu,'f',cfg.f, ...
    'Un_LL',cfg.Un_LL,'C0',cfg.C0,'C_moa',cfg.C_moa, ...
    'C1',cfg.C1,'C2',cfg.C2,'Vref_moa',cfg.moa_Vref_V, ...
    'Iref_moa',cfg.moa_Iref_A,'alpha_moa',cfg.moa_alpha, ...
    'Ts',cfg.Ts,'Ts_model',cfg.Ts,'Cself_pF',cfg.Cself_pF, ...
    'Ccoupling_disabled_F',1e-18);
names = fieldnames(vars);
for k = 1:numel(names)
    in = in.setVariable(names{k},vars.(names{k}));
end
dataset = Simulink.SimulationData.Dataset;
dataset{1} = timeseries(signals.Cs1_pF,signals.t);
dataset{2} = timeseries(signals.Cs2_pF,signals.t);
dataset{3} = timeseries(signals.fault_scale,signals.t);
dataset{4} = timeseries(noiseA,signals.t);
dataset{5} = timeseries(noiseB,signals.t);
dataset{6} = timeseries(noiseC,signals.t);
in = in.setExternalInput(dataset);
in = in.setModelParameter('StopTime',num2str(cfg.StopTime));
out = sim(in);
[data.t,data.ua] = read_signal(out,'uA');
[~,data.ub] = read_signal(out,'uB');
[~,data.uc] = read_signal(out,'uC');
[~,data.ia] = read_signal(out,'iA_total');
[~,data.ib] = read_signal(out,'iB_total');
[~,data.ic] = read_signal(out,'iC_total');
[~,data.irA] = read_signal(out,'iA_R_true');
[~,data.irB] = read_signal(out,'iB_R_true');
[~,data.irC] = read_signal(out,'iC_R_true');
[~,data.Cs1] = read_signal(out,'Cs1_true');
[~,data.Cs2] = read_signal(out,'Cs2_true');
end

function noise = noise_for_snr(x,snrDB)
if isfinite(snrDB)
    noise = rms(x)/10^(snrDB/20)*randn(size(x));
else
    noise = zeros(size(x));
end
end

function [t,x] = read_signal(out,name)
s = out.get(name);
if isa(s,'timeseries')
    t = s.Time; x = s.Data;
else
    t = s.time; x = s.signals.values;
end
t = t(:); x = squeeze(x); x = x(:);
end

function pass = mapping_audit(row,physicalCfg,algorithmCfg,signals, ...
        data,cleanData,noise,ref)
tol = 1e-9;
pass = ...
    numeric_scalar_equal(physicalCfg.SNR_dB,row.SNR_dB,tol) && ...
    abs(physicalCfg.h3_ratio-row.h3_ratio) <= tol && ...
    abs(physicalCfg.phi3_deg-row.h3_phase_deg) <= tol && ...
    abs(physicalCfg.Vneg_pu-row.negative_sequence_pu) <= tol && ...
    abs(physicalCfg.Cself_pF-row.Cself_truth_pF) <= tol && ...
    abs(algorithmCfg.Cself_pF-row.Cself_algorithm_pF) <= tol && ...
    abs(algorithmCfg.phase_error_deg- ...
        row.reference_phase_error_deg) <= tol && ...
    abs(signals.Cs1_pF(1)-row.Cs1_initial_pF) <= tol && ...
    abs(signals.Cs2_pF(1)-row.Cs2_initial_pF) <= tol && ...
    max(abs(data.Cs1-signals.Cs1_pF)) <= tol && ...
    max(abs(data.Cs2-signals.Cs2_pF)) <= tol && ...
    all(isfinite([noise.A;noise.B;noise.C]));
if string(row.experiment_group) == "CSAC_MISMATCH"
    pass = pass && isfield(data,'CsAC_pF') && ...
        max(abs(data.CsAC_pF-row.CsAC_truth_pF)) <= tol;
end
if isfinite(row.Cs1_final_pF)
    pass = pass && abs(signals.Cs1_pF(end)-row.Cs1_final_pF) <= tol;
end
if isfinite(row.Cs2_final_pF)
    pass = pass && abs(signals.Cs2_pF(end)-row.Cs2_final_pF) <= tol;
end
if string(row.fault_mode) == "PERSISTENT_B_RESISTIVE"
    pass = pass && abs(max(signals.fault_scale)-row.fault_factor) <= tol && ...
        all(signals.fault_scale(signals.t < row.fault_start_s) == 1);
else
    pass = pass && all(signals.fault_scale == 1);
end
zeroRef = reconstruct_refs_from_b(data.t,data.ub,algorithmCfg.f, ...
    algorithmCfg.init_start,algorithmCfg.init_end,0);
phase1Delta = wrap_to_180(rad2deg(ref.phi1-zeroRef.phi1));
phase3Delta = wrap_to_180(rad2deg(ref.phi3-zeroRef.phi3));
pass = pass && abs(phase1Delta-row.reference_phase_error_deg) < 1e-10 && ...
    abs(phase3Delta-3*row.reference_phase_error_deg) < 1e-10;
if string(row.experiment_group) == "THIRD_HARMONIC"
    [fundamental,third] = voltage_harmonics(data.t,data.ub,physicalCfg.f);
    pass = pass && abs(third/fundamental-row.h3_ratio) < 1e-8;
end
if string(row.experiment_group) == "NEGATIVE_SEQUENCE"
    balancedMismatch = rms(data.ua-zeroRef.ua)+rms(data.uc-zeroRef.uc);
    pass = pass && row.negative_sequence_pu > 0 && ...
        balancedMismatch > 1e-6 && ...
        string(row.negative_sequence_convention_status) == ...
        "UNRESOLVED_INTERNAL_CONVENTION" && ...
        string(row.interpretation_flag) == ...
        "CONFIGURED_VALIDITY_BOUNDARY_ONLY";
end
pass = pass && max(abs((data.ia-cleanData.ia)-noise.A)) < 1e-12 && ...
    max(abs((data.ib-cleanData.ib)-noise.B)) < 1e-12 && ...
    max(abs((data.ic-cleanData.ic)-noise.C)) < 1e-12;
if isinf(row.SNR_dB)
    pass = pass && string(row.noise_mode) == "NOISE_FREE" && ...
        all(noise.A == 0) && all(noise.B == 0) && all(noise.C == 0);
else
    pass = pass && string(row.noise_mode) == ...
        "PER_PHASE_GAUSSIAN_TOTAL_CURRENT_RMS_SCALED";
end
end

function equal = numeric_scalar_equal(a,b,tolerance)
equal = (isinf(a) && isinf(b) && sign(a) == sign(b)) || ...
    (isfinite(a) && isfinite(b) && abs(a-b) <= tolerance);
end

function [fundamental,third] = voltage_harmonics(t,x,f)
w = 2*pi*f;
index = t >= 0.1 & t < 0.7;
matrix = [sin(w*t(index)),cos(w*t(index)), ...
    sin(3*w*t(index)),cos(3*w*t(index)),ones(nnz(index),1)];
beta = matrix\x(index);
fundamental = hypot(beta(1),beta(2));
third = hypot(beta(3),beta(4));
end

function dataCF = remove_fault_component(data,faultScale)
dataCF = data;
faultIncrementB = (1-1./faultScale).*data.irB;
dataCF.ib = data.ib-faultIncrementB;
dataCF.irB = data.irB-faultIncrementB;
dataCF.scenario = "phase2_registry_counterfactual";
end

function metrics = extract_frozen_metrics(mode,result,counterfactual, ...
        data,cfg,windows,isFault)
metricIndex = data.t >= windows.metric_start_s & ...
    data.t < windows.metric_end_s;
legacy = evaluate_case_metrics(data,result.ir,result.cHist, ...
    mode,"Phase2_registry",cfg);
metrics = struct( ...
    'Cs1_RMSE_pF',sqrt(mean((result.cHist(metricIndex,1)- ...
        data.Cs1(metricIndex)).^2)), ...
    'Cs2_RMSE_pF',sqrt(mean((result.cHist(metricIndex,2)- ...
        data.Cs2(metricIndex)).^2)), ...
    'Cs1_max_abs_error_pF',max(abs(result.cHist(metricIndex,1)- ...
        data.Cs1(metricIndex))), ...
    'Cs2_max_abs_error_pF',max(abs(result.cHist(metricIndex,2)- ...
        data.Cs2(metricIndex))), ...
    'B_resistive_fundamental_error_pct',legacy.B_FundErr_pct, ...
    'fault_factor_true',NaN,'fault_factor_est',NaN, ...
    'fault_retention_error_pct',NaN, ...
    'DeltaCs1_fault_induced_pF',NaN, ...
    'DeltaCs2_fault_induced_pF',NaN, ...
    'Cs_fault_induced_bias_norm_pF',NaN, ...
    'hard_gate_active_ratio',NaN,'hard_gate_latency_s',NaN, ...
    'mean_update_weight',NaN, ...
    'unnecessary_suppression_ratio',NaN, ...
    'information_suppression_ratio_J',NaN, ...
    'information_suppression_ratio_h',NaN);
if isFault
    pre = data.t >= windows.pre_start_s & data.t < windows.pre_end_s;
    post = data.t >= windows.fault_start_s & data.t < windows.fault_end_s;
    metrics.fault_factor_true = fault_factor( ...
        data.t,data.irB,pre,post,cfg.f);
    metrics.fault_factor_est = fault_factor( ...
        data.t,result.ir.B,pre,post,cfg.f);
    metrics.fault_retention_error_pct = ...
        (metrics.fault_factor_est-metrics.fault_factor_true)/ ...
        metrics.fault_factor_true*100;
    actualChange = parameter_change(result.cHist,pre,post);
    cfChange = parameter_change(counterfactual.cHist,pre,post);
    induced = actualChange-cfChange;
    metrics.DeltaCs1_fault_induced_pF = induced(1);
    metrics.DeltaCs2_fault_induced_pF = induced(2);
    metrics.Cs_fault_induced_bias_norm_pF = hypot(induced(1),induced(2));
end
if mode == "M3"
    cycle = result.tracker.cycle;
    active = cycle.gate > 0;
    if isFault
        response = cycle.time_s >= windows.response_start_s;
    else
        response = true(height(cycle),1);
    end
    metrics.hard_gate_active_ratio = mean(active(response));
    first = find(active & response,1,'first');
    if ~isempty(first) && isFault
        metrics.hard_gate_latency_s = ...
            cycle.time_s(first)-windows.response_start_s;
    end
elseif mode == "M4"
    cycle = result.tracker.cycle;
    if isFault
        samplesPerCycle = round((1/median(diff(data.t)))/cfg.f);
        cycleStart = cycle.time_s-(samplesPerCycle-1)*median(diff(data.t));
        index = cycleStart >= windows.fault_start_s & ...
            cycle.time_s < windows.fault_end_s;
        metrics.mean_update_weight = mean(cycle.update_weight(index));
        [metrics.information_suppression_ratio_J, ...
            metrics.information_suppression_ratio_h] = ...
            information_suppression_ratios(cycle,index);
    else
        metrics.mean_update_weight = mean(cycle.update_weight);
        metrics.unnecessary_suppression_ratio = ...
            mean(1-cycle.update_weight);
    end
end
end

function [ratioJ,ratioH] = information_suppression_ratios(cycle,index)
jRaw = cycle{index,{'J_increment_raw_11','J_increment_raw_12', ...
    'J_increment_raw_21','J_increment_raw_22'}};
jApplied = cycle{index,{'J_increment_applied_11', ...
    'J_increment_applied_12','J_increment_applied_21', ...
    'J_increment_applied_22'}};
hRaw = cycle{index,{'h_increment_raw_1','h_increment_raw_2'}};
hApplied = cycle{index,{'h_increment_applied_1', ...
    'h_increment_applied_2'}};
ratioJ = sum(vecnorm(jRaw-jApplied,2,2))/ ...
    (sum(vecnorm(jRaw,2,2))+eps);
ratioH = sum(vecnorm(hRaw-hApplied,2,2))/ ...
    (sum(vecnorm(hRaw,2,2))+eps);
end

function change = parameter_change(cHist,pre,post)
change = mean(cHist(post,:),1)-mean(cHist(pre,:),1);
end

function value = fault_factor(t,x,pre,post,f)
value = fundamental_rms(t(post),x(post),f)/ ...
    (fundamental_rms(t(pre),x(pre),f)+eps);
end

function value = fundamental_rms(t,x,f)
w = 2*pi*f;
coefficients = [sin(w*t),cos(w*t),ones(size(t))]\x;
value = hypot(coefficients(1),coefficients(2))/sqrt(2);
end

function pass = required_outputs_exist(result)
pass = isstruct(result) && ...
    all(isfield(result,{'algorithm_mode','cHist','ir','tracker'})) && ...
    isstruct(result.ir) && all(isfield(result.ir,{'A','B','C'}));
end

function pass = required_metrics_exist(mode,metrics,isFault)
base = [metrics.Cs1_RMSE_pF,metrics.Cs2_RMSE_pF, ...
    metrics.Cs1_max_abs_error_pF,metrics.Cs2_max_abs_error_pF, ...
    metrics.B_resistive_fundamental_error_pct];
pass = all(isfinite(base));
if isFault
    faultValues = [metrics.fault_factor_true,metrics.fault_factor_est, ...
        metrics.fault_retention_error_pct, ...
        metrics.DeltaCs1_fault_induced_pF, ...
        metrics.DeltaCs2_fault_induced_pF, ...
        metrics.Cs_fault_induced_bias_norm_pF];
    pass = pass && all(isfinite(faultValues));
end
if mode == "M3"
    pass = pass && isfinite(metrics.hard_gate_active_ratio);
elseif mode == "M4"
    pass = pass && isfinite(metrics.mean_update_weight);
    if ~isFault
        pass = pass && isfinite(metrics.unnecessary_suppression_ratio);
    end
end
end

function pass = core_outputs_finite(data,ref,result)
dataFields = {'t','ua','ub','uc','ia','ib','ic','irA','irB','irC', ...
    'Cs1','Cs2'};
refFields = {'ua','ub','uc','dua','dub','duc'};
pass = true;
for k = 1:numel(dataFields)
    pass = pass && all(isfinite(data.(dataFields{k})));
end
for k = 1:numel(refFields)
    pass = pass && all(isfinite(ref.(refFields{k})));
end
pass = pass && all(isfinite(result.cHist),'all') && ...
    all(isfinite(result.ir.A)) && all(isfinite(result.ir.B)) && ...
    all(isfinite(result.ir.C));
end

function note = provenance_note(provenance,isFault,row)
note = "anchor="+provenance.anchor_case+ ...
    "; window="+provenance.evaluation_window_set_id+ ...
    "; seed="+string(row.deterministic_seed)+ ...
    "; registry="+provenance.registry_version;
if isFault
    note = note+"; paired_counterfactual_metric_branch=YES";
end
if string(row.experiment_group) == "NEGATIVE_SEQUENCE"
    note = note+"; NEGATIVE_SEQUENCE_INTERNAL_CONVENTION=UNRESOLVED"+ ...
        "; INTERPRETATION=CONFIGURED_VALIDITY_BOUNDARY_ONLY";
end
end

function row = make_result_row(conditionId,group,mode,targetFactor, ...
        targetValue,anchorCase,signature,m,numericalFailure,metricMissing, ...
        registryMatch,sharedPass,frozenPass,notes)
row = table("MAIN",string(conditionId),string(group),string(mode), ...
    string(targetFactor),targetValue,string(anchorCase),string(signature), ...
    m.Cs1_RMSE_pF,m.Cs2_RMSE_pF, ...
    m.Cs1_max_abs_error_pF,m.Cs2_max_abs_error_pF, ...
    m.B_resistive_fundamental_error_pct, ...
    m.fault_factor_true,m.fault_factor_est, ...
    m.fault_retention_error_pct,m.DeltaCs1_fault_induced_pF, ...
    m.DeltaCs2_fault_induced_pF,m.Cs_fault_induced_bias_norm_pF, ...
    m.hard_gate_active_ratio,m.hard_gate_latency_s, ...
    m.mean_update_weight,m.unnecessary_suppression_ratio, ...
    m.information_suppression_ratio_J, ...
    m.information_suppression_ratio_h, ...
    logical(numericalFailure),logical(metricMissing), ...
    logical(registryMatch),logical(sharedPass),logical(frozenPass), ...
    string(notes),'VariableNames',result_variable_names());
end

function rows = failure_rows(registry,conditionId,exception)
match = registry.condition_id == conditionId;
if nnz(match) == 1
    row = registry(match,:);
    group = string(row.experiment_group);
    anchorCase = string(row.anchor_case);
    try
        [targetFactor,targetValue] = target_from_registry(row);
    catch
        targetFactor = "UNKNOWN"; targetValue = NaN;
    end
else
    group = "UNKNOWN"; anchorCase = "UNKNOWN";
    targetFactor = "UNKNOWN"; targetValue = NaN;
end
metrics = empty_metrics();
rows = empty_result_table();
for mode = ["M0","M2","M3","M4"]
    rows = [rows;make_result_row(conditionId,group,mode, ...
        targetFactor,targetValue,anchorCase,"",metrics,true,true,false,false, ...
        false,string(exception.identifier)+": "+ ...
        string(exception.message))]; %#ok<AGROW>
end
end

function metrics = empty_metrics()
metrics = struct('Cs1_RMSE_pF',NaN,'Cs2_RMSE_pF',NaN, ...
    'Cs1_max_abs_error_pF',NaN,'Cs2_max_abs_error_pF',NaN, ...
    'B_resistive_fundamental_error_pct',NaN, ...
    'fault_factor_true',NaN,'fault_factor_est',NaN, ...
    'fault_retention_error_pct',NaN, ...
    'DeltaCs1_fault_induced_pF',NaN, ...
    'DeltaCs2_fault_induced_pF',NaN, ...
    'Cs_fault_induced_bias_norm_pF',NaN, ...
    'hard_gate_active_ratio',NaN,'hard_gate_latency_s',NaN, ...
    'mean_update_weight',NaN,'unnecessary_suppression_ratio',NaN, ...
    'information_suppression_ratio_J',NaN, ...
    'information_suppression_ratio_h',NaN);
end

function tableOut = empty_result_table()
names = result_variable_names();
types = {'string','string','string','string','string','double', ...
    'string','string','double','double','double','double','double', ...
    'double','double','double','double','double','double','double', ...
    'double','double','double','double','double','logical','logical', ...
    'logical','logical','logical','string'};
tableOut = table('Size',[0,numel(names)], ...
    'VariableTypes',types,'VariableNames',names);
end

function names = result_variable_names()
names = {'record_type','condition_id','experiment_group','algorithm_id', ...
    'target_factor','target_value','anchor_case','data_signature', ...
    'Cs1_RMSE_pF','Cs2_RMSE_pF', ...
    'Cs1_max_abs_error_pF','Cs2_max_abs_error_pF', ...
    'B_resistive_fundamental_error_pct', ...
    'fault_factor_true','fault_factor_est','fault_retention_error_pct', ...
    'DeltaCs1_fault_induced_pF','DeltaCs2_fault_induced_pF', ...
    'Cs_fault_induced_bias_norm_pF','hard_gate_active_ratio', ...
    'hard_gate_latency_s','mean_update_weight', ...
    'unnecessary_suppression_ratio','information_suppression_ratio_J', ...
    'information_suppression_ratio_h','numerical_failure', ...
    'metric_missing','registry_match','shared_data_pass', ...
    'frozen_integrity_pass','notes'};
end

function signature = physical_data_signature(data)
signature = numeric_fields_signature(data, ...
    {'t','ua','ub','uc','ia','ib','ic','irA','irB','irC','Cs1','Cs2'});
end

function signature = truth_signature(data,signals)
temporary = struct('t',data.t,'irA',data.irA,'irB',data.irB, ...
    'irC',data.irC,'Cs1',data.Cs1,'Cs2',data.Cs2, ...
    'fault_scale',signals.fault_scale);
signature = numeric_fields_signature(temporary, ...
    {'t','irA','irB','irC','Cs1','Cs2','fault_scale'});
end

function signature = reference_signature(ref)
signature = numeric_fields_signature(ref, ...
    {'ua','ub','uc','dua','dub','duc'});
end

function signature = numeric_fields_signature(container,names)
digester = java.security.MessageDigest.getInstance('SHA-256');
for k = 1:numel(names)
    digester.update(typecast(double(container.(names{k})(:)),'uint8'));
end
hashBytes = typecast(digester.digest(),'uint8');
signature = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function signature = struct_signature(value)
textValue = string(jsonencode(value));
signature = bytes_sha256(unicode2native(char(textValue),'UTF-8'));
end

function integrity = capture_frozen_integrity(paths)
manifest = read_registry(paths.manifest);
n = height(manifest);
labels = strings(n+3,1);
filePaths = strings(n+3,1);
expected = strings(n+3,1);
actual = strings(n+3,1);
for k = 1:n
    labels(k) = "PHASE1:"+manifest.roles(k)+":"+ ...
        manifest.relative_path(k);
    filePaths(k) = fullfile(paths.project_root, ...
        char(manifest.relative_path(k)));
    expected(k) = upper(manifest.sha256(k));
    actual(k) = file_sha256(filePaths(k));
end
labels(n+1:n+3) = ["STEP1_SPECIFICATION"; ...
    "STEP1_CONDITION_REGISTRY";"STEP1_EXECUTION_REGISTRY"];
filePaths(n+1:n+3) = [string(paths.specification); ...
    string(paths.condition_registry);string(paths.execution_registry)];
expected(n+1:n+3) = [ ...
    "9FAB573BCE6D5D0A1F3F6A569771F5B1C69706AB6E6E38FD97843BF41B931531"; ...
    "8A498E19A455C13CAA7B5371BE2F933CA7B7637B893C656C92DA84D88D1938BE"; ...
    "974B8874404C46C4B549CAD8E2D52CCCC7F1D4F81D68AF8911201307230394D7"];
actual(n+1) = canonical_specification_sha256(paths.specification);
actual(n+2) = file_sha256(paths.condition_registry);
actual(n+3) = file_sha256(paths.execution_registry);
itemPass = expected == actual;
integrity = struct('labels',labels,'paths',filePaths, ...
    'expected_sha256',expected,'actual_sha256',actual, ...
    'item_pass',itemPass,'phase1_count',n, ...
    'phase1_pass_count',nnz(itemPass(1:n)), ...
    'step1_pass_count',nnz(itemPass(n+1:end)), ...
    'pass',all(itemPass));
end

function hash = canonical_specification_sha256(path)
textValue = fileread(path);
pattern = '(specification_sha256_canonical:\s*)[0-9A-Fa-f]{64}';
replacement = '$1<SELF_SHA256_CANONICAL_PLACEHOLDER>';
canonical = regexprep(textValue,pattern,replacement,'once');
if strcmp(canonical,textValue)
    error('Phase2:CanonicalHash', ...
        'Specification canonical self-hash field was not found.');
end
hash = bytes_sha256(unicode2native(canonical,'UTF-8'));
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase2:HashRead','Unable to open %s.',path);
end
fileCleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
delete(fileCleanup);
hash = bytes_sha256(bytes);
end

function hash = bytes_sha256(bytes)
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(uint8(bytes));
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function value = truthy(input)
if islogical(input)
    value = input;
elseif isnumeric(input)
    value = input ~= 0;
else
    value = any(upper(string(input)) == ["TRUE","YES","1"]);
end
value = logical(value);
end

function value = wrap_to_180(value)
value = mod(value+180,360)-180;
end

function write_report(paths,rows,smokeIds,conditionComplete,pre,post, ...
        frozenPass,runnerPass)
fileId = fopen(paths.report,'w','n','UTF-8');
if fileId < 0
    error('Phase2:ReportWrite','Unable to create report.');
end
reportCleanup = onCleanup(@() fclose(fileId));
line = @(text) fprintf(fileId,'%s\n',text);
main = rows.record_type == "MAIN";
complete = main & ~rows.numerical_failure & ~rows.metric_missing;

line('# Phase 2 Step 2B-1 — Registry-Driven Runner Smoke Report');
line('');
line('## 1. Runner architecture');
line('');
line(['`run_phase2_deterministic_core.m` directly reads both frozen ' ...
    'registries. It materializes physical truth, algorithm assumptions, ' ...
    'data generation, evaluation windows, and provenance before calling ' ...
    'the frozen `run_phase1a_algorithm` dispatcher.']);
line('');
line(['All algorithms consume one in-memory physical dataset, truth, ' ...
    'noise realization, reconstructed reference, and window definition. ' ...
    'Persistent-fault metrics use a paired counterfactual metric branch ' ...
    'from the same physical realization; this is not an additional ' ...
    'registered physical condition or algorithm evaluation.']);
line('');
line('## 2. Six smoke conditions');
line('');
line('| Condition | Complete evaluations | Status |');
line('|---|---:|---|');
for k = 1:numel(smokeIds)
    index = main & rows.condition_id == smokeIds(k) & complete;
    line(sprintf('| `%s` | %d/4 | %s |',smokeIds(k),nnz(index), ...
        pass_fail(conditionComplete(k))));
end
line('');
line(['Only the six preregistered smoke conditions were run. The full ' ...
    'deterministic matrix, Cself, CsAC, overlap, Monte Carlo, replay, and ' ...
    'sensitivity matrices were not run.']);
line('');
line('## 3. Registry mapping audit');
line('');
line(sprintf(['Unique condition lookup, exact target value, anchor ' ...
    'non-target equality, runtime trajectory/config checks: **%d/24 ' ...
    'algorithm rows pass**.'],nnz(rows.registry_match(main))));
line('');
line(['`P2_PE_100` applies +1 deg to fitted fundamental phase and +3 deg ' ...
    'to fitted third-harmonic phase without changing physical data. ' ...
    '`P2_NS_003` remains ' ...
    '`NEGATIVE_SEQUENCE_INTERNAL_CONVENTION=UNRESOLVED` and ' ...
    '`INTERPRETATION=CONFIGURED_VALIDITY_BOUNDARY_ONLY`.']);
line('');
line(['Schema normalization: the frozen Case06 anchor uses NaN for an ' ...
    'unspecified base `drift_rate_multiplier`, while its Phase 2 ' ...
    'descendant explicitly uses 1. Both map to the unchanged frozen ' ...
    'Case06 Cs trajectory; the runtime trajectory assertion also passed.']);
line('');
line('## 4. Shared-data audit');
line('');
line(sprintf(['Shared physical data/truth/reference/window signature: ' ...
    '**%d/24 algorithm rows pass**.'],nnz(rows.shared_data_pass(main))));
line('');
line(['Each condition was simulated once as a clean/noisy deterministic ' ...
    'pair; M0/M2/M3/M4 received the same noisy arrays and reference object.']);
line('');
line('## 5. Metric extraction audit');
line('');
line(sprintf('Required frozen metrics available: **%d/24 rows**.', ...
    nnz(main & ~rows.metric_missing)));
line('');
line(['Fault rows include retention and signed paired-counterfactual ' ...
    'fault-induced Cs bias. M3 uses response-window hard-gate ratio and ' ...
    'onset latency; M4 uses frozen update-weight definitions. NaN values ' ...
    'in non-applicable fields mean N/A, including no-trigger latency.']);
line('');
line('## 6. Numerical failures');
line('');
line(sprintf('Numerical/execution failures: **%d/24 rows**.', ...
    nnz(main & rows.numerical_failure)));
if any(main & rows.numerical_failure)
    failed = unique(rows.condition_id(main & rows.numerical_failure));
    line(''); line('Affected conditions: `'+strjoin(failed,'`, `')+'`.');
end
line('');
line('## 7. Frozen integrity');
line('');
line(sprintf(['PRE: Phase 1 %d/%d, Step 1 %d/3. POST: Phase 1 %d/%d, ' ...
    'Step 1 %d/3. PRE/POST unchanged: **%s**.'], ...
    pre.phase1_pass_count,pre.phase1_count,pre.step1_pass_count, ...
    post.phase1_pass_count,post.phase1_count,post.step1_pass_count, ...
    pass_fail(frozenPass)));
line('');
line('## 8. Unexpected observations');
line('');
if all(~rows.numerical_failure(main))
    line(['No simulation abort, missing required output, NaN/Inf in core ' ...
        'signals, or missing applicable metric was observed. Metric values ' ...
        'are smoke evidence only and are not robustness conclusions.']);
else
    line(['One or more execution or metric-pipeline failures occurred; ' ...
        'see CSV `notes`. No method parameter was changed in response.']);
end
peM4 = rows(rows.condition_id == "P2_PE_100" & ...
    rows.algorithm_id == "M4",:);
nsM4 = rows(rows.condition_id == "P2_NS_003" & ...
    rows.algorithm_id == "M4",:);
foM4 = rows(rows.condition_id == "P2_FA_FO_130" & ...
    rows.algorithm_id == "M4",:);
if height(peM4) == 1 && height(nsM4) == 1 && height(foM4) == 1
    line('');
    line(sprintf(['Descriptive smoke observations retained without tuning: ' ...
        'M4 B fundamental error is %.6f%% at `P2_PE_100` and %.6f%% at ' ...
        '`P2_NS_003`; M4 fault-retention error is %.6f%% at ' ...
        '`P2_FA_FO_130`. The negative-sequence result remains a configured ' ...
        'validity-boundary observation, not a mechanism claim.'], ...
        peM4.B_resistive_fundamental_error_pct, ...
        nsM4.B_resistive_fundamental_error_pct, ...
        foM4.fault_retention_error_pct));
end
line('');
line(['Before the formal Step 3 CsAC matrix, add a ' ...
    '`GENERIC_ZERO_PATH_REGRESSION`: exercise ideal current -> zero CsAC ' ...
    'contribution -> sigma -> same RNG -> noisy current through the generic ' ...
    'path, without a `CsAC==0` nominal-data shortcut. This does not block ' ...
    'Step 2B.']);
line('');
line('## 9. Authorization for full deterministic core');
line('');
status = status_label(runnerPass,pre.pass,frozenPass);
line('STEP 2B-1 STATUS: **'+status+'**');
line('');
line('REGISTRY RUNNER: **'+authorized_label(runnerPass)+'**');
line('');
conditionCount = 0;
for k = 1:numel(conditionComplete)
    conditionCount = conditionCount+conditionComplete(k);
end
line(sprintf('SMOKE CONDITIONS: **%d / 6 COMPLETE**',conditionCount));
line('');
line(sprintf('ALGORITHM EVALUATIONS: **%d / 24 COMPLETE**',nnz(complete)));
line('');
line('FROZEN SOURCE MODIFIED: **'+yes_no(~frozenPass)+'**');
line('');
line('FULL DETERMINISTIC MATRIX EXECUTED: **NO**');
line('');
line('READY FOR STEP 2B-2: **'+yes_no(runnerPass)+'**');
delete(reportCleanup);
end

function write_step3_report(paths,rows,pre,post,authorization,gate, ...
        cselfDone,csacDone,status,readyForStep4,frozenPass)
fileId = fopen(paths.step3_report,'w','n','UTF-8');
if fileId < 0
    error('Phase2:ReportWrite','Unable to create Step 3 report.');
end
reportCleanup = onCleanup(@() fclose(fileId));
line = @(text) fprintf(fileId,'%s\n',text);
cself = rows(rows.experiment_group == "CSELF_MISMATCH",:);
csac = rows(rows.experiment_group == "CSAC_MISMATCH",:);
complete = ~rows.numerical_failure & ~rows.metric_missing;

line('# Phase 2 Step 3 — Model Mismatch Robustness');
line('');
line('## 1. Scope and frozen authorization');
line('');
line(['This formal batch evaluates only common-mode `Cself` mismatch ' ...
    'and unmodelled A-C coupling. M0/M2/M3/M4, AutoComp9, method ' ...
    'parameters, windows, seeds, and frozen registries were not changed.']);
line('');
line(sprintf(['Step 2A authorization read without editing the registry: ' ...
    'CSELF_SPLIT_INTERFACE_GATE=%s, ZERO_INJECTION_REGRESSION=%s, ' ...
    'NO_FROZEN_SOURCE_DIFF_GATE=%s. Frozen PENDING_GATE labels were ' ...
    'retained.'],pass_fail(authorization.cself), ...
    pass_fail(authorization.csac),pass_fail(authorization.source)));
line('');
line(sprintf(['PRE integrity: Phase 1 %d/%d and Step 1 %d/3. POST ' ...
    'integrity: Phase 1 %d/%d and Step 1 %d/3. PRE/POST unchanged: ' ...
    '**%s**.'],pre.phase1_pass_count,pre.phase1_count, ...
    pre.step1_pass_count,post.phase1_pass_count,post.phase1_count, ...
    post.step1_pass_count,pass_fail(frozenPass)));
line('');

line('## 2. Generic zero-path regression');
line('');
line(['The strengthened path contains no `CsAC==0` nominal-data ' ...
    'shortcut. It executes ideal current → zero CsAC contribution → ' ...
    'recomputed sigma → frozen RNG → noisy current, then compares the ' ...
    'result with the frozen Case02 nominal path.']);
line('');
line('| Comparison | Maximum absolute difference | Tolerance |');
line('|---|---:|---:|');
line(sprintf('| Ideal iA/iB/iC | %.17g A | %.3g |', ...
    gate.ideal_current_max_difference_A,gate.tolerance));
line(sprintf('| Noisy iA/iB/iC | %.17g A | %.3g |', ...
    gate.noisy_current_max_difference_A,gate.tolerance));
line(sprintf('| Reference | %.17g | %.3g |', ...
    gate.reference_max_difference,gate.tolerance));
line(sprintf('| Truth | %.17g | %.3g |', ...
    gate.truth_max_difference,gate.truth_tolerance));
for mode = ["M0" "M2" "M3" "M4"]
    line(sprintf('| %s outputs | %.17g | %.3g |',mode, ...
        gate.(char(mode+"_output_max_difference")),gate.tolerance));
end
line('');
line('GENERIC_ZERO_PATH_REGRESSION: **'+pass_fail(gate.pass)+'**');
if strlength(gate.error) > 0
    line('');
    line('Gate error retained: `'+replace(gate.error,newline,' ')+'`.');
end
line('');

line('## 3. Cself mismatch results');
line('');
line(sprintf(['Completed **%d/6** conditions and **%d/24** evaluations. ' ...
    'Physical truth alone used 360/380/392/408/420/440 pF; the ' ...
    'algorithm assumption remained 400 pF in every row.'], ...
    cselfDone,nnz(complete & rows.experiment_group == "CSELF_MISMATCH")));
line('');
write_step3_metric_table(fileId,cself,"Cself_mismatch_pct");
line('');
line('### Directional symmetry and growth');
line('');
line(['Asymmetry below is `|positive-negative| / mean(|positive|,' ...
    '|negative|)` for paired ±2%, ±5%, and ±10% levels. Zero means ' ...
    'perfect magnitude symmetry; no symmetry threshold was preregistered.']);
line('');
line(['| Algorithm | RMSE-norm asymmetry at 2/5/10% (%) | ' ...
    '|B-error| asymmetry at 2/5/10% (%) | mean RMSE norm 2→10% (pF) | ' ...
    'M3 max gate | M4 mean-g range | M4 max USR |']);
line('|---|---:|---:|---:|---:|---:|---:|');
for mode = ["M0" "M2" "M3" "M4"]
    subset = cself(cself.algorithm_id == mode,:);
    rmseAsym = zeros(1,3); bAsym = zeros(1,3);
    averageNorm = zeros(1,3);
    magnitudes = [2 5 10];
    for k = 1:3
        negative = subset(subset.Cself_mismatch_pct == -magnitudes(k),:);
        positive = subset(subset.Cself_mismatch_pct == magnitudes(k),:);
        negativeNorm = hypot(negative.Cs1_RMSE_pF,negative.Cs2_RMSE_pF);
        positiveNorm = hypot(positive.Cs1_RMSE_pF,positive.Cs2_RMSE_pF);
        rmseAsym(k) = pair_asymmetry(negativeNorm,positiveNorm);
        bAsym(k) = pair_asymmetry( ...
            abs(negative.B_resistive_fundamental_error_pct), ...
            abs(positive.B_resistive_fundamental_error_pct));
        averageNorm(k) = mean([negativeNorm;positiveNorm]);
    end
    if mode == "M3"
        gateMax = max(subset.hard_gate_active_ratio);
    else
        gateMax = NaN;
    end
    if mode == "M4"
        gRange = sprintf('%.6f–%.6f',min(subset.mean_update_weight), ...
            max(subset.mean_update_weight));
        usrMax = max(subset.unnecessary_suppression_ratio);
    else
        gRange = 'N/A'; usrMax = NaN;
    end
    line(sprintf(['| %s | %.3f / %.3f / %.3f | ' ...
        '%.3f / %.3f / %.3f | %.6f → %.6f | %.6g | %s | %.6g |'], ...
        mode,rmseAsym,bAsym,averageNorm(1),averageNorm(3), ...
        gateMax,gRange,usrMax));
end
line('');
for mode = ["M0" "M2" "M3" "M4"]
    subset = sortrows(cself(cself.algorithm_id == mode,:), ...
        'Cself_mismatch_pct');
    normValue = hypot(subset.Cs1_RMSE_pF,subset.Cs2_RMSE_pF);
    [maxB,indexB] = max(abs(subset.B_resistive_fundamental_error_pct));
    line(sprintf(['- %s: tracking-error norm spans %.6f–%.6f pF; ' ...
        'maximum |B fundamental error| is %.6f%% at %+.0f%% mismatch.'], ...
        mode,min(normValue),max(normValue),maxB, ...
        subset.Cself_mismatch_pct(indexB)));
end
line('');
line(['Interpretation: paired-direction asymmetry, error growth, any M3 ' ...
    'gate activity, and M4 suppression are reported directly above. ' ...
    'No pass/fail accuracy threshold was preregistered, so the outer ' ...
    '±10% points are observed validity-boundary evidence rather than a ' ...
    'newly declared operating limit.']);
line('');

line('## 4. Unmodelled CsAC coupling results');
line('');
if gate.pass
    line(sprintf(['Completed **%d/4** conditions and **%d/16** ' ...
        'evaluations. Injection remained `iA=CsAC(duA-duC)`, `iB=0`, ' ...
        '`iC=CsAC(duC-duA)` and occurred before sigma/noise generation.'], ...
        csacDone,nnz(complete & rows.experiment_group == "CSAC_MISMATCH")));
    line('');
    write_step3_metric_table(fileId,csac,"CsAC_truth_pF");
    line('');
    line('### Structural-bias audit');
    line('');
    line(['| Algorithm | corr(CsAC,Cs1 RMSE) | corr(CsAC,Cs2 RMSE) | ' ...
        'more affected side at 3 pF | RMSE norm 0.5→3 pF | ' ...
        '|B error| 0.5→3 pF (%) | M3 max gate | M4 mean-g range |']);
    line('|---|---:|---:|---|---:|---:|---:|---:|');
    for mode = ["M0" "M2" "M3" "M4"]
        subset = sortrows(csac(csac.algorithm_id == mode,:),'CsAC_truth_pF');
        first = subset(1,:); last = subset(end,:);
        if last.Cs1_RMSE_pF >= last.Cs2_RMSE_pF
            side = 'Cs1';
        else
            side = 'Cs2';
        end
        if mode == "M3"
            gateMax = max(subset.hard_gate_active_ratio);
        else
            gateMax = NaN;
        end
        if mode == "M4"
            gRange = sprintf('%.6f–%.6f', ...
                min(subset.mean_update_weight), ...
                max(subset.mean_update_weight));
        else
            gRange = 'N/A';
        end
        line(sprintf(['| %s | %.6f | %.6f | %s | %.6f → %.6f | ' ...
            '%.6f → %.6f | %.6g | %s |'],mode, ...
            safe_corr(subset.CsAC_truth_pF,subset.Cs1_RMSE_pF), ...
            safe_corr(subset.CsAC_truth_pF,subset.Cs2_RMSE_pF),side, ...
            hypot(first.Cs1_RMSE_pF,first.Cs2_RMSE_pF), ...
            hypot(last.Cs1_RMSE_pF,last.Cs2_RMSE_pF), ...
            abs(first.B_resistive_fundamental_error_pct), ...
            abs(last.B_resistive_fundamental_error_pct),gateMax,gRange));
    end
    line('');
    m2Last = csac(csac.algorithm_id == "M2" & ...
        csac.CsAC_truth_pF == max(csac.CsAC_truth_pF),:);
    m3Last = csac(csac.algorithm_id == "M3" & ...
        csac.CsAC_truth_pF == max(csac.CsAC_truth_pF),:);
    m4Last = csac(csac.algorithm_id == "M4" & ...
        csac.CsAC_truth_pF == max(csac.CsAC_truth_pF),:);
    line(sprintf(['At 3 pF, RMSE norms are M2 %.6f pF, M3 %.6f pF, ' ...
        'and M4 %.6f pF; M4 mean update weight is %.6f and USR is ' ...
        '%.6f. These values distinguish weighting response from residual ' ...
        'model bias; they do not establish universal mismatch robustness.'], ...
        hypot(m2Last.Cs1_RMSE_pF,m2Last.Cs2_RMSE_pF), ...
        hypot(m3Last.Cs1_RMSE_pF,m3Last.Cs2_RMSE_pF), ...
        hypot(m4Last.Cs1_RMSE_pF,m4Last.Cs2_RMSE_pF), ...
        m4Last.mean_update_weight,m4Last.unnecessary_suppression_ratio));
else
    line(['The strengthened generic zero-path gate failed. The formal ' ...
        'nonzero CsAC matrix was therefore blocked without relaxing ' ...
        'tolerance or modifying any algorithm.']);
end
line('');

line('## 5. Completeness, negative results, and structural failures');
line('');
line(sprintf(['Registry matches: **%d/%d**; shared-data checks: ' ...
    '**%d/%d**; numerical failures: **%d**; metric-missing rows: ' ...
    '**%d**.'],nnz(rows.registry_match),height(rows), ...
    nnz(rows.shared_data_pass),height(rows), ...
    nnz(rows.numerical_failure),nnz(rows.metric_missing)));
line('');
if nnz(rows.numerical_failure | rows.metric_missing) == 0
    line(['No execution-level structural failure was observed. Large ' ...
        'errors, asymmetric response, gate activation, and suppression ' ...
        'remain performance evidence and were not reclassified as ' ...
        'numerical failures.']);
else
    line(['Execution-level failures are retained in the CSV. No failed ' ...
        'condition was deleted or repaired by parameter changes.']);
end
line('');
line(['This report does **not** claim that M4 is generally robust to ' ...
    'model mismatch. Conclusions are limited to the frozen levels and ' ...
    'the observed data above.']);
line('');

line('## 6. Final status');
line('');
line('STEP 3 STATUS:');
line('**'+status+'**');
line('');
line('CSELF CONDITIONS COMPLETE:');
line(sprintf('**%d / 6**',cselfDone));
line('');
line('CSELF EVALUATIONS COMPLETE:');
line(sprintf('**%d / 24**',nnz(complete & ...
    rows.experiment_group == "CSELF_MISMATCH")));
line('');
line('GENERIC ZERO PATH REGRESSION:');
line('**'+pass_fail(gate.pass)+'**');
line('');
line('CSAC CONDITIONS COMPLETE:');
line(sprintf('**%d / 4**',csacDone));
line('');
line('CSAC EVALUATIONS COMPLETE:');
line(sprintf('**%d / 16**',nnz(complete & ...
    rows.experiment_group == "CSAC_MISMATCH")));
line('');
line('NUMERICAL FAILURES:');
line(sprintf('**%d**',nnz(rows.numerical_failure)));
line('');
line('FROZEN SOURCE MODIFIED:');
line('**'+yes_no(~frozenPass)+'**');
line('');
line('READY FOR STEP 4:');
line('**'+yes_no(readyForStep4)+'**');
end

function write_step3_metric_table(fileId,rows,levelName)
fprintf(fileId,['| Condition | Level | Algorithm | Cs1 RMSE (pF) | ' ...
    'Cs2 RMSE (pF) | Cs1/Cs2 max abs (pF) | B fundamental err (%%) | ' ...
    'M3 gate ratio | M4 mean g | M4 USR |\n']);
fprintf(fileId,'|---|---:|---|---:|---:|---:|---:|---:|---:|---:|\n');
for k = 1:height(rows)
    fprintf(fileId,['| `%s` | %.6g | %s | %.6f | %.6f | ' ...
        '%.6f / %.6f | %.6f | %.6g | %.6g | %.6g |\n'], ...
        rows.condition_id(k),rows.(char(levelName))(k), ...
        rows.algorithm_id(k),rows.Cs1_RMSE_pF(k), ...
        rows.Cs2_RMSE_pF(k),rows.Cs1_max_abs_error_pF(k), ...
        rows.Cs2_max_abs_error_pF(k), ...
        rows.B_resistive_fundamental_error_pct(k), ...
        rows.hard_gate_active_ratio(k),rows.mean_update_weight(k), ...
        rows.unnecessary_suppression_ratio(k));
end
end

function value = pair_asymmetry(a,b)
value = abs(a-b)/(0.5*(abs(a)+abs(b))+eps)*100;
end

function write_step2b2_report(paths,rows,conditions,conditionComplete, ...
        pre,post,frozenPass,batchPass)
fileId = fopen(paths.step2b2_report,'w','n','UTF-8');
if fileId < 0
    error('Phase2:ReportWrite','Unable to create Step 2B-2 report.');
end
reportCleanup = onCleanup(@() fclose(fileId));
line = @(text) fprintf(fileId,'%s\n',text);
main = rows.record_type == "MAIN";
complete = main & ~rows.numerical_failure & ~rows.metric_missing;
numericalFailures = nnz(main & rows.numerical_failure);
metricMissing = nnz(main & rows.metric_missing);

line('# Phase 2 Step 2B-2 — Full Deterministic Core Report');
line('');
line('## 1. Scope and execution completeness');
line('');
line(sprintf(['The frozen `PHASE2_REGISTRY_V1` selected **%d/25** new ' ...
    'physical conditions and **%d/100** registered M0/M2/M3/M4 ' ...
    'evaluations completed.'],nnz(conditionComplete),nnz(complete)));
line('');
line(['The batch contains Fault amplitude (10), SNR (3), reference phase ' ...
    '(5), third-harmonic amplitude (4), and negative sequence (3). ' ...
    'Frozen nominal anchors were reused conceptually and were not ' ...
    're-simulated or duplicated in the 100-row dataset.']);
line('');
line(['Cself mismatch, CsAC mismatch, overlap rate/direction, replay, ' ...
    'sensitivity variants, and Monte Carlo were not executed.']);
line('');
line('## 2. Registry, shared-data, and frozen-integrity audit');
line('');
line(sprintf(['Registry mapping: **%d/100**; shared-data signature: ' ...
    '**%d/100**; required metrics: **%d/100**.'], ...
    nnz(rows.registry_match(main)),nnz(rows.shared_data_pass(main)), ...
    nnz(main & ~rows.metric_missing)));
line('');
line(sprintf(['PRE integrity: Phase 1 %d/%d and Step 1 %d/3. POST ' ...
    'integrity: Phase 1 %d/%d and Step 1 %d/3. PRE/POST unchanged: ' ...
    '**%s**.'],pre.phase1_pass_count,pre.phase1_count, ...
    pre.step1_pass_count,post.phase1_pass_count,post.phase1_count, ...
    post.step1_pass_count,pass_fail(frozenPass)));
line('');
line(['Each condition generated one physical data realization. Its four ' ...
    'algorithms shared truth, Cs trajectory, fault waveform, voltage, ' ...
    'noise, reconstructed reference, windows, and time axis.']);
line('');
line('## 3. Numerical and metric failure audit');
line('');
line(sprintf('Numerical failures: **%d**. Metric-missing rows: **%d**.', ...
    numericalFailures,metricMissing));
line('');
line(['Algorithm performance was never used as a numerical-failure ' ...
    'criterion. All adverse results remain in the CSV.']);
line('');

faultConditions = conditions(conditions.experiment_group == ...
    "FAULT_AMPLITUDE",:);
faultRows = rows(rows.experiment_group == "FAULT_AMPLITUDE",:);
line('## 4. Fault-amplitude chain');
line('');
line(['The table links severity to M3 gate response, M4 update weight, ' ...
    'retention, and signed fault-induced parameter bias.']);
line('');
line(['| Family | Factor | M2 retention err (%) | M2 bias norm (pF) | ' ...
    'M3 gate ratio | M3 latency (s) | M3 retention err (%) | ' ...
    'M4 mean g | M4 retention err (%) | M4 ΔCs1/ΔCs2 (pF) | ' ...
    'M4 bias norm (pF) |']);
line('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
for k = 1:height(faultConditions)
    id = faultConditions.condition_id(k);
    m2 = one_result(faultRows,id,"M2");
    m3 = one_result(faultRows,id,"M3");
    m4 = one_result(faultRows,id,"M4");
    line(sprintf(['| %s | %.3f | %.6f | %.6f | %.6f | %.6g | ' ...
        '%.6f | %.6f | %.6f | %.6f / %.6f | %.6f |'], ...
        faultConditions.family(k),faultConditions.fault_factor(k), ...
        m2.fault_retention_error_pct,m2.Cs_fault_induced_bias_norm_pF, ...
        m3.hard_gate_active_ratio,m3.hard_gate_latency_s, ...
        m3.fault_retention_error_pct,m4.mean_update_weight, ...
        m4.fault_retention_error_pct,m4.DeltaCs1_fault_induced_pF, ...
        m4.DeltaCs2_fault_induced_pF, ...
        m4.Cs_fault_induced_bias_norm_pF));
end
line('');
[faultAnalysis,missIds,triggerIds] = analyze_fault_sweep(faultRows);
line('M3 gate not triggered: '+code_list(missIds)+'.');
line('');
line('M3 gate triggered: '+code_list(triggerIds)+'.');
line('');
line(faultAnalysis.m4_weight_statement);
line('');
line(faultAnalysis.m2_absorption_statement);
line('');
line(faultAnalysis.m4_vs_m2_statement);
line('');
line(faultAnalysis.m4_vs_m3_statement);
line('');
line(['M4 ISR-J/ISR-h are retained for fault rows when available. ' ...
    '**ISR is rejected cycle information and is not equal to final ' ...
    'parameter-bias reduction.**']);
line('');

write_disturbance_section(fileId,rows,conditions,"SNR", ...
    '## 5. Noise / SNR','SNR_dB');
snrRows = rows(rows.experiment_group == "SNR",:);
line(snr_analysis(snrRows));
line('');

write_disturbance_section(fileId,rows,conditions,"REFERENCE_PHASE", ...
    '## 6. Reference-phase sensitivity','reference_phase_error_deg');
phaseRows = rows(rows.experiment_group == "REFERENCE_PHASE",:);
line(phase_analysis(phaseRows));
line('');
line(['This is sensitivity to the frozen coherent reference-phase model, ' ...
    'not complete sensor phase-response validation. Physical voltage, ' ...
    'current, fault waveform, and noise remain unchanged within the sweep.']);
line('');

write_disturbance_section(fileId,rows,conditions,"THIRD_HARMONIC", ...
    '## 7. Third-harmonic amplitude sensitivity','h3_ratio');
h3Rows = rows(rows.experiment_group == "THIRD_HARMONIC",:);
line(harmonic_analysis(h3Rows));
line('');
line(['Only amplitude was swept; `phi3_deg=0` remained fixed. No harmonic ' ...
    'phase sweep was added.']);
line('');

write_disturbance_section(fileId,rows,conditions,"NEGATIVE_SEQUENCE", ...
    '## 8. Negative-sequence validity boundary','negative_sequence_pu');
nsRows = rows(rows.experiment_group == "NEGATIVE_SEQUENCE",:);
line(negative_sequence_analysis(nsRows));
line('');
line(['All nonzero conditions retain ' ...
    '`NEGATIVE_SEQUENCE_INTERNAL_CONVENTION=UNRESOLVED` and ' ...
    '`INTERPRETATION=CONFIGURED_VALIDITY_BOUNDARY_ONLY`. These data are ' ...
    'validity-boundary evidence, not a negative-sequence mechanism proof.']);
line('');

line('## 9. Structural findings and Phase 1C evidence balance');
line('');
if numericalFailures == 0 && metricMissing == 0
    line(['No new execution-level structural failure was found: there was ' ...
        'no abort, corrupt result, missing required output, NaN/Inf in core ' ...
        'signals, validator failure, or missing applicable metric.']);
else
    line(['Execution-level failures exist and are listed in the CSV; no ' ...
        'method parameter was changed in response.']);
end
line('');
line(faultAnalysis.support_statement);
line('');
line(faultAnalysis.limit_statement);
line('');
line(['The phase and negative-sequence tables preserve large-error cases ' ...
    'where present. Therefore the evidence supports the frozen method only ' ...
    'within the tested validity region and does not justify a universal-best ' ...
    'claim.']);
line('');

line('## 10. Required questions and authorization');
line('');
line('| Required question | Answer |');
line('|---|---|');
line(sprintf('| 1. 25 physical conditions complete? | %d/25 |', ...
    nnz(conditionComplete)));
line(sprintf('| 2. 100 algorithm evaluations complete? | %d/100 |', ...
    nnz(complete)));
line(sprintf('| 3. Numerical / metric failures? | %d / %d |', ...
    numericalFailures,metricMissing));
line('| 4. Fault sweep trend? | See Section 4; no monotonicity assumed. |');
line('| 5. M3 threshold misses? | Explicit condition list in Section 4. |');
line('| 6. M4 update weight continuous? | Data-derived result in Section 4. |');
line('| 7. M2 absorption versus severity? | Data-derived result in Section 4. |');
line('| 8. M4 versus M2 preservation stable? | Counts reported in Section 4. |');
line('| 9. M4 versus M3 cost? | Counts reported in Section 4. |');
line('| 10. SNR impact? | Section 5. |');
line('| 11. Reference-phase sensitivity? | Section 6. |');
line('| 12. Harmonic sensitivity? | Section 7. |');
line('| 13. Negative-sequence boundary? | Section 8. |');
line('| 14. New structural failure? | Section 9. |');
line('| 15. Evidence supporting Phase 1C? | Section 9. |');
line('| 16. Evidence limiting Phase 1C? | Section 9. |');
line('| 17. Allow Step 3? | '+yes_no(batchPass)+' |');
line('');
line('STEP 2B-2 STATUS: **'+ ...
    status_label(batchPass,pre.pass,frozenPass)+'**');
line('');
line(sprintf('PHYSICAL CONDITIONS COMPLETE: **%d / 25**', ...
    nnz(conditionComplete)));
line('');
line(sprintf('ALGORITHM EVALUATIONS COMPLETE: **%d / 100**', ...
    nnz(complete)));
line('');
line(sprintf('NUMERICAL FAILURES: **%d**',numericalFailures));
line('');
line(sprintf('METRIC-MISSING ROWS: **%d**',metricMissing));
line('');
line('FROZEN SOURCE MODIFIED: **'+yes_no(~frozenPass)+'**');
line('');
line('FULL DETERMINISTIC CORE COMPLETE: **'+yes_no(batchPass)+'**');
line('');
line('READY FOR STEP 3: **'+yes_no(batchPass)+'**');
delete(reportCleanup);
end

function write_disturbance_section(fileId,rows,conditions,group,titleText, ...
        registryField)
fprintf(fileId,'%s\n\n',titleText);
fprintf(fileId,['| Condition | Level | Algorithm | Cs1 RMSE (pF) | ' ...
    'Cs2 RMSE (pF) | Cs1/Cs2 max abs (pF) | B fundamental err (%%) | ' ...
    'M3 gate ratio | M4 mean g | M4 USR |\n']);
fprintf(fileId,'|---|---:|---|---:|---:|---:|---:|---:|---:|---:|\n');
groupConditions = conditions(conditions.experiment_group == group,:);
for k = 1:height(groupConditions)
    id = groupConditions.condition_id(k);
    level = groupConditions.(char(registryField))(k);
    for mode = ["M0","M2","M3","M4"]
        current = one_result(rows,id,mode);
        fprintf(fileId,['| `%s` | %.6g | %s | %.6f | %.6f | ' ...
            '%.6f / %.6f | %.6f | %.6g | %.6g | %.6g |\n'], ...
            id,level,mode,current.Cs1_RMSE_pF,current.Cs2_RMSE_pF, ...
            current.Cs1_max_abs_error_pF,current.Cs2_max_abs_error_pF, ...
            current.B_resistive_fundamental_error_pct, ...
            current.hard_gate_active_ratio,current.mean_update_weight, ...
            current.unnecessary_suppression_ratio);
    end
end
fprintf(fileId,'\n');
end

function row = one_result(rows,conditionId,algorithmId)
match = rows.condition_id == conditionId & rows.algorithm_id == algorithmId;
if nnz(match) ~= 1
    error('Phase2:ReportRowCardinality', ...
        'Expected one row for %s/%s.',conditionId,algorithmId);
end
row = rows(match,:);
end

function [analysis,missIds,triggerIds] = analyze_fault_sweep(rows)
m2 = rows(rows.algorithm_id == "M2",:);
m3 = rows(rows.algorithm_id == "M3",:);
m4 = rows(rows.algorithm_id == "M4",:);
missIds = m3.condition_id(m3.hard_gate_active_ratio == 0);
triggerIds = m3.condition_id(m3.hard_gate_active_ratio > 0);

families = unique(m4.anchor_case,'stable');
weightParts = strings(0,1);
absorptionParts = strings(0,1);
for k = 1:numel(families)
    family = families(k);
    current4 = m4(m4.anchor_case == family,:);
    current2 = m2(m2.anchor_case == family,:);
    [factor,order] = sort(current4.target_value);
    g = current4.mean_update_weight(order);
    bias = current2.Cs_fault_induced_bias_norm_pF(order);
    weightParts(end+1) = family+": mean g "+ ...
        monotonic_label(g)+sprintf(' (r=%.4f)',safe_corr(factor,g)); %#ok<AGROW>
    absorptionParts(end+1) = family+": M2 bias norm "+ ...
        monotonic_label(bias)+sprintf(' (r=%.4f)', ...
        safe_corr(factor,bias)); %#ok<AGROW>
end
m4BetterRetention = abs(m4.fault_retention_error_pct) < ...
    abs(m2.fault_retention_error_pct);
m4LowerBias = m4.Cs_fault_induced_bias_norm_pF < ...
    m2.Cs_fault_induced_bias_norm_pF;
m4VsM3Retention = abs(m4.fault_retention_error_pct) < ...
    abs(m3.fault_retention_error_pct);
m4VsM3Bias = m4.Cs_fault_induced_bias_norm_pF < ...
    m3.Cs_fault_induced_bias_norm_pF;
analysis = struct( ...
    'm4_weight_statement',"M4 continuous-response audit: "+ ...
        strjoin(weightParts,"; ")+". Monotonicity is descriptive, not required.", ...
    'm2_absorption_statement',"M2 severity audit: "+ ...
        strjoin(absorptionParts,"; ")+".", ...
    'm4_vs_m2_statement',sprintf([ ...
        'M4 versus M2: lower absolute retention error in %d/%d rows and ' ...
        'lower fault-induced bias norm in %d/%d rows.'], ...
        nnz(m4BetterRetention),height(m4),nnz(m4LowerBias),height(m4)), ...
    'm4_vs_m3_statement',sprintf([ ...
        'M4 versus M3: lower absolute retention error in %d/%d rows and ' ...
        'lower fault-induced bias norm in %d/%d rows. The complementary ' ...
        'rows are the observed M4 cost; no threshold was retuned.'], ...
        nnz(m4VsM3Retention),height(m4),nnz(m4VsM3Bias),height(m4)), ...
    'support_statement',sprintf([ ...
        'Phase 1C support: M4 improves M2 absolute fault retention in ' ...
        '%d/%d registered amplitude rows and reduces M2 fault-induced ' ...
        'bias norm in %d/%d rows.'],nnz(m4BetterRetention),height(m4), ...
        nnz(m4LowerBias),height(m4)), ...
    'limit_statement',sprintf([ ...
        'Phase 1C limitation: M4 does not dominate M3; M3 has equal or ' ...
        'better absolute retention in %d/%d rows and equal or lower bias ' ...
        'norm in %d/%d rows.'],height(m4)-nnz(m4VsM3Retention),height(m4), ...
        height(m4)-nnz(m4VsM3Bias),height(m4)));
end

function textValue = snr_analysis(rows)
parts = strings(0,1);
for mode = ["M0","M2","M3","M4"]
    current = rows(rows.algorithm_id == mode,:);
    [levels,order] = sort(current.target_value,'descend');
    values = abs(current.B_resistive_fundamental_error_pct(order));
    parts(end+1) = sprintf( ...
        '%s |B error| spans %.6f%% to %.6f%% over %s dB', ...
        mode,min(values),max(values),strjoin(string(levels.'),',')); %#ok<AGROW>
end
textValue = "SNR descriptive audit: "+strjoin(parts,"; ")+ ...
    ". Tracking RMSE and M3/M4 protection behavior are retained in the table.";
end

function textValue = phase_analysis(rows)
parts = strings(0,1);
for mode = ["M0","M2","M3","M4"]
    current = rows(rows.algorithm_id == mode,:);
    [levels,order] = sort(current.target_value);
    values = abs(current.B_resistive_fundamental_error_pct(order));
    parts(end+1) = sprintf( ...
        '%s |B error| %.6f%% at %.2f deg -> %.6f%% at %.2f deg', ...
        mode,values(1),levels(1),values(end),levels(end)); %#ok<AGROW>
end
textValue = "Reference-phase sensitivity: "+strjoin(parts,"; ")+ ...
    ". Rapid growth, non-monotonicity, or gate activity is preserved as observed.";
end

function textValue = harmonic_analysis(rows)
parts = strings(0,1);
for mode = ["M0","M2","M3","M4"]
    current = rows(rows.algorithm_id == mode,:);
    maxError = max(abs(current.B_resistive_fundamental_error_pct));
    maxRmse = max(hypot(current.Cs1_RMSE_pF,current.Cs2_RMSE_pF));
    parts(end+1) = sprintf('%s max |B error| %.6f%%, max Cs RMSE norm %.6f pF', ...
        mode,maxError,maxRmse); %#ok<AGROW>
end
textValue = "Harmonic-amplitude audit: "+strjoin(parts,"; ")+".";
end

function textValue = negative_sequence_analysis(rows)
parts = strings(0,1);
for mode = ["M0","M2","M3","M4"]
    current = rows(rows.algorithm_id == mode,:);
    [levels,order] = sort(current.target_value);
    values = abs(current.B_resistive_fundamental_error_pct(order));
    parts(end+1) = sprintf('%s |B error| %s%% at Vneg %s',mode, ...
        strjoin(compose('%.6f',values.'),'/'), ...
        strjoin(compose('%.2f',levels.'),'/')); %#ok<AGROW>
end
textValue = "Negative-sequence boundary: "+strjoin(parts,"; ")+".";
end

function label = monotonic_label(values)
tolerance = 1e-12;
if all(diff(values) >= -tolerance)
    label = "is nondecreasing";
elseif all(diff(values) <= tolerance)
    label = "is nonincreasing";
else
    label = "is non-monotonic";
end
end

function value = safe_corr(x,y)
if numel(x) < 2 || numel(unique(x)) < 2 || numel(unique(y)) < 2
    value = NaN;
else
    matrix = corrcoef(x,y);
    value = matrix(1,2);
end
end

function textValue = code_list(values)
if isempty(values)
    textValue = "none";
else
    textValue = "`"+strjoin(values,"`, `")+"`";
end
end

function label = status_label(pass,prePass,frozenPass)
if ~prePass || ~frozenPass
    label = "BLOCKED";
elseif pass
    label = "PASS";
else
    label = "PARTIAL";
end
end

function label = authorized_label(pass)
if pass
    label = "AUTHORIZED";
else
    label = "NOT AUTHORIZED";
end
end

function label = pass_fail(pass)
if pass
    label = "PASS";
else
    label = "FAIL";
end
end

function label = yes_no(value)
if value
    label = "YES";
else
    label = "NO";
end
end
