function baseline = run_phase1a_baseline()
%RUN_PHASE1A_BASELINE Run the frozen six-case Phase 1A baseline.
% This function only orchestrates existing case, algorithm, and metric code.

matlabRoot = fileparts(mfilename('fullpath'));
projectRoot = fileparts(matlabRoot);
outputRoot = fullfile(projectRoot,'paper_research','phase1a_baseline');
frozenMetadata = phase1a_baseline_metadata();
modelPath = fullfile(matlabRoot,'AI6109_MOA_AutoComp9.slx');
modelSha256 = file_sha256(modelPath);
if modelSha256 ~= frozenMetadata.baseline_model_sha256
    error('Phase1A:BaselineIntegrityFailure', ...
        'AutoComp9 SHA-256 does not match the frozen baseline.');
end

cfg = patent_default_config();
cfg.model = char(frozenMetadata.baseline_model);
cfg.output_dir = outputRoot;
caseRegistry = phase1a_case_registry();
algorithmRegistry = phase1a_algorithm_registry();
algorithmRegistry = algorithmRegistry(algorithmRegistry.enabled,:);
resultSchema = phase1a_result_schema();
historicalReference = phase1a_historical_reference();
runMetadata = current_run_metadata(modelPath,modelSha256,projectRoot, ...
    height(caseRegistry));
frozenIntegrity = capture_frozen_integrity(matlabRoot);

resultsTable = resultSchema.empty_result_table;
caseData = struct();
algorithmResults = struct();
selfPF = repmat(cfg.Cself_pF,1,3);
tInput = (0:cfg.Ts:cfg.StopTime).';

for caseIndex = 1:height(caseRegistry)
    caseInfo = caseRegistry(caseIndex,:);
    caseName = caseInfo.case_name;
    fprintf('PHASE1A_CASE_START=%s seed=%d\n',caseName,caseInfo.seed);

    signals = generate_coupling_signals(tInput,caseName,caseInfo.seed);
    [data,~] = simulate_phase2_case(cfg, ...
        char(caseInfo.legacy_scenario_name),caseInfo.seed);
    assert_case_truth(data,signals,caseName);
    ref = reconstruct_refs_from_b(data.t,data.ub,cfg.f, ...
        cfg.init_start,cfg.init_end,cfg.phase_error_deg);

    caseField = char(caseName);
    caseData.(caseField) = minimal_case_data(caseInfo,data,signals);
    algorithmResults.(caseField) = struct();
    for algorithmIndex = 1:height(algorithmRegistry)
        mode = algorithmRegistry.algorithm_mode(algorithmIndex);
        result = run_phase1a_algorithm(mode,data,ref,cfg,selfPF);
        metrics = evaluate_phase1a_metrics( ...
            caseInfo,result,data,cfg,runMetadata);
        resultsTable = [resultsTable;metrics]; %#ok<AGROW>
        algorithmResults.(caseField).(char(mode)) = ...
            minimal_algorithm_result(result);
    end
    fprintf('PHASE1A_CASE_COMPLETE=%s rows=%d\n', ...
        caseName,height(algorithmRegistry));
end

validation = validate_phase1a_baseline(resultsTable,cfg,caseRegistry, ...
    algorithmRegistry,resultSchema,historicalReference,runMetadata, ...
    caseData,algorithmResults,frozenIntegrity,projectRoot);

summaryPath = fullfile(outputRoot,'baseline_summary.csv');
workspacePath = fullfile(outputRoot,'baseline_workspace.mat');
writetable(resultsTable,summaryPath);
baseline = struct( ...
    'cfg',cfg, ...
    'caseRegistry',caseRegistry, ...
    'algorithmRegistry',algorithmRegistry, ...
    'resultSchema',resultSchema, ...
    'historicalReference',historicalReference, ...
    'resultsTable',resultsTable, ...
    'runMetadata',runMetadata, ...
    'caseData',caseData, ...
    'algorithmResults',algorithmResults, ...
    'validation',validation);
save(workspacePath,'cfg','caseRegistry','algorithmRegistry', ...
    'resultSchema','historicalReference','resultsTable','runMetadata', ...
    'caseData','algorithmResults','validation','baseline','-v7.3');

disp(resultsTable);
disp(validation.checks);
fprintf('BASELINE_SUMMARY=%s\n',summaryPath);
fprintf('BASELINE_WORKSPACE=%s\n',workspacePath);
fprintf('CASE_LEVEL_SIMULATOR_CALLS=%d\n', ...
    runMetadata.case_level_simulator_calls);
fprintf('LOW_LEVEL_SIM_INVOCATIONS=%d\n', ...
    runMetadata.low_level_sim_invocation_count);
fprintf('STEP6_FORMAL_BASELINE_RUN=%s\n',pass_label(validation.overall_pass));
if ~validation.overall_pass
    error('Phase1A:FormalBaselineValidationFailure', ...
        'One or more Step 6 validation checks failed.');
end
end

function assert_case_truth(data,signals,caseName)
if numel(data.Cs1) ~= numel(signals.Cs1_pF) || ...
        numel(data.Cs2) ~= numel(signals.Cs2_pF)
    error('Phase1A:CaseSignalMismatch', ...
        '%s truth length differs from the frozen generator.',caseName);
end
Cs1Difference = max(abs(data.Cs1-signals.Cs1_pF));
Cs2Difference = max(abs(data.Cs2-signals.Cs2_pF));
if Cs1Difference > 1e-10 || Cs2Difference > 1e-10
    error('Phase1A:CaseSignalMismatch', ...
        '%s truth differs from the frozen case generator.',caseName);
end
end

function value = minimal_case_data(caseInfo,data,signals)
value = struct( ...
    'case_name',caseInfo.case_name, ...
    'seed',caseInfo.seed, ...
    't',data.t, ...
    'Cs1_true',data.Cs1, ...
    'Cs2_true',data.Cs2, ...
    'fault_scale',signals.fault_scale, ...
    'irA_true',data.irA, ...
    'irB_true',data.irB, ...
    'irC_true',data.irC, ...
    'Cs1_signal_max_abs_diff_pF', ...
    max(abs(data.Cs1-signals.Cs1_pF)), ...
    'Cs2_signal_max_abs_diff_pF', ...
    max(abs(data.Cs2-signals.Cs2_pF)));
end

function value = minimal_algorithm_result(result)
value = struct( ...
    'algorithm_mode',result.algorithm_mode, ...
    'cHist',result.cHist, ...
    'irB',result.ir.B);
if any(result.algorithm_mode == ["M2","M3"])
    value.cycle = result.tracker.cycle;
end
end

function metadata = current_run_metadata( ...
        modelPath,modelSha256,projectRoot,caseCount)
[commitStatus,gitCommit] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD',projectRoot));
[branchStatus,gitBranch] = system(sprintf( ...
    'git -C "%s" branch --show-current',projectRoot));
[statusCode,gitStatus] = system(sprintf( ...
    'git -C "%s" status --short --untracked-files=all',projectRoot));
if commitStatus ~= 0 || branchStatus ~= 0 || statusCode ~= 0
    error('Phase1A:GitMetadataFailure', ...
        'Unable to read Git metadata for the formal baseline.');
end
dirtyStatus = "CLEAN";
if strlength(strtrim(string(gitStatus))) > 0
    dirtyStatus = "DIRTY";
end
simulinkInfo = ver('simulink');
metadata = struct( ...
    'phase1a_step',"Step 6 - Six-Case Formal Baseline Run", ...
    'step5_checkpoint_commit', ...
    "165d2bea04d997de9e82f99818f5c03828c46f94", ...
    'run_starting_commit',strtrim(string(gitCommit)), ...
    'model_file',"AI6109_MOA_AutoComp9.slx", ...
    'model_path',string(modelPath), ...
    'model_sha256',modelSha256, ...
    'baseline_integrity',"PASS", ...
    'run_timestamp',string(datetime('now','TimeZone','Asia/Shanghai', ...
    'Format',"yyyy-MM-dd'T'HH:mm:ssXXX")), ...
    'git_commit',strtrim(string(gitCommit)), ...
    'git_branch',strtrim(string(gitBranch)), ...
    'git_dirty_status',dirtyStatus, ...
    'matlab_version',string(version), ...
    'simulink_version',string(simulinkInfo.Version), ...
    'platform',string(computer), ...
    'case_level_simulator_calls',caseCount, ...
    'low_level_sim_invocation_count',2*caseCount, ...
    'shared_data_per_case',true, ...
    'low_level_run_note', ...
    "Each simulate_phase2_case call contains one zero-noise and one noisy sim invocation.");
end

function integrity = capture_frozen_integrity(matlabRoot)
names = [ ...
    "AI6109_MOA_AutoComp9.slx"
    "generate_coupling_signals.m"
    "run_phase1a_algorithm.m"
    "evaluate_phase1a_metrics.m"
    "track_coupling_cvff_rls.m"
    "initial_coupling_estimate.m"
    "coupling_regressor.m"
    "extract_resistive_current.m"
    "reconstruct_refs_from_b.m"
    "patent_default_config.m"
    "phase1a_case_registry.m"
    "phase1a_algorithm_registry.m"
    "phase1a_result_schema.m"
    "phase1a_historical_reference.m"
    ];
hashes = strings(size(names));
for k = 1:numel(names)
    hashes(k) = file_sha256(fullfile(matlabRoot,names(k)));
end
integrity = table(names,hashes, ...
    'VariableNames',{'file_name','sha256_before_run'});
end

function hash = file_sha256(path)
fileId = fopen(path,'rb');
if fileId < 0
    error('Phase1A:HashFailure','Unable to compute SHA-256 for %s.',path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
digester = java.security.MessageDigest.getInstance('SHA-256');
digester.update(bytes);
hashBytes = typecast(digester.digest(),'uint8');
hash = upper(string(reshape(dec2hex(hashBytes,2).',1,[])));
end

function label = pass_label(value)
if value
    label = "PASS";
else
    label = "FAIL";
end
end
