function out = track_coupling_m4_weighted_rls( ...
        data,ref,cfg,self_pF,options)
%TRACK_COUPLING_M4_WEIGHTED_RLS M4-v0 continuous information protection.
% This is the M4-v0 structural implementation, not the final frozen M4
% formula. Direction quantities are diagnostics only and never control the
% update weight, information state, parameter update, or baseline state.

if nargin < 5 || isempty(options)
    options = struct();
end
forcedUpdateWeight = option_value(options, ...
    'forced_update_weight',NaN);
directionDiagnosticsEnabled = logical(option_value(options, ...
    'direction_diagnostics_enabled',true));
if ~isscalar(directionDiagnosticsEnabled)
    error('M4:InvalidDirectionDiagnosticOption', ...
        'direction_diagnostics_enabled must be scalar.');
end

t = data.t;
sampleCount = numel(t);
sampleRate = 1/median(diff(t));
samplesPerCycle = round(sampleRate/cfg.f);
regularization = 1e-10;

c = initial_coupling_estimate(data,ref,cfg,self_pF);
hist = repmat(c(:).',sampleCount,1);
initializationIndex = t >= cfg.init_start & t < cfg.init_end;
[X0,~] = coupling_regressor( ...
    data,ref,initializationIndex,self_pF);
J = 0.05*(X0'*X0)+1e-8*eye(2);
h = J*c;
initialState = struct('J',J,'h',h,'c',c);

baseIn = NaN;
rows = struct([]);
startIndex = find(t >= cfg.init_end,1);
startIndex = floor((startIndex-1)/samplesPerCycle)*samplesPerCycle+1;
lastFilled = startIndex-1;

for cycleStart = startIndex:samplesPerCycle: ...
        (sampleCount-samplesPerCycle+1)
    index = cycleStart:(cycleStart+samplesPerCycle-1);
    [X,y] = coupling_regressor(data,ref,index,self_pF);
    R = X'*X;
    z = X'*y;
    localLs = (R+regularization*eye(2))\z;
    cPrevious = c;
    JPrevious = J;
    hPrevious = h;
    deltaLocal = localLs-cPrevious;
    innovation = norm(deltaLocal./[5;5]);
    lambda = cfg.lambda_max-(cfg.lambda_max-cfg.lambda_min)* ...
        min(max(innovation/0.20,0),1);

    [Ein,Equad,eInVector,residualFitValid] = ...
        residual_components_with_vector( ...
        data,ref,index,cPrevious,self_pF,cfg.f);
    if isnan(baseIn)
        baseIn = Ein;
    end
    baseInPrevious = baseIn;
    evidence = m4_fault_evidence(Ein,Equad,baseInPrevious, ...
        cfg.gate_ratio,cfg.gate_quad_ratio,forcedUpdateWeight);
    updateWeight = evidence.update_weight;

    JStar = lambda*JPrevious+R;
    hStar = lambda*hPrevious+z;
    JIncrementRaw = JStar-JPrevious;
    hIncrementRaw = hStar-hPrevious;
    cM2Raw = (JStar+regularization*eye(2))\hStar;
    deltaM2Raw = cM2Raw-cPrevious;

    if updateWeight == 0
        J = JPrevious;
        h = hPrevious;
        cRaw = cPrevious;
    elseif updateWeight == 1
        J = JStar;
        h = hStar;
        cRaw = (J+regularization*eye(2))\h;
    else
        J = JPrevious+updateWeight*JIncrementRaw;
        h = hPrevious+updateWeight*hIncrementRaw;
        cRaw = (J+regularization*eye(2))\h;
    end
    JIncrementApplied = J-JPrevious;
    hIncrementApplied = h-hPrevious;
    deltaRaw = cRaw-cPrevious;

    rateLimitedDelta = max(min(deltaRaw, ...
        cfg.rate_limit_pF_per_cycle), ...
        -cfg.rate_limit_pF_per_cycle);
    cAfterRate = cPrevious+rateLimitedDelta;
    c = min(max(cAfterRate,cfg.coupling_bounds_pF(1)), ...
        cfg.coupling_bounds_pF(2));
    if updateWeight == 0
        c = cPrevious;
        cAfterRate = cPrevious;
    end
    deltaApplied = c-cPrevious;
    deltaAfterRate = cAfterRate-cPrevious;
    rateSuppression = deltaRaw-deltaAfterRate;
    projectionSuppression = deltaAfterRate-deltaApplied;
    informationSuppression = deltaM2Raw-deltaRaw;
    totalSuppression = deltaM2Raw-deltaApplied;
    rateLimitActive = any(rateSuppression ~= 0);
    projectionActive = any(projectionSuppression ~= 0);

    if Ein < 1.08*baseInPrevious
        baseInStar = 0.985*baseInPrevious+0.015*Ein;
    else
        baseInStar = baseInPrevious;
    end
    baseIncrementCandidate = baseInStar-baseInPrevious;
    if updateWeight == 0
        baseIn = baseInPrevious;
    elseif updateWeight == 1
        baseIn = baseInStar;
    else
        baseIn = baseInPrevious+ ...
            updateWeight*baseIncrementCandidate;
    end
    baseIncrementApplied = baseIn-baseInPrevious;

    direction = direction_diagnostics( ...
        directionDiagnosticsEnabled,R,X,eInVector, ...
        deltaLocal,deltaRaw,cPrevious,localLs,cRaw, ...
        residualFitValid,regularization);

    hist(index,:) = repmat(c(:).',numel(index),1);
    lastFilled = index(end);
    row = cycle_row(t(index(end)),c,lambda,innovation,localLs, ...
        Ein,Equad,baseIn,baseInStar,baseIncrementCandidate, ...
        baseIncrementApplied,evidence,deltaLocal,deltaM2Raw, ...
        deltaRaw,deltaAfterRate,deltaApplied,totalSuppression, ...
        informationSuppression,rateSuppression, ...
        projectionSuppression,JIncrementRaw,JIncrementApplied, ...
        hIncrementRaw,hIncrementApplied,rateLimitActive, ...
        projectionActive,direction,J,h,forcedUpdateWeight, ...
        directionDiagnosticsEnabled);
    if isempty(rows)
        rows = row;
    else
        rows(end+1,1) = row; %#ok<AGROW>
    end
end

if lastFilled < sampleCount
    hist(lastFilled+1:sampleCount,:) = ...
        repmat(c(:).',sampleCount-lastFilled,1);
end
out = struct();
out.hist = hist;
out.cycle = struct2table(rows);
out.initial_state = initialState;
out.final_state = struct('J',J,'h',h,'c',c,'baseIn',baseIn);
out.options = struct( ...
    'forced_update_weight',forcedUpdateWeight, ...
    'direction_diagnostics_enabled',directionDiagnosticsEnabled);
end

function value = option_value(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function [Ein,Equad,eInVector,fitValid] = ...
        residual_components_with_vector(data,ref,index,c,self_pF,f)
[X,y] = coupling_regressor(data,ref,index,self_pF);
residual = y-X*c;
pointsPerPhase = numel(index);
time = data.t(index);
omega = 2*pi*f;
phase = [2*pi/3,0,-2*pi/3];
EinPerPhase = zeros(3,1);
EquadPerPhase = zeros(3,1);
eInVector = zeros(size(residual));
fitValid = all(isfinite(residual));
for phaseIndex = 1:3
    phaseRows = (phaseIndex-1)*pointsPerPhase+1: ...
        phaseIndex*pointsPerPhase;
    phaseResidual = residual(phaseRows);
    inPhaseBasis = [ ...
        sin(omega*time+ref.phi1+phase(phaseIndex)), ...
        sin(3*omega*time+ref.phi3)];
    quadratureBasis = [ ...
        cos(omega*time+ref.phi1+phase(phaseIndex)), ...
        cos(3*omega*time+ref.phi3)];
    basis = [inPhaseBasis,quadratureBasis,ones(pointsPerPhase,1)];
    coefficients = basis\phaseResidual;
    inPhaseFit = inPhaseBasis*coefficients(1:2);
    quadratureFit = quadratureBasis*coefficients(3:4);
    eInVector(phaseRows) = inPhaseFit;
    EinPerPhase(phaseIndex) = sqrt(mean(inPhaseFit.^2));
    EquadPerPhase(phaseIndex) = sqrt(mean(quadratureFit.^2));
    fitValid = fitValid && all(isfinite(coefficients)) && ...
        all(isfinite(inPhaseFit)) && all(isfinite(quadratureFit));
end
Ein = sqrt(mean(EinPerPhase.^2));
Equad = sqrt(mean(EquadPerPhase.^2));
fitValid = fitValid && isfinite(Ein) && isfinite(Equad);
end

function diagnostics = direction_diagnostics(enabled,R,X,eInVector, ...
        deltaLocal,deltaRaw,cPrevious,localLs,cRaw, ...
        residualFitValid,regularization)
diagnostics = invalid_direction_diagnostics(R);
if ~enabled
    return
end
regularizedR = R+regularization*eye(2);
conditionNumber = cond(R);
q = regularizedR\(X'*eInVector);
numericScale = max([1;abs(cPrevious);abs(localLs);abs(cRaw);abs(q)]);
normThreshold = sqrt(eps)*max(numericScale);
conditionLimit = 1/sqrt(eps);
valid = residualFitValid && all(isfinite(q)) && ...
    isfinite(conditionNumber) && conditionNumber <= conditionLimit && ...
    norm(q) > normThreshold && norm(deltaLocal) > normThreshold && ...
    norm(deltaRaw) > normThreshold;
diagnostics.R_condition_number = conditionNumber;
diagnostics.valid = valid;
if ~valid
    return
end
faultDirection = q/(norm(q)+eps);
diagnostics.fault_direction = faultDirection;
diagnostics.cos_local_fault = ...
    dot(deltaLocal,faultDirection)/(norm(deltaLocal)+eps);
diagnostics.cos_raw_fault = ...
    dot(deltaRaw,faultDirection)/(norm(deltaRaw)+eps);
diagnostics.delta_parallel = ...
    faultDirection*(faultDirection'*deltaRaw);
diagnostics.delta_perpendicular = ...
    deltaRaw-diagnostics.delta_parallel;
end

function diagnostics = invalid_direction_diagnostics(R)
diagnostics = struct( ...
    'fault_direction',[NaN;NaN], ...
    'valid',false, ...
    'cos_local_fault',NaN, ...
    'cos_raw_fault',NaN, ...
    'delta_parallel',[NaN;NaN], ...
    'delta_perpendicular',[NaN;NaN], ...
    'R_condition_number',cond(R));
end

function row = cycle_row(time,c,lambda,innovation,localLs, ...
        Ein,Equad,baseIn,baseInStar,baseIncrementCandidate, ...
        baseIncrementApplied,evidence,deltaLocal,deltaM2Raw, ...
        deltaRaw,deltaAfterRate,deltaApplied,totalSuppression, ...
        informationSuppression,rateSuppression, ...
        projectionSuppression,JIncrementRaw,JIncrementApplied, ...
        hIncrementRaw,hIncrementApplied,rateLimitActive, ...
        projectionActive,direction,J,h,forcedUpdateWeight, ...
        directionDiagnosticsEnabled)
row = struct( ...
    'time_s',time, ...
    'Cs1_pF',c(1), ...
    'Cs2_pF',c(2), ...
    'lambda',lambda, ...
    'innovation_scalar',innovation, ...
    'local_ls_Cs1_pF',localLs(1), ...
    'local_ls_Cs2_pF',localLs(2), ...
    'E_in',Ein, ...
    'E_quad',Equad, ...
    'base_in',baseIn, ...
    'base_in_candidate',baseInStar, ...
    'base_in_increment_candidate',baseIncrementCandidate, ...
    'base_in_increment_applied',baseIncrementApplied, ...
    'evidence_ratio_base',evidence.ratio_base, ...
    'evidence_ratio_quad',evidence.ratio_quad, ...
    'evidence_background_excess',evidence.background_excess, ...
    'evidence_phase_weight',evidence.phase_weight, ...
    'fault_evidence_score',evidence.score, ...
    'update_weight',evidence.update_weight, ...
    'delta_c_local_1',deltaLocal(1), ...
    'delta_c_local_2',deltaLocal(2), ...
    'delta_c_m2_raw_1',deltaM2Raw(1), ...
    'delta_c_m2_raw_2',deltaM2Raw(2), ...
    'delta_c_raw_1',deltaRaw(1), ...
    'delta_c_raw_2',deltaRaw(2), ...
    'delta_c_after_rate_1',deltaAfterRate(1), ...
    'delta_c_after_rate_2',deltaAfterRate(2), ...
    'delta_c_applied_1',deltaApplied(1), ...
    'delta_c_applied_2',deltaApplied(2), ...
    'delta_c_suppressed_1',totalSuppression(1), ...
    'delta_c_suppressed_2',totalSuppression(2), ...
    'delta_c_information_suppressed_1',informationSuppression(1), ...
    'delta_c_information_suppressed_2',informationSuppression(2), ...
    'delta_c_rate_suppressed_1',rateSuppression(1), ...
    'delta_c_rate_suppressed_2',rateSuppression(2), ...
    'delta_c_projection_suppressed_1',projectionSuppression(1), ...
    'delta_c_projection_suppressed_2',projectionSuppression(2), ...
    'J_increment_norm_raw',norm(JIncrementRaw,'fro'), ...
    'J_increment_norm_applied',norm(JIncrementApplied,'fro'), ...
    'h_increment_norm_raw',norm(hIncrementRaw), ...
    'h_increment_norm_applied',norm(hIncrementApplied), ...
    'rate_limit_active',logical(rateLimitActive), ...
    'projection_active',logical(projectionActive), ...
    'm4_evidence_valid',logical(evidence.valid), ...
    'fault_direction_candidate_1',direction.fault_direction(1), ...
    'fault_direction_candidate_2',direction.fault_direction(2), ...
    'direction_candidate_valid',logical(direction.valid), ...
    'cos_local_fault',direction.cos_local_fault, ...
    'cos_raw_fault',direction.cos_raw_fault, ...
    'delta_c_parallel_1',direction.delta_parallel(1), ...
    'delta_c_parallel_2',direction.delta_parallel(2), ...
    'delta_c_perpendicular_1',direction.delta_perpendicular(1), ...
    'delta_c_perpendicular_2',direction.delta_perpendicular(2), ...
    'R_condition_number',direction.R_condition_number, ...
    'J_11',J(1,1), ...
    'J_12',J(1,2), ...
    'J_21',J(2,1), ...
    'J_22',J(2,2), ...
    'h_1',h(1), ...
    'h_2',h(2), ...
    'J_increment_raw_11',JIncrementRaw(1,1), ...
    'J_increment_raw_12',JIncrementRaw(1,2), ...
    'J_increment_raw_21',JIncrementRaw(2,1), ...
    'J_increment_raw_22',JIncrementRaw(2,2), ...
    'J_increment_applied_11',JIncrementApplied(1,1), ...
    'J_increment_applied_12',JIncrementApplied(1,2), ...
    'J_increment_applied_21',JIncrementApplied(2,1), ...
    'J_increment_applied_22',JIncrementApplied(2,2), ...
    'h_increment_raw_1',hIncrementRaw(1), ...
    'h_increment_raw_2',hIncrementRaw(2), ...
    'h_increment_applied_1',hIncrementApplied(1), ...
    'h_increment_applied_2',hIncrementApplied(2), ...
    'forced_update_weight_active',logical(~isnan(forcedUpdateWeight)), ...
    'direction_diagnostics_enabled',logical(directionDiagnosticsEnabled));
end
