function out = track_coupling_m5_directional_rls( ...
        data,ref,cfg,selfPF,mode,options)
%TRACK_COUPLING_M5_DIRECTIONAL_RLS M5 and matched-control tracker.
% The four supported modes share one raw M2 proposal and one constrained
% update path. A test-only forced weight can exercise algebraic endpoints.

arguments
    data (1,1) struct
    ref (1,1) struct
    cfg (1,1) struct
    selfPF (1,3) double {mustBeReal,mustBeFinite}
    mode {mustBeTextScalar}
    options (1,1) struct = struct()
end

variant = variant_definition(mode);
forcedWeight = option_value(options,'forced_selected_weight',NaN);
validate_options(options,forcedWeight);

time = data.t;
sampleCount = numel(time);
sampleRate = 1/median(diff(time));
samplesPerCycle = round(sampleRate/cfg.f);
regularization = 1e-10;
theta = initial_coupling_estimate(data,ref,cfg,selfPF);
history = repmat(theta(:).',sampleCount,1);
initializationIndex = time >= cfg.init_start & time < cfg.init_end;
[X0,~] = coupling_regressor(data,ref,initializationIndex,selfPF);
J = 0.05*(X0.'*X0)+1e-8*eye(2);
h = J*theta;
initialState = struct('J',J,'h',h,'theta',theta);

baseIn = NaN;
gateHold = 0;
rows = struct([]);
startIndex = find(time >= cfg.init_end,1);
startIndex = floor((startIndex-1)/samplesPerCycle)*samplesPerCycle+1;
lastFilled = startIndex-1;

for cycleStart = startIndex:samplesPerCycle: ...
        (sampleCount-samplesPerCycle+1)
    index = cycleStart:(cycleStart+samplesPerCycle-1);
    [X,y] = coupling_regressor(data,ref,index,selfPF);
    R = X.'*X;
    z = X.'*y;
    localLs = (R+regularization*eye(2))\z;
    thetaPrevious = theta;
    JPrevious = J;
    hPrevious = h;
    deltaLocal = localLs-thetaPrevious;
    innovation = norm(deltaLocal./[5;5]);
    lambda = cfg.lambda_max-(cfg.lambda_max-cfg.lambda_min)* ...
        min(max(innovation/0.20,0),1);

    [Ein,Equad] = residual_components( ...
        data,ref,index,thetaPrevious,selfPF,cfg.f);
    if isnan(baseIn)
        baseIn = Ein;
    end
    baseInPrevious = baseIn;
    gateTrigger = time(index(end)) > 1.0 && ...
        Ein > cfg.gate_ratio*baseInPrevious && ...
        Ein > cfg.gate_quad_ratio*Equad;
    if gateTrigger
        gateHold = max(gateHold,cfg.gate_hold_cycles);
    end
    if gateHold > 0
        gate = 1;
        gateHold = gateHold-1;
    else
        gate = 0;
    end
    hardWeight = 1-gate;
    evidence = m4_fault_evidence(Ein,Equad,baseInPrevious, ...
        cfg.gate_ratio,cfg.gate_quad_ratio,NaN);
    rewWeight = evidence.update_weight;
    naturalSelectedWeight = select_weight( ...
        variant.weight_type,hardWeight,rewWeight);
    selectedWeight = naturalSelectedWeight;
    if isfinite(forcedWeight)
        selectedWeight = forcedWeight;
    end

    JStar = lambda*JPrevious+R;
    hStar = lambda*hPrevious+z;
    thetaM2Raw = (JStar+regularization*eye(2))\hStar;
    deltaRaw = thetaM2Raw-thetaPrevious;
    update = m5_directional_update( ...
        deltaRaw,selectedWeight,variant.scope);
    thetaPreconstraint = thetaPrevious+update.delta_protected;

    J = JStar;
    h = (J+regularization*eye(2))*thetaPreconstraint;
    thetaSolveback = (J+regularization*eye(2))\h;
    solvebackError = norm(thetaSolveback-thetaPreconstraint);
    reconciliationResidual = ...
        norm(h-(J+regularization*eye(2))*thetaPreconstraint);

    rateLimitedDelta = max(min(update.delta_protected, ...
        cfg.rate_limit_pF_per_cycle),-cfg.rate_limit_pF_per_cycle);
    thetaRate = thetaPrevious+rateLimitedDelta;
    thetaProjected = min(max(thetaRate,cfg.coupling_bounds_pF(1)), ...
        cfg.coupling_bounds_pF(2));
    rateLimitActive = any(rateLimitedDelta ~= update.delta_protected);
    projectionActive = any(thetaProjected ~= thetaRate);
    theta = thetaProjected;

    if Ein < 1.08*baseInPrevious
        baseInCandidate = 0.985*baseInPrevious+0.015*Ein;
    else
        baseInCandidate = baseInPrevious;
    end
    baseIn = baseInPrevious+selectedWeight* ...
        (baseInCandidate-baseInPrevious);

    numericScale = max([1;abs(thetaPrevious);abs(thetaM2Raw)]);
    deltaAfterRate = thetaRate-thetaPrevious;
    deltaAfterProjection = thetaProjected-thetaPrevious;
    rawAngle = direction_angle(deltaRaw,update.fault_direction,numericScale);
    protectedAngle = direction_angle( ...
        update.delta_protected,update.fault_direction,numericScale);
    rateAngle = direction_angle( ...
        deltaAfterRate,update.fault_direction,numericScale);
    projectionAngle = direction_angle( ...
        deltaAfterProjection,update.fault_direction,numericScale);
    parallelEnergyFraction = update.parallel_norm^2/( ...
        update.parallel_norm^2+update.perp_norm^2+eps);
    finalMismatch = norm(h-J*theta);
    finalRegularizedMismatch = norm( ...
        h-(J+regularization*eye(2))*theta);

    history(index,:) = repmat(theta(:).',numel(index),1);
    lastFilled = index(end);
    row = cycle_row(time(index(end)),variant,thetaPrevious, ...
        thetaM2Raw,deltaRaw,update,gate,hardWeight,rewWeight, ...
        selectedWeight,thetaPreconstraint,thetaRate,thetaProjected, ...
        rateLimitActive,projectionActive,rawAngle,protectedAngle, ...
        rateAngle,projectionAngle,J,hStar,h,solvebackError, ...
        reconciliationResidual,finalMismatch, ...
        finalRegularizedMismatch,baseInPrevious,baseInCandidate, ...
        baseIn,lambda,innovation,localLs,Ein,Equad,evidence, ...
        gateTrigger,naturalSelectedWeight,forcedWeight, ...
        parallelEnergyFraction,deltaAfterRate,deltaAfterProjection);
    if isempty(rows)
        rows = row;
    else
        rows(end+1,1) = row; %#ok<AGROW>
    end
end

if lastFilled < sampleCount
    history(lastFilled+1:sampleCount,:) = ...
        repmat(theta(:).',sampleCount-lastFilled,1);
end

out = struct( ...
    'hist',history, ...
    'cycle',struct2table(rows), ...
    'initial_state',initialState, ...
    'final_state',struct('J',J,'h',h,'theta',theta,'baseIn',baseIn), ...
    'variant',variant, ...
    'options',struct('forced_selected_weight',forcedWeight));
end

function variant = variant_definition(mode)
mode = upper(strtrim(string(mode)));
switch mode
    case "M5_DH"
        variant = struct('mode',mode,'scope',"directional", ...
            'weight_type',"hard",'role',"DIRECTIONAL_HARD");
    case "M5_FULL"
        variant = struct('mode',mode,'scope',"directional", ...
            'weight_type',"continuous",'role',"PRODUCTION_CANDIDATE");
    case "GLOBAL_HARD_MATCHED"
        variant = struct('mode',mode,'scope',"global", ...
            'weight_type',"hard", ...
            'role',"ABLATION_ONLY_GLOBAL_HARD_MATCHED");
    case "GLOBAL_CONTINUOUS_MATCHED"
        variant = struct('mode',mode,'scope',"global", ...
            'weight_type',"continuous", ...
            'role',"ABLATION_ONLY_GLOBAL_CONTINUOUS_MATCHED");
    otherwise
        error('M5:UnknownMode','Unsupported M5 mode: %s.',mode);
end
end

function value = option_value(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function validate_options(options,forcedWeight)
allowed = "forced_selected_weight";
names = string(fieldnames(options));
if any(~ismember(names,allowed))
    error('M5:UnknownOption','M5 tracker received an unknown option.');
end
if ~(isscalar(forcedWeight) && (isnan(forcedWeight) || ...
        (isfinite(forcedWeight) && forcedWeight >= 0 && forcedWeight <= 1)))
    error('M5:InvalidForcedWeight', ...
        'forced_selected_weight must be NaN or a scalar in [0,1].');
end
end

function selectedWeight = select_weight(weightType,hardWeight,rewWeight)
if weightType == "hard"
    selectedWeight = hardWeight;
else
    selectedWeight = rewWeight;
end
end

function [Ein,Equad] = residual_components( ...
        data,ref,index,theta,selfPF,frequency)
[X,y] = coupling_regressor(data,ref,index,selfPF);
residual = y-X*theta;
pointsPerPhase = numel(index);
time = data.t(index);
omega = 2*pi*frequency;
phase = [2*pi/3,0,-2*pi/3];
EinPerPhase = zeros(3,1);
EquadPerPhase = zeros(3,1);
for phaseIndex = 1:3
    phaseRows = (phaseIndex-1)*pointsPerPhase+1: ...
        phaseIndex*pointsPerPhase;
    phaseResidual = residual(phaseRows);
    inPhaseBasis = [ ...
        sin(omega*time+ref.phi1+phase(phaseIndex)), ...
        sin(3*omega*time+ref.phi3)];
    quadratureBasis = [ ...
        cos(omega*time+ref.phi1+phase(phaseIndex)), ...
        cos(3*omega*time+ref.phi3)];
    basis = [inPhaseBasis,quadratureBasis,ones(pointsPerPhase,1)];
    coefficients = basis\phaseResidual;
    inPhaseFit = inPhaseBasis*coefficients(1:2);
    quadratureFit = quadratureBasis*coefficients(3:4);
    EinPerPhase(phaseIndex) = sqrt(mean(inPhaseFit.^2));
    EquadPerPhase(phaseIndex) = sqrt(mean(quadratureFit.^2));
end
Ein = sqrt(mean(EinPerPhase.^2));
Equad = sqrt(mean(EquadPerPhase.^2));
end

function angle = direction_angle(vector,direction,numericScale)
normThreshold = sqrt(eps)*max(1,numericScale);
vectorNorm = norm(vector);
if ~(all(isfinite(vector)) && vectorNorm > normThreshold)
    angle = NaN;
    return
end
alignment = abs(dot(vector,direction))/vectorNorm;
alignment = min(max(alignment,0),1);
angle = rad2deg(acos(alignment));
end

function row = cycle_row(time,variant,thetaPrevious,thetaM2Raw, ...
        deltaRaw,update,gate,hardWeight,rewWeight,selectedWeight, ...
        thetaPreconstraint,thetaRate,thetaProjected,rateLimitActive, ...
        projectionActive,rawAngle,protectedAngle,rateAngle, ...
        projectionAngle,J,hStar,hReconciled,solvebackError, ...
        reconciliationResidual,finalMismatch,finalRegularizedMismatch, ...
        baseInPrevious,baseInCandidate,baseInNew,lambda,innovation, ...
        localLs,Ein,Equad,evidence,gateTrigger,naturalSelectedWeight, ...
        forcedWeight,parallelEnergyFraction,deltaAfterRate, ...
        deltaAfterProjection)
row = struct( ...
    'time_s',time, ...
    'variant',variant.mode, ...
    'variant_role',variant.role, ...
    'operator_scope',variant.scope, ...
    'weight_type',variant.weight_type, ...
    'theta_previous_Cs1',thetaPrevious(1), ...
    'theta_previous_Cs2',thetaPrevious(2), ...
    'theta_M2_raw_Cs1',thetaM2Raw(1), ...
    'theta_M2_raw_Cs2',thetaM2Raw(2), ...
    'delta_raw_Cs1',deltaRaw(1), ...
    'delta_raw_Cs2',deltaRaw(2), ...
    'delta_parallel_Cs1',update.delta_parallel(1), ...
    'delta_parallel_Cs2',update.delta_parallel(2), ...
    'delta_perp_Cs1',update.delta_perp(1), ...
    'delta_perp_Cs2',update.delta_perp(2), ...
    'parallel_norm',update.parallel_norm, ...
    'perp_norm',update.perp_norm, ...
    'parallel_energy_fraction',parallelEnergyFraction, ...
    'decomposition_error_norm',update.decomposition_error_norm, ...
    'raw_signed_projection_df',dot(deltaRaw,update.fault_direction), ...
    'gate_trigger',logical(gateTrigger), ...
    'gate',gate, ...
    'w_hard',hardWeight, ...
    'w_REW',rewWeight, ...
    'natural_selected_weight',naturalSelectedWeight, ...
    'selected_weight',selectedWeight, ...
    'forced_weight_active',logical(isfinite(forcedWeight)), ...
    'theta_preconstraint_Cs1',thetaPreconstraint(1), ...
    'theta_preconstraint_Cs2',thetaPreconstraint(2), ...
    'delta_protected_Cs1',update.delta_protected(1), ...
    'delta_protected_Cs2',update.delta_protected(2), ...
    'theta_rate_Cs1',thetaRate(1), ...
    'theta_rate_Cs2',thetaRate(2), ...
    'delta_after_rate_Cs1',deltaAfterRate(1), ...
    'delta_after_rate_Cs2',deltaAfterRate(2), ...
    'theta_projected_Cs1',thetaProjected(1), ...
    'theta_projected_Cs2',thetaProjected(2), ...
    'delta_after_projection_Cs1',deltaAfterProjection(1), ...
    'delta_after_projection_Cs2',deltaAfterProjection(2), ...
    'rate_limit_active',logical(rateLimitActive), ...
    'projection_active',logical(projectionActive), ...
    'raw_angle_to_df_deg',rawAngle, ...
    'protected_angle_to_df_deg',protectedAngle, ...
    'post_rate_angle_to_df_deg',rateAngle, ...
    'post_projection_angle_to_df_deg',projectionAngle, ...
    'rate_rotation_deg',angle_difference(protectedAngle,rateAngle), ...
    'projection_rotation_deg',angle_difference(rateAngle,projectionAngle), ...
    'J11',J(1,1), ...
    'J12',J(1,2), ...
    'J21',J(2,1), ...
    'J22',J(2,2), ...
    'h_star_1',hStar(1), ...
    'h_star_2',hStar(2), ...
    'h_reconciled_1',hReconciled(1), ...
    'h_reconciled_2',hReconciled(2), ...
    'solveback_error_norm',solvebackError, ...
    'reconciliation_residual_norm',reconciliationResidual, ...
    'final_h_Jtheta_mismatch_norm',finalMismatch, ...
    'final_regularized_mismatch_norm',finalRegularizedMismatch, ...
    'baseIn_previous',baseInPrevious, ...
    'baseIn_candidate',baseInCandidate, ...
    'baseIn_new',baseInNew, ...
    'lambda',lambda, ...
    'innovation_scalar',innovation, ...
    'local_ls_Cs1',localLs(1), ...
    'local_ls_Cs2',localLs(2), ...
    'E_in',Ein, ...
    'E_quad',Equad, ...
    'evidence_ratio_base',evidence.ratio_base, ...
    'evidence_ratio_quad',evidence.ratio_quad, ...
    'fault_evidence_score',evidence.score, ...
    'evidence_valid',logical(evidence.valid));
end

function difference = angle_difference(firstAngle,secondAngle)
if isfinite(firstAngle) && isfinite(secondAngle)
    difference = secondAngle-firstAngle;
else
    difference = NaN;
end
end

